#!/bin/tcsh

set odir = `pwd`

# prepare CMSSW
set MYCMSSWVER = CMSSW_4_2_8_patch7
cmsrel ${MYCMSSWVER}
ln -s ${MYCMSSWVER} mycmsswlink

cd ${odir}

source ${odir}/mkBrLimits_submit
echo done with jobs! 

source ${odir}/mkBrLimits_process
echo done with plotting!

# Finally, remove LandS and clean directory

# # compress LandS output files,
# # remove LandS and clean directory from files created by LandS
# rm -r LSFJOB_*
# rm *Hybrid*root
rm spli*root
#rm -r mycmsswlink/src/HiggsAnalysis
#rm -r mycmsswlink/src/UserCode
#rm -r mycmsswlink/tmp
rm -r mycmsswlink
rm -r CMSSW_*

echo mkBrLimits done!
