#!/bin/tcsh

set odir = `pwd`

# prepare CMSSW
set MYCMSSWVER = CMSSW_4_2_8_patch7
cmsrel ${MYCMSSWVER}
ln -s ${MYCMSSWVER} mycmsswlink

cd ${odir}

source ${odir}/mkBrLimits_submit
echo done with jobs! 

source ${odir}/mkBrLimits_process
echo done with plotting!

# TODO: remove LandS and clean

# # compress LandS output files,
# # remove LandS and clean directory from files created by LandS
# tar -cf output_Lands.tar output_LandS_*
# rm output_LandS_*
# rm -r LSFJOB_*
# rm *Hybrid*root
# #rm input_luminosity_*
# rm -r CMSSW_*
rm -r mycmsswlink/src/HiggsAnalysis
rm -r mycmsswlink/src/UserCode
rm -r mycmsswlink/tmp
