#!/bin/tcsh

set odir = $1
set datacard1 = ${odir}/$2 
set datacard2 = ${odir}/$3
set datacard3 = ${odir}/$4 
set outputfile = outputs/output_LandS_`basename ${datacard1} .txt`_obs

echo "Calculating obs value with datacard ${datacard1} ${datacard2} ${datacard3}, output is ${outputfile}"
echo

cd ${odir}/mycmsswlink/src
cmsenv

cd ${odir}
${odir}/mycmsswlink/src/UserCode/mschen/LandS/test/lands.exe --PhysicsModel ChargedHiggs  -M Hybrid --bQuickEstimateInitialLimit 0 --initialRmin 0. --initialRmax 0.09  -d ${datacard1} | tail -5 >& ${outputfile}

exit 0
