#!/bin/tcsh

# Set here number of toy MC (default 10)
set nToys = 10

# parameters for mkBrLimits_submitExpSplit:
# workdir, job number (seed), mass point, datacard file name(s)
set odir = $1
set myseed = $2 
set myjobname = split$3_$2
set datacard1 = $4 
set datacard2 = $5
set datacard3 = $6 
set datacard4 = $7 
#set outputfile = outputs/output_`basename ${datacard1} .txt`_expSplit
set outputfile = /dev/null #this output not needed, need only the one from merged results

echo "Calculating exp value with datacard ${datacard1} ${datacard2} ${datacard3}, output is ${outputfile}"
echo

cd ${odir}/mycmsswlink/src
cmsenv

cd ${odir}
#./mycmsswlink/src/UserCode/mschen/LandS/test/lands.exe --PhysicsModel ChargedHiggs  -M Hybrid --bQuickEstimateInitialLimit 0 --initialRmin 0. --initialRmax 0.09  -d ${datacard1} ${datacard2} ${datacard3} ${datacard4} --doExpectation 1 -t ${nToys} --seed ${myseed} -n ${myjobname} | tail -5 >& ${outputfile}
./mycmsswlink/src/UserCode/mschen/LandS/test/lands.exe --PhysicsModel ChargedHiggs  -M Hybrid --bQuickEstimateInitialLimit 0 --initialRmin 0. --initialRmax 0.09  -d ${datacard1} ${datacard2} ${datacard3} ${datacard4} --doExpectation 1 -t ${nToys} --seed ${myseed} -n ${myjobname} >& ${outputfile}

exit 0
