#!/bin/tcsh

# run here ROOT script to produce br limit plots 
# and Python script to produce tan(beta) plots

if ( !(-e mycmsswlink) ) then
  set MYCMSSWVER = CMSSW_4_2_8_patch7
  cmsrel ${MYCMSSWVER}
  ln -s ${MYCMSSWVER} mycmsswlink
endif

# set CMSSW variables to make possible to run ROOT
cd mycmsswlink/src
cmsenv
cd ../..

root -b -q mkBrLimits_processBrPlots.cxx
echo Br limit plots ready!

# prepare Higgs analysis area for the necessary tan(b) conversions
cd mycmsswlink/src
#git clone http://cmsdoc.cern.ch/~slehti/HiggsAnalysis.git
git clone ~slehti/public/html/HiggsAnalysis.git
cmsenv
source /afs/cern.ch/cms/LCG/LCG-2/UI/cms_ui_env.csh
source /afs/cern.ch/cms/ccs/wm/scripts/Crab/crab.csh
# -- following not needed since not running cmsRun --
#./HiggsAnalysis/HeavyChHiggsToTauNu/test/checkoutTags.sh
scram b -j 4
cmsenv
cd ../..
./mkBrLimits_processTanbPlots.py
./mkBrLimits_processTanbPlots.py -ma

echo TanB plots ready!
