#!/bin/tcsh

set odir = $1
set datacard1 = ${odir}/$2 
set datacard2 = ${odir}/$3
set datacard3 = ${odir}/$4 
set outputfile = output_LandS_`basename ${datacard1} .txt`_exp
#set outputfile = output_LandS_exp

echo "Calculating exp value with datacard ${datacard1} ${datacard2} ${datacard3}, output is ${outputfile}"
echo

#setenv ROOTSYS "/afs/cern.ch/sw/lcg/app/releases/ROOT/5.28.00/x86_64-slc5-gcc43-dbg/root"
#setenv PATH "$ROOTSYS/bin:$PATH"
#setenv LD_LIBRARY_PATH "$ROOTSYS/lib"
cd ${odir}
cmsenv

#${odir}/LandS_AN/LandS/test/lands.exe -d ${datacard} -M Hybrid  -v 1 --bQuickEstimateInitialLimit 0 --initialRmin 0 --initialRmax 0.1 --doExpectation 1 -t 1000 | tail -5 >& ${outputfile}

${odir}/UserCode/mschen/LandS/test/lands.exe --PhysicsModel ChargedHiggs  -M Hybrid --bQuickEstimateInitialLimit 0 --initialRmin 0. --initialRmax 0.05  -d ${datacard1} --doExpectation 1 -t 1000 | tail -5 >& ${outputfile}

#cp ${outputfile} ${odir}

exit 0
