#!/bin/tcsh

# write name of datacard here
# remove .txt
#---set filename = HPlusHadronic_120
#HPlusHadronic
#HPlus_hadronic_ltau
#HPlus_hadronic_ltau_emu
set name = HPlus_hadronic_ltau

# check if jobs producing same output files are running
# NOTE: a job with longer name containing the name of this job might block this 
# job, even though it would not produce output files with same name
while (`bjobs -w |& grep $name` != "") 
  echo Waiting for previous jobs to end.  You might want to bkill these jobs...
  sleep 10
end

#input file names
set f1 = ${name}_80
set f2 = ${name}_100
set f3 = ${name}_120
set f4 = ${name}_140
set f5 = ${name}_150
set f6 = ${name}_155
set f7 = ${name}_160

#individual names for jobs
set jobname = ${name}_`date +"%H%M%S"`
set j1 = ${jobname}_80
set j2 = ${jobname}_100
set j3 = ${jobname}_120
set j4 = ${jobname}_140
set j5 = ${jobname}_150
set j6 = ${jobname}_155
set j7 = ${jobname}_160

set odir = `pwd`
set outputfile = output_LandS_`basename ${name} .txt`

# generates the files output_LandS_HPlusHadronic_*_obs
bsub -q cmscaf1nd -J ${j1}_o ${odir}/script_run_LandS_obs ${odir} ${f1}.txt
bsub -q cmscaf1nd -J ${j2}_o ${odir}/script_run_LandS_obs ${odir} ${f2}.txt
bsub -q cmscaf1nd -J ${j3}_o ${odir}/script_run_LandS_obs ${odir} ${f3}.txt
bsub -q cmscaf1nd -J ${j4}_o ${odir}/script_run_LandS_obs ${odir} ${f4}.txt
bsub -q cmscaf1nd -J ${j5}_o ${odir}/script_run_LandS_obs ${odir} ${f5}.txt
bsub -q cmscaf1nd -J ${j6}_o ${odir}/script_run_LandS_obs ${odir} ${f6}.txt
bsub -q cmscaf1nd -J ${j7}_o ${odir}/script_run_LandS_obs ${odir} ${f7}.txt

# generates the files output_LandS_HPlusHadronic_*_obs
bsub -q cmscaf1nd -J ${j1}_e ${odir}/script_run_LandS_exp ${odir} ${f1}.txt
bsub -q cmscaf1nd -J ${j2}_e ${odir}/script_run_LandS_exp ${odir} ${f2}.txt
bsub -q cmscaf1nd -J ${j3}_e ${odir}/script_run_LandS_exp ${odir} ${f3}.txt
bsub -q cmscaf1nd -J ${j4}_e ${odir}/script_run_LandS_exp ${odir} ${f4}.txt
bsub -q cmscaf1nd -J ${j5}_e ${odir}/script_run_LandS_exp ${odir} ${f5}.txt
bsub -q cmscaf1nd -J ${j6}_e ${odir}/script_run_LandS_exp ${odir} ${f6}.txt
bsub -q cmscaf1nd -J ${j7}_e ${odir}/script_run_LandS_exp ${odir} ${f7}.txt

# here check if jobs with same name are running
echo Checking jobs with name $name.
while (`bjobs -w |& grep $jobname` != "") # check if job name exists
  echo Waiting for jobs to end `date`
  sleep 30
end

set output1 = output_LandS_${f1}
set output2 = output_LandS_${f2}
set output3 = output_LandS_${f3}
set output4 = output_LandS_${f4}
set output5 = output_LandS_${f5}
set output6 = output_LandS_${f6}
set output7 = output_LandS_${f7}

# collect observed values
head -3 ${output1}_obs | tail -1 | awk '{print $12 }' >&! ${output1}
head -3 ${output2}_obs | tail -1 | awk '{print $12 }' >&! ${output2}
head -3 ${output3}_obs | tail -1 | awk '{print $12 }' >&! ${output3}
head -3 ${output4}_obs | tail -1 | awk '{print $12 }' >&! ${output4}
head -3 ${output5}_obs | tail -1 | awk '{print $12 }' >&! ${output5}
head -3 ${output6}_obs | tail -1 | awk '{print $12 }' >&! ${output6}
head -3 ${output7}_obs | tail -1 | awk '{print $12 }' >&! ${output7}

head -3 ${output1}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output1}
head -3 ${output2}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output2}
head -3 ${output3}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output3}
head -3 ${output4}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output4}
head -3 ${output5}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output5}
head -3 ${output6}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output6}
head -3 ${output7}_exp | tail -1 | awk '{print $2 " " $3 " " $7 " " $5 " " $6}' >> ${output7}


#ls ${odir}/output_LandS_*
cd ${odir}
ls -al output_LandS_*

echo Ready!
