// Class: ReadCutsD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::CutsD
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/36       [336420]
Creator        : skonstan
Date           : Thu Oct  5 11:52:39 2017
Host           : Linux buildvm-19.phx2.fedoraproject.org 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/s/skonstan/TMVA_BDT/test
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.96602058411,7.69307804108]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-4.08540010452,4.0258936882]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.05078554153,4.35967063904]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.95050764084,4.92254400253]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.91655540466,9.52782058716]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.874833107,14.2917308807]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCutsD : public IClassifierReader {

 public:

   // constructor
   ReadCutsD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCutsD" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -5.51657390594482;
      fVmax[0] = 4.66987371444702;
      fVmin[1] = -3.72306704521179;
      fVmax[1] = 3.67532062530518;
      fVmin[2] = -4.17426443099976;
      fVmax[2] = 4.27801322937012;
      fVmin[3] = -4.02366638183594;
      fVmax[3] = 3.33031582832336;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadCutsD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][4][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCutsD"
};
   inline double ReadCutsD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadCutsD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 1.2395003327;
   fDecTF_1[0][0][1] = 0.0644039261065;
   fDecTF_1[0][0][2] = -0.150829404298;
   fDecTF_1[0][0][3] = -1.06801829045;
   fDecTF_1[0][1][0] = 0.0644039261065;
   fDecTF_1[0][1][1] = 0.92837476007;
   fDecTF_1[0][1][2] = 0.155584144488;
   fDecTF_1[0][1][3] = -0.223558339298;
   fDecTF_1[0][2][0] = -0.150829404298;
   fDecTF_1[0][2][1] = 0.155584144488;
   fDecTF_1[0][2][2] = 1.8100606832;
   fDecTF_1[0][2][3] = -0.870070799343;
   fDecTF_1[0][3][0] = -1.06801829045;
   fDecTF_1[0][3][1] = -0.223558339298;
   fDecTF_1[0][3][2] = -0.870070799343;
   fDecTF_1[0][3][3] = 2.84309636288;
   fDecTF_1[1][0][0] = 1.25967097333;
   fDecTF_1[1][0][1] = 0.0688290791784;
   fDecTF_1[1][0][2] = -0.173098394706;
   fDecTF_1[1][0][3] = -1.08093556826;
   fDecTF_1[1][1][0] = 0.0688290791784;
   fDecTF_1[1][1][1] = 0.943299470831;
   fDecTF_1[1][1][2] = 0.17078423454;
   fDecTF_1[1][1][3] = -0.252911927321;
   fDecTF_1[1][2][0] = -0.173098394706;
   fDecTF_1[1][2][1] = 0.17078423454;
   fDecTF_1[1][2][2] = 1.82643296655;
   fDecTF_1[1][2][3] = -0.849423951331;
   fDecTF_1[1][3][0] = -1.08093556826;
   fDecTF_1[1][3][1] = -0.252911927321;
   fDecTF_1[1][3][2] = -0.849423951331;
   fDecTF_1[1][3][3] = 2.82345882514;
   fDecTF_1[2][0][0] = 1.13598019233;
   fDecTF_1[2][0][1] = 0.0329071597404;
   fDecTF_1[2][0][2] = -0.212915273962;
   fDecTF_1[2][0][3] = -0.809588363306;
   fDecTF_1[2][1][0] = 0.0329071597404;
   fDecTF_1[2][1][1] = 0.923945538223;
   fDecTF_1[2][1][2] = 0.150797311181;
   fDecTF_1[2][1][3] = -0.148781037371;
   fDecTF_1[2][2][0] = -0.212915273962;
   fDecTF_1[2][2][1] = 0.150797311181;
   fDecTF_1[2][2][2] = 1.78749447917;
   fDecTF_1[2][2][3] = -0.757048316013;
   fDecTF_1[2][3][0] = -0.809588363306;
   fDecTF_1[2][3][1] = -0.148781037371;
   fDecTF_1[2][3][2] = -0.757048316013;
   fDecTF_1[2][3][3] = 2.1456373175;
}

//_______________________________________________________________________
inline void ReadCutsD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   } 

   std::vector<double> tv;
   for (int i=0; i<4;i++) {
      double v = 0;
      for (int j=0; j<4; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<4;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadCutsD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadCutsD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
