{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus
//=========  (Wed Jul 30 13:56:25 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->Range(-81.01265,0.3266171,425.3165,1.628691);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__29 = new TH1F("hframe__29","",1000,0,400);
   hframe__29->SetMinimum(0.7042185);
   hframe__29->SetMaximum(1.628691);
   hframe__29->SetDirectory(0);
   hframe__29->SetStats(0);
   hframe__29->SetLineStyle(0);
   hframe__29->SetMarkerStyle(20);
   hframe__29->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__29->GetXaxis()->SetLabelFont(43);
   hframe__29->GetXaxis()->SetLabelOffset(0.007);
   hframe__29->GetXaxis()->SetLabelSize(27);
   hframe__29->GetXaxis()->SetTitleSize(33);
   hframe__29->GetXaxis()->SetTitleOffset(2.925);
   hframe__29->GetXaxis()->SetTitleFont(43);
   hframe__29->GetYaxis()->SetTitle("Ratio");
   hframe__29->GetYaxis()->SetNdivisions(505);
   hframe__29->GetYaxis()->SetLabelFont(43);
   hframe__29->GetYaxis()->SetLabelOffset(0.007);
   hframe__29->GetYaxis()->SetLabelSize(21);
   hframe__29->GetYaxis()->SetTitleSize(33);
   hframe__29->GetYaxis()->SetTitleOffset(1.796875);
   hframe__29->GetYaxis()->SetTitleFont(43);
   hframe__29->GetZaxis()->SetLabelFont(43);
   hframe__29->GetZaxis()->SetLabelOffset(0.007);
   hframe__29->GetZaxis()->SetLabelSize(27);
   hframe__29->GetZaxis()->SetTitleSize(33);
   hframe__29->GetZaxis()->SetTitleFont(43);
   hframe__29->Draw(" ");
   Double_t xAxis21[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30","#tau p_{T}<50",10, xAxis21);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(1,1.480628);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(2,0.9132951);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(3,1.072348);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(4,1.054768);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(5,0.903034);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(6,1.257256);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(7,1.020933);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(8,0.9543122);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(9,1.150522);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(10,1.036641);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinContent(11,1.092922);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(1,0.4651133);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(2,0.3341569);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(3,0.2051233);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(4,0.1903635);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(5,0.1440735);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(6,0.1271102);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(7,0.1369519);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(8,0.1654157);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(9,0.2162907);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(10,0.2870681);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetBinError(11,0.9353953);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetEntries(190.1075);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__30->Draw("EP same");
   Double_t xAxis22[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31","#tau p_{T}<50",10, xAxis22);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(5,0.7207969);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(6,0.9898824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(7,0.7621042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(8,0.7042185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(9,0.8474045);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(10,0.7913883);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinContent(11,1.088221);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(5,0.1149444);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(6,0.100059);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(7,0.1022867);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(8,0.1220903);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(9,0.1592168);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(10,0.2184464);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetBinError(11,0.931372);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetEntries(188.642);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__31->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph5 = new TH1F("Graph_Graph5","Graph",100,0,440);
   Graph_Graph5->SetMinimum(0.9);
   Graph_Graph5->SetMaximum(2.1);
   Graph_Graph5->SetDirectory(0);
   Graph_Graph5->SetStats(0);
   Graph_Graph5->SetLineStyle(0);
   Graph_Graph5->SetMarkerStyle(20);
   Graph_Graph5->GetXaxis()->SetLabelFont(43);
   Graph_Graph5->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph5->GetXaxis()->SetLabelSize(27);
   Graph_Graph5->GetXaxis()->SetTitleSize(33);
   Graph_Graph5->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph5->GetXaxis()->SetTitleFont(43);
   Graph_Graph5->GetYaxis()->SetLabelFont(43);
   Graph_Graph5->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph5->GetYaxis()->SetLabelSize(27);
   Graph_Graph5->GetYaxis()->SetTitleSize(33);
   Graph_Graph5->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph5->GetYaxis()->SetTitleFont(43);
   Graph_Graph5->GetZaxis()->SetLabelFont(43);
   Graph_Graph5->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph5->GetZaxis()->SetLabelSize(27);
   Graph_Graph5->GetZaxis()->SetTitleSize(33);
   Graph_Graph5->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph5);
   
   graph->Draw("l");
   
   TH1F *hframe__32 = new TH1F("hframe__32","",1000,0,400);
   hframe__32->SetMinimum(0.7042185);
   hframe__32->SetMaximum(1.628691);
   hframe__32->SetDirectory(0);
   hframe__32->SetStats(0);
   hframe__32->SetLineStyle(0);
   hframe__32->SetMarkerStyle(20);
   hframe__32->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__32->GetXaxis()->SetLabelFont(43);
   hframe__32->GetXaxis()->SetLabelOffset(0.007);
   hframe__32->GetXaxis()->SetLabelSize(27);
   hframe__32->GetXaxis()->SetTitleSize(33);
   hframe__32->GetXaxis()->SetTitleOffset(2.925);
   hframe__32->GetXaxis()->SetTitleFont(43);
   hframe__32->GetYaxis()->SetTitle("Ratio");
   hframe__32->GetYaxis()->SetNdivisions(505);
   hframe__32->GetYaxis()->SetLabelFont(43);
   hframe__32->GetYaxis()->SetLabelOffset(0.007);
   hframe__32->GetYaxis()->SetLabelSize(21);
   hframe__32->GetYaxis()->SetTitleSize(33);
   hframe__32->GetYaxis()->SetTitleOffset(1.796875);
   hframe__32->GetYaxis()->SetTitleFont(43);
   hframe__32->GetZaxis()->SetLabelFont(43);
   hframe__32->GetZaxis()->SetLabelOffset(0.007);
   hframe__32->GetZaxis()->SetLabelSize(27);
   hframe__32->GetZaxis()->SetTitleSize(33);
   hframe__32->GetZaxis()->SetTitleFont(43);
   hframe__32->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->Range(-81.01265,-2.854876,425.3165,33.17621);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__33 = new TH1F("hframe__33","",1000,0,400);
   hframe__33->SetMinimum(1.829165);
   hframe__33->SetMaximum(31.37465);
   hframe__33->SetDirectory(0);
   hframe__33->SetStats(0);
   hframe__33->SetLineStyle(0);
   hframe__33->SetMarkerStyle(20);
   hframe__33->GetXaxis()->SetLabelFont(43);
   hframe__33->GetXaxis()->SetLabelOffset(0.007);
   hframe__33->GetXaxis()->SetLabelSize(0);
   hframe__33->GetXaxis()->SetTitleSize(0);
   hframe__33->GetXaxis()->SetTitleOffset(0.9);
   hframe__33->GetXaxis()->SetTitleFont(43);
   hframe__33->GetYaxis()->SetTitle("N_{events}");
   hframe__33->GetYaxis()->SetLabelFont(43);
   hframe__33->GetYaxis()->SetLabelOffset(0.007);
   hframe__33->GetYaxis()->SetLabelSize(27);
   hframe__33->GetYaxis()->SetTitleSize(33);
   hframe__33->GetYaxis()->SetTitleOffset(1.796875);
   hframe__33->GetYaxis()->SetTitleFont(43);
   hframe__33->GetZaxis()->SetLabelFont(43);
   hframe__33->GetZaxis()->SetLabelOffset(0.007);
   hframe__33->GetZaxis()->SetLabelSize(27);
   hframe__33->GetZaxis()->SetTitleSize(33);
   hframe__33->GetZaxis()->SetTitleFont(43);
   hframe__33->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis23[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis23);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.708313);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.117852);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,9.266926);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,12.50275);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,18.61256);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,28.52241);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,23.26699);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,15.73869);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,15.36124);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,6.525952);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1395273);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.5475685);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.6409827);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.035354);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.161829);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.247112);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.485037);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.341849);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,1.102417);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,1.092012);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.7033533);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.08055611);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis24[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis24);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,14.85644);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,22.45671);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,17.3683);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,11.6141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.31415);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,4.982014);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.1389271);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9927686);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.168366);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.004578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.8145114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.8011357);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.525429);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.08020962);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis25[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis25);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,20.61114);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.68624);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,22.78992);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,16.49218);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,13.35154);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,6.295283);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.1276645);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.984329);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.96608);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.760173);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.614869);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.323627);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.605844);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.08065877);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(901.3783);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__34 = new TH1F("hframe__34","",1000,0,400);
   hframe__34->SetMinimum(1.829165);
   hframe__34->SetMaximum(31.37465);
   hframe__34->SetDirectory(0);
   hframe__34->SetStats(0);
   hframe__34->SetLineStyle(0);
   hframe__34->SetMarkerStyle(20);
   hframe__34->GetXaxis()->SetLabelFont(43);
   hframe__34->GetXaxis()->SetLabelOffset(0.007);
   hframe__34->GetXaxis()->SetLabelSize(0);
   hframe__34->GetXaxis()->SetTitleSize(0);
   hframe__34->GetXaxis()->SetTitleOffset(0.9);
   hframe__34->GetXaxis()->SetTitleFont(43);
   hframe__34->GetYaxis()->SetTitle("N_{events}");
   hframe__34->GetYaxis()->SetLabelFont(43);
   hframe__34->GetYaxis()->SetLabelOffset(0.007);
   hframe__34->GetYaxis()->SetLabelSize(27);
   hframe__34->GetYaxis()->SetTitleSize(33);
   hframe__34->GetYaxis()->SetTitleOffset(1.796875);
   hframe__34->GetYaxis()->SetTitleFont(43);
   hframe__34->GetZaxis()->SetLabelFont(43);
   hframe__34->GetZaxis()->SetLabelOffset(0.007);
   hframe__34->GetZaxis()->SetLabelSize(27);
   hframe__34->GetZaxis()->SetTitleSize(33);
   hframe__34->GetZaxis()->SetTitleFont(43);
   hframe__34->Draw("sameaxis");
   
   TH1F *hframe__35 = new TH1F("hframe__35","",1000,0,400);
   hframe__35->SetMinimum(1.829165);
   hframe__35->SetMaximum(31.37465);
   hframe__35->SetDirectory(0);
   hframe__35->SetStats(0);
   hframe__35->SetLineStyle(0);
   hframe__35->SetMarkerStyle(20);
   hframe__35->GetXaxis()->SetLabelFont(43);
   hframe__35->GetXaxis()->SetLabelOffset(0.007);
   hframe__35->GetXaxis()->SetLabelSize(0);
   hframe__35->GetXaxis()->SetTitleSize(0);
   hframe__35->GetXaxis()->SetTitleOffset(0.9);
   hframe__35->GetXaxis()->SetTitleFont(43);
   hframe__35->GetYaxis()->SetTitle("N_{events}");
   hframe__35->GetYaxis()->SetLabelFont(43);
   hframe__35->GetYaxis()->SetLabelOffset(0.007);
   hframe__35->GetYaxis()->SetLabelSize(27);
   hframe__35->GetYaxis()->SetTitleSize(33);
   hframe__35->GetYaxis()->SetTitleOffset(1.796875);
   hframe__35->GetYaxis()->SetTitleFont(43);
   hframe__35->GetZaxis()->SetLabelFont(43);
   hframe__35->GetZaxis()->SetLabelOffset(0.007);
   hframe__35->GetZaxis()->SetLabelSize(27);
   hframe__35->GetZaxis()->SetTitleSize(33);
   hframe__35->GetZaxis()->SetTitleFont(43);
   hframe__35->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.6_QCDTailKillerLoosePlus);
}
