{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus
//=========  (Wed Jul 30 13:56:55 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->Range(-81.01265,0.09368099,425.3165,1.754896);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__190 = new TH1F("hframe__190","",1000,0,400);
   hframe__190->SetMinimum(0.5754333);
   hframe__190->SetMaximum(1.754896);
   hframe__190->SetDirectory(0);
   hframe__190->SetStats(0);
   hframe__190->SetLineStyle(0);
   hframe__190->SetMarkerStyle(20);
   hframe__190->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__190->GetXaxis()->SetLabelFont(43);
   hframe__190->GetXaxis()->SetLabelOffset(0.007);
   hframe__190->GetXaxis()->SetLabelSize(27);
   hframe__190->GetXaxis()->SetTitleSize(33);
   hframe__190->GetXaxis()->SetTitleOffset(2.925);
   hframe__190->GetXaxis()->SetTitleFont(43);
   hframe__190->GetYaxis()->SetTitle("Ratio");
   hframe__190->GetYaxis()->SetNdivisions(505);
   hframe__190->GetYaxis()->SetLabelFont(43);
   hframe__190->GetYaxis()->SetLabelOffset(0.007);
   hframe__190->GetYaxis()->SetLabelSize(21);
   hframe__190->GetYaxis()->SetTitleSize(33);
   hframe__190->GetYaxis()->SetTitleOffset(1.796875);
   hframe__190->GetYaxis()->SetTitleFont(43);
   hframe__190->GetZaxis()->SetLabelFont(43);
   hframe__190->GetZaxis()->SetLabelOffset(0.007);
   hframe__190->GetZaxis()->SetLabelSize(27);
   hframe__190->GetZaxis()->SetTitleSize(33);
   hframe__190->GetZaxis()->SetTitleFont(43);
   hframe__190->Draw(" ");
   Double_t xAxis136[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191","#tau p_{T}<50",10, xAxis136);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(1,1.523764);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(2,0.93552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(3,1.102776);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(4,1.084577);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(5,1.025615);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(6,1.230964);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(7,0.7672505);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(8,0.9289689);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(9,1.59536);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinContent(10,0.9345812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(1,0.478693);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(2,0.3425138);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(3,0.2108915);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(4,0.1957423);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(5,0.187064);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(6,0.230528);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(7,0.1812981);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(8,0.2808383);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(9,0.7001997);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetBinError(10,0.4625022);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetEntries(92.89848);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__191->Draw("EP same");
   Double_t xAxis137[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192","#tau p_{T}<50",10, xAxis137);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(5,0.7852051);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(6,0.9266732);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(7,0.5754333);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(8,0.6842363);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(9,1.174884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinContent(10,0.6684515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(5,0.1431421);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(6,0.1733767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(7,0.1358588);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(8,0.2067999);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(9,0.5152653);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetBinError(10,0.3299514);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetEntries(94.75576);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__192->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph28 = new TH1F("Graph_Graph28","Graph",100,0,440);
   Graph_Graph28->SetMinimum(0.9);
   Graph_Graph28->SetMaximum(2.1);
   Graph_Graph28->SetDirectory(0);
   Graph_Graph28->SetStats(0);
   Graph_Graph28->SetLineStyle(0);
   Graph_Graph28->SetMarkerStyle(20);
   Graph_Graph28->GetXaxis()->SetLabelFont(43);
   Graph_Graph28->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph28->GetXaxis()->SetLabelSize(27);
   Graph_Graph28->GetXaxis()->SetTitleSize(33);
   Graph_Graph28->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph28->GetXaxis()->SetTitleFont(43);
   Graph_Graph28->GetYaxis()->SetLabelFont(43);
   Graph_Graph28->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph28->GetYaxis()->SetLabelSize(27);
   Graph_Graph28->GetYaxis()->SetTitleSize(33);
   Graph_Graph28->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph28->GetYaxis()->SetTitleFont(43);
   Graph_Graph28->GetZaxis()->SetLabelFont(43);
   Graph_Graph28->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph28->GetZaxis()->SetLabelSize(27);
   Graph_Graph28->GetZaxis()->SetTitleSize(33);
   Graph_Graph28->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph28);
   
   graph->Draw("l");
   
   TH1F *hframe__193 = new TH1F("hframe__193","",1000,0,400);
   hframe__193->SetMinimum(0.5754333);
   hframe__193->SetMaximum(1.754896);
   hframe__193->SetDirectory(0);
   hframe__193->SetStats(0);
   hframe__193->SetLineStyle(0);
   hframe__193->SetMarkerStyle(20);
   hframe__193->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__193->GetXaxis()->SetLabelFont(43);
   hframe__193->GetXaxis()->SetLabelOffset(0.007);
   hframe__193->GetXaxis()->SetLabelSize(27);
   hframe__193->GetXaxis()->SetTitleSize(33);
   hframe__193->GetXaxis()->SetTitleOffset(2.925);
   hframe__193->GetXaxis()->SetTitleFont(43);
   hframe__193->GetYaxis()->SetTitle("Ratio");
   hframe__193->GetYaxis()->SetNdivisions(505);
   hframe__193->GetYaxis()->SetLabelFont(43);
   hframe__193->GetYaxis()->SetLabelOffset(0.007);
   hframe__193->GetYaxis()->SetLabelSize(21);
   hframe__193->GetYaxis()->SetTitleSize(33);
   hframe__193->GetYaxis()->SetTitleOffset(1.796875);
   hframe__193->GetYaxis()->SetTitleFont(43);
   hframe__193->GetZaxis()->SetLabelFont(43);
   hframe__193->GetZaxis()->SetLabelOffset(0.007);
   hframe__193->GetZaxis()->SetLabelSize(27);
   hframe__193->GetZaxis()->SetTitleSize(33);
   hframe__193->GetZaxis()->SetTitleFont(43);
   hframe__193->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->Range(-81.01265,-0.7303868,425.3165,15.91497);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__194 = new TH1F("hframe__194","",1000,0,400);
   hframe__194->SetMinimum(1.433509);
   hframe__194->SetMaximum(15.0827);
   hframe__194->SetDirectory(0);
   hframe__194->SetStats(0);
   hframe__194->SetLineStyle(0);
   hframe__194->SetMarkerStyle(20);
   hframe__194->GetXaxis()->SetLabelFont(43);
   hframe__194->GetXaxis()->SetLabelOffset(0.007);
   hframe__194->GetXaxis()->SetLabelSize(0);
   hframe__194->GetXaxis()->SetTitleSize(0);
   hframe__194->GetXaxis()->SetTitleOffset(0.9);
   hframe__194->GetXaxis()->SetTitleFont(43);
   hframe__194->GetYaxis()->SetTitle("N_{events}");
   hframe__194->GetYaxis()->SetLabelFont(43);
   hframe__194->GetYaxis()->SetLabelOffset(0.007);
   hframe__194->GetYaxis()->SetLabelSize(27);
   hframe__194->GetYaxis()->SetTitleSize(33);
   hframe__194->GetYaxis()->SetTitleOffset(1.796875);
   hframe__194->GetYaxis()->SetTitleFont(43);
   hframe__194->GetZaxis()->SetLabelFont(43);
   hframe__194->GetZaxis()->SetLabelOffset(0.007);
   hframe__194->GetZaxis()->SetLabelSize(27);
   hframe__194->GetZaxis()->SetTitleSize(33);
   hframe__194->GetZaxis()->SetTitleFont(43);
   hframe__194->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis138[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis138);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.787216);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.193725);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,9.529875);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,12.85609);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,13.71155);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,11.33124);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,8.171209);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,5.749051);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,4.799375);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,2.00423);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.5636042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.6579486);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.06396);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.194639);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.110336);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,0.9770708);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.8178332);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.6719209);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.6265353);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.4222003);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis139[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis139);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,10.49748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,8.530189);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.128358);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.23449);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.534443);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.433509);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8478657);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7322293);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6105065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4940598);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4574585);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.2976706);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis140[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis140);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,13.36909);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.205174);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,10.64999);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,6.188637);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.008334);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,2.144523);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,-0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.184911);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.530287);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.279653);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,1.725427);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,1.260593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.9603232);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(420.2798);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__195 = new TH1F("hframe__195","",1000,0,400);
   hframe__195->SetMinimum(1.433509);
   hframe__195->SetMaximum(15.0827);
   hframe__195->SetDirectory(0);
   hframe__195->SetStats(0);
   hframe__195->SetLineStyle(0);
   hframe__195->SetMarkerStyle(20);
   hframe__195->GetXaxis()->SetLabelFont(43);
   hframe__195->GetXaxis()->SetLabelOffset(0.007);
   hframe__195->GetXaxis()->SetLabelSize(0);
   hframe__195->GetXaxis()->SetTitleSize(0);
   hframe__195->GetXaxis()->SetTitleOffset(0.9);
   hframe__195->GetXaxis()->SetTitleFont(43);
   hframe__195->GetYaxis()->SetTitle("N_{events}");
   hframe__195->GetYaxis()->SetLabelFont(43);
   hframe__195->GetYaxis()->SetLabelOffset(0.007);
   hframe__195->GetYaxis()->SetLabelSize(27);
   hframe__195->GetYaxis()->SetTitleSize(33);
   hframe__195->GetYaxis()->SetTitleOffset(1.796875);
   hframe__195->GetYaxis()->SetTitleFont(43);
   hframe__195->GetZaxis()->SetLabelFont(43);
   hframe__195->GetZaxis()->SetLabelOffset(0.007);
   hframe__195->GetZaxis()->SetLabelSize(27);
   hframe__195->GetZaxis()->SetTitleSize(33);
   hframe__195->GetZaxis()->SetTitleFont(43);
   hframe__195->Draw("sameaxis");
   
   TH1F *hframe__196 = new TH1F("hframe__196","",1000,0,400);
   hframe__196->SetMinimum(1.433509);
   hframe__196->SetMaximum(15.0827);
   hframe__196->SetDirectory(0);
   hframe__196->SetStats(0);
   hframe__196->SetLineStyle(0);
   hframe__196->SetMarkerStyle(20);
   hframe__196->GetXaxis()->SetLabelFont(43);
   hframe__196->GetXaxis()->SetLabelOffset(0.007);
   hframe__196->GetXaxis()->SetLabelSize(0);
   hframe__196->GetXaxis()->SetTitleSize(0);
   hframe__196->GetXaxis()->SetTitleOffset(0.9);
   hframe__196->GetXaxis()->SetTitleFont(43);
   hframe__196->GetYaxis()->SetTitle("N_{events}");
   hframe__196->GetYaxis()->SetLabelFont(43);
   hframe__196->GetYaxis()->SetLabelOffset(0.007);
   hframe__196->GetYaxis()->SetLabelSize(27);
   hframe__196->GetYaxis()->SetTitleSize(33);
   hframe__196->GetYaxis()->SetTitleOffset(1.796875);
   hframe__196->GetYaxis()->SetTitleFont(43);
   hframe__196->GetZaxis()->SetLabelFont(43);
   hframe__196->GetZaxis()->SetLabelOffset(0.007);
   hframe__196->GetZaxis()->SetLabelSize(27);
   hframe__196->GetZaxis()->SetTitleSize(33);
   hframe__196->GetZaxis()->SetTitleFont(43);
   hframe__196->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.55_QCDTailKillerTightPlus);
}
