{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus/Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus
//=========  (Wed Jul 30 13:56:46 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->Range(-81.01265,0.4016473,425.3165,1.391443);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__148 = new TH1F("hframe__148","",1000,0,400);
   hframe__148->SetMinimum(0.6886879);
   hframe__148->SetMaximum(1.391443);
   hframe__148->SetDirectory(0);
   hframe__148->SetStats(0);
   hframe__148->SetLineStyle(0);
   hframe__148->SetMarkerStyle(20);
   hframe__148->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__148->GetXaxis()->SetLabelFont(43);
   hframe__148->GetXaxis()->SetLabelOffset(0.007);
   hframe__148->GetXaxis()->SetLabelSize(27);
   hframe__148->GetXaxis()->SetTitleSize(33);
   hframe__148->GetXaxis()->SetTitleOffset(2.925);
   hframe__148->GetXaxis()->SetTitleFont(43);
   hframe__148->GetYaxis()->SetTitle("Ratio");
   hframe__148->GetYaxis()->SetNdivisions(505);
   hframe__148->GetYaxis()->SetLabelFont(43);
   hframe__148->GetYaxis()->SetLabelOffset(0.007);
   hframe__148->GetYaxis()->SetLabelSize(21);
   hframe__148->GetYaxis()->SetTitleSize(33);
   hframe__148->GetYaxis()->SetTitleOffset(1.796875);
   hframe__148->GetYaxis()->SetTitleFont(43);
   hframe__148->GetZaxis()->SetLabelFont(43);
   hframe__148->GetZaxis()->SetLabelOffset(0.007);
   hframe__148->GetZaxis()->SetLabelSize(27);
   hframe__148->GetZaxis()->SetTitleSize(33);
   hframe__148->GetZaxis()->SetTitleFont(43);
   hframe__148->Draw(" ");
   Double_t xAxis106[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149","#tau p_{T}<50",10, xAxis106);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(1,1.264948);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(2,0.8021701);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(3,0.920208);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(4,0.9057246);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(5,0.7652153);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(6,1.084668);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(7,0.8147142);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(8,0.7760211);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(9,0.9197235);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(10,0.7765349);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinContent(11,1.138059);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(1,0.3974783);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(2,0.2925231);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(3,0.1763727);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(4,0.163542);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(5,0.1301865);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(6,0.144781);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(7,0.1429156);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(8,0.1820958);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(9,0.2558806);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(10,0.2703341);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetBinError(11,1.224977);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetEntries(153.4253);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__149->Draw("EP same");
   Double_t xAxis107[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150","#tau p_{T}<50",10, xAxis107);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(5,0.6969547);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(6,0.978788);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(7,0.7266998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(8,0.6886879);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(9,0.8167623);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(10,0.6924216);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinContent(11,1.136218);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(5,0.118574);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(6,0.1306626);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(7,0.1275215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(8,0.1616419);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(9,0.2272129);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(10,0.2408043);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetBinError(11,1.222996);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetEntries(153.3889);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__150->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph22 = new TH1F("Graph_Graph22","Graph",100,0,440);
   Graph_Graph22->SetMinimum(0.9);
   Graph_Graph22->SetMaximum(2.1);
   Graph_Graph22->SetDirectory(0);
   Graph_Graph22->SetStats(0);
   Graph_Graph22->SetLineStyle(0);
   Graph_Graph22->SetMarkerStyle(20);
   Graph_Graph22->GetXaxis()->SetLabelFont(43);
   Graph_Graph22->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph22->GetXaxis()->SetLabelSize(27);
   Graph_Graph22->GetXaxis()->SetTitleSize(33);
   Graph_Graph22->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph22->GetXaxis()->SetTitleFont(43);
   Graph_Graph22->GetYaxis()->SetLabelFont(43);
   Graph_Graph22->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph22->GetYaxis()->SetLabelSize(27);
   Graph_Graph22->GetYaxis()->SetTitleSize(33);
   Graph_Graph22->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph22->GetYaxis()->SetTitleFont(43);
   Graph_Graph22->GetZaxis()->SetLabelFont(43);
   Graph_Graph22->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph22->GetZaxis()->SetLabelSize(27);
   Graph_Graph22->GetZaxis()->SetTitleSize(33);
   Graph_Graph22->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph22);
   
   graph->Draw("l");
   
   TH1F *hframe__151 = new TH1F("hframe__151","",1000,0,400);
   hframe__151->SetMinimum(0.6886879);
   hframe__151->SetMaximum(1.391443);
   hframe__151->SetDirectory(0);
   hframe__151->SetStats(0);
   hframe__151->SetLineStyle(0);
   hframe__151->SetMarkerStyle(20);
   hframe__151->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__151->GetXaxis()->SetLabelFont(43);
   hframe__151->GetXaxis()->SetLabelOffset(0.007);
   hframe__151->GetXaxis()->SetLabelSize(27);
   hframe__151->GetXaxis()->SetTitleSize(33);
   hframe__151->GetXaxis()->SetTitleOffset(2.925);
   hframe__151->GetXaxis()->SetTitleFont(43);
   hframe__151->GetYaxis()->SetTitle("Ratio");
   hframe__151->GetYaxis()->SetNdivisions(505);
   hframe__151->GetYaxis()->SetLabelFont(43);
   hframe__151->GetYaxis()->SetLabelOffset(0.007);
   hframe__151->GetYaxis()->SetLabelSize(21);
   hframe__151->GetYaxis()->SetTitleSize(33);
   hframe__151->GetYaxis()->SetTitleOffset(1.796875);
   hframe__151->GetYaxis()->SetTitleFont(43);
   hframe__151->GetZaxis()->SetLabelFont(43);
   hframe__151->GetZaxis()->SetLabelOffset(0.007);
   hframe__151->GetZaxis()->SetLabelSize(27);
   hframe__151->GetZaxis()->SetTitleSize(33);
   hframe__151->GetZaxis()->SetTitleFont(43);
   hframe__151->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->Range(-81.01265,-1.226501,425.3165,22.27862);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__152 = new TH1F("hframe__152","",1000,0,400);
   hframe__152->SetMinimum(1.829165);
   hframe__152->SetMaximum(21.10336);
   hframe__152->SetDirectory(0);
   hframe__152->SetStats(0);
   hframe__152->SetLineStyle(0);
   hframe__152->SetMarkerStyle(20);
   hframe__152->GetXaxis()->SetLabelFont(43);
   hframe__152->GetXaxis()->SetLabelOffset(0.007);
   hframe__152->GetXaxis()->SetLabelSize(0);
   hframe__152->GetXaxis()->SetTitleSize(0);
   hframe__152->GetXaxis()->SetTitleOffset(0.9);
   hframe__152->GetXaxis()->SetTitleFont(43);
   hframe__152->GetYaxis()->SetTitle("N_{events}");
   hframe__152->GetYaxis()->SetLabelFont(43);
   hframe__152->GetYaxis()->SetLabelOffset(0.007);
   hframe__152->GetYaxis()->SetLabelSize(27);
   hframe__152->GetYaxis()->SetTitleSize(33);
   hframe__152->GetYaxis()->SetTitleOffset(1.796875);
   hframe__152->GetYaxis()->SetTitleFont(43);
   hframe__152->GetZaxis()->SetLabelFont(43);
   hframe__152->GetZaxis()->SetLabelOffset(0.007);
   hframe__152->GetZaxis()->SetLabelSize(27);
   hframe__152->GetZaxis()->SetTitleSize(33);
   hframe__152->GetZaxis()->SetTitleFont(43);
   hframe__152->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Medium");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis108[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis108);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.313798);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.738488);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,7.952172);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,10.73606);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,14.68056);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,16.09764);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,12.28425);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,7.972788);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,7.059105);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,3.213661);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.09276813);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4681381);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5570437);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.8936521);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.9994455);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.037882);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.045333);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.9055981);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.7228011);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.6779568);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.4548631);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.06559697);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis109[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis109);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,13.37099);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,14.52627);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,10.95717);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,7.075533);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,6.268853);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,2.865561);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.09261809);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9453297);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.9437324);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.8093866);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.6424967);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.6015612);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.4030667);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.06549088);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis110[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis110);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,19.18487);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,14.84108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,15.07799);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,10.27393);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,7.675248);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,4.138463);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.08151437);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.968778);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.73075);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.400046);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.223616);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.004103);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.316265);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.06615137);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(613.1472);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__153 = new TH1F("hframe__153","",1000,0,400);
   hframe__153->SetMinimum(1.829165);
   hframe__153->SetMaximum(21.10336);
   hframe__153->SetDirectory(0);
   hframe__153->SetStats(0);
   hframe__153->SetLineStyle(0);
   hframe__153->SetMarkerStyle(20);
   hframe__153->GetXaxis()->SetLabelFont(43);
   hframe__153->GetXaxis()->SetLabelOffset(0.007);
   hframe__153->GetXaxis()->SetLabelSize(0);
   hframe__153->GetXaxis()->SetTitleSize(0);
   hframe__153->GetXaxis()->SetTitleOffset(0.9);
   hframe__153->GetXaxis()->SetTitleFont(43);
   hframe__153->GetYaxis()->SetTitle("N_{events}");
   hframe__153->GetYaxis()->SetLabelFont(43);
   hframe__153->GetYaxis()->SetLabelOffset(0.007);
   hframe__153->GetYaxis()->SetLabelSize(27);
   hframe__153->GetYaxis()->SetTitleSize(33);
   hframe__153->GetYaxis()->SetTitleOffset(1.796875);
   hframe__153->GetYaxis()->SetTitleFont(43);
   hframe__153->GetZaxis()->SetLabelFont(43);
   hframe__153->GetZaxis()->SetLabelOffset(0.007);
   hframe__153->GetZaxis()->SetLabelSize(27);
   hframe__153->GetZaxis()->SetTitleSize(33);
   hframe__153->GetZaxis()->SetTitleFont(43);
   hframe__153->Draw("sameaxis");
   
   TH1F *hframe__154 = new TH1F("hframe__154","",1000,0,400);
   hframe__154->SetMinimum(1.829165);
   hframe__154->SetMaximum(21.10336);
   hframe__154->SetDirectory(0);
   hframe__154->SetStats(0);
   hframe__154->SetLineStyle(0);
   hframe__154->SetMarkerStyle(20);
   hframe__154->GetXaxis()->SetLabelFont(43);
   hframe__154->GetXaxis()->SetLabelOffset(0.007);
   hframe__154->GetXaxis()->SetLabelSize(0);
   hframe__154->GetXaxis()->SetTitleSize(0);
   hframe__154->GetXaxis()->SetTitleOffset(0.9);
   hframe__154->GetXaxis()->SetTitleFont(43);
   hframe__154->GetYaxis()->SetTitle("N_{events}");
   hframe__154->GetYaxis()->SetLabelFont(43);
   hframe__154->GetYaxis()->SetLabelOffset(0.007);
   hframe__154->GetYaxis()->SetLabelSize(27);
   hframe__154->GetYaxis()->SetTitleSize(33);
   hframe__154->GetYaxis()->SetTitleOffset(1.796875);
   hframe__154->GetYaxis()->SetTitleFont(43);
   hframe__154->GetZaxis()->SetLabelFont(43);
   hframe__154->GetZaxis()->SetLabelOffset(0.007);
   hframe__154->GetZaxis()->SetLabelSize(27);
   hframe__154->GetZaxis()->SetTitleSize(33);
   hframe__154->GetZaxis()->SetTitleFont(43);
   hframe__154->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus->SetSelected(Mt_DataDrivenVsMC_w=0.85_QCDTailKillerMediumPlus);
}
