{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus
//=========  (Wed Jul 30 13:57:01 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->Range(-81.01265,0.1566536,425.3165,1.600721);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__211 = new TH1F("hframe__211","",1000,0,400);
   hframe__211->SetMinimum(0.5754333);
   hframe__211->SetMaximum(1.600721);
   hframe__211->SetDirectory(0);
   hframe__211->SetStats(0);
   hframe__211->SetLineStyle(0);
   hframe__211->SetMarkerStyle(20);
   hframe__211->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__211->GetXaxis()->SetLabelFont(43);
   hframe__211->GetXaxis()->SetLabelOffset(0.007);
   hframe__211->GetXaxis()->SetLabelSize(27);
   hframe__211->GetXaxis()->SetTitleSize(33);
   hframe__211->GetXaxis()->SetTitleOffset(2.925);
   hframe__211->GetXaxis()->SetTitleFont(43);
   hframe__211->GetYaxis()->SetTitle("Ratio");
   hframe__211->GetYaxis()->SetNdivisions(505);
   hframe__211->GetYaxis()->SetLabelFont(43);
   hframe__211->GetYaxis()->SetLabelOffset(0.007);
   hframe__211->GetYaxis()->SetLabelSize(21);
   hframe__211->GetYaxis()->SetTitleSize(33);
   hframe__211->GetYaxis()->SetTitleOffset(1.796875);
   hframe__211->GetYaxis()->SetTitleFont(43);
   hframe__211->GetZaxis()->SetLabelFont(43);
   hframe__211->GetZaxis()->SetLabelOffset(0.007);
   hframe__211->GetZaxis()->SetLabelSize(27);
   hframe__211->GetZaxis()->SetTitleSize(33);
   hframe__211->GetZaxis()->SetTitleFont(43);
   hframe__211->Draw(" ");
   Double_t xAxis151[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212","#tau p_{T}<50",10, xAxis151);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(1,1.394356);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(2,0.8688451);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(3,1.011492);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(4,0.9951507);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(5,0.9454786);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(6,1.129534);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(7,0.7033114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(8,0.8473913);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(9,1.455201);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinContent(10,0.8458713);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(1,0.4380018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(2,0.3174708);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(3,0.1936033);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(4,0.1796192);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(5,0.1723881);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(6,0.2114309);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(7,0.1661148);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(8,0.2561075);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(9,0.6384756);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetBinError(10,0.418201);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetEntries(93.45504);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__212->Draw("EP same");
   Double_t xAxis152[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213","#tau p_{T}<50",10, xAxis152);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(5,0.7852051);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(6,0.9266732);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(7,0.5754333);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(8,0.6842363);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(9,1.174884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinContent(10,0.6684515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(5,0.1431421);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(6,0.1733767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(7,0.1358588);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(8,0.2067999);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(9,0.5152653);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetBinError(10,0.3299514);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetEntries(94.75576);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__213->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph31 = new TH1F("Graph_Graph31","Graph",100,0,440);
   Graph_Graph31->SetMinimum(0.9);
   Graph_Graph31->SetMaximum(2.1);
   Graph_Graph31->SetDirectory(0);
   Graph_Graph31->SetStats(0);
   Graph_Graph31->SetLineStyle(0);
   Graph_Graph31->SetMarkerStyle(20);
   Graph_Graph31->GetXaxis()->SetLabelFont(43);
   Graph_Graph31->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph31->GetXaxis()->SetLabelSize(27);
   Graph_Graph31->GetXaxis()->SetTitleSize(33);
   Graph_Graph31->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph31->GetXaxis()->SetTitleFont(43);
   Graph_Graph31->GetYaxis()->SetLabelFont(43);
   Graph_Graph31->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph31->GetYaxis()->SetLabelSize(27);
   Graph_Graph31->GetYaxis()->SetTitleSize(33);
   Graph_Graph31->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph31->GetYaxis()->SetTitleFont(43);
   Graph_Graph31->GetZaxis()->SetLabelFont(43);
   Graph_Graph31->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph31->GetZaxis()->SetLabelSize(27);
   Graph_Graph31->GetZaxis()->SetTitleSize(33);
   Graph_Graph31->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph31);
   
   graph->Draw("l");
   
   TH1F *hframe__214 = new TH1F("hframe__214","",1000,0,400);
   hframe__214->SetMinimum(0.5754333);
   hframe__214->SetMaximum(1.600721);
   hframe__214->SetDirectory(0);
   hframe__214->SetStats(0);
   hframe__214->SetLineStyle(0);
   hframe__214->SetMarkerStyle(20);
   hframe__214->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__214->GetXaxis()->SetLabelFont(43);
   hframe__214->GetXaxis()->SetLabelOffset(0.007);
   hframe__214->GetXaxis()->SetLabelSize(27);
   hframe__214->GetXaxis()->SetTitleSize(33);
   hframe__214->GetXaxis()->SetTitleOffset(2.925);
   hframe__214->GetXaxis()->SetTitleFont(43);
   hframe__214->GetYaxis()->SetTitle("Ratio");
   hframe__214->GetYaxis()->SetNdivisions(505);
   hframe__214->GetYaxis()->SetLabelFont(43);
   hframe__214->GetYaxis()->SetLabelOffset(0.007);
   hframe__214->GetYaxis()->SetLabelSize(21);
   hframe__214->GetYaxis()->SetTitleSize(33);
   hframe__214->GetYaxis()->SetTitleOffset(1.796875);
   hframe__214->GetYaxis()->SetTitleFont(43);
   hframe__214->GetZaxis()->SetLabelFont(43);
   hframe__214->GetZaxis()->SetLabelOffset(0.007);
   hframe__214->GetZaxis()->SetLabelSize(27);
   hframe__214->GetZaxis()->SetTitleSize(33);
   hframe__214->GetZaxis()->SetTitleFont(43);
   hframe__214->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->Range(-81.01265,-0.6706663,425.3165,15.5153);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__215 = new TH1F("hframe__215","",1000,0,400);
   hframe__215->SetMinimum(1.433509);
   hframe__215->SetMaximum(14.706);
   hframe__215->SetDirectory(0);
   hframe__215->SetStats(0);
   hframe__215->SetLineStyle(0);
   hframe__215->SetMarkerStyle(20);
   hframe__215->GetXaxis()->SetLabelFont(43);
   hframe__215->GetXaxis()->SetLabelOffset(0.007);
   hframe__215->GetXaxis()->SetLabelSize(0);
   hframe__215->GetXaxis()->SetTitleSize(0);
   hframe__215->GetXaxis()->SetTitleOffset(0.9);
   hframe__215->GetXaxis()->SetTitleFont(43);
   hframe__215->GetYaxis()->SetTitle("N_{events}");
   hframe__215->GetYaxis()->SetLabelFont(43);
   hframe__215->GetYaxis()->SetLabelOffset(0.007);
   hframe__215->GetYaxis()->SetLabelSize(27);
   hframe__215->GetYaxis()->SetTitleSize(33);
   hframe__215->GetYaxis()->SetTitleOffset(1.796875);
   hframe__215->GetYaxis()->SetTitleFont(43);
   hframe__215->GetZaxis()->SetLabelFont(43);
   hframe__215->GetZaxis()->SetLabelOffset(0.007);
   hframe__215->GetZaxis()->SetLabelSize(27);
   hframe__215->GetZaxis()->SetTitleSize(33);
   hframe__215->GetZaxis()->SetTitleFont(43);
   hframe__215->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis153[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis153);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.550507);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.966107);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,8.741025);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,11.79607);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,12.64019);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,10.39756);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,7.490259);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,5.244197);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,4.377731);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,1.81399);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.5156328);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.6072142);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.9783837);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.096514);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.021783);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,0.8945238);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.7477959);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.6118121);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.5693756);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.3801019);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis154[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis154);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,10.49748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,8.530189);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.128358);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.23449);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.534443);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.433509);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8478657);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7322293);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6105065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4940598);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4574585);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.2976706);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis155[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis155);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,13.36909);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.205174);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,10.64999);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,6.188637);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.008334);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,2.144523);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,-0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.184911);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.530287);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.279653);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,1.725427);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,1.260593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.9603232);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(420.2798);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__216 = new TH1F("hframe__216","",1000,0,400);
   hframe__216->SetMinimum(1.433509);
   hframe__216->SetMaximum(14.706);
   hframe__216->SetDirectory(0);
   hframe__216->SetStats(0);
   hframe__216->SetLineStyle(0);
   hframe__216->SetMarkerStyle(20);
   hframe__216->GetXaxis()->SetLabelFont(43);
   hframe__216->GetXaxis()->SetLabelOffset(0.007);
   hframe__216->GetXaxis()->SetLabelSize(0);
   hframe__216->GetXaxis()->SetTitleSize(0);
   hframe__216->GetXaxis()->SetTitleOffset(0.9);
   hframe__216->GetXaxis()->SetTitleFont(43);
   hframe__216->GetYaxis()->SetTitle("N_{events}");
   hframe__216->GetYaxis()->SetLabelFont(43);
   hframe__216->GetYaxis()->SetLabelOffset(0.007);
   hframe__216->GetYaxis()->SetLabelSize(27);
   hframe__216->GetYaxis()->SetTitleSize(33);
   hframe__216->GetYaxis()->SetTitleOffset(1.796875);
   hframe__216->GetYaxis()->SetTitleFont(43);
   hframe__216->GetZaxis()->SetLabelFont(43);
   hframe__216->GetZaxis()->SetLabelOffset(0.007);
   hframe__216->GetZaxis()->SetLabelSize(27);
   hframe__216->GetZaxis()->SetTitleSize(33);
   hframe__216->GetZaxis()->SetTitleFont(43);
   hframe__216->Draw("sameaxis");
   
   TH1F *hframe__217 = new TH1F("hframe__217","",1000,0,400);
   hframe__217->SetMinimum(1.433509);
   hframe__217->SetMaximum(14.706);
   hframe__217->SetDirectory(0);
   hframe__217->SetStats(0);
   hframe__217->SetLineStyle(0);
   hframe__217->SetMarkerStyle(20);
   hframe__217->GetXaxis()->SetLabelFont(43);
   hframe__217->GetXaxis()->SetLabelOffset(0.007);
   hframe__217->GetXaxis()->SetLabelSize(0);
   hframe__217->GetXaxis()->SetTitleSize(0);
   hframe__217->GetXaxis()->SetTitleOffset(0.9);
   hframe__217->GetXaxis()->SetTitleFont(43);
   hframe__217->GetYaxis()->SetTitle("N_{events}");
   hframe__217->GetYaxis()->SetLabelFont(43);
   hframe__217->GetYaxis()->SetLabelOffset(0.007);
   hframe__217->GetYaxis()->SetLabelSize(27);
   hframe__217->GetYaxis()->SetTitleSize(33);
   hframe__217->GetYaxis()->SetTitleOffset(1.796875);
   hframe__217->GetYaxis()->SetTitleFont(43);
   hframe__217->GetZaxis()->SetLabelFont(43);
   hframe__217->GetZaxis()->SetLabelOffset(0.007);
   hframe__217->GetZaxis()->SetLabelSize(27);
   hframe__217->GetZaxis()->SetTitleSize(33);
   hframe__217->GetZaxis()->SetTitleFont(43);
   hframe__217->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.7_QCDTailKillerTightPlus);
}
