{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus
//=========  (Fri Aug  1 10:26:34 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->Range(-81.01265,0.883605,425.3165,1.391379);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__15 = new TH1F("hframe__15","",1000,0,400);
   hframe__15->SetMinimum(1.03086);
   hframe__15->SetMaximum(1.391379);
   hframe__15->SetDirectory(0);
   hframe__15->SetStats(0);
   hframe__15->SetLineStyle(0);
   hframe__15->SetMarkerStyle(20);
   hframe__15->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__15->GetXaxis()->SetLabelFont(43);
   hframe__15->GetXaxis()->SetLabelOffset(0.007);
   hframe__15->GetXaxis()->SetLabelSize(27);
   hframe__15->GetXaxis()->SetTitleSize(33);
   hframe__15->GetXaxis()->SetTitleOffset(2.925);
   hframe__15->GetXaxis()->SetTitleFont(43);
   hframe__15->GetYaxis()->SetTitle("Ratio");
   hframe__15->GetYaxis()->SetNdivisions(505);
   hframe__15->GetYaxis()->SetLabelFont(43);
   hframe__15->GetYaxis()->SetLabelOffset(0.007);
   hframe__15->GetYaxis()->SetLabelSize(21);
   hframe__15->GetYaxis()->SetTitleSize(33);
   hframe__15->GetYaxis()->SetTitleOffset(1.796875);
   hframe__15->GetYaxis()->SetTitleFont(43);
   hframe__15->GetZaxis()->SetLabelFont(43);
   hframe__15->GetZaxis()->SetLabelOffset(0.007);
   hframe__15->GetZaxis()->SetLabelSize(27);
   hframe__15->GetZaxis()->SetTitleSize(33);
   hframe__15->GetZaxis()->SetTitleFont(43);
   hframe__15->Draw(" ");
   Double_t xAxis11[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16","#tau p_{T}<50",10, xAxis11);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(1,1.200512);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(2,1.188692);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(3,1.173826);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(4,1.188026);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(5,1.170351);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(6,1.163628);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(7,1.239046);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(8,1.26489);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(9,1.223402);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(10,1.259849);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinContent(11,1.023747);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(1,0.2494004);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(2,0.231425);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(3,0.1306175);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(4,0.116199);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(5,0.1005232);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(6,0.08294751);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(7,0.09940116);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(8,0.1237141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(9,0.1214998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(10,0.1820839);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetBinError(11,0.835886);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetEntries(616.468);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__16->Draw("EP same");
   Double_t xAxis12[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17","#tau p_{T}<50",10, xAxis12);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(1,1.039155);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(2,1.037946);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(3,1.032302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(4,1.036355);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(5,1.032704);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(6,1.03086);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(7,1.054772);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(8,1.049779);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(9,1.035498);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(10,1.038362);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinContent(11,0.9287245);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(1,0.2157572);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(2,0.2022065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(3,0.114812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(4,0.1013175);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(5,0.08867435);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(6,0.07346575);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(7,0.0845251);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(8,0.1024578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(9,0.1025954);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(10,0.149261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetBinError(11,0.7583004);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetEntries(618.0382);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__17->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph3 = new TH1F("Graph_Graph3","Graph",100,0,440);
   Graph_Graph3->SetMinimum(0.9);
   Graph_Graph3->SetMaximum(2.1);
   Graph_Graph3->SetDirectory(0);
   Graph_Graph3->SetStats(0);
   Graph_Graph3->SetLineStyle(0);
   Graph_Graph3->SetMarkerStyle(20);
   Graph_Graph3->GetXaxis()->SetLabelFont(43);
   Graph_Graph3->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph3->GetXaxis()->SetLabelSize(27);
   Graph_Graph3->GetXaxis()->SetTitleSize(33);
   Graph_Graph3->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph3->GetXaxis()->SetTitleFont(43);
   Graph_Graph3->GetYaxis()->SetLabelFont(43);
   Graph_Graph3->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph3->GetYaxis()->SetLabelSize(27);
   Graph_Graph3->GetYaxis()->SetTitleSize(33);
   Graph_Graph3->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph3->GetYaxis()->SetTitleFont(43);
   Graph_Graph3->GetZaxis()->SetLabelFont(43);
   Graph_Graph3->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph3->GetZaxis()->SetLabelSize(27);
   Graph_Graph3->GetZaxis()->SetTitleSize(33);
   Graph_Graph3->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph3);
   
   graph->Draw("l");
   
   TH1F *hframe__18 = new TH1F("hframe__18","",1000,0,400);
   hframe__18->SetMinimum(1.03086);
   hframe__18->SetMaximum(1.391379);
   hframe__18->SetDirectory(0);
   hframe__18->SetStats(0);
   hframe__18->SetLineStyle(0);
   hframe__18->SetMarkerStyle(20);
   hframe__18->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__18->GetXaxis()->SetLabelFont(43);
   hframe__18->GetXaxis()->SetLabelOffset(0.007);
   hframe__18->GetXaxis()->SetLabelSize(27);
   hframe__18->GetXaxis()->SetTitleSize(33);
   hframe__18->GetXaxis()->SetTitleOffset(2.925);
   hframe__18->GetXaxis()->SetTitleFont(43);
   hframe__18->GetYaxis()->SetTitle("Ratio");
   hframe__18->GetYaxis()->SetNdivisions(505);
   hframe__18->GetYaxis()->SetLabelFont(43);
   hframe__18->GetYaxis()->SetLabelOffset(0.007);
   hframe__18->GetYaxis()->SetLabelSize(21);
   hframe__18->GetYaxis()->SetTitleSize(33);
   hframe__18->GetYaxis()->SetTitleOffset(1.796875);
   hframe__18->GetYaxis()->SetTitleFont(43);
   hframe__18->GetZaxis()->SetLabelFont(43);
   hframe__18->GetZaxis()->SetLabelOffset(0.007);
   hframe__18->GetZaxis()->SetLabelSize(27);
   hframe__18->GetZaxis()->SetTitleSize(33);
   hframe__18->GetZaxis()->SetTitleFont(43);
   hframe__18->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->Range(-81.01265,-1.572137,425.3165,31.032);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__19 = new TH1F("hframe__19","",1000,0,400);
   hframe__19->SetMinimum(2.6664);
   hframe__19->SetMaximum(29.40179);
   hframe__19->SetDirectory(0);
   hframe__19->SetStats(0);
   hframe__19->SetLineStyle(0);
   hframe__19->SetMarkerStyle(20);
   hframe__19->GetXaxis()->SetLabelFont(43);
   hframe__19->GetXaxis()->SetLabelOffset(0.007);
   hframe__19->GetXaxis()->SetLabelSize(0);
   hframe__19->GetXaxis()->SetTitleSize(0);
   hframe__19->GetXaxis()->SetTitleOffset(0.9);
   hframe__19->GetXaxis()->SetTitleFont(43);
   hframe__19->GetYaxis()->SetTitle("N_{events}");
   hframe__19->GetYaxis()->SetLabelFont(43);
   hframe__19->GetYaxis()->SetLabelOffset(0.007);
   hframe__19->GetYaxis()->SetLabelSize(27);
   hframe__19->GetYaxis()->SetTitleSize(33);
   hframe__19->GetYaxis()->SetTitleOffset(1.796875);
   hframe__19->GetYaxis()->SetTitleFont(43);
   hframe__19->GetZaxis()->SetLabelFont(43);
   hframe__19->GetZaxis()->SetLabelOffset(0.007);
   hframe__19->GetZaxis()->SetLabelSize(27);
   hframe__19->GetZaxis()->SetTitleSize(33);
   hframe__19->GetZaxis()->SetTitleFont(43);
   hframe__19->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis13[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis13);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.201046);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,4.044528);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,11.14156);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,14.45425);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,18.65464);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,26.7289);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,21.6891);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,14.56996);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,13.66734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,6.52089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1602972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4703205);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5554354);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.8768442);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.9988863);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.129052);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.347085);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.212585);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,1.004429);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.9398766);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.6530679);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.09254766);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(2002.499);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis14[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.770804);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,3.531615);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,9.798261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,12.60893);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,16.46063);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,23.67917);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,18.46346);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,12.09215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.56815);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,5.374489);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.1454187);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4066458);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.485624);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.7703552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.870556);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9956718);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.192814);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.029912);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.83006);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.7915925);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.5321744);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.08395754);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(2002.499);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis15[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis15);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,2.6664);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.402503);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,9.491659);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,12.1666);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,15.93935);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.97032);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,17.50468);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,11.51875);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,11.17159);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,5.17593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.156579);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.3916108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,0.4695473);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,0.7466735);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,0.8421149);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,0.9714105);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.157981);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,1.007125);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,0.7991696);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,0.80047);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.5393507);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.09040091);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(1943.889);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__20 = new TH1F("hframe__20","",1000,0,400);
   hframe__20->SetMinimum(2.6664);
   hframe__20->SetMaximum(29.40179);
   hframe__20->SetDirectory(0);
   hframe__20->SetStats(0);
   hframe__20->SetLineStyle(0);
   hframe__20->SetMarkerStyle(20);
   hframe__20->GetXaxis()->SetLabelFont(43);
   hframe__20->GetXaxis()->SetLabelOffset(0.007);
   hframe__20->GetXaxis()->SetLabelSize(0);
   hframe__20->GetXaxis()->SetTitleSize(0);
   hframe__20->GetXaxis()->SetTitleOffset(0.9);
   hframe__20->GetXaxis()->SetTitleFont(43);
   hframe__20->GetYaxis()->SetTitle("N_{events}");
   hframe__20->GetYaxis()->SetLabelFont(43);
   hframe__20->GetYaxis()->SetLabelOffset(0.007);
   hframe__20->GetYaxis()->SetLabelSize(27);
   hframe__20->GetYaxis()->SetTitleSize(33);
   hframe__20->GetYaxis()->SetTitleOffset(1.796875);
   hframe__20->GetYaxis()->SetTitleFont(43);
   hframe__20->GetZaxis()->SetLabelFont(43);
   hframe__20->GetZaxis()->SetLabelOffset(0.007);
   hframe__20->GetZaxis()->SetLabelSize(27);
   hframe__20->GetZaxis()->SetTitleSize(33);
   hframe__20->GetZaxis()->SetTitleFont(43);
   hframe__20->Draw("sameaxis");
   
   TH1F *hframe__21 = new TH1F("hframe__21","",1000,0,400);
   hframe__21->SetMinimum(2.6664);
   hframe__21->SetMaximum(29.40179);
   hframe__21->SetDirectory(0);
   hframe__21->SetStats(0);
   hframe__21->SetLineStyle(0);
   hframe__21->SetMarkerStyle(20);
   hframe__21->GetXaxis()->SetLabelFont(43);
   hframe__21->GetXaxis()->SetLabelOffset(0.007);
   hframe__21->GetXaxis()->SetLabelSize(0);
   hframe__21->GetXaxis()->SetTitleSize(0);
   hframe__21->GetXaxis()->SetTitleOffset(0.9);
   hframe__21->GetXaxis()->SetTitleFont(43);
   hframe__21->GetYaxis()->SetTitle("N_{events}");
   hframe__21->GetYaxis()->SetLabelFont(43);
   hframe__21->GetYaxis()->SetLabelOffset(0.007);
   hframe__21->GetYaxis()->SetLabelSize(27);
   hframe__21->GetYaxis()->SetTitleSize(33);
   hframe__21->GetYaxis()->SetTitleOffset(1.796875);
   hframe__21->GetYaxis()->SetTitleFont(43);
   hframe__21->GetZaxis()->SetLabelFont(43);
   hframe__21->GetZaxis()->SetLabelOffset(0.007);
   hframe__21->GetZaxis()->SetLabelSize(27);
   hframe__21->GetZaxis()->SetTitleSize(33);
   hframe__21->GetZaxis()->SetTitleFont(43);
   hframe__21->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.75_QCDTailKillerLoosePlus);
}
