{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus
//=========  (Fri Aug  1 10:26:33 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->Range(-81.01265,0.8526775,425.3165,1.467099);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__8 = new TH1F("hframe__8","",1000,0,400);
   hframe__8->SetMinimum(1.03086);
   hframe__8->SetMaximum(1.467099);
   hframe__8->SetDirectory(0);
   hframe__8->SetStats(0);
   hframe__8->SetLineStyle(0);
   hframe__8->SetMarkerStyle(20);
   hframe__8->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__8->GetXaxis()->SetLabelFont(43);
   hframe__8->GetXaxis()->SetLabelOffset(0.007);
   hframe__8->GetXaxis()->SetLabelSize(27);
   hframe__8->GetXaxis()->SetTitleSize(33);
   hframe__8->GetXaxis()->SetTitleOffset(2.925);
   hframe__8->GetXaxis()->SetTitleFont(43);
   hframe__8->GetYaxis()->SetTitle("Ratio");
   hframe__8->GetYaxis()->SetNdivisions(505);
   hframe__8->GetYaxis()->SetLabelFont(43);
   hframe__8->GetYaxis()->SetLabelOffset(0.007);
   hframe__8->GetYaxis()->SetLabelSize(21);
   hframe__8->GetYaxis()->SetTitleSize(33);
   hframe__8->GetYaxis()->SetTitleOffset(1.796875);
   hframe__8->GetYaxis()->SetTitleFont(43);
   hframe__8->GetZaxis()->SetLabelFont(43);
   hframe__8->GetZaxis()->SetLabelOffset(0.007);
   hframe__8->GetZaxis()->SetLabelSize(27);
   hframe__8->GetZaxis()->SetTitleSize(33);
   hframe__8->GetZaxis()->SetTitleFont(43);
   hframe__8->Draw(" ");
   Double_t xAxis6[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9","#tau p_{T}<50",10, xAxis6);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(1,1.252146);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(2,1.236931);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(3,1.219114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(4,1.236561);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(5,1.214398);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(6,1.206113);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(7,1.298013);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(8,1.333726);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(9,1.283531);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(10,1.330725);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(11,1.054154);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(1,0.2603114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(2,0.2408852);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(3,0.1357313);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(4,0.1210176);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(5,0.1043465);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(6,0.08600853);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(7,0.1042249);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(8,0.1306212);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(9,0.127635);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(10,0.1927421);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(11,0.8607134);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetEntries(615.241);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->Draw("EP same");
   Double_t xAxis7[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10","#tau p_{T}<50",10, xAxis7);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(1,1.039155);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(2,1.037946);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(3,1.032302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(4,1.036355);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(5,1.032704);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(6,1.03086);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(7,1.054772);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(8,1.049779);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(9,1.035498);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(10,1.038362);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(11,0.9287245);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(1,0.2157572);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(2,0.2022065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(3,0.114812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(4,0.1013175);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(5,0.08867435);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(6,0.07346575);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(7,0.0845251);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(8,0.1024578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(9,0.1025954);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(10,0.149261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(11,0.7583004);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetEntries(618.0382);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,0,440);
   Graph_Graph2->SetMinimum(0.9);
   Graph_Graph2->SetMaximum(2.1);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);
   Graph_Graph2->SetLineStyle(0);
   Graph_Graph2->SetMarkerStyle(20);
   Graph_Graph2->GetXaxis()->SetLabelFont(43);
   Graph_Graph2->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetXaxis()->SetLabelSize(27);
   Graph_Graph2->GetXaxis()->SetTitleSize(33);
   Graph_Graph2->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph2->GetXaxis()->SetTitleFont(43);
   Graph_Graph2->GetYaxis()->SetLabelFont(43);
   Graph_Graph2->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetYaxis()->SetLabelSize(27);
   Graph_Graph2->GetYaxis()->SetTitleSize(33);
   Graph_Graph2->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph2->GetYaxis()->SetTitleFont(43);
   Graph_Graph2->GetZaxis()->SetLabelFont(43);
   Graph_Graph2->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetZaxis()->SetLabelSize(27);
   Graph_Graph2->GetZaxis()->SetTitleSize(33);
   Graph_Graph2->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph2);
   
   graph->Draw("l");
   
   TH1F *hframe__11 = new TH1F("hframe__11","",1000,0,400);
   hframe__11->SetMinimum(1.03086);
   hframe__11->SetMaximum(1.467099);
   hframe__11->SetDirectory(0);
   hframe__11->SetStats(0);
   hframe__11->SetLineStyle(0);
   hframe__11->SetMarkerStyle(20);
   hframe__11->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__11->GetXaxis()->SetLabelFont(43);
   hframe__11->GetXaxis()->SetLabelOffset(0.007);
   hframe__11->GetXaxis()->SetLabelSize(27);
   hframe__11->GetXaxis()->SetTitleSize(33);
   hframe__11->GetXaxis()->SetTitleOffset(2.925);
   hframe__11->GetXaxis()->SetTitleFont(43);
   hframe__11->GetYaxis()->SetTitle("Ratio");
   hframe__11->GetYaxis()->SetNdivisions(505);
   hframe__11->GetYaxis()->SetLabelFont(43);
   hframe__11->GetYaxis()->SetLabelOffset(0.007);
   hframe__11->GetYaxis()->SetLabelSize(21);
   hframe__11->GetYaxis()->SetTitleSize(33);
   hframe__11->GetYaxis()->SetTitleOffset(1.796875);
   hframe__11->GetYaxis()->SetTitleFont(43);
   hframe__11->GetZaxis()->SetLabelFont(43);
   hframe__11->GetZaxis()->SetLabelOffset(0.007);
   hframe__11->GetZaxis()->SetLabelSize(27);
   hframe__11->GetZaxis()->SetTitleSize(33);
   hframe__11->GetZaxis()->SetTitleFont(43);
   hframe__11->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->Range(-81.01265,-1.742326,425.3165,32.17095);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__12 = new TH1F("hframe__12","",1000,0,400);
   hframe__12->SetMinimum(2.6664);
   hframe__12->SetMaximum(30.47529);
   hframe__12->SetDirectory(0);
   hframe__12->SetStats(0);
   hframe__12->SetLineStyle(0);
   hframe__12->SetMarkerStyle(20);
   hframe__12->GetXaxis()->SetLabelFont(43);
   hframe__12->GetXaxis()->SetLabelOffset(0.007);
   hframe__12->GetXaxis()->SetLabelSize(0);
   hframe__12->GetXaxis()->SetTitleSize(0);
   hframe__12->GetXaxis()->SetTitleOffset(0.9);
   hframe__12->GetXaxis()->SetTitleFont(43);
   hframe__12->GetYaxis()->SetTitle("N_{events}");
   hframe__12->GetYaxis()->SetLabelFont(43);
   hframe__12->GetYaxis()->SetLabelOffset(0.007);
   hframe__12->GetYaxis()->SetLabelSize(27);
   hframe__12->GetYaxis()->SetTitleSize(33);
   hframe__12->GetYaxis()->SetTitleOffset(1.796875);
   hframe__12->GetYaxis()->SetTitleFont(43);
   hframe__12->GetZaxis()->SetLabelFont(43);
   hframe__12->GetZaxis()->SetLabelOffset(0.007);
   hframe__12->GetZaxis()->SetLabelSize(27);
   hframe__12->GetZaxis()->SetTitleSize(33);
   hframe__12->GetZaxis()->SetTitleFont(43);
   hframe__12->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis8[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis8);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.338723);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,4.20866);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,11.57141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,15.04475);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,19.35672);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,27.70481);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,22.7213);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,15.36286);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,14.33908);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,6.887738);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1650584);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4912435);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.578307);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.9116728);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.040924);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.172451);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.397325);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.272631);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,1.061939);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.988707);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.6929017);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.0952965);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(2002.499);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis9[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis9);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.770804);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,3.531615);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,9.798261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,12.60893);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,16.46063);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,23.67917);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,18.46346);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,12.09215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.56815);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,5.374489);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.1454187);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4066458);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.485624);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.7703552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.870556);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9956718);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.192814);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.029912);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.83006);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.7915925);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.5321744);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.08395754);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(2002.499);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis10[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis10);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,2.6664);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.402503);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,9.491659);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,12.1666);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,15.93935);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.97032);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,17.50468);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,11.51875);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,11.17159);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,5.17593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.156579);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.3916108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,0.4695473);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,0.7466735);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,0.8421149);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,0.9714105);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.157981);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,1.007125);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,0.7991696);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,0.80047);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.5393507);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.09040091);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(1943.889);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__13 = new TH1F("hframe__13","",1000,0,400);
   hframe__13->SetMinimum(2.6664);
   hframe__13->SetMaximum(30.47529);
   hframe__13->SetDirectory(0);
   hframe__13->SetStats(0);
   hframe__13->SetLineStyle(0);
   hframe__13->SetMarkerStyle(20);
   hframe__13->GetXaxis()->SetLabelFont(43);
   hframe__13->GetXaxis()->SetLabelOffset(0.007);
   hframe__13->GetXaxis()->SetLabelSize(0);
   hframe__13->GetXaxis()->SetTitleSize(0);
   hframe__13->GetXaxis()->SetTitleOffset(0.9);
   hframe__13->GetXaxis()->SetTitleFont(43);
   hframe__13->GetYaxis()->SetTitle("N_{events}");
   hframe__13->GetYaxis()->SetLabelFont(43);
   hframe__13->GetYaxis()->SetLabelOffset(0.007);
   hframe__13->GetYaxis()->SetLabelSize(27);
   hframe__13->GetYaxis()->SetTitleSize(33);
   hframe__13->GetYaxis()->SetTitleOffset(1.796875);
   hframe__13->GetYaxis()->SetTitleFont(43);
   hframe__13->GetZaxis()->SetLabelFont(43);
   hframe__13->GetZaxis()->SetLabelOffset(0.007);
   hframe__13->GetZaxis()->SetLabelSize(27);
   hframe__13->GetZaxis()->SetTitleSize(33);
   hframe__13->GetZaxis()->SetTitleFont(43);
   hframe__13->Draw("sameaxis");
   
   TH1F *hframe__14 = new TH1F("hframe__14","",1000,0,400);
   hframe__14->SetMinimum(2.6664);
   hframe__14->SetMaximum(30.47529);
   hframe__14->SetDirectory(0);
   hframe__14->SetStats(0);
   hframe__14->SetLineStyle(0);
   hframe__14->SetMarkerStyle(20);
   hframe__14->GetXaxis()->SetLabelFont(43);
   hframe__14->GetXaxis()->SetLabelOffset(0.007);
   hframe__14->GetXaxis()->SetLabelSize(0);
   hframe__14->GetXaxis()->SetTitleSize(0);
   hframe__14->GetXaxis()->SetTitleOffset(0.9);
   hframe__14->GetXaxis()->SetTitleFont(43);
   hframe__14->GetYaxis()->SetTitle("N_{events}");
   hframe__14->GetYaxis()->SetLabelFont(43);
   hframe__14->GetYaxis()->SetLabelOffset(0.007);
   hframe__14->GetYaxis()->SetLabelSize(27);
   hframe__14->GetYaxis()->SetTitleSize(33);
   hframe__14->GetYaxis()->SetTitleOffset(1.796875);
   hframe__14->GetYaxis()->SetTitleFont(43);
   hframe__14->GetZaxis()->SetLabelFont(43);
   hframe__14->GetZaxis()->SetLabelOffset(0.007);
   hframe__14->GetZaxis()->SetLabelSize(27);
   hframe__14->GetZaxis()->SetTitleSize(33);
   hframe__14->GetZaxis()->SetTitleFont(43);
   hframe__14->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.67_QCDTailKillerLoosePlus);
}
