{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus/Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus
//=========  (Wed Jul 30 13:56:35 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus", "Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2", "Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->Range(-81.01265,0.2659813,425.3165,1.72359);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__99 = new TH1F("hframe__99","",1000,0,400);
   hframe__99->SetMinimum(0.6886879);
   hframe__99->SetMaximum(1.72359);
   hframe__99->SetDirectory(0);
   hframe__99->SetStats(0);
   hframe__99->SetLineStyle(0);
   hframe__99->SetMarkerStyle(20);
   hframe__99->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__99->GetXaxis()->SetLabelFont(43);
   hframe__99->GetXaxis()->SetLabelOffset(0.007);
   hframe__99->GetXaxis()->SetLabelSize(27);
   hframe__99->GetXaxis()->SetTitleSize(33);
   hframe__99->GetXaxis()->SetTitleOffset(2.925);
   hframe__99->GetXaxis()->SetTitleFont(43);
   hframe__99->GetYaxis()->SetTitle("Ratio");
   hframe__99->GetYaxis()->SetNdivisions(505);
   hframe__99->GetYaxis()->SetLabelFont(43);
   hframe__99->GetYaxis()->SetLabelOffset(0.007);
   hframe__99->GetYaxis()->SetLabelSize(21);
   hframe__99->GetYaxis()->SetTitleSize(33);
   hframe__99->GetYaxis()->SetTitleOffset(1.796875);
   hframe__99->GetYaxis()->SetTitleFont(43);
   hframe__99->GetZaxis()->SetLabelFont(43);
   hframe__99->GetZaxis()->SetLabelOffset(0.007);
   hframe__99->GetZaxis()->SetLabelSize(27);
   hframe__99->GetZaxis()->SetTitleSize(33);
   hframe__99->GetZaxis()->SetTitleFont(43);
   hframe__99->Draw(" ");
   Double_t xAxis71[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100","#tau p_{T}<50",10, xAxis71);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(1,1.5669);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(2,0.9577451);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(3,1.133205);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(4,1.114386);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(5,0.9244903);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(6,1.331721);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(7,1.020081);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(8,0.9797987);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(9,1.159966);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(10,0.9727991);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinContent(11,1.142353);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(1,0.4922868);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(2,0.3508792);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(3,0.2166647);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(4,0.2011249);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(5,0.157382);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(6,0.1778749);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(7,0.1789677);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(8,0.229977);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(9,0.3229474);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(10,0.3396817);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetBinError(11,1.229599);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetEntries(153.06);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__100->Draw("EP same");
   Double_t xAxis72[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101","#tau p_{T}<50",10, xAxis72);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(5,0.6969547);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(6,0.978788);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(7,0.7266998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(8,0.6886879);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(9,0.8167623);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(10,0.6924216);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinContent(11,1.136218);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(5,0.118574);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(6,0.1306626);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(7,0.1275215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(8,0.1616419);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(9,0.2272129);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(10,0.2408043);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetBinError(11,1.222996);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetEntries(153.3889);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__101->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph15 = new TH1F("Graph_Graph15","Graph",100,0,440);
   Graph_Graph15->SetMinimum(0.9);
   Graph_Graph15->SetMaximum(2.1);
   Graph_Graph15->SetDirectory(0);
   Graph_Graph15->SetStats(0);
   Graph_Graph15->SetLineStyle(0);
   Graph_Graph15->SetMarkerStyle(20);
   Graph_Graph15->GetXaxis()->SetLabelFont(43);
   Graph_Graph15->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph15->GetXaxis()->SetLabelSize(27);
   Graph_Graph15->GetXaxis()->SetTitleSize(33);
   Graph_Graph15->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph15->GetXaxis()->SetTitleFont(43);
   Graph_Graph15->GetYaxis()->SetLabelFont(43);
   Graph_Graph15->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph15->GetYaxis()->SetLabelSize(27);
   Graph_Graph15->GetYaxis()->SetTitleSize(33);
   Graph_Graph15->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph15->GetYaxis()->SetTitleFont(43);
   Graph_Graph15->GetZaxis()->SetLabelFont(43);
   Graph_Graph15->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph15->GetZaxis()->SetLabelSize(27);
   Graph_Graph15->GetZaxis()->SetTitleSize(33);
   Graph_Graph15->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph15);
   
   graph->Draw("l");
   
   TH1F *hframe__102 = new TH1F("hframe__102","",1000,0,400);
   hframe__102->SetMinimum(0.6886879);
   hframe__102->SetMaximum(1.72359);
   hframe__102->SetDirectory(0);
   hframe__102->SetStats(0);
   hframe__102->SetLineStyle(0);
   hframe__102->SetMarkerStyle(20);
   hframe__102->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__102->GetXaxis()->SetLabelFont(43);
   hframe__102->GetXaxis()->SetLabelOffset(0.007);
   hframe__102->GetXaxis()->SetLabelSize(27);
   hframe__102->GetXaxis()->SetTitleSize(33);
   hframe__102->GetXaxis()->SetTitleOffset(2.925);
   hframe__102->GetXaxis()->SetTitleFont(43);
   hframe__102->GetYaxis()->SetTitle("Ratio");
   hframe__102->GetYaxis()->SetNdivisions(505);
   hframe__102->GetYaxis()->SetLabelFont(43);
   hframe__102->GetYaxis()->SetLabelOffset(0.007);
   hframe__102->GetYaxis()->SetLabelSize(21);
   hframe__102->GetYaxis()->SetTitleSize(33);
   hframe__102->GetYaxis()->SetTitleOffset(1.796875);
   hframe__102->GetYaxis()->SetTitleFont(43);
   hframe__102->GetZaxis()->SetLabelFont(43);
   hframe__102->GetZaxis()->SetLabelOffset(0.007);
   hframe__102->GetZaxis()->SetLabelSize(27);
   hframe__102->GetZaxis()->SetTitleSize(33);
   hframe__102->GetZaxis()->SetTitleFont(43);
   hframe__102->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1", "Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->Range(-81.01265,-1.327524,425.3165,22.9547);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__103 = new TH1F("hframe__103","",1000,0,400);
   hframe__103->SetMinimum(1.829165);
   hframe__103->SetMaximum(21.74059);
   hframe__103->SetDirectory(0);
   hframe__103->SetStats(0);
   hframe__103->SetLineStyle(0);
   hframe__103->SetMarkerStyle(20);
   hframe__103->GetXaxis()->SetLabelFont(43);
   hframe__103->GetXaxis()->SetLabelOffset(0.007);
   hframe__103->GetXaxis()->SetLabelSize(0);
   hframe__103->GetXaxis()->SetTitleSize(0);
   hframe__103->GetXaxis()->SetTitleOffset(0.9);
   hframe__103->GetXaxis()->SetTitleFont(43);
   hframe__103->GetYaxis()->SetTitle("N_{events}");
   hframe__103->GetYaxis()->SetLabelFont(43);
   hframe__103->GetYaxis()->SetLabelOffset(0.007);
   hframe__103->GetYaxis()->SetLabelSize(27);
   hframe__103->GetYaxis()->SetTitleSize(33);
   hframe__103->GetYaxis()->SetTitleOffset(1.796875);
   hframe__103->GetYaxis()->SetTitleFont(43);
   hframe__103->GetZaxis()->SetLabelFont(43);
   hframe__103->GetZaxis()->SetLabelOffset(0.007);
   hframe__103->GetZaxis()->SetLabelSize(27);
   hframe__103->GetZaxis()->SetTitleSize(33);
   hframe__103->GetZaxis()->SetTitleFont(43);
   hframe__103->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Medium");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis73[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis73);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.866119);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.269598);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,9.792828);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,13.20943);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,17.73623);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,19.76417);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,15.38078);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,10.06639);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,8.903028);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,4.025893);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.0931182);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.5796802);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.6749634);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.092639);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.227538);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.258425);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.287006);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.134845);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.914307);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.8600957);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.5801557);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.06584451);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis74[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis74);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,13.37099);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,14.52627);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,10.95717);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,7.075533);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,6.268853);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,2.865561);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.09261809);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9453297);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.9437324);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.8093866);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.6424967);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.6015612);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.4030667);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.06549088);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis75[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis75);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,19.18487);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,14.84108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,15.07799);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,10.27393);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,7.675248);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,4.138463);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.08151437);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.968778);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.73075);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.400046);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.223616);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.004103);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.316265);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.06615137);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(613.1472);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__104 = new TH1F("hframe__104","",1000,0,400);
   hframe__104->SetMinimum(1.829165);
   hframe__104->SetMaximum(21.74059);
   hframe__104->SetDirectory(0);
   hframe__104->SetStats(0);
   hframe__104->SetLineStyle(0);
   hframe__104->SetMarkerStyle(20);
   hframe__104->GetXaxis()->SetLabelFont(43);
   hframe__104->GetXaxis()->SetLabelOffset(0.007);
   hframe__104->GetXaxis()->SetLabelSize(0);
   hframe__104->GetXaxis()->SetTitleSize(0);
   hframe__104->GetXaxis()->SetTitleOffset(0.9);
   hframe__104->GetXaxis()->SetTitleFont(43);
   hframe__104->GetYaxis()->SetTitle("N_{events}");
   hframe__104->GetYaxis()->SetLabelFont(43);
   hframe__104->GetYaxis()->SetLabelOffset(0.007);
   hframe__104->GetYaxis()->SetLabelSize(27);
   hframe__104->GetYaxis()->SetTitleSize(33);
   hframe__104->GetYaxis()->SetTitleOffset(1.796875);
   hframe__104->GetYaxis()->SetTitleFont(43);
   hframe__104->GetZaxis()->SetLabelFont(43);
   hframe__104->GetZaxis()->SetLabelOffset(0.007);
   hframe__104->GetZaxis()->SetLabelSize(27);
   hframe__104->GetZaxis()->SetTitleSize(33);
   hframe__104->GetZaxis()->SetTitleFont(43);
   hframe__104->Draw("sameaxis");
   
   TH1F *hframe__105 = new TH1F("hframe__105","",1000,0,400);
   hframe__105->SetMinimum(1.829165);
   hframe__105->SetMaximum(21.74059);
   hframe__105->SetDirectory(0);
   hframe__105->SetStats(0);
   hframe__105->SetLineStyle(0);
   hframe__105->SetMarkerStyle(20);
   hframe__105->GetXaxis()->SetLabelFont(43);
   hframe__105->GetXaxis()->SetLabelOffset(0.007);
   hframe__105->GetXaxis()->SetLabelSize(0);
   hframe__105->GetXaxis()->SetTitleSize(0);
   hframe__105->GetXaxis()->SetTitleOffset(0.9);
   hframe__105->GetXaxis()->SetTitleFont(43);
   hframe__105->GetYaxis()->SetTitle("N_{events}");
   hframe__105->GetYaxis()->SetLabelFont(43);
   hframe__105->GetYaxis()->SetLabelOffset(0.007);
   hframe__105->GetYaxis()->SetLabelSize(27);
   hframe__105->GetYaxis()->SetTitleSize(33);
   hframe__105->GetYaxis()->SetTitleOffset(1.796875);
   hframe__105->GetYaxis()->SetTitleFont(43);
   hframe__105->GetZaxis()->SetLabelFont(43);
   hframe__105->GetZaxis()->SetLabelOffset(0.007);
   hframe__105->GetZaxis()->SetLabelSize(27);
   hframe__105->GetZaxis()->SetTitleSize(33);
   hframe__105->GetZaxis()->SetTitleFont(43);
   hframe__105->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->Modified();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus->SetSelected(Mt_DataDrivenVsMC_w=0.5_QCDTailKillerMediumPlus);
}
