{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus/Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus
//=========  (Fri Aug  1 10:26:38 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus", "Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2", "Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->Range(-81.01265,0.827271,425.3165,1.528487);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__22 = new TH1F("hframe__22","",1000,0,400);
   hframe__22->SetMinimum(1.030624);
   hframe__22->SetMaximum(1.528487);
   hframe__22->SetDirectory(0);
   hframe__22->SetStats(0);
   hframe__22->SetLineStyle(0);
   hframe__22->SetMarkerStyle(20);
   hframe__22->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__22->GetXaxis()->SetLabelFont(43);
   hframe__22->GetXaxis()->SetLabelOffset(0.007);
   hframe__22->GetXaxis()->SetLabelSize(27);
   hframe__22->GetXaxis()->SetTitleSize(33);
   hframe__22->GetXaxis()->SetTitleOffset(2.925);
   hframe__22->GetXaxis()->SetTitleFont(43);
   hframe__22->GetYaxis()->SetTitle("Ratio");
   hframe__22->GetYaxis()->SetNdivisions(505);
   hframe__22->GetYaxis()->SetLabelFont(43);
   hframe__22->GetYaxis()->SetLabelOffset(0.007);
   hframe__22->GetYaxis()->SetLabelSize(21);
   hframe__22->GetYaxis()->SetTitleSize(33);
   hframe__22->GetYaxis()->SetTitleOffset(1.796875);
   hframe__22->GetYaxis()->SetTitleFont(43);
   hframe__22->GetZaxis()->SetLabelFont(43);
   hframe__22->GetZaxis()->SetLabelOffset(0.007);
   hframe__22->GetZaxis()->SetLabelSize(27);
   hframe__22->GetZaxis()->SetTitleSize(33);
   hframe__22->GetZaxis()->SetTitleFont(43);
   hframe__22->Draw(" ");
   Double_t xAxis16[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23","#tau p_{T}<50",10, xAxis16);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(1,1.2586);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(2,1.24296);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(3,1.224775);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(4,1.242628);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(5,1.221469);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(6,1.219929);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(7,1.301721);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(8,1.322148);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(9,1.297437);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(10,1.389534);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(11,1.057955);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(1,0.2616794);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(2,0.2420709);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(3,0.1363722);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(4,0.1216215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(5,0.1099359);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(6,0.1068003);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(7,0.1326981);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(8,0.1662527);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(9,0.1772049);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(10,0.2664767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(11,1.057955);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetEntries(488.0012);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->Draw("EP same");
   Double_t xAxis17[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24","#tau p_{T}<50",10, xAxis17);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(1,1.039155);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(2,1.037946);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(3,1.032302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(4,1.036355);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(5,1.033007);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(6,1.030624);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(7,1.057487);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(8,1.043093);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(9,1.064998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(10,1.063498);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(11,0.9287245);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(1,0.2157572);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(2,0.2022065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(3,0.114812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(4,0.1013175);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(5,0.09289638);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(6,0.09014005);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(7,0.107557);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(8,0.1307654);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(9,0.1450876);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(10,0.2024779);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(11,0.9287245);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetEntries(499.0078);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph4 = new TH1F("Graph_Graph4","Graph",100,0,440);
   Graph_Graph4->SetMinimum(0.9);
   Graph_Graph4->SetMaximum(2.1);
   Graph_Graph4->SetDirectory(0);
   Graph_Graph4->SetStats(0);
   Graph_Graph4->SetLineStyle(0);
   Graph_Graph4->SetMarkerStyle(20);
   Graph_Graph4->GetXaxis()->SetLabelFont(43);
   Graph_Graph4->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetXaxis()->SetLabelSize(27);
   Graph_Graph4->GetXaxis()->SetTitleSize(33);
   Graph_Graph4->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph4->GetXaxis()->SetTitleFont(43);
   Graph_Graph4->GetYaxis()->SetLabelFont(43);
   Graph_Graph4->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetYaxis()->SetLabelSize(27);
   Graph_Graph4->GetYaxis()->SetTitleSize(33);
   Graph_Graph4->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph4->GetYaxis()->SetTitleFont(43);
   Graph_Graph4->GetZaxis()->SetLabelFont(43);
   Graph_Graph4->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetZaxis()->SetLabelSize(27);
   Graph_Graph4->GetZaxis()->SetTitleSize(33);
   Graph_Graph4->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph4);
   
   graph->Draw("l");
   
   TH1F *hframe__25 = new TH1F("hframe__25","",1000,0,400);
   hframe__25->SetMinimum(1.030624);
   hframe__25->SetMaximum(1.528487);
   hframe__25->SetDirectory(0);
   hframe__25->SetStats(0);
   hframe__25->SetLineStyle(0);
   hframe__25->SetMarkerStyle(20);
   hframe__25->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__25->GetXaxis()->SetLabelFont(43);
   hframe__25->GetXaxis()->SetLabelOffset(0.007);
   hframe__25->GetXaxis()->SetLabelSize(27);
   hframe__25->GetXaxis()->SetTitleSize(33);
   hframe__25->GetXaxis()->SetTitleOffset(2.925);
   hframe__25->GetXaxis()->SetTitleFont(43);
   hframe__25->GetYaxis()->SetTitle("Ratio");
   hframe__25->GetYaxis()->SetNdivisions(505);
   hframe__25->GetYaxis()->SetLabelFont(43);
   hframe__25->GetYaxis()->SetLabelOffset(0.007);
   hframe__25->GetYaxis()->SetLabelSize(21);
   hframe__25->GetYaxis()->SetTitleSize(33);
   hframe__25->GetYaxis()->SetTitleOffset(1.796875);
   hframe__25->GetYaxis()->SetTitleFont(43);
   hframe__25->GetZaxis()->SetLabelFont(43);
   hframe__25->GetZaxis()->SetLabelOffset(0.007);
   hframe__25->GetZaxis()->SetLabelSize(27);
   hframe__25->GetZaxis()->SetTitleSize(33);
   hframe__25->GetZaxis()->SetTitleFont(43);
   hframe__25->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1", "Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->Range(-81.01265,-0.1122753,425.3165,21.26215);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__26 = new TH1F("hframe__26","",1000,0,400);
   hframe__26->SetMinimum(2.6664);
   hframe__26->SetMaximum(20.19343);
   hframe__26->SetDirectory(0);
   hframe__26->SetStats(0);
   hframe__26->SetLineStyle(0);
   hframe__26->SetMarkerStyle(20);
   hframe__26->GetXaxis()->SetLabelFont(43);
   hframe__26->GetXaxis()->SetLabelOffset(0.007);
   hframe__26->GetXaxis()->SetLabelSize(0);
   hframe__26->GetXaxis()->SetTitleSize(0);
   hframe__26->GetXaxis()->SetTitleOffset(0.9);
   hframe__26->GetXaxis()->SetTitleFont(43);
   hframe__26->GetYaxis()->SetTitle("N_{events}");
   hframe__26->GetYaxis()->SetLabelFont(43);
   hframe__26->GetYaxis()->SetLabelOffset(0.007);
   hframe__26->GetYaxis()->SetLabelSize(27);
   hframe__26->GetYaxis()->SetTitleSize(33);
   hframe__26->GetYaxis()->SetTitleOffset(1.796875);
   hframe__26->GetYaxis()->SetTitleFont(43);
   hframe__26->GetZaxis()->SetLabelFont(43);
   hframe__26->GetZaxis()->SetLabelOffset(0.007);
   hframe__26->GetZaxis()->SetLabelSize(27);
   hframe__26->GetZaxis()->SetTitleSize(33);
   hframe__26->GetZaxis()->SetTitleFont(43);
   hframe__26->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Medium");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis18[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis18);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.355933);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,4.229177);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,11.62515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,15.11856);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,17.67021);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,18.35767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,14.42329);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,9.278589);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,7.923599);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,4.161353);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1104357);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4938742);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5811811);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.916048);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.046206);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.120835);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.13744);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.01737);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.822929);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.7341885);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.5484601);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.07808982);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1501.595);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis19[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis19);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.770804);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,3.531615);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,9.798261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,12.60893);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,14.94386);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,15.50897);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,11.71714);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,7.320239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,6.50407);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,3.184945);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.09694581);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4066458);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.485624);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.7703552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.870556);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9463109);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.95908);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.8225795);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.6452765);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.5993151);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.4133239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.06855104);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1501.595);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis20[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,2.6664);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.402503);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,9.491659);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,12.1666);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,14.46637);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,15.04814);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,11.08017);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,7.017817);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,6.107118);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,2.994783);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.104386);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.3916108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,0.4695473);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,0.7466735);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,0.8421149);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,0.9237073);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,0.9307143);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,0.8154627);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,0.6255522);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,0.6128063);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.4171948);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.07381203);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(1448.164);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__27 = new TH1F("hframe__27","",1000,0,400);
   hframe__27->SetMinimum(2.6664);
   hframe__27->SetMaximum(20.19343);
   hframe__27->SetDirectory(0);
   hframe__27->SetStats(0);
   hframe__27->SetLineStyle(0);
   hframe__27->SetMarkerStyle(20);
   hframe__27->GetXaxis()->SetLabelFont(43);
   hframe__27->GetXaxis()->SetLabelOffset(0.007);
   hframe__27->GetXaxis()->SetLabelSize(0);
   hframe__27->GetXaxis()->SetTitleSize(0);
   hframe__27->GetXaxis()->SetTitleOffset(0.9);
   hframe__27->GetXaxis()->SetTitleFont(43);
   hframe__27->GetYaxis()->SetTitle("N_{events}");
   hframe__27->GetYaxis()->SetLabelFont(43);
   hframe__27->GetYaxis()->SetLabelOffset(0.007);
   hframe__27->GetYaxis()->SetLabelSize(27);
   hframe__27->GetYaxis()->SetTitleSize(33);
   hframe__27->GetYaxis()->SetTitleOffset(1.796875);
   hframe__27->GetYaxis()->SetTitleFont(43);
   hframe__27->GetZaxis()->SetLabelFont(43);
   hframe__27->GetZaxis()->SetLabelOffset(0.007);
   hframe__27->GetZaxis()->SetLabelSize(27);
   hframe__27->GetZaxis()->SetTitleSize(33);
   hframe__27->GetZaxis()->SetTitleFont(43);
   hframe__27->Draw("sameaxis");
   
   TH1F *hframe__28 = new TH1F("hframe__28","",1000,0,400);
   hframe__28->SetMinimum(2.6664);
   hframe__28->SetMaximum(20.19343);
   hframe__28->SetDirectory(0);
   hframe__28->SetStats(0);
   hframe__28->SetLineStyle(0);
   hframe__28->SetMarkerStyle(20);
   hframe__28->GetXaxis()->SetLabelFont(43);
   hframe__28->GetXaxis()->SetLabelOffset(0.007);
   hframe__28->GetXaxis()->SetLabelSize(0);
   hframe__28->GetXaxis()->SetTitleSize(0);
   hframe__28->GetXaxis()->SetTitleOffset(0.9);
   hframe__28->GetXaxis()->SetTitleFont(43);
   hframe__28->GetYaxis()->SetTitle("N_{events}");
   hframe__28->GetYaxis()->SetLabelFont(43);
   hframe__28->GetYaxis()->SetLabelOffset(0.007);
   hframe__28->GetYaxis()->SetLabelSize(27);
   hframe__28->GetYaxis()->SetTitleSize(33);
   hframe__28->GetYaxis()->SetTitleOffset(1.796875);
   hframe__28->GetYaxis()->SetTitleFont(43);
   hframe__28->GetZaxis()->SetLabelFont(43);
   hframe__28->GetZaxis()->SetLabelOffset(0.007);
   hframe__28->GetZaxis()->SetLabelSize(27);
   hframe__28->GetZaxis()->SetTitleSize(33);
   hframe__28->GetZaxis()->SetTitleFont(43);
   hframe__28->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus->SetSelected(Mt_DataDrivenVsMC_w=0.66_QCDTailKillerMediumPlus);
}
