{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus/Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus
//=========  (Wed Jul 30 13:56:47 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus", "Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2", "Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->Range(-81.01265,0.4210281,425.3165,1.343993);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__155 = new TH1F("hframe__155","",1000,0,400);
   hframe__155->SetMinimum(0.6886879);
   hframe__155->SetMaximum(1.343993);
   hframe__155->SetDirectory(0);
   hframe__155->SetStats(0);
   hframe__155->SetLineStyle(0);
   hframe__155->SetMarkerStyle(20);
   hframe__155->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__155->GetXaxis()->SetLabelFont(43);
   hframe__155->GetXaxis()->SetLabelOffset(0.007);
   hframe__155->GetXaxis()->SetLabelSize(27);
   hframe__155->GetXaxis()->SetTitleSize(33);
   hframe__155->GetXaxis()->SetTitleOffset(2.925);
   hframe__155->GetXaxis()->SetTitleFont(43);
   hframe__155->GetYaxis()->SetTitle("Ratio");
   hframe__155->GetYaxis()->SetNdivisions(505);
   hframe__155->GetYaxis()->SetLabelFont(43);
   hframe__155->GetYaxis()->SetLabelOffset(0.007);
   hframe__155->GetYaxis()->SetLabelSize(21);
   hframe__155->GetYaxis()->SetTitleSize(33);
   hframe__155->GetYaxis()->SetTitleOffset(1.796875);
   hframe__155->GetYaxis()->SetTitleFont(43);
   hframe__155->GetZaxis()->SetLabelFont(43);
   hframe__155->GetZaxis()->SetLabelOffset(0.007);
   hframe__155->GetZaxis()->SetLabelSize(27);
   hframe__155->GetZaxis()->SetTitleSize(33);
   hframe__155->GetZaxis()->SetTitleFont(43);
   hframe__155->Draw(" ");
   Double_t xAxis111[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156","#tau p_{T}<50",10, xAxis111);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(1,1.221812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(2,0.7799451);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(3,0.88978);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(4,0.875916);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(5,0.7424617);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(6,1.049375);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(7,0.7853761);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(8,0.74691);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(9,0.8854031);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(10,0.7484971);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinContent(11,1.137445);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(1,0.3840169);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(2,0.2842327);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(3,0.170645);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(4,0.1581956);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(5,0.1263121);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(6,0.1400694);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(7,0.1377793);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(8,0.175272);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(9,0.2463182);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(10,0.2604743);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetBinError(11,1.224316);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetEntries(153.434);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__156->Draw("EP same");
   Double_t xAxis112[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157","#tau p_{T}<50",10, xAxis112);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(5,0.6969547);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(6,0.978788);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(7,0.7266998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(8,0.6886879);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(9,0.8167623);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(10,0.6924216);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinContent(11,1.136218);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(5,0.118574);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(6,0.1306626);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(7,0.1275215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(8,0.1616419);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(9,0.2272129);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(10,0.2408043);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetBinError(11,1.222996);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetEntries(153.3889);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__157->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph23 = new TH1F("Graph_Graph23","Graph",100,0,440);
   Graph_Graph23->SetMinimum(0.9);
   Graph_Graph23->SetMaximum(2.1);
   Graph_Graph23->SetDirectory(0);
   Graph_Graph23->SetStats(0);
   Graph_Graph23->SetLineStyle(0);
   Graph_Graph23->SetMarkerStyle(20);
   Graph_Graph23->GetXaxis()->SetLabelFont(43);
   Graph_Graph23->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph23->GetXaxis()->SetLabelSize(27);
   Graph_Graph23->GetXaxis()->SetTitleSize(33);
   Graph_Graph23->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph23->GetXaxis()->SetTitleFont(43);
   Graph_Graph23->GetYaxis()->SetLabelFont(43);
   Graph_Graph23->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph23->GetYaxis()->SetLabelSize(27);
   Graph_Graph23->GetYaxis()->SetTitleSize(33);
   Graph_Graph23->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph23->GetYaxis()->SetTitleFont(43);
   Graph_Graph23->GetZaxis()->SetLabelFont(43);
   Graph_Graph23->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph23->GetZaxis()->SetLabelSize(27);
   Graph_Graph23->GetZaxis()->SetTitleSize(33);
   Graph_Graph23->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph23);
   
   graph->Draw("l");
   
   TH1F *hframe__158 = new TH1F("hframe__158","",1000,0,400);
   hframe__158->SetMinimum(0.6886879);
   hframe__158->SetMaximum(1.343993);
   hframe__158->SetDirectory(0);
   hframe__158->SetStats(0);
   hframe__158->SetLineStyle(0);
   hframe__158->SetMarkerStyle(20);
   hframe__158->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__158->GetXaxis()->SetLabelFont(43);
   hframe__158->GetXaxis()->SetLabelOffset(0.007);
   hframe__158->GetXaxis()->SetLabelSize(27);
   hframe__158->GetXaxis()->SetTitleSize(33);
   hframe__158->GetXaxis()->SetTitleOffset(2.925);
   hframe__158->GetXaxis()->SetTitleFont(43);
   hframe__158->GetYaxis()->SetTitle("Ratio");
   hframe__158->GetYaxis()->SetNdivisions(505);
   hframe__158->GetYaxis()->SetLabelFont(43);
   hframe__158->GetYaxis()->SetLabelOffset(0.007);
   hframe__158->GetYaxis()->SetLabelSize(21);
   hframe__158->GetYaxis()->SetTitleSize(33);
   hframe__158->GetYaxis()->SetTitleOffset(1.796875);
   hframe__158->GetYaxis()->SetTitleFont(43);
   hframe__158->GetZaxis()->SetLabelFont(43);
   hframe__158->GetZaxis()->SetLabelOffset(0.007);
   hframe__158->GetZaxis()->SetLabelSize(27);
   hframe__158->GetZaxis()->SetTitleSize(33);
   hframe__158->GetZaxis()->SetTitleFont(43);
   hframe__158->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1", "Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->Range(-81.01265,-1.226501,425.3165,22.27862);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__159 = new TH1F("hframe__159","",1000,0,400);
   hframe__159->SetMinimum(1.829165);
   hframe__159->SetMaximum(21.10336);
   hframe__159->SetDirectory(0);
   hframe__159->SetStats(0);
   hframe__159->SetLineStyle(0);
   hframe__159->SetMarkerStyle(20);
   hframe__159->GetXaxis()->SetLabelFont(43);
   hframe__159->GetXaxis()->SetLabelOffset(0.007);
   hframe__159->GetXaxis()->SetLabelSize(0);
   hframe__159->GetXaxis()->SetTitleSize(0);
   hframe__159->GetXaxis()->SetTitleOffset(0.9);
   hframe__159->GetXaxis()->SetTitleFont(43);
   hframe__159->GetYaxis()->SetTitle("N_{events}");
   hframe__159->GetYaxis()->SetLabelFont(43);
   hframe__159->GetYaxis()->SetLabelOffset(0.007);
   hframe__159->GetYaxis()->SetLabelSize(27);
   hframe__159->GetYaxis()->SetTitleSize(33);
   hframe__159->GetYaxis()->SetTitleOffset(1.796875);
   hframe__159->GetYaxis()->SetTitleFont(43);
   hframe__159->GetZaxis()->SetLabelFont(43);
   hframe__159->GetZaxis()->SetLabelOffset(0.007);
   hframe__159->GetZaxis()->SetLabelSize(27);
   hframe__159->GetZaxis()->SetTitleSize(33);
   hframe__159->GetZaxis()->SetTitleFont(43);
   hframe__159->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Medium");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis113[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis113);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.234895);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.662616);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,7.689222);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,10.38272);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,14.24403);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,15.57385);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,11.84189);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,7.673703);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,6.795688);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,3.097628);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.09271812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4524384);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5404727);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.865639);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.9673791);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.006868);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.011299);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.8733515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.6958784);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.6523457);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.4374302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.06556161);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis114[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,13.37099);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,14.52627);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,10.95717);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,7.075533);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,6.268853);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,2.865561);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.09261809);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9453297);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.9437324);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.8093866);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.6424967);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.6015612);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.4030667);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.06549088);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis115[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis115);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,19.18487);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,14.84108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,15.07799);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,10.27393);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,7.675248);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,4.138463);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.08151437);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.968778);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.73075);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.400046);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.223616);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.004103);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.316265);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.06615137);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(613.1472);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__160 = new TH1F("hframe__160","",1000,0,400);
   hframe__160->SetMinimum(1.829165);
   hframe__160->SetMaximum(21.10336);
   hframe__160->SetDirectory(0);
   hframe__160->SetStats(0);
   hframe__160->SetLineStyle(0);
   hframe__160->SetMarkerStyle(20);
   hframe__160->GetXaxis()->SetLabelFont(43);
   hframe__160->GetXaxis()->SetLabelOffset(0.007);
   hframe__160->GetXaxis()->SetLabelSize(0);
   hframe__160->GetXaxis()->SetTitleSize(0);
   hframe__160->GetXaxis()->SetTitleOffset(0.9);
   hframe__160->GetXaxis()->SetTitleFont(43);
   hframe__160->GetYaxis()->SetTitle("N_{events}");
   hframe__160->GetYaxis()->SetLabelFont(43);
   hframe__160->GetYaxis()->SetLabelOffset(0.007);
   hframe__160->GetYaxis()->SetLabelSize(27);
   hframe__160->GetYaxis()->SetTitleSize(33);
   hframe__160->GetYaxis()->SetTitleOffset(1.796875);
   hframe__160->GetYaxis()->SetTitleFont(43);
   hframe__160->GetZaxis()->SetLabelFont(43);
   hframe__160->GetZaxis()->SetLabelOffset(0.007);
   hframe__160->GetZaxis()->SetLabelSize(27);
   hframe__160->GetZaxis()->SetTitleSize(33);
   hframe__160->GetZaxis()->SetTitleFont(43);
   hframe__160->Draw("sameaxis");
   
   TH1F *hframe__161 = new TH1F("hframe__161","",1000,0,400);
   hframe__161->SetMinimum(1.829165);
   hframe__161->SetMaximum(21.10336);
   hframe__161->SetDirectory(0);
   hframe__161->SetStats(0);
   hframe__161->SetLineStyle(0);
   hframe__161->SetMarkerStyle(20);
   hframe__161->GetXaxis()->SetLabelFont(43);
   hframe__161->GetXaxis()->SetLabelOffset(0.007);
   hframe__161->GetXaxis()->SetLabelSize(0);
   hframe__161->GetXaxis()->SetTitleSize(0);
   hframe__161->GetXaxis()->SetTitleOffset(0.9);
   hframe__161->GetXaxis()->SetTitleFont(43);
   hframe__161->GetYaxis()->SetTitle("N_{events}");
   hframe__161->GetYaxis()->SetLabelFont(43);
   hframe__161->GetYaxis()->SetLabelOffset(0.007);
   hframe__161->GetYaxis()->SetLabelSize(27);
   hframe__161->GetYaxis()->SetTitleSize(33);
   hframe__161->GetYaxis()->SetTitleOffset(1.796875);
   hframe__161->GetYaxis()->SetTitleFont(43);
   hframe__161->GetZaxis()->SetLabelFont(43);
   hframe__161->GetZaxis()->SetLabelOffset(0.007);
   hframe__161->GetZaxis()->SetLabelSize(27);
   hframe__161->GetZaxis()->SetTitleSize(33);
   hframe__161->GetZaxis()->SetTitleFont(43);
   hframe__161->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->Modified();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus->SetSelected(Mt_DataDrivenVsMC_w=0.9_QCDTailKillerMediumPlus);
}
