{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus
//=========  (Wed Aug 13 16:33:25 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->Range(-81.01265,0.6922547,425.3165,1.166558);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__1 = new TH1F("hframe__1","",1000,0,400);
   hframe__1->SetMinimum(0.8298027);
   hframe__1->SetMaximum(1.166558);
   hframe__1->SetDirectory(0);
   hframe__1->SetStats(0);
   hframe__1->SetLineStyle(0);
   hframe__1->SetMarkerStyle(20);
   hframe__1->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__1->GetXaxis()->SetLabelFont(43);
   hframe__1->GetXaxis()->SetLabelOffset(0.007);
   hframe__1->GetXaxis()->SetLabelSize(27);
   hframe__1->GetXaxis()->SetTitleSize(33);
   hframe__1->GetXaxis()->SetTitleOffset(2.925);
   hframe__1->GetXaxis()->SetTitleFont(43);
   hframe__1->GetYaxis()->SetTitle("Ratio");
   hframe__1->GetYaxis()->SetNdivisions(505);
   hframe__1->GetYaxis()->SetLabelFont(43);
   hframe__1->GetYaxis()->SetLabelOffset(0.007);
   hframe__1->GetYaxis()->SetLabelSize(21);
   hframe__1->GetYaxis()->SetTitleSize(33);
   hframe__1->GetYaxis()->SetTitleOffset(1.796875);
   hframe__1->GetYaxis()->SetTitleFont(43);
   hframe__1->GetZaxis()->SetLabelFont(43);
   hframe__1->GetZaxis()->SetLabelOffset(0.007);
   hframe__1->GetZaxis()->SetLabelSize(27);
   hframe__1->GetZaxis()->SetTitleSize(33);
   hframe__1->GetZaxis()->SetTitleFont(43);
   hframe__1->Draw(" ");
   Double_t xAxis1[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2","#tau p_{T}<50",10, xAxis1);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(1,1.060507);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(2,1.055374);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(3,1.013528);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(4,1.038412);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(5,1.016245);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(6,1.034478);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(7,0.9732041);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(8,1.053179);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(9,1.024292);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(10,0.8744884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinContent(11,0.9978434);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(1,0.2198697);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(2,0.189955);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(3,0.113136);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(4,0.1013248);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(5,0.08943951);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(6,0.07540551);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(7,0.08457968);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(8,0.1044921);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(9,0.1043318);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(10,0.1591313);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetBinError(11,0.8210524);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetEntries(586.4366);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__2->Draw("EP same");
   Double_t xAxis2[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3","#tau p_{T}<50",10, xAxis2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(1,1.034032);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(2,1.037006);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(3,0.991746);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(4,1.015073);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(5,0.9972583);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(6,1.014132);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(7,0.9412873);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(8,1.012255);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(9,0.9789543);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(10,0.8298027);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinContent(11,0.9523166);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(1,0.2145485);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(2,0.1867345);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(3,0.110781);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(4,0.09912395);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(5,0.08782472);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(6,0.07396552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(7,0.08186115);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(8,0.1005176);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(9,0.09978163);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(10,0.1510138);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetBinError(11,0.7835918);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetEntries(585.5402);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__3->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,0,440);
   Graph_Graph1->SetMinimum(0.9);
   Graph_Graph1->SetMaximum(2.1);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->SetLineStyle(0);
   Graph_Graph1->SetMarkerStyle(20);
   Graph_Graph1->GetXaxis()->SetLabelFont(43);
   Graph_Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetXaxis()->SetLabelSize(27);
   Graph_Graph1->GetXaxis()->SetTitleSize(33);
   Graph_Graph1->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph1->GetXaxis()->SetTitleFont(43);
   Graph_Graph1->GetYaxis()->SetLabelFont(43);
   Graph_Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetYaxis()->SetLabelSize(27);
   Graph_Graph1->GetYaxis()->SetTitleSize(33);
   Graph_Graph1->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph1->GetYaxis()->SetTitleFont(43);
   Graph_Graph1->GetZaxis()->SetLabelFont(43);
   Graph_Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetZaxis()->SetLabelSize(27);
   Graph_Graph1->GetZaxis()->SetTitleSize(33);
   Graph_Graph1->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph1);
   
   graph->Draw("l");
   
   TH1F *hframe__4 = new TH1F("hframe__4","",1000,0,400);
   hframe__4->SetMinimum(0.8298027);
   hframe__4->SetMaximum(1.166558);
   hframe__4->SetDirectory(0);
   hframe__4->SetStats(0);
   hframe__4->SetLineStyle(0);
   hframe__4->SetMarkerStyle(20);
   hframe__4->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__4->GetXaxis()->SetLabelFont(43);
   hframe__4->GetXaxis()->SetLabelOffset(0.007);
   hframe__4->GetXaxis()->SetLabelSize(27);
   hframe__4->GetXaxis()->SetTitleSize(33);
   hframe__4->GetXaxis()->SetTitleOffset(2.925);
   hframe__4->GetXaxis()->SetTitleFont(43);
   hframe__4->GetYaxis()->SetTitle("Ratio");
   hframe__4->GetYaxis()->SetNdivisions(505);
   hframe__4->GetYaxis()->SetLabelFont(43);
   hframe__4->GetYaxis()->SetLabelOffset(0.007);
   hframe__4->GetYaxis()->SetLabelSize(21);
   hframe__4->GetYaxis()->SetTitleSize(33);
   hframe__4->GetYaxis()->SetTitleOffset(1.796875);
   hframe__4->GetYaxis()->SetTitleFont(43);
   hframe__4->GetZaxis()->SetLabelFont(43);
   hframe__4->GetZaxis()->SetLabelOffset(0.007);
   hframe__4->GetZaxis()->SetLabelSize(27);
   hframe__4->GetZaxis()->SetTitleSize(33);
   hframe__4->GetZaxis()->SetTitleFont(43);
   hframe__4->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->Range(-81.01265,-1.145284,425.3165,28.38795);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__5 = new TH1F("hframe__5","",1000,0,400);
   hframe__5->SetMinimum(2.694036);
   hframe__5->SetMaximum(26.91128);
   hframe__5->SetDirectory(0);
   hframe__5->SetStats(0);
   hframe__5->SetLineStyle(0);
   hframe__5->SetMarkerStyle(20);
   hframe__5->GetXaxis()->SetLabelFont(43);
   hframe__5->GetXaxis()->SetLabelOffset(0.007);
   hframe__5->GetXaxis()->SetLabelSize(0);
   hframe__5->GetXaxis()->SetTitleSize(0);
   hframe__5->GetXaxis()->SetTitleOffset(0.9);
   hframe__5->GetXaxis()->SetTitleFont(43);
   hframe__5->GetYaxis()->SetTitle("N_{events}");
   hframe__5->GetYaxis()->SetLabelFont(43);
   hframe__5->GetYaxis()->SetLabelOffset(0.007);
   hframe__5->GetYaxis()->SetLabelSize(27);
   hframe__5->GetYaxis()->SetTitleSize(33);
   hframe__5->GetYaxis()->SetTitleOffset(1.796875);
   hframe__5->GetYaxis()->SetTitleFont(43);
   hframe__5->GetZaxis()->SetLabelFont(43);
   hframe__5->GetZaxis()->SetLabelOffset(0.007);
   hframe__5->GetZaxis()->SetLabelSize(27);
   hframe__5->GetZaxis()->SetTitleSize(33);
   hframe__5->GetZaxis()->SetTitleFont(43);
   hframe__5->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis3[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis3);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.857044);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.881396);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,10.26861);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,13.0928);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,16.97052);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,24.4648);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,19.05075);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,12.72064);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,12.24327);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,5.638563);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1539157);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4188037);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.4936711);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.7963207);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.89689);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.023443);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.228584);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.055693);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.8602771);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.8301422);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.5546497);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.08886325);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(2038.923);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis4[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.785719);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,3.813843);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,10.04792);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,12.79853);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,16.65346);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,23.98363);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,18.42597);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,12.22635);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.70136);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,5.350437);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.1468932);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4089875);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.4855243);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.7803209);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.8781042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,1.005691);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.205899);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.022769);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.8283683);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.7946149);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.5264743);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.08480885);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(2038.923);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis5[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis5);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,2.694036);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.677743);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,10.13155);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,12.60848);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,16.69924);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,23.64941);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,19.57529);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,12.07833);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,11.95292);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,6.447843);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.1542483);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.3949873);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,0.4683706);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,0.8134629);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,0.8761411);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,1.070417);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.249486);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,1.310563);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,0.8768385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,0.9085457);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.9871152);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.09043094);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(2026.691);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__6 = new TH1F("hframe__6","",1000,0,400);
   hframe__6->SetMinimum(2.694036);
   hframe__6->SetMaximum(26.91128);
   hframe__6->SetDirectory(0);
   hframe__6->SetStats(0);
   hframe__6->SetLineStyle(0);
   hframe__6->SetMarkerStyle(20);
   hframe__6->GetXaxis()->SetLabelFont(43);
   hframe__6->GetXaxis()->SetLabelOffset(0.007);
   hframe__6->GetXaxis()->SetLabelSize(0);
   hframe__6->GetXaxis()->SetTitleSize(0);
   hframe__6->GetXaxis()->SetTitleOffset(0.9);
   hframe__6->GetXaxis()->SetTitleFont(43);
   hframe__6->GetYaxis()->SetTitle("N_{events}");
   hframe__6->GetYaxis()->SetLabelFont(43);
   hframe__6->GetYaxis()->SetLabelOffset(0.007);
   hframe__6->GetYaxis()->SetLabelSize(27);
   hframe__6->GetYaxis()->SetTitleSize(33);
   hframe__6->GetYaxis()->SetTitleOffset(1.796875);
   hframe__6->GetYaxis()->SetTitleFont(43);
   hframe__6->GetZaxis()->SetLabelFont(43);
   hframe__6->GetZaxis()->SetLabelOffset(0.007);
   hframe__6->GetZaxis()->SetLabelSize(27);
   hframe__6->GetZaxis()->SetTitleSize(33);
   hframe__6->GetZaxis()->SetTitleFont(43);
   hframe__6->Draw("sameaxis");
   
   TH1F *hframe__7 = new TH1F("hframe__7","",1000,0,400);
   hframe__7->SetMinimum(2.694036);
   hframe__7->SetMaximum(26.91128);
   hframe__7->SetDirectory(0);
   hframe__7->SetStats(0);
   hframe__7->SetLineStyle(0);
   hframe__7->SetMarkerStyle(20);
   hframe__7->GetXaxis()->SetLabelFont(43);
   hframe__7->GetXaxis()->SetLabelOffset(0.007);
   hframe__7->GetXaxis()->SetLabelSize(0);
   hframe__7->GetXaxis()->SetTitleSize(0);
   hframe__7->GetXaxis()->SetTitleOffset(0.9);
   hframe__7->GetXaxis()->SetTitleFont(43);
   hframe__7->GetYaxis()->SetTitle("N_{events}");
   hframe__7->GetYaxis()->SetLabelFont(43);
   hframe__7->GetYaxis()->SetLabelOffset(0.007);
   hframe__7->GetYaxis()->SetLabelSize(27);
   hframe__7->GetYaxis()->SetTitleSize(33);
   hframe__7->GetYaxis()->SetTitleOffset(1.796875);
   hframe__7->GetYaxis()->SetTitleFont(43);
   hframe__7->GetZaxis()->SetLabelFont(43);
   hframe__7->GetZaxis()->SetLabelOffset(0.007);
   hframe__7->GetZaxis()->SetLabelSize(27);
   hframe__7->GetZaxis()->SetTitleSize(33);
   hframe__7->GetZaxis()->SetTitleFont(43);
   hframe__7->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus);
}
