{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus
//=========  (Wed Jul 30 13:57:04 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->Range(-81.01265,0.1986354,425.3165,1.497939);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__225 = new TH1F("hframe__225","",1000,0,400);
   hframe__225->SetMinimum(0.5754333);
   hframe__225->SetMaximum(1.497939);
   hframe__225->SetDirectory(0);
   hframe__225->SetStats(0);
   hframe__225->SetLineStyle(0);
   hframe__225->SetMarkerStyle(20);
   hframe__225->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__225->GetXaxis()->SetLabelFont(43);
   hframe__225->GetXaxis()->SetLabelOffset(0.007);
   hframe__225->GetXaxis()->SetLabelSize(27);
   hframe__225->GetXaxis()->SetTitleSize(33);
   hframe__225->GetXaxis()->SetTitleOffset(2.925);
   hframe__225->GetXaxis()->SetTitleFont(43);
   hframe__225->GetYaxis()->SetTitle("Ratio");
   hframe__225->GetYaxis()->SetNdivisions(505);
   hframe__225->GetYaxis()->SetLabelFont(43);
   hframe__225->GetYaxis()->SetLabelOffset(0.007);
   hframe__225->GetYaxis()->SetLabelSize(21);
   hframe__225->GetYaxis()->SetTitleSize(33);
   hframe__225->GetYaxis()->SetTitleOffset(1.796875);
   hframe__225->GetYaxis()->SetTitleFont(43);
   hframe__225->GetZaxis()->SetLabelFont(43);
   hframe__225->GetZaxis()->SetLabelOffset(0.007);
   hframe__225->GetZaxis()->SetLabelSize(27);
   hframe__225->GetZaxis()->SetTitleSize(33);
   hframe__225->GetZaxis()->SetTitleFont(43);
   hframe__225->Draw(" ");
   Double_t xAxis161[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226","#tau p_{T}<50",10, xAxis161);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(1,1.308084);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(2,0.8243951);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(3,0.9506361);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(4,0.9355332);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(5,0.8920541);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(6,1.061914);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(7,0.6606854);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(8,0.7930064);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(9,1.361762);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinContent(10,0.7867314);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(1,0.4109644);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(2,0.3008269);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(3,0.1821089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(4,0.1688951);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(5,0.1626214);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(6,0.1987221);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(7,0.1560104);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(8,0.2396449);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(9,0.5973642);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetBinError(10,0.3887223);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetEntries(93.86079);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__226->Draw("EP same");
   Double_t xAxis162[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227","#tau p_{T}<50",10, xAxis162);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(5,0.7852051);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(6,0.9266732);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(7,0.5754333);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(8,0.6842363);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(9,1.174884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinContent(10,0.6684515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(5,0.1431421);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(6,0.1733767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(7,0.1358588);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(8,0.2067999);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(9,0.5152653);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetBinError(10,0.3299514);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetEntries(94.75576);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__227->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph33 = new TH1F("Graph_Graph33","Graph",100,0,440);
   Graph_Graph33->SetMinimum(0.9);
   Graph_Graph33->SetMaximum(2.1);
   Graph_Graph33->SetDirectory(0);
   Graph_Graph33->SetStats(0);
   Graph_Graph33->SetLineStyle(0);
   Graph_Graph33->SetMarkerStyle(20);
   Graph_Graph33->GetXaxis()->SetLabelFont(43);
   Graph_Graph33->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph33->GetXaxis()->SetLabelSize(27);
   Graph_Graph33->GetXaxis()->SetTitleSize(33);
   Graph_Graph33->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph33->GetXaxis()->SetTitleFont(43);
   Graph_Graph33->GetYaxis()->SetLabelFont(43);
   Graph_Graph33->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph33->GetYaxis()->SetLabelSize(27);
   Graph_Graph33->GetYaxis()->SetTitleSize(33);
   Graph_Graph33->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph33->GetYaxis()->SetTitleFont(43);
   Graph_Graph33->GetZaxis()->SetLabelFont(43);
   Graph_Graph33->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph33->GetZaxis()->SetLabelSize(27);
   Graph_Graph33->GetZaxis()->SetTitleSize(33);
   Graph_Graph33->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph33);
   
   graph->Draw("l");
   
   TH1F *hframe__228 = new TH1F("hframe__228","",1000,0,400);
   hframe__228->SetMinimum(0.5754333);
   hframe__228->SetMaximum(1.497939);
   hframe__228->SetDirectory(0);
   hframe__228->SetStats(0);
   hframe__228->SetLineStyle(0);
   hframe__228->SetMarkerStyle(20);
   hframe__228->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__228->GetXaxis()->SetLabelFont(43);
   hframe__228->GetXaxis()->SetLabelOffset(0.007);
   hframe__228->GetXaxis()->SetLabelSize(27);
   hframe__228->GetXaxis()->SetTitleSize(33);
   hframe__228->GetXaxis()->SetTitleOffset(2.925);
   hframe__228->GetXaxis()->SetTitleFont(43);
   hframe__228->GetYaxis()->SetTitle("Ratio");
   hframe__228->GetYaxis()->SetNdivisions(505);
   hframe__228->GetYaxis()->SetLabelFont(43);
   hframe__228->GetYaxis()->SetLabelOffset(0.007);
   hframe__228->GetYaxis()->SetLabelSize(21);
   hframe__228->GetYaxis()->SetTitleSize(33);
   hframe__228->GetYaxis()->SetTitleOffset(1.796875);
   hframe__228->GetYaxis()->SetTitleFont(43);
   hframe__228->GetZaxis()->SetLabelFont(43);
   hframe__228->GetZaxis()->SetLabelOffset(0.007);
   hframe__228->GetZaxis()->SetLabelSize(27);
   hframe__228->GetZaxis()->SetTitleSize(33);
   hframe__228->GetZaxis()->SetTitleFont(43);
   hframe__228->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->Range(-81.01265,-0.6706663,425.3165,15.5153);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__229 = new TH1F("hframe__229","",1000,0,400);
   hframe__229->SetMinimum(1.433509);
   hframe__229->SetMaximum(14.706);
   hframe__229->SetDirectory(0);
   hframe__229->SetStats(0);
   hframe__229->SetLineStyle(0);
   hframe__229->SetMarkerStyle(20);
   hframe__229->GetXaxis()->SetLabelFont(43);
   hframe__229->GetXaxis()->SetLabelOffset(0.007);
   hframe__229->GetXaxis()->SetLabelSize(0);
   hframe__229->GetXaxis()->SetTitleSize(0);
   hframe__229->GetXaxis()->SetTitleOffset(0.9);
   hframe__229->GetXaxis()->SetTitleFont(43);
   hframe__229->GetYaxis()->SetTitle("N_{events}");
   hframe__229->GetYaxis()->SetLabelFont(43);
   hframe__229->GetYaxis()->SetLabelOffset(0.007);
   hframe__229->GetYaxis()->SetLabelSize(27);
   hframe__229->GetYaxis()->SetTitleSize(33);
   hframe__229->GetYaxis()->SetTitleOffset(1.796875);
   hframe__229->GetYaxis()->SetTitleFont(43);
   hframe__229->GetZaxis()->SetLabelFont(43);
   hframe__229->GetZaxis()->SetLabelOffset(0.007);
   hframe__229->GetZaxis()->SetLabelSize(27);
   hframe__229->GetZaxis()->SetTitleSize(33);
   hframe__229->GetZaxis()->SetTitleFont(43);
   hframe__229->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis163[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis163);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.392701);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.814361);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,8.215124);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,11.0894);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,11.92595);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,9.775101);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,7.036292);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,4.907629);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,4.096635);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,1.687163);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.483908);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5736954);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.9217877);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.031666);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,0.9632671);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,0.8399437);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.7015524);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.5721329);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.531651);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.3523118);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis164[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis164);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,10.49748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,8.530189);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.128358);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.23449);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.534443);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.433509);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8478657);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7322293);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6105065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4940598);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4574585);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.2976706);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis165[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,13.36909);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.205174);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,10.64999);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,6.188637);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.008334);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,2.144523);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,-0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.184911);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.530287);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.279653);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,1.725427);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,1.260593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.9603232);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(420.2798);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__230 = new TH1F("hframe__230","",1000,0,400);
   hframe__230->SetMinimum(1.433509);
   hframe__230->SetMaximum(14.706);
   hframe__230->SetDirectory(0);
   hframe__230->SetStats(0);
   hframe__230->SetLineStyle(0);
   hframe__230->SetMarkerStyle(20);
   hframe__230->GetXaxis()->SetLabelFont(43);
   hframe__230->GetXaxis()->SetLabelOffset(0.007);
   hframe__230->GetXaxis()->SetLabelSize(0);
   hframe__230->GetXaxis()->SetTitleSize(0);
   hframe__230->GetXaxis()->SetTitleOffset(0.9);
   hframe__230->GetXaxis()->SetTitleFont(43);
   hframe__230->GetYaxis()->SetTitle("N_{events}");
   hframe__230->GetYaxis()->SetLabelFont(43);
   hframe__230->GetYaxis()->SetLabelOffset(0.007);
   hframe__230->GetYaxis()->SetLabelSize(27);
   hframe__230->GetYaxis()->SetTitleSize(33);
   hframe__230->GetYaxis()->SetTitleOffset(1.796875);
   hframe__230->GetYaxis()->SetTitleFont(43);
   hframe__230->GetZaxis()->SetLabelFont(43);
   hframe__230->GetZaxis()->SetLabelOffset(0.007);
   hframe__230->GetZaxis()->SetLabelSize(27);
   hframe__230->GetZaxis()->SetTitleSize(33);
   hframe__230->GetZaxis()->SetTitleFont(43);
   hframe__230->Draw("sameaxis");
   
   TH1F *hframe__231 = new TH1F("hframe__231","",1000,0,400);
   hframe__231->SetMinimum(1.433509);
   hframe__231->SetMaximum(14.706);
   hframe__231->SetDirectory(0);
   hframe__231->SetStats(0);
   hframe__231->SetLineStyle(0);
   hframe__231->SetMarkerStyle(20);
   hframe__231->GetXaxis()->SetLabelFont(43);
   hframe__231->GetXaxis()->SetLabelOffset(0.007);
   hframe__231->GetXaxis()->SetLabelSize(0);
   hframe__231->GetXaxis()->SetTitleSize(0);
   hframe__231->GetXaxis()->SetTitleOffset(0.9);
   hframe__231->GetXaxis()->SetTitleFont(43);
   hframe__231->GetYaxis()->SetTitle("N_{events}");
   hframe__231->GetYaxis()->SetLabelFont(43);
   hframe__231->GetYaxis()->SetLabelOffset(0.007);
   hframe__231->GetYaxis()->SetLabelSize(27);
   hframe__231->GetYaxis()->SetTitleSize(33);
   hframe__231->GetYaxis()->SetTitleOffset(1.796875);
   hframe__231->GetYaxis()->SetTitleFont(43);
   hframe__231->GetZaxis()->SetLabelFont(43);
   hframe__231->GetZaxis()->SetLabelOffset(0.007);
   hframe__231->GetZaxis()->SetLabelSize(27);
   hframe__231->GetZaxis()->SetTitleSize(33);
   hframe__231->GetZaxis()->SetTitleFont(43);
   hframe__231->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.8_QCDTailKillerTightPlus);
}
