{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus
//=========  (Wed Jul 30 13:20:02 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->Range(-141.7721,-0.7815251,744.3038,1.913389);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__22 = new TH1F("hframe__22","",1000,0,700);
   hframe__22->SetMinimum(0);
   hframe__22->SetMaximum(1.913389);
   hframe__22->SetDirectory(0);
   hframe__22->SetStats(0);
   hframe__22->SetLineStyle(0);
   hframe__22->SetMarkerStyle(20);
   hframe__22->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__22->GetXaxis()->SetLabelFont(43);
   hframe__22->GetXaxis()->SetLabelOffset(0.007);
   hframe__22->GetXaxis()->SetLabelSize(27);
   hframe__22->GetXaxis()->SetTitleSize(33);
   hframe__22->GetXaxis()->SetTitleOffset(2.925);
   hframe__22->GetXaxis()->SetTitleFont(43);
   hframe__22->GetYaxis()->SetTitle("Ratio");
   hframe__22->GetYaxis()->SetNdivisions(505);
   hframe__22->GetYaxis()->SetLabelFont(43);
   hframe__22->GetYaxis()->SetLabelOffset(0.007);
   hframe__22->GetYaxis()->SetLabelSize(21);
   hframe__22->GetYaxis()->SetTitleSize(33);
   hframe__22->GetYaxis()->SetTitleOffset(1.796875);
   hframe__22->GetYaxis()->SetTitleFont(43);
   hframe__22->GetZaxis()->SetLabelFont(43);
   hframe__22->GetZaxis()->SetLabelOffset(0.007);
   hframe__22->GetZaxis()->SetLabelSize(27);
   hframe__22->GetZaxis()->SetTitleSize(33);
   hframe__22->GetZaxis()->SetTitleFont(43);
   hframe__22->Draw(" ");
   Double_t xAxis16[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 700}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23","#tau p_{T}<50",10, xAxis16);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(1,1.739445);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(2,1.046645);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(3,1.254917);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(4,1.23362);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(5,1.039712);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(6,1.457786);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(7,1.215055);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(8,1.141883);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinContent(9,1.37786);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(1,0.5467827);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(2,0.3844134);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(3,0.2397995);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(4,0.222689);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(5,0.1660104);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(6,0.1475114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(7,0.1630447);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(8,0.198013);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(9,0.259205);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetBinError(10,nan);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetEntries(11.50692);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__23->Draw("EP same");
   Double_t xAxis17[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 700}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24","#tau p_{T}<50",10, xAxis17);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(5,0.7207969);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(6,0.9898824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(7,0.7621042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(8,0.7042185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(9,0.8474045);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinContent(10,nan);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(5,0.1149444);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(6,0.100059);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(7,0.1022867);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(8,0.1220903);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(9,0.1592168);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetBinError(10,nan);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetEntries(nan);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__24->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,700,1);
   
   TH1F *Graph_Graph4 = new TH1F("Graph_Graph4","Graph",100,0,770);
   Graph_Graph4->SetMinimum(0.9);
   Graph_Graph4->SetMaximum(2.1);
   Graph_Graph4->SetDirectory(0);
   Graph_Graph4->SetStats(0);
   Graph_Graph4->SetLineStyle(0);
   Graph_Graph4->SetMarkerStyle(20);
   Graph_Graph4->GetXaxis()->SetLabelFont(43);
   Graph_Graph4->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetXaxis()->SetLabelSize(27);
   Graph_Graph4->GetXaxis()->SetTitleSize(33);
   Graph_Graph4->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph4->GetXaxis()->SetTitleFont(43);
   Graph_Graph4->GetYaxis()->SetLabelFont(43);
   Graph_Graph4->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetYaxis()->SetLabelSize(27);
   Graph_Graph4->GetYaxis()->SetTitleSize(33);
   Graph_Graph4->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph4->GetYaxis()->SetTitleFont(43);
   Graph_Graph4->GetZaxis()->SetLabelFont(43);
   Graph_Graph4->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetZaxis()->SetLabelSize(27);
   Graph_Graph4->GetZaxis()->SetTitleSize(33);
   Graph_Graph4->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph4);
   
   graph->Draw("l");
   
   TH1F *hframe__25 = new TH1F("hframe__25","",1000,0,700);
   hframe__25->SetMinimum(0);
   hframe__25->SetMaximum(1.913389);
   hframe__25->SetDirectory(0);
   hframe__25->SetStats(0);
   hframe__25->SetLineStyle(0);
   hframe__25->SetMarkerStyle(20);
   hframe__25->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__25->GetXaxis()->SetLabelFont(43);
   hframe__25->GetXaxis()->SetLabelOffset(0.007);
   hframe__25->GetXaxis()->SetLabelSize(27);
   hframe__25->GetXaxis()->SetTitleSize(33);
   hframe__25->GetXaxis()->SetTitleOffset(2.925);
   hframe__25->GetXaxis()->SetTitleFont(43);
   hframe__25->GetYaxis()->SetTitle("Ratio");
   hframe__25->GetYaxis()->SetNdivisions(505);
   hframe__25->GetYaxis()->SetLabelFont(43);
   hframe__25->GetYaxis()->SetLabelOffset(0.007);
   hframe__25->GetYaxis()->SetLabelSize(21);
   hframe__25->GetYaxis()->SetTitleSize(33);
   hframe__25->GetYaxis()->SetTitleOffset(1.796875);
   hframe__25->GetYaxis()->SetTitleFont(43);
   hframe__25->GetZaxis()->SetLabelFont(43);
   hframe__25->GetZaxis()->SetLabelOffset(0.007);
   hframe__25->GetZaxis()->SetLabelSize(27);
   hframe__25->GetZaxis()->SetTitleSize(33);
   hframe__25->GetZaxis()->SetTitleFont(43);
   hframe__25->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->Range(-141.7721,-3.648225,744.3038,38.48554);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__26 = new TH1F("hframe__26","",1000,0,700);
   hframe__26->SetMinimum(1.829165);
   hframe__26->SetMaximum(36.37885);
   hframe__26->SetDirectory(0);
   hframe__26->SetStats(0);
   hframe__26->SetLineStyle(0);
   hframe__26->SetMarkerStyle(20);
   hframe__26->GetXaxis()->SetLabelFont(43);
   hframe__26->GetXaxis()->SetLabelOffset(0.007);
   hframe__26->GetXaxis()->SetLabelSize(0);
   hframe__26->GetXaxis()->SetTitleSize(0);
   hframe__26->GetXaxis()->SetTitleOffset(0.9);
   hframe__26->GetXaxis()->SetTitleFont(43);
   hframe__26->GetYaxis()->SetTitle("N_{events}");
   hframe__26->GetYaxis()->SetLabelFont(43);
   hframe__26->GetYaxis()->SetLabelOffset(0.007);
   hframe__26->GetYaxis()->SetLabelSize(27);
   hframe__26->GetYaxis()->SetTitleSize(33);
   hframe__26->GetYaxis()->SetTitleOffset(1.796875);
   hframe__26->GetYaxis()->SetTitleFont(43);
   hframe__26->GetZaxis()->SetLabelFont(43);
   hframe__26->GetZaxis()->SetLabelOffset(0.007);
   hframe__26->GetZaxis()->SetLabelSize(27);
   hframe__26->GetZaxis()->SetTitleSize(33);
   hframe__26->GetZaxis()->SetTitleFont(43);
   hframe__26->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis18[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 700}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis18);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.181731);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.573089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,10.84463);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,14.62279);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,21.42964);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,33.07169);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,27.69101);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,18.83214);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,18.39655);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,7.823883);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.6443262);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.7434447);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.207976);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.359904);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.442273);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.727501);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.599772);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,1.322551);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,1.313998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,inf);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis19[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 700}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis19);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,14.85644);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,22.45671);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,17.3683);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,11.6141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.31415);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,inf);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9927686);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.168366);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.004578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.8145114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.8011357);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,2.148273e+91);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis20[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 700}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,20.61114);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.68624);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,22.78992);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,16.49218);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,13.35154);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,inf);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.984329);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.96608);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.760173);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.614869);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.323627);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,nan);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(901.3783);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__27 = new TH1F("hframe__27","",1000,0,700);
   hframe__27->SetMinimum(1.829165);
   hframe__27->SetMaximum(36.37885);
   hframe__27->SetDirectory(0);
   hframe__27->SetStats(0);
   hframe__27->SetLineStyle(0);
   hframe__27->SetMarkerStyle(20);
   hframe__27->GetXaxis()->SetLabelFont(43);
   hframe__27->GetXaxis()->SetLabelOffset(0.007);
   hframe__27->GetXaxis()->SetLabelSize(0);
   hframe__27->GetXaxis()->SetTitleSize(0);
   hframe__27->GetXaxis()->SetTitleOffset(0.9);
   hframe__27->GetXaxis()->SetTitleFont(43);
   hframe__27->GetYaxis()->SetTitle("N_{events}");
   hframe__27->GetYaxis()->SetLabelFont(43);
   hframe__27->GetYaxis()->SetLabelOffset(0.007);
   hframe__27->GetYaxis()->SetLabelSize(27);
   hframe__27->GetYaxis()->SetTitleSize(33);
   hframe__27->GetYaxis()->SetTitleOffset(1.796875);
   hframe__27->GetYaxis()->SetTitleFont(43);
   hframe__27->GetZaxis()->SetLabelFont(43);
   hframe__27->GetZaxis()->SetLabelOffset(0.007);
   hframe__27->GetZaxis()->SetLabelSize(27);
   hframe__27->GetZaxis()->SetTitleSize(33);
   hframe__27->GetZaxis()->SetTitleFont(43);
   hframe__27->Draw("sameaxis");
   
   TH1F *hframe__28 = new TH1F("hframe__28","",1000,0,700);
   hframe__28->SetMinimum(1.829165);
   hframe__28->SetMaximum(36.37885);
   hframe__28->SetDirectory(0);
   hframe__28->SetStats(0);
   hframe__28->SetLineStyle(0);
   hframe__28->SetMarkerStyle(20);
   hframe__28->GetXaxis()->SetLabelFont(43);
   hframe__28->GetXaxis()->SetLabelOffset(0.007);
   hframe__28->GetXaxis()->SetLabelSize(0);
   hframe__28->GetXaxis()->SetTitleSize(0);
   hframe__28->GetXaxis()->SetTitleOffset(0.9);
   hframe__28->GetXaxis()->SetTitleFont(43);
   hframe__28->GetYaxis()->SetTitle("N_{events}");
   hframe__28->GetYaxis()->SetLabelFont(43);
   hframe__28->GetYaxis()->SetLabelOffset(0.007);
   hframe__28->GetYaxis()->SetLabelSize(27);
   hframe__28->GetYaxis()->SetTitleSize(33);
   hframe__28->GetYaxis()->SetTitleOffset(1.796875);
   hframe__28->GetYaxis()->SetTitleFont(43);
   hframe__28->GetZaxis()->SetLabelFont(43);
   hframe__28->GetZaxis()->SetLabelOffset(0.007);
   hframe__28->GetZaxis()->SetLabelSize(27);
   hframe__28->GetZaxis()->SetTitleSize(33);
   hframe__28->GetZaxis()->SetTitleFont(43);
   hframe__28->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.3_QCDTailKillerLoosePlus);
}
