{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus/Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus
//=========  (Wed Jul 30 13:56:39 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus", "Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2", "Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->Range(-81.01265,0.304743,425.3165,1.628691);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__113 = new TH1F("hframe__113","",1000,0,400);
   hframe__113->SetMinimum(0.6886879);
   hframe__113->SetMaximum(1.628691);
   hframe__113->SetDirectory(0);
   hframe__113->SetStats(0);
   hframe__113->SetLineStyle(0);
   hframe__113->SetMarkerStyle(20);
   hframe__113->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__113->GetXaxis()->SetLabelFont(43);
   hframe__113->GetXaxis()->SetLabelOffset(0.007);
   hframe__113->GetXaxis()->SetLabelSize(27);
   hframe__113->GetXaxis()->SetTitleSize(33);
   hframe__113->GetXaxis()->SetTitleOffset(2.925);
   hframe__113->GetXaxis()->SetTitleFont(43);
   hframe__113->GetYaxis()->SetTitle("Ratio");
   hframe__113->GetYaxis()->SetNdivisions(505);
   hframe__113->GetYaxis()->SetLabelFont(43);
   hframe__113->GetYaxis()->SetLabelOffset(0.007);
   hframe__113->GetYaxis()->SetLabelSize(21);
   hframe__113->GetYaxis()->SetTitleSize(33);
   hframe__113->GetYaxis()->SetTitleOffset(1.796875);
   hframe__113->GetYaxis()->SetTitleFont(43);
   hframe__113->GetZaxis()->SetLabelFont(43);
   hframe__113->GetZaxis()->SetLabelOffset(0.007);
   hframe__113->GetZaxis()->SetLabelSize(27);
   hframe__113->GetZaxis()->SetTitleSize(33);
   hframe__113->GetZaxis()->SetTitleFont(43);
   hframe__113->Draw(" ");
   Double_t xAxis81[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114","#tau p_{T}<50",10, xAxis81);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(1,1.480628);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(2,0.9132951);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(3,1.072348);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(4,1.054768);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(5,0.8789831);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(6,1.261134);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(7,0.9614049);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(8,0.9215764);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(9,1.091325);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(10,0.9167236);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinContent(11,1.141126);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(1,0.4651133);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(2,0.3341569);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(3,0.2051233);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(4,0.1903635);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(5,0.1496006);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(6,0.1684028);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(7,0.1686528);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(8,0.2162801);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(9,0.3037667);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(10,0.3198203);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetBinError(11,1.228279);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetEntries(153.1987);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__114->Draw("EP same");
   Double_t xAxis82[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115","#tau p_{T}<50",10, xAxis82);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(5,0.6969547);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(6,0.978788);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(7,0.7266998);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(8,0.6886879);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(9,0.8167623);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(10,0.6924216);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinContent(11,1.136218);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(5,0.118574);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(6,0.1306626);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(7,0.1275215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(8,0.1616419);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(9,0.2272129);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(10,0.2408043);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetBinError(11,1.222996);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetEntries(153.3889);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__115->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph17 = new TH1F("Graph_Graph17","Graph",100,0,440);
   Graph_Graph17->SetMinimum(0.9);
   Graph_Graph17->SetMaximum(2.1);
   Graph_Graph17->SetDirectory(0);
   Graph_Graph17->SetStats(0);
   Graph_Graph17->SetLineStyle(0);
   Graph_Graph17->SetMarkerStyle(20);
   Graph_Graph17->GetXaxis()->SetLabelFont(43);
   Graph_Graph17->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph17->GetXaxis()->SetLabelSize(27);
   Graph_Graph17->GetXaxis()->SetTitleSize(33);
   Graph_Graph17->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph17->GetXaxis()->SetTitleFont(43);
   Graph_Graph17->GetYaxis()->SetLabelFont(43);
   Graph_Graph17->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph17->GetYaxis()->SetLabelSize(27);
   Graph_Graph17->GetYaxis()->SetTitleSize(33);
   Graph_Graph17->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph17->GetYaxis()->SetTitleFont(43);
   Graph_Graph17->GetZaxis()->SetLabelFont(43);
   Graph_Graph17->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph17->GetZaxis()->SetLabelSize(27);
   Graph_Graph17->GetZaxis()->SetTitleSize(33);
   Graph_Graph17->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph17);
   
   graph->Draw("l");
   
   TH1F *hframe__116 = new TH1F("hframe__116","",1000,0,400);
   hframe__116->SetMinimum(0.6886879);
   hframe__116->SetMaximum(1.628691);
   hframe__116->SetDirectory(0);
   hframe__116->SetStats(0);
   hframe__116->SetLineStyle(0);
   hframe__116->SetMarkerStyle(20);
   hframe__116->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__116->GetXaxis()->SetLabelFont(43);
   hframe__116->GetXaxis()->SetLabelOffset(0.007);
   hframe__116->GetXaxis()->SetLabelSize(27);
   hframe__116->GetXaxis()->SetTitleSize(33);
   hframe__116->GetXaxis()->SetTitleOffset(2.925);
   hframe__116->GetXaxis()->SetTitleFont(43);
   hframe__116->GetYaxis()->SetTitle("Ratio");
   hframe__116->GetYaxis()->SetNdivisions(505);
   hframe__116->GetYaxis()->SetLabelFont(43);
   hframe__116->GetYaxis()->SetLabelOffset(0.007);
   hframe__116->GetYaxis()->SetLabelSize(21);
   hframe__116->GetYaxis()->SetTitleSize(33);
   hframe__116->GetYaxis()->SetTitleOffset(1.796875);
   hframe__116->GetYaxis()->SetTitleFont(43);
   hframe__116->GetZaxis()->SetLabelFont(43);
   hframe__116->GetZaxis()->SetLabelOffset(0.007);
   hframe__116->GetZaxis()->SetLabelSize(27);
   hframe__116->GetZaxis()->SetTitleSize(33);
   hframe__116->GetZaxis()->SetTitleFont(43);
   hframe__116->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1", "Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->Range(-81.01265,-1.226501,425.3165,22.27862);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__117 = new TH1F("hframe__117","",1000,0,400);
   hframe__117->SetMinimum(1.829165);
   hframe__117->SetMaximum(21.10336);
   hframe__117->SetDirectory(0);
   hframe__117->SetStats(0);
   hframe__117->SetLineStyle(0);
   hframe__117->SetMarkerStyle(20);
   hframe__117->GetXaxis()->SetLabelFont(43);
   hframe__117->GetXaxis()->SetLabelOffset(0.007);
   hframe__117->GetXaxis()->SetLabelSize(0);
   hframe__117->GetXaxis()->SetTitleSize(0);
   hframe__117->GetXaxis()->SetTitleOffset(0.9);
   hframe__117->GetXaxis()->SetTitleFont(43);
   hframe__117->GetYaxis()->SetTitle("N_{events}");
   hframe__117->GetYaxis()->SetLabelFont(43);
   hframe__117->GetYaxis()->SetLabelOffset(0.007);
   hframe__117->GetYaxis()->SetLabelSize(27);
   hframe__117->GetYaxis()->SetTitleSize(33);
   hframe__117->GetYaxis()->SetTitleOffset(1.796875);
   hframe__117->GetYaxis()->SetTitleFont(43);
   hframe__117->GetZaxis()->SetLabelFont(43);
   hframe__117->GetZaxis()->SetLabelOffset(0.007);
   hframe__117->GetZaxis()->SetLabelSize(27);
   hframe__117->GetZaxis()->SetTitleSize(33);
   hframe__117->GetZaxis()->SetTitleFont(43);
   hframe__117->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Medium");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis83[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis83);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.708313);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.117852);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,9.266926);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,12.50275);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,16.86318);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,18.71659);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,14.49606);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,9.468214);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,8.376193);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,3.793827);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.09301818);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.5475685);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.6409827);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.035354);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.161829);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.194895);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.217448);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.068833);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.8591507);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.8076436);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.5438896);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.06577379);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis84[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis84);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,13.37099);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,14.52627);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,10.95717);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,7.075533);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,6.268853);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,2.865561);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.09261809);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9453297);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.9437324);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.8093866);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.6424967);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.6015612);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.4030667);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.06549088);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1125.145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis85[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis85);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,19.18487);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,14.84108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,15.07799);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,10.27393);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,7.675248);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,4.138463);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.08151437);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.968778);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.73075);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.400046);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.223616);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.004103);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.316265);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.06615137);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(613.1472);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__118 = new TH1F("hframe__118","",1000,0,400);
   hframe__118->SetMinimum(1.829165);
   hframe__118->SetMaximum(21.10336);
   hframe__118->SetDirectory(0);
   hframe__118->SetStats(0);
   hframe__118->SetLineStyle(0);
   hframe__118->SetMarkerStyle(20);
   hframe__118->GetXaxis()->SetLabelFont(43);
   hframe__118->GetXaxis()->SetLabelOffset(0.007);
   hframe__118->GetXaxis()->SetLabelSize(0);
   hframe__118->GetXaxis()->SetTitleSize(0);
   hframe__118->GetXaxis()->SetTitleOffset(0.9);
   hframe__118->GetXaxis()->SetTitleFont(43);
   hframe__118->GetYaxis()->SetTitle("N_{events}");
   hframe__118->GetYaxis()->SetLabelFont(43);
   hframe__118->GetYaxis()->SetLabelOffset(0.007);
   hframe__118->GetYaxis()->SetLabelSize(27);
   hframe__118->GetYaxis()->SetTitleSize(33);
   hframe__118->GetYaxis()->SetTitleOffset(1.796875);
   hframe__118->GetYaxis()->SetTitleFont(43);
   hframe__118->GetZaxis()->SetLabelFont(43);
   hframe__118->GetZaxis()->SetLabelOffset(0.007);
   hframe__118->GetZaxis()->SetLabelSize(27);
   hframe__118->GetZaxis()->SetTitleSize(33);
   hframe__118->GetZaxis()->SetTitleFont(43);
   hframe__118->Draw("sameaxis");
   
   TH1F *hframe__119 = new TH1F("hframe__119","",1000,0,400);
   hframe__119->SetMinimum(1.829165);
   hframe__119->SetMaximum(21.10336);
   hframe__119->SetDirectory(0);
   hframe__119->SetStats(0);
   hframe__119->SetLineStyle(0);
   hframe__119->SetMarkerStyle(20);
   hframe__119->GetXaxis()->SetLabelFont(43);
   hframe__119->GetXaxis()->SetLabelOffset(0.007);
   hframe__119->GetXaxis()->SetLabelSize(0);
   hframe__119->GetXaxis()->SetTitleSize(0);
   hframe__119->GetXaxis()->SetTitleOffset(0.9);
   hframe__119->GetXaxis()->SetTitleFont(43);
   hframe__119->GetYaxis()->SetTitle("N_{events}");
   hframe__119->GetYaxis()->SetLabelFont(43);
   hframe__119->GetYaxis()->SetLabelOffset(0.007);
   hframe__119->GetYaxis()->SetLabelSize(27);
   hframe__119->GetYaxis()->SetTitleSize(33);
   hframe__119->GetYaxis()->SetTitleOffset(1.796875);
   hframe__119->GetYaxis()->SetTitleFont(43);
   hframe__119->GetZaxis()->SetLabelFont(43);
   hframe__119->GetZaxis()->SetLabelOffset(0.007);
   hframe__119->GetZaxis()->SetLabelSize(27);
   hframe__119->GetZaxis()->SetTitleSize(33);
   hframe__119->GetZaxis()->SetTitleFont(43);
   hframe__119->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->Modified();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->cd();
   Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus->SetSelected(Mt_DataDrivenVsMC_w=0.6_QCDTailKillerMediumPlus);
}
