{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus
//=========  (Wed Jul 30 13:57:10 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->Range(-81.01265,0.2196263,425.3165,1.446547);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__232 = new TH1F("hframe__232","",1000,0,400);
   hframe__232->SetMinimum(0.5754333);
   hframe__232->SetMaximum(1.446547);
   hframe__232->SetDirectory(0);
   hframe__232->SetStats(0);
   hframe__232->SetLineStyle(0);
   hframe__232->SetMarkerStyle(20);
   hframe__232->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__232->GetXaxis()->SetLabelFont(43);
   hframe__232->GetXaxis()->SetLabelOffset(0.007);
   hframe__232->GetXaxis()->SetLabelSize(27);
   hframe__232->GetXaxis()->SetTitleSize(33);
   hframe__232->GetXaxis()->SetTitleOffset(2.925);
   hframe__232->GetXaxis()->SetTitleFont(43);
   hframe__232->GetYaxis()->SetTitle("Ratio");
   hframe__232->GetYaxis()->SetNdivisions(505);
   hframe__232->GetYaxis()->SetLabelFont(43);
   hframe__232->GetYaxis()->SetLabelOffset(0.007);
   hframe__232->GetYaxis()->SetLabelSize(21);
   hframe__232->GetYaxis()->SetTitleSize(33);
   hframe__232->GetYaxis()->SetTitleOffset(1.796875);
   hframe__232->GetYaxis()->SetTitleFont(43);
   hframe__232->GetZaxis()->SetLabelFont(43);
   hframe__232->GetZaxis()->SetLabelOffset(0.007);
   hframe__232->GetZaxis()->SetLabelSize(27);
   hframe__232->GetZaxis()->SetTitleSize(33);
   hframe__232->GetZaxis()->SetTitleFont(43);
   hframe__232->Draw(" ");
   Double_t xAxis166[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233","#tau p_{T}<50",10, xAxis166);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(1,1.264948);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(2,0.8021701);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(3,0.920208);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(4,0.9057246);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(5,0.8653418);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(6,1.028104);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(7,0.6393724);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(8,0.7658139);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(9,1.315043);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinContent(10,0.7571614);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(1,0.3974783);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(2,0.2925231);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(3,0.1763727);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(4,0.163542);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(5,0.1577442);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(6,0.1923759);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(7,0.1509647);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(8,0.2314226);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(9,0.5768223);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetBinError(10,0.3740035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetEntries(94.07433);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__233->Draw("EP same");
   Double_t xAxis167[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234","#tau p_{T}<50",10, xAxis167);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(5,0.7852051);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(6,0.9266732);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(7,0.5754333);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(8,0.6842363);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(9,1.174884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinContent(10,0.6684515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(5,0.1431421);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(6,0.1733767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(7,0.1358588);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(8,0.2067999);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(9,0.5152653);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetBinError(10,0.3299514);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetEntries(94.75576);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__234->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph34 = new TH1F("Graph_Graph34","Graph",100,0,440);
   Graph_Graph34->SetMinimum(0.9);
   Graph_Graph34->SetMaximum(2.1);
   Graph_Graph34->SetDirectory(0);
   Graph_Graph34->SetStats(0);
   Graph_Graph34->SetLineStyle(0);
   Graph_Graph34->SetMarkerStyle(20);
   Graph_Graph34->GetXaxis()->SetLabelFont(43);
   Graph_Graph34->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph34->GetXaxis()->SetLabelSize(27);
   Graph_Graph34->GetXaxis()->SetTitleSize(33);
   Graph_Graph34->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph34->GetXaxis()->SetTitleFont(43);
   Graph_Graph34->GetYaxis()->SetLabelFont(43);
   Graph_Graph34->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph34->GetYaxis()->SetLabelSize(27);
   Graph_Graph34->GetYaxis()->SetTitleSize(33);
   Graph_Graph34->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph34->GetYaxis()->SetTitleFont(43);
   Graph_Graph34->GetZaxis()->SetLabelFont(43);
   Graph_Graph34->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph34->GetZaxis()->SetLabelSize(27);
   Graph_Graph34->GetZaxis()->SetTitleSize(33);
   Graph_Graph34->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph34);
   
   graph->Draw("l");
   
   TH1F *hframe__235 = new TH1F("hframe__235","",1000,0,400);
   hframe__235->SetMinimum(0.5754333);
   hframe__235->SetMaximum(1.446547);
   hframe__235->SetDirectory(0);
   hframe__235->SetStats(0);
   hframe__235->SetLineStyle(0);
   hframe__235->SetMarkerStyle(20);
   hframe__235->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__235->GetXaxis()->SetLabelFont(43);
   hframe__235->GetXaxis()->SetLabelOffset(0.007);
   hframe__235->GetXaxis()->SetLabelSize(27);
   hframe__235->GetXaxis()->SetTitleSize(33);
   hframe__235->GetXaxis()->SetTitleOffset(2.925);
   hframe__235->GetXaxis()->SetTitleFont(43);
   hframe__235->GetYaxis()->SetTitle("Ratio");
   hframe__235->GetYaxis()->SetNdivisions(505);
   hframe__235->GetYaxis()->SetLabelFont(43);
   hframe__235->GetYaxis()->SetLabelOffset(0.007);
   hframe__235->GetYaxis()->SetLabelSize(21);
   hframe__235->GetYaxis()->SetTitleSize(33);
   hframe__235->GetYaxis()->SetTitleOffset(1.796875);
   hframe__235->GetYaxis()->SetTitleFont(43);
   hframe__235->GetZaxis()->SetLabelFont(43);
   hframe__235->GetZaxis()->SetLabelOffset(0.007);
   hframe__235->GetZaxis()->SetLabelSize(27);
   hframe__235->GetZaxis()->SetTitleSize(33);
   hframe__235->GetZaxis()->SetTitleFont(43);
   hframe__235->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->Range(-81.01265,-0.6706663,425.3165,15.5153);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__236 = new TH1F("hframe__236","",1000,0,400);
   hframe__236->SetMinimum(1.433509);
   hframe__236->SetMaximum(14.706);
   hframe__236->SetDirectory(0);
   hframe__236->SetStats(0);
   hframe__236->SetLineStyle(0);
   hframe__236->SetMarkerStyle(20);
   hframe__236->GetXaxis()->SetLabelFont(43);
   hframe__236->GetXaxis()->SetLabelOffset(0.007);
   hframe__236->GetXaxis()->SetLabelSize(0);
   hframe__236->GetXaxis()->SetTitleSize(0);
   hframe__236->GetXaxis()->SetTitleOffset(0.9);
   hframe__236->GetXaxis()->SetTitleFont(43);
   hframe__236->GetYaxis()->SetTitle("N_{events}");
   hframe__236->GetYaxis()->SetLabelFont(43);
   hframe__236->GetYaxis()->SetLabelOffset(0.007);
   hframe__236->GetYaxis()->SetLabelSize(27);
   hframe__236->GetYaxis()->SetTitleSize(33);
   hframe__236->GetYaxis()->SetTitleOffset(1.796875);
   hframe__236->GetYaxis()->SetTitleFont(43);
   hframe__236->GetZaxis()->SetLabelFont(43);
   hframe__236->GetZaxis()->SetLabelOffset(0.007);
   hframe__236->GetZaxis()->SetLabelSize(27);
   hframe__236->GetZaxis()->SetTitleSize(33);
   hframe__236->GetZaxis()->SetTitleFont(43);
   hframe__236->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis168[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis168);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.313798);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.738488);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,7.952172);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,10.73606);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,11.56884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,9.463873);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,6.809309);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,4.739344);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,3.956087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,1.62375);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4681381);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5570437);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.8936521);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.9994455);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,0.9341938);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,0.8128163);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.6785925);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.5524369);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.5129287);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.3385198);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis169[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis169);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,10.49748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,8.530189);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.128358);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.23449);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.534443);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.433509);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8478657);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7322293);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6105065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4940598);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4574585);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.2976706);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis170[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis170);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,13.36909);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.205174);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,10.64999);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,6.188637);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.008334);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,2.144523);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,-0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.184911);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.530287);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.279653);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,1.725427);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,1.260593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.9603232);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(420.2798);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__237 = new TH1F("hframe__237","",1000,0,400);
   hframe__237->SetMinimum(1.433509);
   hframe__237->SetMaximum(14.706);
   hframe__237->SetDirectory(0);
   hframe__237->SetStats(0);
   hframe__237->SetLineStyle(0);
   hframe__237->SetMarkerStyle(20);
   hframe__237->GetXaxis()->SetLabelFont(43);
   hframe__237->GetXaxis()->SetLabelOffset(0.007);
   hframe__237->GetXaxis()->SetLabelSize(0);
   hframe__237->GetXaxis()->SetTitleSize(0);
   hframe__237->GetXaxis()->SetTitleOffset(0.9);
   hframe__237->GetXaxis()->SetTitleFont(43);
   hframe__237->GetYaxis()->SetTitle("N_{events}");
   hframe__237->GetYaxis()->SetLabelFont(43);
   hframe__237->GetYaxis()->SetLabelOffset(0.007);
   hframe__237->GetYaxis()->SetLabelSize(27);
   hframe__237->GetYaxis()->SetTitleSize(33);
   hframe__237->GetYaxis()->SetTitleOffset(1.796875);
   hframe__237->GetYaxis()->SetTitleFont(43);
   hframe__237->GetZaxis()->SetLabelFont(43);
   hframe__237->GetZaxis()->SetLabelOffset(0.007);
   hframe__237->GetZaxis()->SetLabelSize(27);
   hframe__237->GetZaxis()->SetTitleSize(33);
   hframe__237->GetZaxis()->SetTitleFont(43);
   hframe__237->Draw("sameaxis");
   
   TH1F *hframe__238 = new TH1F("hframe__238","",1000,0,400);
   hframe__238->SetMinimum(1.433509);
   hframe__238->SetMaximum(14.706);
   hframe__238->SetDirectory(0);
   hframe__238->SetStats(0);
   hframe__238->SetLineStyle(0);
   hframe__238->SetMarkerStyle(20);
   hframe__238->GetXaxis()->SetLabelFont(43);
   hframe__238->GetXaxis()->SetLabelOffset(0.007);
   hframe__238->GetXaxis()->SetLabelSize(0);
   hframe__238->GetXaxis()->SetTitleSize(0);
   hframe__238->GetXaxis()->SetTitleOffset(0.9);
   hframe__238->GetXaxis()->SetTitleFont(43);
   hframe__238->GetYaxis()->SetTitle("N_{events}");
   hframe__238->GetYaxis()->SetLabelFont(43);
   hframe__238->GetYaxis()->SetLabelOffset(0.007);
   hframe__238->GetYaxis()->SetLabelSize(27);
   hframe__238->GetYaxis()->SetTitleSize(33);
   hframe__238->GetYaxis()->SetTitleOffset(1.796875);
   hframe__238->GetYaxis()->SetTitleFont(43);
   hframe__238->GetZaxis()->SetLabelFont(43);
   hframe__238->GetZaxis()->SetLabelOffset(0.007);
   hframe__238->GetZaxis()->SetLabelSize(27);
   hframe__238->GetZaxis()->SetTitleSize(33);
   hframe__238->GetZaxis()->SetTitleFont(43);
   hframe__238->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.85_QCDTailKillerTightPlus);
}
