{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus
//=========  (Fri Aug  1 10:26:43 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->Range(-81.01265,0.7855879,425.3165,1.62447);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__50 = new TH1F("hframe__50","",1000,0,400);
   hframe__50->SetMinimum(1.028864);
   hframe__50->SetMaximum(1.62447);
   hframe__50->SetDirectory(0);
   hframe__50->SetStats(0);
   hframe__50->SetLineStyle(0);
   hframe__50->SetMarkerStyle(20);
   hframe__50->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__50->GetXaxis()->SetLabelFont(43);
   hframe__50->GetXaxis()->SetLabelOffset(0.007);
   hframe__50->GetXaxis()->SetLabelSize(27);
   hframe__50->GetXaxis()->SetTitleSize(33);
   hframe__50->GetXaxis()->SetTitleOffset(2.925);
   hframe__50->GetXaxis()->SetTitleFont(43);
   hframe__50->GetYaxis()->SetTitle("Ratio");
   hframe__50->GetYaxis()->SetNdivisions(505);
   hframe__50->GetYaxis()->SetLabelFont(43);
   hframe__50->GetYaxis()->SetLabelOffset(0.007);
   hframe__50->GetYaxis()->SetLabelSize(21);
   hframe__50->GetYaxis()->SetTitleSize(33);
   hframe__50->GetYaxis()->SetTitleOffset(1.796875);
   hframe__50->GetYaxis()->SetTitleFont(43);
   hframe__50->GetZaxis()->SetLabelFont(43);
   hframe__50->GetZaxis()->SetLabelOffset(0.007);
   hframe__50->GetZaxis()->SetLabelSize(27);
   hframe__50->GetZaxis()->SetTitleSize(33);
   hframe__50->GetZaxis()->SetTitleFont(43);
   hframe__50->Draw(" ");
   Double_t xAxis36[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51","#tau p_{T}<50",10, xAxis36);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(1,1.252146);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(2,1.236931);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(3,1.219114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(4,1.236561);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(5,1.22179);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(6,1.221242);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(7,1.292205);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(8,1.301723);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(9,1.290248);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinContent(10,1.476791);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(1,0.2603114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(2,0.2408852);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(3,0.1357313);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(4,0.1210176);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(5,0.1221618);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(6,0.1371643);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(7,0.1794025);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(8,0.2164241);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(9,0.2341984);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetBinError(10,0.4083865);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetEntries(329.512);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__51->Draw("EP same");
   Double_t xAxis37[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52","#tau p_{T}<50",10, xAxis37);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(1,1.039155);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(2,1.037946);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(3,1.032302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(4,1.036355);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(5,1.033776);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(6,1.028864);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(7,1.068263);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(8,1.046857);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(9,1.070101);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinContent(10,1.128127);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(1,0.2157572);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(2,0.2022065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(3,0.114812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(4,0.1013175);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(5,0.103263);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(6,0.1154273);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(7,0.1480535);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(8,0.1736083);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(9,0.1938378);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetBinError(10,0.3102965);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetEntries(345.1088);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__52->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph8 = new TH1F("Graph_Graph8","Graph",100,0,440);
   Graph_Graph8->SetMinimum(0.9);
   Graph_Graph8->SetMaximum(2.1);
   Graph_Graph8->SetDirectory(0);
   Graph_Graph8->SetStats(0);
   Graph_Graph8->SetLineStyle(0);
   Graph_Graph8->SetMarkerStyle(20);
   Graph_Graph8->GetXaxis()->SetLabelFont(43);
   Graph_Graph8->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph8->GetXaxis()->SetLabelSize(27);
   Graph_Graph8->GetXaxis()->SetTitleSize(33);
   Graph_Graph8->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph8->GetXaxis()->SetTitleFont(43);
   Graph_Graph8->GetYaxis()->SetLabelFont(43);
   Graph_Graph8->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph8->GetYaxis()->SetLabelSize(27);
   Graph_Graph8->GetYaxis()->SetTitleSize(33);
   Graph_Graph8->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph8->GetYaxis()->SetTitleFont(43);
   Graph_Graph8->GetZaxis()->SetLabelFont(43);
   Graph_Graph8->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph8->GetZaxis()->SetLabelSize(27);
   Graph_Graph8->GetZaxis()->SetTitleSize(33);
   Graph_Graph8->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph8);
   
   graph->Draw("l");
   
   TH1F *hframe__53 = new TH1F("hframe__53","",1000,0,400);
   hframe__53->SetMinimum(1.028864);
   hframe__53->SetMaximum(1.62447);
   hframe__53->SetDirectory(0);
   hframe__53->SetStats(0);
   hframe__53->SetLineStyle(0);
   hframe__53->SetMarkerStyle(20);
   hframe__53->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__53->GetXaxis()->SetLabelFont(43);
   hframe__53->GetXaxis()->SetLabelOffset(0.007);
   hframe__53->GetXaxis()->SetLabelSize(27);
   hframe__53->GetXaxis()->SetTitleSize(33);
   hframe__53->GetXaxis()->SetTitleOffset(2.925);
   hframe__53->GetXaxis()->SetTitleFont(43);
   hframe__53->GetYaxis()->SetTitle("Ratio");
   hframe__53->GetYaxis()->SetNdivisions(505);
   hframe__53->GetYaxis()->SetLabelFont(43);
   hframe__53->GetYaxis()->SetLabelOffset(0.007);
   hframe__53->GetYaxis()->SetLabelSize(21);
   hframe__53->GetYaxis()->SetTitleSize(33);
   hframe__53->GetYaxis()->SetTitleOffset(1.796875);
   hframe__53->GetYaxis()->SetTitleFont(43);
   hframe__53->GetZaxis()->SetLabelFont(43);
   hframe__53->GetZaxis()->SetLabelOffset(0.007);
   hframe__53->GetZaxis()->SetLabelSize(27);
   hframe__53->GetZaxis()->SetTitleSize(33);
   hframe__53->GetZaxis()->SetTitleFont(43);
   hframe__53->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->Range(-81.01265,-0.8882573,425.3165,17.46699);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__54 = new TH1F("hframe__54","",1000,0,400);
   hframe__54->SetMinimum(1.497924);
   hframe__54->SetMaximum(16.54922);
   hframe__54->SetDirectory(0);
   hframe__54->SetStats(0);
   hframe__54->SetLineStyle(0);
   hframe__54->SetMarkerStyle(20);
   hframe__54->GetXaxis()->SetLabelFont(43);
   hframe__54->GetXaxis()->SetLabelOffset(0.007);
   hframe__54->GetXaxis()->SetLabelSize(0);
   hframe__54->GetXaxis()->SetTitleSize(0);
   hframe__54->GetXaxis()->SetTitleOffset(0.9);
   hframe__54->GetXaxis()->SetTitleFont(43);
   hframe__54->GetYaxis()->SetTitle("N_{events}");
   hframe__54->GetYaxis()->SetLabelFont(43);
   hframe__54->GetYaxis()->SetLabelOffset(0.007);
   hframe__54->GetYaxis()->SetLabelSize(27);
   hframe__54->GetYaxis()->SetTitleSize(33);
   hframe__54->GetYaxis()->SetTitleOffset(1.796875);
   hframe__54->GetYaxis()->SetTitleFont(43);
   hframe__54->GetZaxis()->SetLabelFont(43);
   hframe__54->GetZaxis()->SetLabelOffset(0.007);
   hframe__54->GetZaxis()->SetLabelSize(27);
   hframe__54->GetZaxis()->SetTitleSize(33);
   hframe__54->GetZaxis()->SetTitleFont(43);
   hframe__54->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis38[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis38);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.338723);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,4.20866);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,11.57141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,15.04475);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,14.22574);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,11.07946);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,7.960324);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,5.277272);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,4.445722);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,2.212121);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4912435);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.578307);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.9116728);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.040924);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.001566);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,0.8809949);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.750265);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.6157013);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.5485071);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.4044521);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1123.751);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis39[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis39);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.770804);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,3.531615);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,9.798261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,12.60893);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,12.03662);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,9.334145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.580781);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.24403);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.687176);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.689849);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4066458);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.485624);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.7703552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.870556);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8457872);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7405494);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6178975);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4925964);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4528847);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.3051619);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1123.751);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis40[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis40);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,2.6664);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.402503);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,9.491659);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,12.1666);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,11.64336);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.072286);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,6.160265);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,4.054066);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.445634);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,1.497924);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.3916108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,0.4695473);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,0.7466735);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,0.8421149);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,0.8266196);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,0.7196294);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,0.6279795);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,0.4802024);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,0.4587375);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.3107748);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(1079.466);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__55 = new TH1F("hframe__55","",1000,0,400);
   hframe__55->SetMinimum(1.497924);
   hframe__55->SetMaximum(16.54922);
   hframe__55->SetDirectory(0);
   hframe__55->SetStats(0);
   hframe__55->SetLineStyle(0);
   hframe__55->SetMarkerStyle(20);
   hframe__55->GetXaxis()->SetLabelFont(43);
   hframe__55->GetXaxis()->SetLabelOffset(0.007);
   hframe__55->GetXaxis()->SetLabelSize(0);
   hframe__55->GetXaxis()->SetTitleSize(0);
   hframe__55->GetXaxis()->SetTitleOffset(0.9);
   hframe__55->GetXaxis()->SetTitleFont(43);
   hframe__55->GetYaxis()->SetTitle("N_{events}");
   hframe__55->GetYaxis()->SetLabelFont(43);
   hframe__55->GetYaxis()->SetLabelOffset(0.007);
   hframe__55->GetYaxis()->SetLabelSize(27);
   hframe__55->GetYaxis()->SetTitleSize(33);
   hframe__55->GetYaxis()->SetTitleOffset(1.796875);
   hframe__55->GetYaxis()->SetTitleFont(43);
   hframe__55->GetZaxis()->SetLabelFont(43);
   hframe__55->GetZaxis()->SetLabelOffset(0.007);
   hframe__55->GetZaxis()->SetLabelSize(27);
   hframe__55->GetZaxis()->SetTitleSize(33);
   hframe__55->GetZaxis()->SetTitleFont(43);
   hframe__55->Draw("sameaxis");
   
   TH1F *hframe__56 = new TH1F("hframe__56","",1000,0,400);
   hframe__56->SetMinimum(1.497924);
   hframe__56->SetMaximum(16.54922);
   hframe__56->SetDirectory(0);
   hframe__56->SetStats(0);
   hframe__56->SetLineStyle(0);
   hframe__56->SetMarkerStyle(20);
   hframe__56->GetXaxis()->SetLabelFont(43);
   hframe__56->GetXaxis()->SetLabelOffset(0.007);
   hframe__56->GetXaxis()->SetLabelSize(0);
   hframe__56->GetXaxis()->SetTitleSize(0);
   hframe__56->GetXaxis()->SetTitleOffset(0.9);
   hframe__56->GetXaxis()->SetTitleFont(43);
   hframe__56->GetYaxis()->SetTitle("N_{events}");
   hframe__56->GetYaxis()->SetLabelFont(43);
   hframe__56->GetYaxis()->SetLabelOffset(0.007);
   hframe__56->GetYaxis()->SetLabelSize(27);
   hframe__56->GetYaxis()->SetTitleSize(33);
   hframe__56->GetYaxis()->SetTitleOffset(1.796875);
   hframe__56->GetYaxis()->SetTitleFont(43);
   hframe__56->GetZaxis()->SetLabelFont(43);
   hframe__56->GetZaxis()->SetLabelOffset(0.007);
   hframe__56->GetZaxis()->SetLabelSize(27);
   hframe__56->GetZaxis()->SetTitleSize(33);
   hframe__56->GetZaxis()->SetTitleFont(43);
   hframe__56->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.67_QCDTailKillerTightPlus);
}
