{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus
//=========  (Wed Jul 30 13:56:50 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->Range(-81.01265,0.03070836,425.3165,1.90907);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__169 = new TH1F("hframe__169","",1000,0,400);
   hframe__169->SetMinimum(0.5754333);
   hframe__169->SetMaximum(1.90907);
   hframe__169->SetDirectory(0);
   hframe__169->SetStats(0);
   hframe__169->SetLineStyle(0);
   hframe__169->SetMarkerStyle(20);
   hframe__169->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__169->GetXaxis()->SetLabelFont(43);
   hframe__169->GetXaxis()->SetLabelOffset(0.007);
   hframe__169->GetXaxis()->SetLabelSize(27);
   hframe__169->GetXaxis()->SetTitleSize(33);
   hframe__169->GetXaxis()->SetTitleOffset(2.925);
   hframe__169->GetXaxis()->SetTitleFont(43);
   hframe__169->GetYaxis()->SetTitle("Ratio");
   hframe__169->GetYaxis()->SetNdivisions(505);
   hframe__169->GetYaxis()->SetLabelFont(43);
   hframe__169->GetYaxis()->SetLabelOffset(0.007);
   hframe__169->GetYaxis()->SetLabelSize(21);
   hframe__169->GetYaxis()->SetTitleSize(33);
   hframe__169->GetYaxis()->SetTitleOffset(1.796875);
   hframe__169->GetYaxis()->SetTitleFont(43);
   hframe__169->GetZaxis()->SetLabelFont(43);
   hframe__169->GetZaxis()->SetLabelOffset(0.007);
   hframe__169->GetZaxis()->SetLabelSize(27);
   hframe__169->GetZaxis()->SetTitleSize(33);
   hframe__169->GetZaxis()->SetTitleFont(43);
   hframe__169->Draw(" ");
   Double_t xAxis121[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170","#tau p_{T}<50",10, xAxis121);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(1,1.653172);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(2,1.002195);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(3,1.194061);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(4,1.174003);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(5,1.105752);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(6,1.332395);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(7,0.8311895);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(8,1.010546);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(9,1.735518);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinContent(10,1.023291);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(1,0.5195125);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(2,0.3676327);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(3,0.2282243);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(4,0.2119008);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(5,0.2017649);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(6,0.2496576);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(7,0.196507);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(8,0.3056037);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(9,0.7619775);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetBinError(10,0.5068799);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetEntries(92.40002);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__170->Draw("EP same");
   Double_t xAxis122[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171","#tau p_{T}<50",10, xAxis122);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(5,0.7852051);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(6,0.9266732);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(7,0.5754333);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(8,0.6842363);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(9,1.174884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinContent(10,0.6684515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(5,0.1431421);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(6,0.1733767);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(7,0.1358588);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(8,0.2067999);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(9,0.5152653);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetBinError(10,0.3299514);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetEntries(94.75576);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__171->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph25 = new TH1F("Graph_Graph25","Graph",100,0,440);
   Graph_Graph25->SetMinimum(0.9);
   Graph_Graph25->SetMaximum(2.1);
   Graph_Graph25->SetDirectory(0);
   Graph_Graph25->SetStats(0);
   Graph_Graph25->SetLineStyle(0);
   Graph_Graph25->SetMarkerStyle(20);
   Graph_Graph25->GetXaxis()->SetLabelFont(43);
   Graph_Graph25->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph25->GetXaxis()->SetLabelSize(27);
   Graph_Graph25->GetXaxis()->SetTitleSize(33);
   Graph_Graph25->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph25->GetXaxis()->SetTitleFont(43);
   Graph_Graph25->GetYaxis()->SetLabelFont(43);
   Graph_Graph25->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph25->GetYaxis()->SetLabelSize(27);
   Graph_Graph25->GetYaxis()->SetTitleSize(33);
   Graph_Graph25->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph25->GetYaxis()->SetTitleFont(43);
   Graph_Graph25->GetZaxis()->SetLabelFont(43);
   Graph_Graph25->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph25->GetZaxis()->SetLabelSize(27);
   Graph_Graph25->GetZaxis()->SetTitleSize(33);
   Graph_Graph25->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph25);
   
   graph->Draw("l");
   
   TH1F *hframe__172 = new TH1F("hframe__172","",1000,0,400);
   hframe__172->SetMinimum(0.5754333);
   hframe__172->SetMaximum(1.90907);
   hframe__172->SetDirectory(0);
   hframe__172->SetStats(0);
   hframe__172->SetLineStyle(0);
   hframe__172->SetMarkerStyle(20);
   hframe__172->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__172->GetXaxis()->SetLabelFont(43);
   hframe__172->GetXaxis()->SetLabelOffset(0.007);
   hframe__172->GetXaxis()->SetLabelSize(27);
   hframe__172->GetXaxis()->SetTitleSize(33);
   hframe__172->GetXaxis()->SetTitleOffset(2.925);
   hframe__172->GetXaxis()->SetTitleFont(43);
   hframe__172->GetYaxis()->SetTitle("Ratio");
   hframe__172->GetYaxis()->SetNdivisions(505);
   hframe__172->GetYaxis()->SetLabelFont(43);
   hframe__172->GetYaxis()->SetLabelOffset(0.007);
   hframe__172->GetYaxis()->SetLabelSize(21);
   hframe__172->GetYaxis()->SetTitleSize(33);
   hframe__172->GetYaxis()->SetTitleOffset(1.796875);
   hframe__172->GetYaxis()->SetTitleFont(43);
   hframe__172->GetZaxis()->SetLabelFont(43);
   hframe__172->GetZaxis()->SetLabelOffset(0.007);
   hframe__172->GetZaxis()->SetLabelSize(27);
   hframe__172->GetZaxis()->SetTitleSize(33);
   hframe__172->GetZaxis()->SetTitleFont(43);
   hframe__172->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->Range(-81.01265,-0.9172208,425.3165,17.16532);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__173 = new TH1F("hframe__173","",1000,0,400);
   hframe__173->SetMinimum(1.433509);
   hframe__173->SetMaximum(16.26119);
   hframe__173->SetDirectory(0);
   hframe__173->SetStats(0);
   hframe__173->SetLineStyle(0);
   hframe__173->SetMarkerStyle(20);
   hframe__173->GetXaxis()->SetLabelFont(43);
   hframe__173->GetXaxis()->SetLabelOffset(0.007);
   hframe__173->GetXaxis()->SetLabelSize(0);
   hframe__173->GetXaxis()->SetTitleSize(0);
   hframe__173->GetXaxis()->SetTitleOffset(0.9);
   hframe__173->GetXaxis()->SetTitleFont(43);
   hframe__173->GetYaxis()->SetTitle("N_{events}");
   hframe__173->GetYaxis()->SetLabelFont(43);
   hframe__173->GetYaxis()->SetLabelOffset(0.007);
   hframe__173->GetYaxis()->SetLabelSize(27);
   hframe__173->GetYaxis()->SetTitleSize(33);
   hframe__173->GetYaxis()->SetTitleOffset(1.796875);
   hframe__173->GetYaxis()->SetTitleFont(43);
   hframe__173->GetZaxis()->SetLabelFont(43);
   hframe__173->GetZaxis()->SetLabelOffset(0.007);
   hframe__173->GetZaxis()->SetLabelSize(27);
   hframe__173->GetZaxis()->SetTitleSize(33);
   hframe__173->GetZaxis()->SetTitleFont(43);
   hframe__173->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis123[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis123);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.023925);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.421344);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,10.31873);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,13.91611);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,14.7829);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,12.26493);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,8.85216);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,6.253904);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,5.221018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,2.194471);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.6119402);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.7091257);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.150193);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.293579);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.199638);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.060261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.8885071);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.7325828);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.6842291);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.4646748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis124[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis124);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,10.49748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,8.530189);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.128358);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.23449);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.534443);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.433509);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8478657);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7322293);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6105065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4940598);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4574585);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.2976706);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(775.3466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis125[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis125);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,13.36909);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.205174);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,10.64999);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,6.188637);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.008334);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,2.144523);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,-0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.184911);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.530287);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.279653);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,1.725427);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,1.260593);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.9603232);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.01078588);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(420.2798);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__174 = new TH1F("hframe__174","",1000,0,400);
   hframe__174->SetMinimum(1.433509);
   hframe__174->SetMaximum(16.26119);
   hframe__174->SetDirectory(0);
   hframe__174->SetStats(0);
   hframe__174->SetLineStyle(0);
   hframe__174->SetMarkerStyle(20);
   hframe__174->GetXaxis()->SetLabelFont(43);
   hframe__174->GetXaxis()->SetLabelOffset(0.007);
   hframe__174->GetXaxis()->SetLabelSize(0);
   hframe__174->GetXaxis()->SetTitleSize(0);
   hframe__174->GetXaxis()->SetTitleOffset(0.9);
   hframe__174->GetXaxis()->SetTitleFont(43);
   hframe__174->GetYaxis()->SetTitle("N_{events}");
   hframe__174->GetYaxis()->SetLabelFont(43);
   hframe__174->GetYaxis()->SetLabelOffset(0.007);
   hframe__174->GetYaxis()->SetLabelSize(27);
   hframe__174->GetYaxis()->SetTitleSize(33);
   hframe__174->GetYaxis()->SetTitleOffset(1.796875);
   hframe__174->GetYaxis()->SetTitleFont(43);
   hframe__174->GetZaxis()->SetLabelFont(43);
   hframe__174->GetZaxis()->SetLabelOffset(0.007);
   hframe__174->GetZaxis()->SetLabelSize(27);
   hframe__174->GetZaxis()->SetTitleSize(33);
   hframe__174->GetZaxis()->SetTitleFont(43);
   hframe__174->Draw("sameaxis");
   
   TH1F *hframe__175 = new TH1F("hframe__175","",1000,0,400);
   hframe__175->SetMinimum(1.433509);
   hframe__175->SetMaximum(16.26119);
   hframe__175->SetDirectory(0);
   hframe__175->SetStats(0);
   hframe__175->SetLineStyle(0);
   hframe__175->SetMarkerStyle(20);
   hframe__175->GetXaxis()->SetLabelFont(43);
   hframe__175->GetXaxis()->SetLabelOffset(0.007);
   hframe__175->GetXaxis()->SetLabelSize(0);
   hframe__175->GetXaxis()->SetTitleSize(0);
   hframe__175->GetXaxis()->SetTitleOffset(0.9);
   hframe__175->GetXaxis()->SetTitleFont(43);
   hframe__175->GetYaxis()->SetTitle("N_{events}");
   hframe__175->GetYaxis()->SetLabelFont(43);
   hframe__175->GetYaxis()->SetLabelOffset(0.007);
   hframe__175->GetYaxis()->SetLabelSize(27);
   hframe__175->GetYaxis()->SetTitleSize(33);
   hframe__175->GetYaxis()->SetTitleOffset(1.796875);
   hframe__175->GetYaxis()->SetTitleFont(43);
   hframe__175->GetZaxis()->SetLabelFont(43);
   hframe__175->GetZaxis()->SetLabelOffset(0.007);
   hframe__175->GetZaxis()->SetLabelSize(27);
   hframe__175->GetZaxis()->SetTitleSize(33);
   hframe__175->GetZaxis()->SetTitleFont(43);
   hframe__175->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.4_QCDTailKillerTightPlus);
}
