{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus
//=========  (Wed Jul 30 13:56:22 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->Range(-81.01265,0.2684745,425.3165,1.77104);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__8 = new TH1F("hframe__8","",1000,0,400);
   hframe__8->SetMinimum(0.7042185);
   hframe__8->SetMaximum(1.77104);
   hframe__8->SetDirectory(0);
   hframe__8->SetStats(0);
   hframe__8->SetLineStyle(0);
   hframe__8->SetMarkerStyle(20);
   hframe__8->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__8->GetXaxis()->SetLabelFont(43);
   hframe__8->GetXaxis()->SetLabelOffset(0.007);
   hframe__8->GetXaxis()->SetLabelSize(27);
   hframe__8->GetXaxis()->SetTitleSize(33);
   hframe__8->GetXaxis()->SetTitleOffset(2.925);
   hframe__8->GetXaxis()->SetTitleFont(43);
   hframe__8->GetYaxis()->SetTitle("Ratio");
   hframe__8->GetYaxis()->SetNdivisions(505);
   hframe__8->GetYaxis()->SetLabelFont(43);
   hframe__8->GetYaxis()->SetLabelOffset(0.007);
   hframe__8->GetYaxis()->SetLabelSize(21);
   hframe__8->GetYaxis()->SetTitleSize(33);
   hframe__8->GetYaxis()->SetTitleOffset(1.796875);
   hframe__8->GetYaxis()->SetTitleFont(43);
   hframe__8->GetZaxis()->SetLabelFont(43);
   hframe__8->GetZaxis()->SetLabelOffset(0.007);
   hframe__8->GetZaxis()->SetLabelSize(27);
   hframe__8->GetZaxis()->SetTitleSize(33);
   hframe__8->GetZaxis()->SetTitleFont(43);
   hframe__8->Draw(" ");
   Double_t xAxis6[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9","#tau p_{T}<50",10, xAxis6);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(1,1.610036);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(2,0.9799702);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(3,1.163632);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(4,1.144194);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(5,0.9713729);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(6,1.357521);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(7,1.117994);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(8,1.048097);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(9,1.264191);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(10,1.128611);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinContent(11,1.094684);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(1,0.5058937);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(2,0.3592523);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(3,0.2224424);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(4,0.2065112);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(5,0.1550348);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(6,0.137302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(7,0.1499915);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(8,0.181707);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(9,0.23774);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(10,0.3129621);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetBinError(11,0.936904);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetEntries(190.2787);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__9->Draw("EP same");
   Double_t xAxis7[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10","#tau p_{T}<50",10, xAxis7);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(5,0.7207969);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(6,0.9898824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(7,0.7621042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(8,0.7042185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(9,0.8474045);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(10,0.7913883);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinContent(11,1.088221);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(5,0.1149444);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(6,0.100059);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(7,0.1022867);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(8,0.1220903);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(9,0.1592168);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(10,0.2184464);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetBinError(11,0.931372);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetEntries(188.642);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__10->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,0,440);
   Graph_Graph2->SetMinimum(0.9);
   Graph_Graph2->SetMaximum(2.1);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);
   Graph_Graph2->SetLineStyle(0);
   Graph_Graph2->SetMarkerStyle(20);
   Graph_Graph2->GetXaxis()->SetLabelFont(43);
   Graph_Graph2->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetXaxis()->SetLabelSize(27);
   Graph_Graph2->GetXaxis()->SetTitleSize(33);
   Graph_Graph2->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph2->GetXaxis()->SetTitleFont(43);
   Graph_Graph2->GetYaxis()->SetLabelFont(43);
   Graph_Graph2->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetYaxis()->SetLabelSize(27);
   Graph_Graph2->GetYaxis()->SetTitleSize(33);
   Graph_Graph2->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph2->GetYaxis()->SetTitleFont(43);
   Graph_Graph2->GetZaxis()->SetLabelFont(43);
   Graph_Graph2->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetZaxis()->SetLabelSize(27);
   Graph_Graph2->GetZaxis()->SetTitleSize(33);
   Graph_Graph2->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph2);
   
   graph->Draw("l");
   
   TH1F *hframe__11 = new TH1F("hframe__11","",1000,0,400);
   hframe__11->SetMinimum(0.7042185);
   hframe__11->SetMaximum(1.77104);
   hframe__11->SetDirectory(0);
   hframe__11->SetStats(0);
   hframe__11->SetLineStyle(0);
   hframe__11->SetMarkerStyle(20);
   hframe__11->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__11->GetXaxis()->SetLabelFont(43);
   hframe__11->GetXaxis()->SetLabelOffset(0.007);
   hframe__11->GetXaxis()->SetLabelSize(27);
   hframe__11->GetXaxis()->SetTitleSize(33);
   hframe__11->GetXaxis()->SetTitleOffset(2.925);
   hframe__11->GetXaxis()->SetTitleFont(43);
   hframe__11->GetYaxis()->SetTitle("Ratio");
   hframe__11->GetYaxis()->SetNdivisions(505);
   hframe__11->GetYaxis()->SetLabelFont(43);
   hframe__11->GetYaxis()->SetLabelOffset(0.007);
   hframe__11->GetYaxis()->SetLabelSize(21);
   hframe__11->GetYaxis()->SetTitleSize(33);
   hframe__11->GetYaxis()->SetTitleOffset(1.796875);
   hframe__11->GetYaxis()->SetTitleFont(43);
   hframe__11->GetZaxis()->SetLabelFont(43);
   hframe__11->GetZaxis()->SetLabelOffset(0.007);
   hframe__11->GetZaxis()->SetLabelSize(27);
   hframe__11->GetZaxis()->SetTitleSize(33);
   hframe__11->GetZaxis()->SetTitleFont(43);
   hframe__11->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->Range(-81.01265,-3.251551,425.3165,35.83088);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__12 = new TH1F("hframe__12","",1000,0,400);
   hframe__12->SetMinimum(1.829165);
   hframe__12->SetMaximum(33.87676);
   hframe__12->SetDirectory(0);
   hframe__12->SetStats(0);
   hframe__12->SetLineStyle(0);
   hframe__12->SetMarkerStyle(20);
   hframe__12->GetXaxis()->SetLabelFont(43);
   hframe__12->GetXaxis()->SetLabelOffset(0.007);
   hframe__12->GetXaxis()->SetLabelSize(0);
   hframe__12->GetXaxis()->SetTitleSize(0);
   hframe__12->GetXaxis()->SetTitleOffset(0.9);
   hframe__12->GetXaxis()->SetTitleFont(43);
   hframe__12->GetYaxis()->SetTitle("N_{events}");
   hframe__12->GetYaxis()->SetLabelFont(43);
   hframe__12->GetYaxis()->SetLabelOffset(0.007);
   hframe__12->GetYaxis()->SetLabelSize(27);
   hframe__12->GetYaxis()->SetTitleSize(33);
   hframe__12->GetYaxis()->SetTitleOffset(1.796875);
   hframe__12->GetYaxis()->SetTitleFont(43);
   hframe__12->GetZaxis()->SetLabelFont(43);
   hframe__12->GetZaxis()->SetLabelOffset(0.007);
   hframe__12->GetZaxis()->SetLabelSize(27);
   hframe__12->GetZaxis()->SetTitleSize(33);
   hframe__12->GetZaxis()->SetTitleFont(43);
   hframe__12->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis8[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis8);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.945022);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,3.345471);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,10.05578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,13.56277);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,20.0211);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,30.79705);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,25.479);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,17.28542);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,16.87889);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,7.104928);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1397523);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.5957932);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.6920235);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,1.121385);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.26052);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.344345);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.605884);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.470448);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,1.212182);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,1.202733);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.7726127);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.08068604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis9[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis9);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,14.85644);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,22.45671);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,17.3683);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,11.6141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.31415);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,4.982014);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.1389271);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9927686);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.168366);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.004578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.8145114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.8011357);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.525429);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.08020962);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis10[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis10);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,20.61114);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.68624);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,22.78992);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,16.49218);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,13.35154);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,6.295283);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.1276645);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.984329);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.96608);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.760173);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.614869);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.323627);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.605844);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.08065877);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(901.3783);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__13 = new TH1F("hframe__13","",1000,0,400);
   hframe__13->SetMinimum(1.829165);
   hframe__13->SetMaximum(33.87676);
   hframe__13->SetDirectory(0);
   hframe__13->SetStats(0);
   hframe__13->SetLineStyle(0);
   hframe__13->SetMarkerStyle(20);
   hframe__13->GetXaxis()->SetLabelFont(43);
   hframe__13->GetXaxis()->SetLabelOffset(0.007);
   hframe__13->GetXaxis()->SetLabelSize(0);
   hframe__13->GetXaxis()->SetTitleSize(0);
   hframe__13->GetXaxis()->SetTitleOffset(0.9);
   hframe__13->GetXaxis()->SetTitleFont(43);
   hframe__13->GetYaxis()->SetTitle("N_{events}");
   hframe__13->GetYaxis()->SetLabelFont(43);
   hframe__13->GetYaxis()->SetLabelOffset(0.007);
   hframe__13->GetYaxis()->SetLabelSize(27);
   hframe__13->GetYaxis()->SetTitleSize(33);
   hframe__13->GetYaxis()->SetTitleOffset(1.796875);
   hframe__13->GetYaxis()->SetTitleFont(43);
   hframe__13->GetZaxis()->SetLabelFont(43);
   hframe__13->GetZaxis()->SetLabelOffset(0.007);
   hframe__13->GetZaxis()->SetLabelSize(27);
   hframe__13->GetZaxis()->SetTitleSize(33);
   hframe__13->GetZaxis()->SetTitleFont(43);
   hframe__13->Draw("sameaxis");
   
   TH1F *hframe__14 = new TH1F("hframe__14","",1000,0,400);
   hframe__14->SetMinimum(1.829165);
   hframe__14->SetMaximum(33.87676);
   hframe__14->SetDirectory(0);
   hframe__14->SetStats(0);
   hframe__14->SetLineStyle(0);
   hframe__14->SetMarkerStyle(20);
   hframe__14->GetXaxis()->SetLabelFont(43);
   hframe__14->GetXaxis()->SetLabelOffset(0.007);
   hframe__14->GetXaxis()->SetLabelSize(0);
   hframe__14->GetXaxis()->SetTitleSize(0);
   hframe__14->GetXaxis()->SetTitleOffset(0.9);
   hframe__14->GetXaxis()->SetTitleFont(43);
   hframe__14->GetYaxis()->SetTitle("N_{events}");
   hframe__14->GetYaxis()->SetLabelFont(43);
   hframe__14->GetYaxis()->SetLabelOffset(0.007);
   hframe__14->GetYaxis()->SetLabelSize(27);
   hframe__14->GetYaxis()->SetTitleSize(33);
   hframe__14->GetYaxis()->SetTitleOffset(1.796875);
   hframe__14->GetYaxis()->SetTitleFont(43);
   hframe__14->GetZaxis()->SetLabelFont(43);
   hframe__14->GetZaxis()->SetLabelOffset(0.007);
   hframe__14->GetZaxis()->SetLabelSize(27);
   hframe__14->GetZaxis()->SetTitleSize(33);
   hframe__14->GetZaxis()->SetTitleFont(43);
   hframe__14->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.45_QCDTailKillerLoosePlus);
}
