{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus
//=========  (Wed Jul 23 10:30:10 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->Range(-101.2658,0.462283,531.6456,1.296543);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__43 = new TH1F("hframe__43","",1000,0,500);
   hframe__43->SetMinimum(0.7042185);
   hframe__43->SetMaximum(1.296543);
   hframe__43->SetDirectory(0);
   hframe__43->SetStats(0);
   hframe__43->SetLineStyle(0);
   hframe__43->SetMarkerStyle(20);
   hframe__43->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__43->GetXaxis()->SetLabelFont(43);
   hframe__43->GetXaxis()->SetLabelOffset(0.007);
   hframe__43->GetXaxis()->SetLabelSize(27);
   hframe__43->GetXaxis()->SetTitleSize(33);
   hframe__43->GetXaxis()->SetTitleOffset(2.925);
   hframe__43->GetXaxis()->SetTitleFont(43);
   hframe__43->GetYaxis()->SetTitle("Ratio");
   hframe__43->GetYaxis()->SetNdivisions(505);
   hframe__43->GetYaxis()->SetLabelFont(43);
   hframe__43->GetYaxis()->SetLabelOffset(0.007);
   hframe__43->GetYaxis()->SetLabelSize(21);
   hframe__43->GetYaxis()->SetTitleSize(33);
   hframe__43->GetYaxis()->SetTitleOffset(1.796875);
   hframe__43->GetYaxis()->SetTitleFont(43);
   hframe__43->GetZaxis()->SetLabelFont(43);
   hframe__43->GetZaxis()->SetLabelOffset(0.007);
   hframe__43->GetZaxis()->SetLabelSize(27);
   hframe__43->GetZaxis()->SetTitleSize(33);
   hframe__43->GetZaxis()->SetTitleFont(43);
   hframe__43->Draw(" ");
   Double_t xAxis31[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 500}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44","#tau p_{T}<50",10, xAxis31);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(1,1.178676);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(2,0.7577201);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(3,0.8593519);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(4,0.8461072);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(5,0.7435766);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(6,1.023304);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(7,0.7944579);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(8,0.7354802);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(9,0.8852941);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(10,0.8260689);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(11,1.003985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(1,0.370583);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(2,0.2759569);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(3,0.1649266);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(4,0.1528566);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(5,0.1185751);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(6,0.103427);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(7,0.1066079);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(8,0.1274926);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(9,0.1663369);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(10,0.2254096);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(11,1.41985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetEntries(189.4716);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->Draw("EP same");
   Double_t xAxis32[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 500}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45","#tau p_{T}<50",10, xAxis32);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(5,0.7207969);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(6,0.9898824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(7,0.7621042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(8,0.7042185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(9,0.8474045);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(10,0.7957963);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(11,1.003444);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(5,0.1149444);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(6,0.100059);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(7,0.1022867);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(8,0.1220903);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(9,0.1592168);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(10,0.2170805);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(11,1.419084);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetEntries(189.1474);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,500,1);
   
   TH1F *Graph_Graph7 = new TH1F("Graph_Graph7","Graph",100,0,550);
   Graph_Graph7->SetMinimum(0.9);
   Graph_Graph7->SetMaximum(2.1);
   Graph_Graph7->SetDirectory(0);
   Graph_Graph7->SetStats(0);
   Graph_Graph7->SetLineStyle(0);
   Graph_Graph7->SetMarkerStyle(20);
   Graph_Graph7->GetXaxis()->SetLabelFont(43);
   Graph_Graph7->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetXaxis()->SetLabelSize(27);
   Graph_Graph7->GetXaxis()->SetTitleSize(33);
   Graph_Graph7->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph7->GetXaxis()->SetTitleFont(43);
   Graph_Graph7->GetYaxis()->SetLabelFont(43);
   Graph_Graph7->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetYaxis()->SetLabelSize(27);
   Graph_Graph7->GetYaxis()->SetTitleSize(33);
   Graph_Graph7->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph7->GetYaxis()->SetTitleFont(43);
   Graph_Graph7->GetZaxis()->SetLabelFont(43);
   Graph_Graph7->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetZaxis()->SetLabelSize(27);
   Graph_Graph7->GetZaxis()->SetTitleSize(33);
   Graph_Graph7->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph7);
   
   graph->Draw("l");
   
   TH1F *hframe__46 = new TH1F("hframe__46","",1000,0,500);
   hframe__46->SetMinimum(0.7042185);
   hframe__46->SetMaximum(1.296543);
   hframe__46->SetDirectory(0);
   hframe__46->SetStats(0);
   hframe__46->SetLineStyle(0);
   hframe__46->SetMarkerStyle(20);
   hframe__46->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__46->GetXaxis()->SetLabelFont(43);
   hframe__46->GetXaxis()->SetLabelOffset(0.007);
   hframe__46->GetXaxis()->SetLabelSize(27);
   hframe__46->GetXaxis()->SetTitleSize(33);
   hframe__46->GetXaxis()->SetTitleOffset(2.925);
   hframe__46->GetXaxis()->SetTitleFont(43);
   hframe__46->GetYaxis()->SetTitle("Ratio");
   hframe__46->GetYaxis()->SetNdivisions(505);
   hframe__46->GetYaxis()->SetLabelFont(43);
   hframe__46->GetYaxis()->SetLabelOffset(0.007);
   hframe__46->GetYaxis()->SetLabelSize(21);
   hframe__46->GetYaxis()->SetTitleSize(33);
   hframe__46->GetYaxis()->SetTitleOffset(1.796875);
   hframe__46->GetYaxis()->SetTitleFont(43);
   hframe__46->GetZaxis()->SetLabelFont(43);
   hframe__46->GetZaxis()->SetLabelOffset(0.007);
   hframe__46->GetZaxis()->SetLabelSize(27);
   hframe__46->GetZaxis()->SetTitleSize(33);
   hframe__46->GetZaxis()->SetTitleFont(43);
   hframe__46->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->Range(-101.2658,-1.929302,531.6456,26.98198);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__47 = new TH1F("hframe__47","",1000,0,500);
   hframe__47->SetMinimum(1.829165);
   hframe__47->SetMaximum(25.53642);
   hframe__47->SetDirectory(0);
   hframe__47->SetStats(0);
   hframe__47->SetLineStyle(0);
   hframe__47->SetMarkerStyle(20);
   hframe__47->GetXaxis()->SetLabelFont(43);
   hframe__47->GetXaxis()->SetLabelOffset(0.007);
   hframe__47->GetXaxis()->SetLabelSize(0);
   hframe__47->GetXaxis()->SetTitleSize(0);
   hframe__47->GetXaxis()->SetTitleOffset(0.9);
   hframe__47->GetXaxis()->SetTitleFont(43);
   hframe__47->GetYaxis()->SetTitle("N_{events}");
   hframe__47->GetYaxis()->SetLabelFont(43);
   hframe__47->GetYaxis()->SetLabelOffset(0.007);
   hframe__47->GetYaxis()->SetLabelSize(27);
   hframe__47->GetYaxis()->SetTitleSize(33);
   hframe__47->GetYaxis()->SetTitleOffset(1.796875);
   hframe__47->GetYaxis()->SetTitleFont(43);
   hframe__47->GetZaxis()->SetLabelFont(43);
   hframe__47->GetZaxis()->SetLabelOffset(0.007);
   hframe__47->GetZaxis()->SetLabelSize(27);
   hframe__47->GetZaxis()->SetTitleSize(33);
   hframe__47->GetZaxis()->SetTitleFont(43);
   hframe__47->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis33[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 500}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis33);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.155992);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.586743);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,7.426271);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,10.02938);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,15.32596);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,23.21492);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,18.10563);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,12.12967);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,11.82004);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,5.267674);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.04633405);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4368165);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5239899);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.8377605);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.9354824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.024046);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.207359);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.046105);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.8499553);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.8369952);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.5508223);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.04633405);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis34[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 500}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis34);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,14.85644);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,22.45671);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,17.3683);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,11.6141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.31415);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,5.074632);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.04630905);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9927686);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.168366);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.004578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.8145114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.8011357);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.5294948);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.04630905);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis35[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 500}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis35);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,20.61114);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.68624);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,22.78992);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,16.49218);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,13.35154);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,6.376798);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.04615013);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.984329);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.96608);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.760173);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.614869);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.323627);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.607206);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.04615013);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(901.3783);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__48 = new TH1F("hframe__48","",1000,0,500);
   hframe__48->SetMinimum(1.829165);
   hframe__48->SetMaximum(25.53642);
   hframe__48->SetDirectory(0);
   hframe__48->SetStats(0);
   hframe__48->SetLineStyle(0);
   hframe__48->SetMarkerStyle(20);
   hframe__48->GetXaxis()->SetLabelFont(43);
   hframe__48->GetXaxis()->SetLabelOffset(0.007);
   hframe__48->GetXaxis()->SetLabelSize(0);
   hframe__48->GetXaxis()->SetTitleSize(0);
   hframe__48->GetXaxis()->SetTitleOffset(0.9);
   hframe__48->GetXaxis()->SetTitleFont(43);
   hframe__48->GetYaxis()->SetTitle("N_{events}");
   hframe__48->GetYaxis()->SetLabelFont(43);
   hframe__48->GetYaxis()->SetLabelOffset(0.007);
   hframe__48->GetYaxis()->SetLabelSize(27);
   hframe__48->GetYaxis()->SetTitleSize(33);
   hframe__48->GetYaxis()->SetTitleOffset(1.796875);
   hframe__48->GetYaxis()->SetTitleFont(43);
   hframe__48->GetZaxis()->SetLabelFont(43);
   hframe__48->GetZaxis()->SetLabelOffset(0.007);
   hframe__48->GetZaxis()->SetLabelSize(27);
   hframe__48->GetZaxis()->SetTitleSize(33);
   hframe__48->GetZaxis()->SetTitleFont(43);
   hframe__48->Draw("sameaxis");
   
   TH1F *hframe__49 = new TH1F("hframe__49","",1000,0,500);
   hframe__49->SetMinimum(1.829165);
   hframe__49->SetMaximum(25.53642);
   hframe__49->SetDirectory(0);
   hframe__49->SetStats(0);
   hframe__49->SetLineStyle(0);
   hframe__49->SetMarkerStyle(20);
   hframe__49->GetXaxis()->SetLabelFont(43);
   hframe__49->GetXaxis()->SetLabelOffset(0.007);
   hframe__49->GetXaxis()->SetLabelSize(0);
   hframe__49->GetXaxis()->SetTitleSize(0);
   hframe__49->GetXaxis()->SetTitleOffset(0.9);
   hframe__49->GetXaxis()->SetTitleFont(43);
   hframe__49->GetYaxis()->SetTitle("N_{events}");
   hframe__49->GetYaxis()->SetLabelFont(43);
   hframe__49->GetYaxis()->SetLabelOffset(0.007);
   hframe__49->GetYaxis()->SetLabelSize(27);
   hframe__49->GetYaxis()->SetTitleSize(33);
   hframe__49->GetYaxis()->SetTitleOffset(1.796875);
   hframe__49->GetYaxis()->SetTitleFont(43);
   hframe__49->GetZaxis()->SetLabelFont(43);
   hframe__49->GetZaxis()->SetLabelOffset(0.007);
   hframe__49->GetZaxis()->SetLabelSize(27);
   hframe__49->GetZaxis()->SetTitleSize(33);
   hframe__49->GetZaxis()->SetTitleFont(43);
   hframe__49->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.95_QCDTailKillerLoosePlus);
}
