{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus/Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus
//=========  (Fri Aug  1 10:26:42 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus = new TCanvas("Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus", "Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2
   TPad *Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2", "Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->Range(-81.01265,0.7808408,425.3165,1.636092);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__43 = new TH1F("hframe__43","",1000,0,400);
   hframe__43->SetMinimum(1.028864);
   hframe__43->SetMaximum(1.636092);
   hframe__43->SetDirectory(0);
   hframe__43->SetStats(0);
   hframe__43->SetLineStyle(0);
   hframe__43->SetMarkerStyle(20);
   hframe__43->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__43->GetXaxis()->SetLabelFont(43);
   hframe__43->GetXaxis()->SetLabelOffset(0.007);
   hframe__43->GetXaxis()->SetLabelSize(27);
   hframe__43->GetXaxis()->SetTitleSize(33);
   hframe__43->GetXaxis()->SetTitleOffset(2.925);
   hframe__43->GetXaxis()->SetTitleFont(43);
   hframe__43->GetYaxis()->SetTitle("Ratio");
   hframe__43->GetYaxis()->SetNdivisions(505);
   hframe__43->GetYaxis()->SetLabelFont(43);
   hframe__43->GetYaxis()->SetLabelOffset(0.007);
   hframe__43->GetYaxis()->SetLabelSize(21);
   hframe__43->GetYaxis()->SetTitleSize(33);
   hframe__43->GetYaxis()->SetTitleOffset(1.796875);
   hframe__43->GetYaxis()->SetTitleFont(43);
   hframe__43->GetZaxis()->SetLabelFont(43);
   hframe__43->GetZaxis()->SetLabelOffset(0.007);
   hframe__43->GetZaxis()->SetLabelSize(27);
   hframe__43->GetZaxis()->SetTitleSize(33);
   hframe__43->GetZaxis()->SetTitleFont(43);
   hframe__43->Draw(" ");
   Double_t xAxis31[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44","#tau p_{T}<50",10, xAxis31);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(1,1.2586);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(2,1.24296);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(3,1.224775);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(4,1.242628);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(5,1.227487);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(6,1.227072);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(7,1.298991);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(8,1.309447);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(9,1.296919);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinContent(10,1.487356);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(1,0.2616794);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(2,0.2420709);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(3,0.1363722);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(4,0.1216215);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(5,0.1227403);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(6,0.1378308);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(7,0.1803646);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(8,0.2177393);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(9,0.2354368);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetBinError(10,0.4113954);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetEntries(329.0748);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__44->Draw("EP same");
   Double_t xAxis32[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45","#tau p_{T}<50",10, xAxis32);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(1,1.039155);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(2,1.037946);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(3,1.032302);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(4,1.036355);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(5,1.033776);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(6,1.028864);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(7,1.068263);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(8,1.046857);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(9,1.070101);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinContent(10,1.128127);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(1,0.2157572);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(2,0.2022065);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(3,0.114812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(4,0.1013175);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(5,0.103263);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(6,0.1154273);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(7,0.1480535);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(8,0.1736083);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(9,0.1938378);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetBinError(10,0.3102965);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetEntries(345.1088);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__45->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph7 = new TH1F("Graph_Graph7","Graph",100,0,440);
   Graph_Graph7->SetMinimum(0.9);
   Graph_Graph7->SetMaximum(2.1);
   Graph_Graph7->SetDirectory(0);
   Graph_Graph7->SetStats(0);
   Graph_Graph7->SetLineStyle(0);
   Graph_Graph7->SetMarkerStyle(20);
   Graph_Graph7->GetXaxis()->SetLabelFont(43);
   Graph_Graph7->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetXaxis()->SetLabelSize(27);
   Graph_Graph7->GetXaxis()->SetTitleSize(33);
   Graph_Graph7->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph7->GetXaxis()->SetTitleFont(43);
   Graph_Graph7->GetYaxis()->SetLabelFont(43);
   Graph_Graph7->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetYaxis()->SetLabelSize(27);
   Graph_Graph7->GetYaxis()->SetTitleSize(33);
   Graph_Graph7->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph7->GetYaxis()->SetTitleFont(43);
   Graph_Graph7->GetZaxis()->SetLabelFont(43);
   Graph_Graph7->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph7->GetZaxis()->SetLabelSize(27);
   Graph_Graph7->GetZaxis()->SetTitleSize(33);
   Graph_Graph7->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph7);
   
   graph->Draw("l");
   
   TH1F *hframe__46 = new TH1F("hframe__46","",1000,0,400);
   hframe__46->SetMinimum(1.028864);
   hframe__46->SetMaximum(1.636092);
   hframe__46->SetDirectory(0);
   hframe__46->SetStats(0);
   hframe__46->SetLineStyle(0);
   hframe__46->SetMarkerStyle(20);
   hframe__46->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__46->GetXaxis()->SetLabelFont(43);
   hframe__46->GetXaxis()->SetLabelOffset(0.007);
   hframe__46->GetXaxis()->SetLabelSize(27);
   hframe__46->GetXaxis()->SetTitleSize(33);
   hframe__46->GetXaxis()->SetTitleOffset(2.925);
   hframe__46->GetXaxis()->SetTitleFont(43);
   hframe__46->GetYaxis()->SetTitle("Ratio");
   hframe__46->GetYaxis()->SetNdivisions(505);
   hframe__46->GetYaxis()->SetLabelFont(43);
   hframe__46->GetYaxis()->SetLabelOffset(0.007);
   hframe__46->GetYaxis()->SetLabelSize(21);
   hframe__46->GetYaxis()->SetTitleSize(33);
   hframe__46->GetYaxis()->SetTitleOffset(1.796875);
   hframe__46->GetYaxis()->SetTitleFont(43);
   hframe__46->GetZaxis()->SetLabelFont(43);
   hframe__46->GetZaxis()->SetLabelOffset(0.007);
   hframe__46->GetZaxis()->SetLabelSize(27);
   hframe__46->GetZaxis()->SetTitleSize(33);
   hframe__46->GetZaxis()->SetTitleFont(43);
   hframe__46->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1", "Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->Range(-81.01265,-0.9011296,425.3165,17.55313);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__47 = new TH1F("hframe__47","",1000,0,400);
   hframe__47->SetMinimum(1.497924);
   hframe__47->SetMaximum(16.63042);
   hframe__47->SetDirectory(0);
   hframe__47->SetStats(0);
   hframe__47->SetLineStyle(0);
   hframe__47->SetMarkerStyle(20);
   hframe__47->GetXaxis()->SetLabelFont(43);
   hframe__47->GetXaxis()->SetLabelOffset(0.007);
   hframe__47->GetXaxis()->SetLabelSize(0);
   hframe__47->GetXaxis()->SetTitleSize(0);
   hframe__47->GetXaxis()->SetTitleOffset(0.9);
   hframe__47->GetXaxis()->SetTitleFont(43);
   hframe__47->GetYaxis()->SetTitle("N_{events}");
   hframe__47->GetYaxis()->SetLabelFont(43);
   hframe__47->GetYaxis()->SetLabelOffset(0.007);
   hframe__47->GetYaxis()->SetLabelSize(27);
   hframe__47->GetYaxis()->SetTitleSize(33);
   hframe__47->GetYaxis()->SetTitleOffset(1.796875);
   hframe__47->GetYaxis()->SetTitleFont(43);
   hframe__47->GetZaxis()->SetLabelFont(43);
   hframe__47->GetZaxis()->SetLabelOffset(0.007);
   hframe__47->GetZaxis()->SetLabelSize(27);
   hframe__47->GetZaxis()->SetTitleSize(33);
   hframe__47->GetZaxis()->SetTitleFont(43);
   hframe__47->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Tight");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis33[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis33);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,3.355933);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,4.229177);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,11.62515);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,15.11856);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,14.29208);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,11.13235);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,8.002129);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,5.308583);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,4.468708);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,2.227947);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4938742);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5811811);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.916048);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,1.046206);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.006384);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,0.8853519);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,0.7543854);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.6195344);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.5514824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.407543);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1123.751);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis34[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis34);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.770804);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,3.531615);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,9.798261);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,12.60893);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,12.03662);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,9.334145);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,6.580781);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,4.24403);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,3.687176);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,1.689849);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4066458);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.485624);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.7703552);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.870556);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.8457872);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,0.7405494);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,0.6178975);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.4925964);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.4528847);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.3051619);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1123.751);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis35[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis35);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,2.6664);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.402503);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,9.491659);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,12.1666);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,11.64336);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,9.072286);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,6.160265);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,4.054066);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,3.445634);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,1.497924);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.3916108);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,0.4695473);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,0.7466735);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,0.8421149);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,0.8266196);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,0.7196294);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,0.6279795);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,0.4802024);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,0.4587375);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,0.3107748);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(1079.466);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__48 = new TH1F("hframe__48","",1000,0,400);
   hframe__48->SetMinimum(1.497924);
   hframe__48->SetMaximum(16.63042);
   hframe__48->SetDirectory(0);
   hframe__48->SetStats(0);
   hframe__48->SetLineStyle(0);
   hframe__48->SetMarkerStyle(20);
   hframe__48->GetXaxis()->SetLabelFont(43);
   hframe__48->GetXaxis()->SetLabelOffset(0.007);
   hframe__48->GetXaxis()->SetLabelSize(0);
   hframe__48->GetXaxis()->SetTitleSize(0);
   hframe__48->GetXaxis()->SetTitleOffset(0.9);
   hframe__48->GetXaxis()->SetTitleFont(43);
   hframe__48->GetYaxis()->SetTitle("N_{events}");
   hframe__48->GetYaxis()->SetLabelFont(43);
   hframe__48->GetYaxis()->SetLabelOffset(0.007);
   hframe__48->GetYaxis()->SetLabelSize(27);
   hframe__48->GetYaxis()->SetTitleSize(33);
   hframe__48->GetYaxis()->SetTitleOffset(1.796875);
   hframe__48->GetYaxis()->SetTitleFont(43);
   hframe__48->GetZaxis()->SetLabelFont(43);
   hframe__48->GetZaxis()->SetLabelOffset(0.007);
   hframe__48->GetZaxis()->SetLabelSize(27);
   hframe__48->GetZaxis()->SetTitleSize(33);
   hframe__48->GetZaxis()->SetTitleFont(43);
   hframe__48->Draw("sameaxis");
   
   TH1F *hframe__49 = new TH1F("hframe__49","",1000,0,400);
   hframe__49->SetMinimum(1.497924);
   hframe__49->SetMaximum(16.63042);
   hframe__49->SetDirectory(0);
   hframe__49->SetStats(0);
   hframe__49->SetLineStyle(0);
   hframe__49->SetMarkerStyle(20);
   hframe__49->GetXaxis()->SetLabelFont(43);
   hframe__49->GetXaxis()->SetLabelOffset(0.007);
   hframe__49->GetXaxis()->SetLabelSize(0);
   hframe__49->GetXaxis()->SetTitleSize(0);
   hframe__49->GetXaxis()->SetTitleOffset(0.9);
   hframe__49->GetXaxis()->SetTitleFont(43);
   hframe__49->GetYaxis()->SetTitle("N_{events}");
   hframe__49->GetYaxis()->SetLabelFont(43);
   hframe__49->GetYaxis()->SetLabelOffset(0.007);
   hframe__49->GetYaxis()->SetLabelSize(27);
   hframe__49->GetYaxis()->SetTitleSize(33);
   hframe__49->GetYaxis()->SetTitleOffset(1.796875);
   hframe__49->GetYaxis()->SetTitleFont(43);
   hframe__49->GetZaxis()->SetLabelFont(43);
   hframe__49->GetZaxis()->SetLabelOffset(0.007);
   hframe__49->GetZaxis()->SetLabelSize(27);
   hframe__49->GetZaxis()->SetTitleSize(33);
   hframe__49->GetZaxis()->SetTitleFont(43);
   hframe__49->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->Modified();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->cd();
   Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus->SetSelected(Mt_DataDrivenVsMC_w=0.66_QCDTailKillerTightPlus);
}
