{
//=========Macro generated from canvas: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus/Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus
//=========  (Wed Jul 30 13:56:29 2014) by ROOT version5.32/00
   TCanvas *Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus = new TCanvas("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus",0,0,600,750);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetHighLightColor(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->Range(0,0,1,1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2
   TPad *Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2 = new TPad("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2",0.01,0.01,0.99,0.302);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->Draw();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->Range(-81.01265,0.4235213,425.3165,1.391443);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetTopMargin(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetBottomMargin(0.29);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->SetFrameBorderMode(0);
   
   TH1F *hframe__64 = new TH1F("hframe__64","",1000,0,400);
   hframe__64->SetMinimum(0.7042185);
   hframe__64->SetMaximum(1.391443);
   hframe__64->SetDirectory(0);
   hframe__64->SetStats(0);
   hframe__64->SetLineStyle(0);
   hframe__64->SetMarkerStyle(20);
   hframe__64->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__64->GetXaxis()->SetLabelFont(43);
   hframe__64->GetXaxis()->SetLabelOffset(0.007);
   hframe__64->GetXaxis()->SetLabelSize(27);
   hframe__64->GetXaxis()->SetTitleSize(33);
   hframe__64->GetXaxis()->SetTitleOffset(2.925);
   hframe__64->GetXaxis()->SetTitleFont(43);
   hframe__64->GetYaxis()->SetTitle("Ratio");
   hframe__64->GetYaxis()->SetNdivisions(505);
   hframe__64->GetYaxis()->SetLabelFont(43);
   hframe__64->GetYaxis()->SetLabelOffset(0.007);
   hframe__64->GetYaxis()->SetLabelSize(21);
   hframe__64->GetYaxis()->SetTitleSize(33);
   hframe__64->GetYaxis()->SetTitleOffset(1.796875);
   hframe__64->GetYaxis()->SetTitleFont(43);
   hframe__64->GetZaxis()->SetLabelFont(43);
   hframe__64->GetZaxis()->SetLabelOffset(0.007);
   hframe__64->GetZaxis()->SetLabelSize(27);
   hframe__64->GetZaxis()->SetTitleSize(33);
   hframe__64->GetZaxis()->SetTitleFont(43);
   hframe__64->Draw(" ");
   Double_t xAxis46[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65","#tau p_{T}<50",10, xAxis46);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(1,1.264948);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(2,0.8021701);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(3,0.920208);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(4,0.9057246);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(5,0.7891359);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(6,1.090147);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(7,0.8591651);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(8,0.7980036);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(9,0.9610735);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(10,0.8833582);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinContent(11,1.089983);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(1,0.3974783);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(2,0.2925231);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(3,0.1763727);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(4,0.163542);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(5,0.1258466);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(6,0.1101762);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(7,0.1152625);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(8,0.138311);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(9,0.1805916);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(10,0.2440858);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetBinError(11,0.9328807);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetEntries(189.4424);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.__65->Draw("EP same");
   Double_t xAxis47[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66 = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66","#tau p_{T}<50",10, xAxis47);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(1,1.13554);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(2,0.735495);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(3,0.8289239);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(4,0.8162985);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(5,0.7207969);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(6,0.9898824);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(7,0.7621042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(8,0.7042185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(9,0.8474045);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(10,0.7913883);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinContent(11,1.088221);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(1,0.3571796);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(2,0.2676972);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(3,0.1592185);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(4,0.1475258);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(5,0.1149444);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(6,0.100059);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(7,0.1022867);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(8,0.1220903);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(9,0.1592168);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(10,0.2184464);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetBinError(11,0.931372);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetEntries(188.642);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetDirectory(0);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetYaxis()->SetTitle("Ratio");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)__66->Draw("EP same");
   
   TGraph *graph = new TGraph(2);
   graph->SetName("Graph");
   graph->SetTitle("Graph");
   graph->SetFillColor(1);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   graph->SetLineColor(ci);
   graph->SetLineStyle(3);
   graph->SetLineWidth(2);
   graph->SetMarkerStyle(20);
   graph->SetPoint(0,0,1);
   graph->SetPoint(1,400,1);
   
   TH1F *Graph_Graph10 = new TH1F("Graph_Graph10","Graph",100,0,440);
   Graph_Graph10->SetMinimum(0.9);
   Graph_Graph10->SetMaximum(2.1);
   Graph_Graph10->SetDirectory(0);
   Graph_Graph10->SetStats(0);
   Graph_Graph10->SetLineStyle(0);
   Graph_Graph10->SetMarkerStyle(20);
   Graph_Graph10->GetXaxis()->SetLabelFont(43);
   Graph_Graph10->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph10->GetXaxis()->SetLabelSize(27);
   Graph_Graph10->GetXaxis()->SetTitleSize(33);
   Graph_Graph10->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph10->GetXaxis()->SetTitleFont(43);
   Graph_Graph10->GetYaxis()->SetLabelFont(43);
   Graph_Graph10->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph10->GetYaxis()->SetLabelSize(27);
   Graph_Graph10->GetYaxis()->SetTitleSize(33);
   Graph_Graph10->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph10->GetYaxis()->SetTitleFont(43);
   Graph_Graph10->GetZaxis()->SetLabelFont(43);
   Graph_Graph10->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph10->GetZaxis()->SetLabelSize(27);
   Graph_Graph10->GetZaxis()->SetTitleSize(33);
   Graph_Graph10->GetZaxis()->SetTitleFont(43);
   graph->SetHistogram(Graph_Graph10);
   
   graph->Draw("l");
   
   TH1F *hframe__67 = new TH1F("hframe__67","",1000,0,400);
   hframe__67->SetMinimum(0.7042185);
   hframe__67->SetMaximum(1.391443);
   hframe__67->SetDirectory(0);
   hframe__67->SetStats(0);
   hframe__67->SetLineStyle(0);
   hframe__67->SetMarkerStyle(20);
   hframe__67->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   hframe__67->GetXaxis()->SetLabelFont(43);
   hframe__67->GetXaxis()->SetLabelOffset(0.007);
   hframe__67->GetXaxis()->SetLabelSize(27);
   hframe__67->GetXaxis()->SetTitleSize(33);
   hframe__67->GetXaxis()->SetTitleOffset(2.925);
   hframe__67->GetXaxis()->SetTitleFont(43);
   hframe__67->GetYaxis()->SetTitle("Ratio");
   hframe__67->GetYaxis()->SetNdivisions(505);
   hframe__67->GetYaxis()->SetLabelFont(43);
   hframe__67->GetYaxis()->SetLabelOffset(0.007);
   hframe__67->GetYaxis()->SetLabelSize(21);
   hframe__67->GetYaxis()->SetTitleSize(33);
   hframe__67->GetYaxis()->SetTitleOffset(1.796875);
   hframe__67->GetYaxis()->SetTitleFont(43);
   hframe__67->GetZaxis()->SetLabelFont(43);
   hframe__67->GetZaxis()->SetLabelOffset(0.007);
   hframe__67->GetZaxis()->SetLabelSize(27);
   hframe__67->GetZaxis()->SetTitleSize(33);
   hframe__67->GetZaxis()->SetTitleFont(43);
   hframe__67->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_2->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: coverpad
   coverpad = new TPad("coverpad", "coverpad",0.065,0.285,0.165,0.33);
   coverpad->Draw();
   coverpad->cd();
   coverpad->Range(0,0,1,1);
   coverpad->SetFillColor(0);
   coverpad->SetBorderMode(0);
   coverpad->SetBorderSize(2);
   coverpad->SetTickx(1);
   coverpad->SetTicky(1);
   coverpad->SetLeftMargin(0.16);
   coverpad->SetRightMargin(0.05);
   coverpad->SetTopMargin(0.05);
   coverpad->SetBottomMargin(0.13);
   coverpad->SetFrameFillStyle(0);
   coverpad->SetFrameBorderMode(0);
   coverpad->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->cd();
  
// ------------>Primitives in pad: Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1 = new TPad("Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1", "Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1",0.01,0.2,0.99,0.99);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->Draw();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->Range(-81.01265,-2.193752,425.3165,28.75176);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetFillColor(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetFillStyle(4000);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetBorderSize(2);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetTickx(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetTicky(1);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetLeftMargin(0.16);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetRightMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetTopMargin(0.05);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetBottomMargin(0.13);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetFrameFillStyle(0);
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->SetFrameBorderMode(0);
   
   TH1F *hframe__68 = new TH1F("hframe__68","",1000,0,400);
   hframe__68->SetMinimum(1.829165);
   hframe__68->SetMaximum(27.20448);
   hframe__68->SetDirectory(0);
   hframe__68->SetStats(0);
   hframe__68->SetLineStyle(0);
   hframe__68->SetMarkerStyle(20);
   hframe__68->GetXaxis()->SetLabelFont(43);
   hframe__68->GetXaxis()->SetLabelOffset(0.007);
   hframe__68->GetXaxis()->SetLabelSize(0);
   hframe__68->GetXaxis()->SetTitleSize(0);
   hframe__68->GetXaxis()->SetTitleOffset(0.9);
   hframe__68->GetXaxis()->SetTitleFont(43);
   hframe__68->GetYaxis()->SetTitle("N_{events}");
   hframe__68->GetYaxis()->SetLabelFont(43);
   hframe__68->GetYaxis()->SetLabelOffset(0.007);
   hframe__68->GetYaxis()->SetLabelSize(27);
   hframe__68->GetYaxis()->SetTitleSize(33);
   hframe__68->GetYaxis()->SetTitleOffset(1.796875);
   hframe__68->GetYaxis()->SetTitleFont(43);
   hframe__68->GetZaxis()->SetLabelFont(43);
   hframe__68->GetZaxis()->SetLabelOffset(0.007);
   hframe__68->GetZaxis()->SetLabelSize(27);
   hframe__68->GetZaxis()->SetTitleSize(33);
   hframe__68->GetZaxis()->SetTitleFont(43);
   hframe__68->Draw(" ");
   TLatex *   tex = new TLatex(0.65,0.3,"R_{BB} Loose");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(25);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis48[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal. = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","#tau p_{T}<50",10, xAxis48);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(1,2.313798);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(2,2.738488);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(3,7.952172);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(4,10.73606);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(5,16.26499);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(6,24.73135);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(7,19.58031);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(8,13.16082);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(9,12.83181);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(10,5.56099);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinContent(11,0.1391522);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(1,0.4681381);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(2,0.5570437);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(3,0.8936521);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(4,0.9994455);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(5,1.087106);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(6,1.28593);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(7,1.129801);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(8,0.9214002);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(9,0.9092281);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(10,0.5906462);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetBinError(11,0.08033955);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetLineWidth(4);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.->Draw("HIST same");
   Double_t xAxis49[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","#tau p_{T}<50",10, xAxis49);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(1,2.077089);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(2,2.51087);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(3,7.163321);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(4,9.67604);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(5,14.85644);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(6,22.45671);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(7,17.3683);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(8,11.6141);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(9,11.31415);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(10,4.982014);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinContent(11,0.1389271);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(1,0.4212812);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(2,0.5076042);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(3,0.8100306);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(4,0.9037734);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(5,0.9927686);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(6,1.168366);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(7,1.004578);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(8,0.8145114);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(9,0.8011357);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(10,0.525429);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetBinError(11,0.08020962);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetEntries(1604.018);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineColor(14);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)->Draw("HIST same");
   Double_t xAxis50[11] = {0, 20, 40, 60, 80, 100, 120, 140, 160, 200, 400}; 
   
   TH1F *QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau) = new TH1F("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","#tau p_{T}<50",10, xAxis50);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(1,1.829165);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(2,3.41385);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(3,8.641712);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(4,11.85356);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(5,20.61114);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(6,22.68624);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(7,22.78992);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(8,16.49218);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(9,13.35154);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(10,6.295283);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinContent(11,0.1276645);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(1,0.4397692);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(2,1.033238);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(3,1.34175);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(4,1.833951);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(5,2.984329);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(6,1.96608);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(7,2.760173);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(8,2.614869);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(9,2.323627);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(10,1.605844);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetBinError(11,0.08065877);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetEntries(901.3783);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineColor(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetLineWidth(2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerStyle(20);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->SetMarkerSize(1.2);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitle("m_{T}(tau,MET), GeV/c^{2}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetXaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitle("N_{events}");
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetYaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetLabelSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleSize(0.035);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->GetZaxis()->SetTitleFont(42);
   QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.38,0.67,0.58,0.97,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(MC, mis-ID. #tau)","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau)","l");
   entry->SetLineColor(14);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","QCD(Data)+EWK+t#bar{t}(Data, mis-ID. #tau), q-g bal.","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *hframe__69 = new TH1F("hframe__69","",1000,0,400);
   hframe__69->SetMinimum(1.829165);
   hframe__69->SetMaximum(27.20448);
   hframe__69->SetDirectory(0);
   hframe__69->SetStats(0);
   hframe__69->SetLineStyle(0);
   hframe__69->SetMarkerStyle(20);
   hframe__69->GetXaxis()->SetLabelFont(43);
   hframe__69->GetXaxis()->SetLabelOffset(0.007);
   hframe__69->GetXaxis()->SetLabelSize(0);
   hframe__69->GetXaxis()->SetTitleSize(0);
   hframe__69->GetXaxis()->SetTitleOffset(0.9);
   hframe__69->GetXaxis()->SetTitleFont(43);
   hframe__69->GetYaxis()->SetTitle("N_{events}");
   hframe__69->GetYaxis()->SetLabelFont(43);
   hframe__69->GetYaxis()->SetLabelOffset(0.007);
   hframe__69->GetYaxis()->SetLabelSize(27);
   hframe__69->GetYaxis()->SetTitleSize(33);
   hframe__69->GetYaxis()->SetTitleOffset(1.796875);
   hframe__69->GetYaxis()->SetTitleFont(43);
   hframe__69->GetZaxis()->SetLabelFont(43);
   hframe__69->GetZaxis()->SetLabelOffset(0.007);
   hframe__69->GetZaxis()->SetLabelSize(27);
   hframe__69->GetZaxis()->SetTitleSize(33);
   hframe__69->GetZaxis()->SetTitleFont(43);
   hframe__69->Draw("sameaxis");
   
   TH1F *hframe__70 = new TH1F("hframe__70","",1000,0,400);
   hframe__70->SetMinimum(1.829165);
   hframe__70->SetMaximum(27.20448);
   hframe__70->SetDirectory(0);
   hframe__70->SetStats(0);
   hframe__70->SetLineStyle(0);
   hframe__70->SetMarkerStyle(20);
   hframe__70->GetXaxis()->SetLabelFont(43);
   hframe__70->GetXaxis()->SetLabelOffset(0.007);
   hframe__70->GetXaxis()->SetLabelSize(0);
   hframe__70->GetXaxis()->SetTitleSize(0);
   hframe__70->GetXaxis()->SetTitleOffset(0.9);
   hframe__70->GetXaxis()->SetTitleFont(43);
   hframe__70->GetYaxis()->SetTitle("N_{events}");
   hframe__70->GetYaxis()->SetLabelFont(43);
   hframe__70->GetYaxis()->SetLabelOffset(0.007);
   hframe__70->GetYaxis()->SetLabelSize(27);
   hframe__70->GetYaxis()->SetTitleSize(33);
   hframe__70->GetYaxis()->SetTitleOffset(1.796875);
   hframe__70->GetYaxis()->SetTitleFont(43);
   hframe__70->GetZaxis()->SetLabelFont(43);
   hframe__70->GetZaxis()->SetLabelOffset(0.007);
   hframe__70->GetZaxis()->SetLabelSize(27);
   hframe__70->GetZaxis()->SetTitleSize(33);
   hframe__70->GetZaxis()->SetTitleFont(43);
   hframe__70->Draw("sameaxis");
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus_1->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->Modified();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->cd();
   Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus->SetSelected(Mt_DataDrivenVsMC_w=0.85_QCDTailKillerLoosePlus);
}
