## TreeCutHelper module
# TreeAnalysis Variable, Cuts and Cut-Combination definitions
#
# This modules contains definitions for most available tree variables
# in the tree generated by running treeAnalysis_cfg.py
# The primary goal is to have a generic module which other plotting 
# scripts can load to save code-space, but also make sure that a 
# unique convection is used for variables, cuts, histogam names, 
# xLabel and yLabels.

######################################################################
# All imported modules here
######################################################################
from HiggsAnalysis.HeavyChHiggsToTauNu.tools.cutstring import * # And, Not, Or
from ROOT import TCutG
import ROOT
import math
from TreeVarHelper import * 

######################################################################
### Function Definition
######################################################################
### DeltaPhi Circular Cuts
def GetCollinearDeltaPhiCCut(CutName, nPoints, radius, varX, varY):
    ### Collinear Circular Cut
    phi = 0.0
    CCut = TCutG(CutName, nPoints+4)
    CCut.SetVarY(varY)
    CCut.SetVarX(varX)

    ### Generate circular-cut of given radius 
    for i in range(0, nPoints):
        phi = (0.5*math.pi/float(nPoints))*i #90 degrees movement only
        x = radius*math.cos(phi)
        y = radius*math.sin(phi)
        yNew = 180-y
        CCut.SetPoint(i, yNew, x)
        # print "[%s, %s]" % (x, yNew)

    CCut.SetPoint(nPoints+1, 180.0-radius, 0.0)
    CCut.SetPoint(nPoints+2, 0.0, 0.0)
    CCut.SetPoint(nPoints+3, 0.0, 180.0)
    CCut.SetPoint(nPoints+4, 180.0, 180.0)
    CCut.SetName(CutName)
    
    return CCut

######################################################################
### DeltaPhi Circular Cuts
def GetBackToBackDeltaPhiCCut(CutName, nPoints, radius, varX, varY):
    ### Back-to-Back Circular Cut
    phi = 0.0
    CCut = TCutG(CutName, nPoints+4)
    CCut.SetVarY(varY)
    CCut.SetVarX(varX)

    ### Generate circular-cut of given radius 
    for i in range(0, nPoints):
        phi = (0.5*math.pi/float(nPoints))*i #90 degrees movement only
        x = radius*math.cos(phi)
        y = radius*math.sin(phi)
        xNew = 180-x
        CCut.SetPoint(i, y, xNew)
        #print "[%s, %s]" % (xNew, y)

    CCut.SetPoint(nPoints+1, radius, 180.0)
    CCut.SetPoint(nPoints+2, 180.0, 180.0 )
    CCut.SetPoint(nPoints+3, 180.0, 0)
    CCut.SetPoint(nPoints+4, 0, 0)
    CCut.SetName(CutName)
    
    return CCut

######################################################################
### DeltaPhi Triangular Cuts
def GetCollinearDeltaPhiTrCut(CutName, xMax, yMax, varX, varY):
    ### Collinear Triangular Cut
    TrCut = TCutG(CutName, 6)
    TrCut.SetVarY(varY)
    TrCut.SetVarX(varX)

    ### Generate triangular cut with given points
    TrCut.SetPoint(0, 0.0, 0.0)
    TrCut.SetPoint(1, yMax, 0.0)
    TrCut.SetPoint(2, 180.0, xMax)
    TrCut.SetPoint(3, 180.0, 180.0)
    TrCut.SetPoint(4, 180.0, 0.0)
    TrCut.SetPoint(5, 0.0, 0.0)
    TrCut.SetName(CutName)
    
    return TrCut

######################################################################
### Per-event cuts: HIG-12-037 #HIG-11-019
######################################################################
### Tau-jet 
TauPtCut        = TauPt + ">=41"
TauEtaCut       = TauEta + "<=2.1"
TauIsoCut       = TauIso + ">= 0.5"  #">= 1.0" 
RtauCut         = Rtau + ">= 0.7" 
TauEleDiscCut   = TauEleDisc + ">=1"
TauMuDiscCut    = TauMuDisc + ">=1"
TauIsFakeCut    = TauIsFake + "==1"
TauIsNotFakeCut = TauIsFake + "==0"
TauCandCut      = And(TauPtCut, TauEtaCut, TauEleDiscCut, TauMuDiscCut)
TauOneProngCut  = TauOneProng + "==1";
TauIDCut        = TauIsoCut + "&&" + RtauCut + "&&" + TauOneProngCut + "&&" + TauEleDiscCut + "&&" + TauMuDiscCut

### Isolated e/mu veto

### Jets
NJetsCut         = NJets + ">=3"
JetsPtCut        = JetsPt + ">=3"
JetsEtaCut       = JetsEta + ">=3"
NFwdJetsCutValue = "<=1"
NFwdJetsCut      = NFwdJets + NFwdJetsCutValue

### MET
MetCut = Met + ">= 60" #">=50"

### Btagging
BtagCut =  Btag + ">=1.0"

### DeltaPhi(tau,MET)
DeltaPhiTauMetCut = DeltaPhiTauMet + "<= 160"

### mT(tau,MET)
MtCutValue = " >= 80"
MtCut = Mt + MtCutValue

### Event Shape Variables
SphericityCut  = Sphericity + ">= 0.9"
AplanarityCut  = Aplanarity + ">= 0.1"
PlanarityCut   = Planarity  + "<= 0.3"
CircularityCut = Circularity + ">= 0.5"
AlphaTCut      = AlphaT + ">= 0.50"
CparameterCut  = Cparameter + ">= 0.0"
DparameterCut  = Dparameter + ">= 0.0"
JetThrustCut   = JetThrust + ">= 0.0"
MT_QOneCut     = MT_QOne + ">= 0.0"
MT_QTwoCut     = MT_QTwo + ">= 0.0"
MT_QThreeCut   = MT_QThree + ">= 0.0"
ST_QOneCut     = MT_QOne + ">= 0.0"
ST_QTwoCut     = MT_QTwo + ">= 0.0"
ST_QThreeCut   = MT_QThree + ">= 0.0"
YCut           = Y + ">= 0.0"
SphericityAltCut        = SphericityAlt + ">= 0.9"
AplanarityAltCut        = AplanarityAlt + "<= 0.1"
PlanarityAltCut         = PlanarityAlt + "<= 0.3" 
vDiJetMassesNoTauCut    = vDiJetMassesNoTau + " <= 400 " + " && " + vDiJetMassesNoTau + ">=40"
vDiJetMassesNoTauSumCut = vDiJetMassesNoTauSum + " >= 2"

### Leading Jets
LdgJetCut      = LdgJet + ".Pt()>=0.0"
NLdgJetCut     = NLdgJet + ".Pt()>=0.0"
NNLdgJetCut    = NNLdgJet + ".Pt()>=0.0"
HtCut          = Ht + ">= 150"
MHTCut         = MHT + ">=60"
MHT_SelJetsCut = MHT_SelJets + ">=60"
MHT_AllJetsCut = MHT_AllJets + ">=60"

### DeltaPhi(jet, MHT)
DeltaPhiMHTLdgJetCut   = DeltaPhiMHTLdgJet + ">=60"
DeltaPhiMHTNLdgJetCut  = DeltaPhiMHTNLdgJet + ">=60"
DeltaPhiMHTNNLdgJetCut = DeltaPhiMHTNNLdgJet + ">=60"

### DeltaPhi(jet,MET)
DeltaPhiMetLdgJetCut   = DeltaPhiMetLdgJet + ">= 60"
DeltaPhiMetNLdgJetCut  = DeltaPhiMetLdgJet + ">= 60"
DeltaPhiMetNNLdgJetCut = DeltaPhiMetLdgJet + ">= 60"

### DeltaPhi Circular Cuts
Jet1_CollinearCut_R40 = GetCollinearDeltaPhiCCut("Jet1_CollinearCut_R40", 5000, 40, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_CollinearCut_R40 = GetCollinearDeltaPhiCCut("Jet2_CollinearCut_R40", 5000, 40, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_CollinearCut_R40 = GetCollinearDeltaPhiCCut("Jet3_CollinearCut_R40", 5000, 40, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

Jet1_CollinearCut_R60 = GetCollinearDeltaPhiCCut("Jet1_CollinearCut_R60", 5000, 60, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_CollinearCut_R60 = GetCollinearDeltaPhiCCut("Jet2_CollinearCut_R60", 5000, 60, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_CollinearCut_R60 = GetCollinearDeltaPhiCCut("Jet3_CollinearCut_R60", 5000, 60, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

Jet1_CollinearCut_R80 = GetCollinearDeltaPhiCCut("Jet1_CollinearCut_R80", 5000, 80, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_CollinearCut_R80 = GetCollinearDeltaPhiCCut("Jet2_CollinearCut_R80", 5000, 80, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_CollinearCut_R80 = GetCollinearDeltaPhiCCut("Jet3_CollinearCut_R80", 5000, 80, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

Jet1_BackToBackCut_R40 = GetBackToBackDeltaPhiCCut("Jet1_BackToBackCut_R40", 5000, 40, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_BackToBackCut_R40 = GetBackToBackDeltaPhiCCut("Jet2_BackToBackCut_R40", 5000, 40, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_BackToBackCut_R40 = GetBackToBackDeltaPhiCCut("Jet3_BackToBackCut_R40", 5000, 40, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

Jet1_BackToBackCut_R60 = GetBackToBackDeltaPhiCCut("Jet1_BackToBackCut_R60", 5000, 60, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_BackToBackCut_R60 = GetBackToBackDeltaPhiCCut("Jet2_BackToBackCut_R60", 5000, 60, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_BackToBackCut_R60 = GetBackToBackDeltaPhiCCut("Jet3_BackToBackCut_R60", 5000, 60, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

Jet1_BackToBackCut_R80 = GetBackToBackDeltaPhiCCut("Jet1_BackToBackCut_R80", 5000, 80, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_BackToBackCut_R80 = GetBackToBackDeltaPhiCCut("Jet2_BackToBackCut_R80", 5000, 80, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_BackToBackCut_R80 = GetBackToBackDeltaPhiCCut("Jet3_BackToBackCut_R80", 5000, 80, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

### DeltaPhi Triangular Cuts
Jet1_CollinearCut_X40_Y140 = GetCollinearDeltaPhiTrCut("Jet1_CollinearCut_X40_Y140", 40.0, 140.0, DeltaPhiMetLdgJet, DeltaPhiTauMet)
Jet2_CollinearCut_X40_Y140 = GetCollinearDeltaPhiTrCut("Jet2_CollinearCut_X40_Y140", 40.0, 140.0, DeltaPhiMetNLdgJet, DeltaPhiTauMet)
Jet3_CollinearCut_X40_Y140 = GetCollinearDeltaPhiTrCut("Jet3_CollinearCut_X40_Y140", 40.0, 140.0, DeltaPhiMetNNLdgJet, DeltaPhiTauMet)

### DeltaPhi Scenario Cuts
DeltaPhiLooseCuts       = And(Jet1_BackToBackCut_R40.GetName(), Jet2_BackToBackCut_R40.GetName(), Jet3_BackToBackCut_R40.GetName())
DeltaPhiMediumCuts      = And(Jet1_BackToBackCut_R60.GetName(), Jet2_BackToBackCut_R60.GetName(), Jet3_BackToBackCut_R60.GetName())
DeltaPhiMediumPlusCuts  = And(Jet1_BackToBackCut_R60.GetName(), Jet2_BackToBackCut_R60.GetName(), Jet3_BackToBackCut_R60.GetName(), "!" + Jet1_CollinearCut_X40_Y140.GetName(), "!" + Jet2_CollinearCut_X40_Y140.GetName(), "!" + Jet3_CollinearCut_X40_Y140.GetName())
DeltaPhiTightCuts       = And(Jet1_BackToBackCut_R80.GetName(), Jet2_BackToBackCut_R80.GetName(), Jet3_BackToBackCut_R80.GetName())
DeltaPhiTightPlusCuts  = And(Jet1_BackToBackCut_R80.GetName(), Jet2_BackToBackCut_R80.GetName(), Jet3_BackToBackCut_R80.GetName(), "!" + Jet1_CollinearCut_X40_Y140.GetName(), "!" + Jet2_CollinearCut_X40_Y140.GetName(), "!" + Jet3_CollinearCut_X40_Y140.GetName())

### Other
LdgJetNLdgJetPtSumCut          = LdgJetNLdgJetPtSum + ">=0"
DeltaHtTwoLdgJetsCut           = DeltaHtTwoLdgJets + ">=0"
DeltaPtLdgJetNLdgJetCut        = DeltaPtLdgJetNLdgJet + ">=0"
DeltaPhiMHTMetCut              = DeltaPhiMHTMet + ">=0"
DeltaPtLdgJetNLdgJetDivMetCut  = DeltaPtLdgJetNLdgJetDivMet + "<=1.0" # "<=1.8"
DeltaPtLdgJetNLdgJetDivMHTCut  = DeltaPtLdgJetNLdgJetDivMet + "<=1.0"
