{
//=========Macro generated from canvas: baselinetaup_Teq120to150Integral/
//=========  (Thu Jul 31 09:28:39 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Teq120to150Integral = new TCanvas("baselinetaup_Teq120to150Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselinetaup_Teq120to150Integral->SetHighLightColor(2);
   baselinetaup_Teq120to150Integral->Range(-101.2658,-1.543997,531.6456,2.640593);
   baselinetaup_Teq120to150Integral->SetFillColor(0);
   baselinetaup_Teq120to150Integral->SetBorderMode(0);
   baselinetaup_Teq120to150Integral->SetBorderSize(2);
   baselinetaup_Teq120to150Integral->SetLogy();
   baselinetaup_Teq120to150Integral->SetTickx(1);
   baselinetaup_Teq120to150Integral->SetTicky(1);
   baselinetaup_Teq120to150Integral->SetLeftMargin(0.16);
   baselinetaup_Teq120to150Integral->SetRightMargin(0.05);
   baselinetaup_Teq120to150Integral->SetTopMargin(0.05);
   baselinetaup_Teq120to150Integral->SetBottomMargin(0.13);
   baselinetaup_Teq120to150Integral->SetFrameFillStyle(0);
   baselinetaup_Teq120to150Integral->SetFrameBorderMode(0);
   baselinetaup_Teq120to150Integral->SetFrameFillStyle(0);
   baselinetaup_Teq120to150Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__115 = new TH1F("hframe__115","",1000,0,500);
   hframe__115->SetMinimum(0.1);
   hframe__115->SetMaximum(270);
   hframe__115->SetDirectory(0);
   hframe__115->SetStats(0);
   hframe__115->SetLineStyle(0);
   hframe__115->SetMarkerStyle(20);
   hframe__115->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__115->GetXaxis()->SetLabelFont(43);
   hframe__115->GetXaxis()->SetLabelOffset(0.007);
   hframe__115->GetXaxis()->SetLabelSize(27);
   hframe__115->GetXaxis()->SetTitleSize(33);
   hframe__115->GetXaxis()->SetTitleOffset(0.9);
   hframe__115->GetXaxis()->SetTitleFont(43);
   hframe__115->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__115->GetYaxis()->SetLabelFont(43);
   hframe__115->GetYaxis()->SetLabelOffset(0.007);
   hframe__115->GetYaxis()->SetLabelSize(27);
   hframe__115->GetYaxis()->SetTitleSize(33);
   hframe__115->GetYaxis()->SetTitleOffset(1.25);
   hframe__115->GetYaxis()->SetTitleFont(43);
   hframe__115->GetZaxis()->SetLabelFont(43);
   hframe__115->GetZaxis()->SetLabelOffset(0.007);
   hframe__115->GetZaxis()->SetLabelSize(27);
   hframe__115->GetZaxis()->SetTitleSize(33);
   hframe__115->GetZaxis()->SetTitleFont(43);
   hframe__115->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 763 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6","#tau p_{T}=120..150",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(1,46);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(2,131);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(3,135);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(4,114);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(5,95);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(6,60);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(7,42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(8,22);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(9,15);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(10,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(11,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(12,11);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(13,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(14,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(15,11);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(16,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(17,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(18,8);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(19,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(20,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(21,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(22,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(23,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(25,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(26,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(27,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(28,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(29,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(30,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(31,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(32,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(35,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(36,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(37,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(40,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(46,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinContent(51,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(1,6.78233);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(2,11.44552);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(3,11.61895);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(4,10.67708);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(5,9.746794);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(6,7.745967);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(7,6.480741);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(8,4.690416);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(9,3.872983);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(10,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(11,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(12,3.316625);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(13,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(14,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(15,3.316625);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(16,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(17,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(18,2.828427);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(19,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(20,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(21,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(22,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(23,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(25,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(26,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(27,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(28,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(29,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(30,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(31,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(32,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(35,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(36,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(37,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(40,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(46,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetBinError(51,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetEntries(766);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts6->Draw("HIST same");
   
   TH1F *hframe__116 = new TH1F("hframe__116","",1000,0,500);
   hframe__116->SetMinimum(0.1);
   hframe__116->SetMaximum(270);
   hframe__116->SetDirectory(0);
   hframe__116->SetStats(0);
   hframe__116->SetLineStyle(0);
   hframe__116->SetMarkerStyle(20);
   hframe__116->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__116->GetXaxis()->SetLabelFont(43);
   hframe__116->GetXaxis()->SetLabelOffset(0.007);
   hframe__116->GetXaxis()->SetLabelSize(27);
   hframe__116->GetXaxis()->SetTitleSize(33);
   hframe__116->GetXaxis()->SetTitleOffset(0.9);
   hframe__116->GetXaxis()->SetTitleFont(43);
   hframe__116->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__116->GetYaxis()->SetLabelFont(43);
   hframe__116->GetYaxis()->SetLabelOffset(0.007);
   hframe__116->GetYaxis()->SetLabelSize(27);
   hframe__116->GetYaxis()->SetTitleSize(33);
   hframe__116->GetYaxis()->SetTitleOffset(1.25);
   hframe__116->GetYaxis()->SetTitleFont(43);
   hframe__116->GetZaxis()->SetLabelFont(43);
   hframe__116->GetZaxis()->SetLabelOffset(0.007);
   hframe__116->GetZaxis()->SetLabelSize(27);
   hframe__116->GetZaxis()->SetTitleSize(33);
   hframe__116->GetZaxis()->SetTitleFont(43);
   hframe__116->Draw("sameaxis");
   baselinetaup_Teq120to150Integral->Modified();
   baselinetaup_Teq120to150Integral->cd();
   baselinetaup_Teq120to150Integral->SetSelected(baselinetaup_Teq120to150Integral);
}
