{
//=========Macro generated from canvas: baseline1Integral/
//=========  (Sun Jul 20 15:00:26 2014) by ROOT version5.32/00
   TCanvas *baseline1Integral = new TCanvas("baseline1Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baseline1Integral->SetHighLightColor(2);
   baseline1Integral->Range(-101.2658,-1.598975,531.6456,3.008526);
   baseline1Integral->SetFillColor(0);
   baseline1Integral->SetBorderMode(0);
   baseline1Integral->SetBorderSize(2);
   baseline1Integral->SetLogy();
   baseline1Integral->SetTickx(1);
   baseline1Integral->SetTicky(1);
   baseline1Integral->SetLeftMargin(0.16);
   baseline1Integral->SetRightMargin(0.05);
   baseline1Integral->SetTopMargin(0.05);
   baseline1Integral->SetBottomMargin(0.13);
   baseline1Integral->SetFrameFillStyle(0);
   baseline1Integral->SetFrameBorderMode(0);
   baseline1Integral->SetFrameFillStyle(0);
   baseline1Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__25 = new TH1F("hframe__25","",1000,0,500);
   hframe__25->SetMinimum(0.1);
   hframe__25->SetMaximum(600);
   hframe__25->SetDirectory(0);
   hframe__25->SetStats(0);
   hframe__25->SetLineStyle(0);
   hframe__25->SetMarkerStyle(20);
   hframe__25->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__25->GetXaxis()->SetLabelFont(43);
   hframe__25->GetXaxis()->SetLabelOffset(0.007);
   hframe__25->GetXaxis()->SetLabelSize(27);
   hframe__25->GetXaxis()->SetTitleSize(33);
   hframe__25->GetXaxis()->SetTitleOffset(0.9);
   hframe__25->GetXaxis()->SetTitleFont(43);
   hframe__25->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__25->GetYaxis()->SetLabelFont(43);
   hframe__25->GetYaxis()->SetLabelOffset(0.007);
   hframe__25->GetYaxis()->SetLabelSize(27);
   hframe__25->GetYaxis()->SetTitleSize(33);
   hframe__25->GetYaxis()->SetTitleOffset(1.25);
   hframe__25->GetYaxis()->SetTitleFont(43);
   hframe__25->GetZaxis()->SetLabelFont(43);
   hframe__25->GetZaxis()->SetLabelOffset(0.007);
   hframe__25->GetZaxis()->SetLabelSize(27);
   hframe__25->GetZaxis()->SetTitleSize(33);
   hframe__25->GetZaxis()->SetTitleFont(43);
   hframe__25->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 2301 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1","#tau p_{T}=50..60",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(1,68);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(2,208);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(3,290);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(4,300);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(5,266);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(6,170);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(7,118);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(8,95);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(9,62);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(10,71);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(11,78);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(12,67);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(13,70);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(14,75);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(15,50);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(16,53);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(17,42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(18,30);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(19,37);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(20,21);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(21,31);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(22,22);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(23,12);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(24,17);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(25,12);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(26,9);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(27,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(28,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(29,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(30,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(31,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(34,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(35,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(36,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(38,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(40,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(41,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinContent(45,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(1,8.246211);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(2,14.42221);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(3,17.02939);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(4,17.32051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(5,16.30951);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(6,13.0384);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(7,10.86278);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(8,9.746794);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(9,7.874008);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(10,8.42615);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(11,8.831761);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(12,8.185353);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(13,8.3666);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(14,8.660254);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(15,7.071068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(16,7.28011);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(17,6.480741);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(18,5.477226);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(19,6.082763);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(20,4.582576);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(21,5.567764);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(22,4.690416);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(23,3.464102);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(24,4.123106);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(25,3.464102);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(26,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(27,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(28,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(29,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(30,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(31,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(34,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(35,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(36,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(38,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(40,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(41,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetBinError(45,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetEntries(2301);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts1->Draw("HIST same");
   
   TH1F *hframe__26 = new TH1F("hframe__26","",1000,0,500);
   hframe__26->SetMinimum(0.1);
   hframe__26->SetMaximum(600);
   hframe__26->SetDirectory(0);
   hframe__26->SetStats(0);
   hframe__26->SetLineStyle(0);
   hframe__26->SetMarkerStyle(20);
   hframe__26->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__26->GetXaxis()->SetLabelFont(43);
   hframe__26->GetXaxis()->SetLabelOffset(0.007);
   hframe__26->GetXaxis()->SetLabelSize(27);
   hframe__26->GetXaxis()->SetTitleSize(33);
   hframe__26->GetXaxis()->SetTitleOffset(0.9);
   hframe__26->GetXaxis()->SetTitleFont(43);
   hframe__26->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__26->GetYaxis()->SetLabelFont(43);
   hframe__26->GetYaxis()->SetLabelOffset(0.007);
   hframe__26->GetYaxis()->SetLabelSize(27);
   hframe__26->GetYaxis()->SetTitleSize(33);
   hframe__26->GetYaxis()->SetTitleOffset(1.25);
   hframe__26->GetYaxis()->SetTitleFont(43);
   hframe__26->GetZaxis()->SetLabelFont(43);
   hframe__26->GetZaxis()->SetLabelOffset(0.007);
   hframe__26->GetZaxis()->SetLabelSize(27);
   hframe__26->GetZaxis()->SetTitleSize(33);
   hframe__26->GetZaxis()->SetTitleFont(43);
   hframe__26->Draw("sameaxis");
   baseline1Integral->Modified();
   baseline1Integral->cd();
   baseline1Integral->SetSelected(baseline1Integral);
}
