{
//=========Macro generated from canvas: baseline3Integral/
//=========  (Sun Jul 20 15:00:32 2014) by ROOT version5.32/00
   TCanvas *baseline3Integral = new TCanvas("baseline3Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baseline3Integral->SetHighLightColor(2);
   baseline3Integral->Range(-101.2658,-1.552163,531.6456,2.695244);
   baseline3Integral->SetFillColor(0);
   baseline3Integral->SetBorderMode(0);
   baseline3Integral->SetBorderSize(2);
   baseline3Integral->SetLogy();
   baseline3Integral->SetTickx(1);
   baseline3Integral->SetTicky(1);
   baseline3Integral->SetLeftMargin(0.16);
   baseline3Integral->SetRightMargin(0.05);
   baseline3Integral->SetTopMargin(0.05);
   baseline3Integral->SetBottomMargin(0.13);
   baseline3Integral->SetFrameFillStyle(0);
   baseline3Integral->SetFrameBorderMode(0);
   baseline3Integral->SetFrameFillStyle(0);
   baseline3Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__61 = new TH1F("hframe__61","",1000,0,500);
   hframe__61->SetMinimum(0.1);
   hframe__61->SetMaximum(304);
   hframe__61->SetDirectory(0);
   hframe__61->SetStats(0);
   hframe__61->SetLineStyle(0);
   hframe__61->SetMarkerStyle(20);
   hframe__61->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__61->GetXaxis()->SetLabelFont(43);
   hframe__61->GetXaxis()->SetLabelOffset(0.007);
   hframe__61->GetXaxis()->SetLabelSize(27);
   hframe__61->GetXaxis()->SetTitleSize(33);
   hframe__61->GetXaxis()->SetTitleOffset(0.9);
   hframe__61->GetXaxis()->SetTitleFont(43);
   hframe__61->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__61->GetYaxis()->SetLabelFont(43);
   hframe__61->GetYaxis()->SetLabelOffset(0.007);
   hframe__61->GetYaxis()->SetLabelSize(27);
   hframe__61->GetYaxis()->SetTitleSize(33);
   hframe__61->GetYaxis()->SetTitleOffset(1.25);
   hframe__61->GetYaxis()->SetTitleFont(43);
   hframe__61->GetZaxis()->SetLabelFont(43);
   hframe__61->GetZaxis()->SetLabelOffset(0.007);
   hframe__61->GetZaxis()->SetLabelSize(27);
   hframe__61->GetZaxis()->SetTitleSize(33);
   hframe__61->GetZaxis()->SetTitleFont(43);
   hframe__61->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 1098 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3","#tau p_{T}=70..80",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(1,35);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(2,120);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(3,149);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(4,152);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(5,123);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(6,92);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(7,64);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(8,31);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(9,33);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(10,30);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(11,21);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(12,19);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(13,37);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(14,27);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(15,31);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(16,15);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(17,12);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(18,24);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(19,8);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(20,15);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(21,11);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(22,12);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(23,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(24,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(25,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(26,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(27,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(28,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(29,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(30,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(31,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(32,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(34,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(35,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(37,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(40,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(51,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(1,5.91608);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(2,10.95445);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(3,12.20656);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(4,12.32883);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(5,11.09054);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(6,9.591663);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(7,8);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(8,5.567764);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(9,5.744563);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(10,5.477226);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(11,4.582576);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(12,4.358899);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(13,6.082763);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(14,5.196152);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(15,5.567764);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(16,3.872983);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(17,3.464102);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(18,4.898979);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(19,2.828427);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(20,3.872983);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(21,3.316625);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(22,3.464102);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(23,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(24,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(25,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(26,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(27,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(28,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(29,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(30,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(31,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(32,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(34,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(35,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(37,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(40,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(51,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetEntries(1100);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->Draw("HIST same");
   
   TH1F *hframe__62 = new TH1F("hframe__62","",1000,0,500);
   hframe__62->SetMinimum(0.1);
   hframe__62->SetMaximum(304);
   hframe__62->SetDirectory(0);
   hframe__62->SetStats(0);
   hframe__62->SetLineStyle(0);
   hframe__62->SetMarkerStyle(20);
   hframe__62->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__62->GetXaxis()->SetLabelFont(43);
   hframe__62->GetXaxis()->SetLabelOffset(0.007);
   hframe__62->GetXaxis()->SetLabelSize(27);
   hframe__62->GetXaxis()->SetTitleSize(33);
   hframe__62->GetXaxis()->SetTitleOffset(0.9);
   hframe__62->GetXaxis()->SetTitleFont(43);
   hframe__62->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__62->GetYaxis()->SetLabelFont(43);
   hframe__62->GetYaxis()->SetLabelOffset(0.007);
   hframe__62->GetYaxis()->SetLabelSize(27);
   hframe__62->GetYaxis()->SetTitleSize(33);
   hframe__62->GetYaxis()->SetTitleOffset(1.25);
   hframe__62->GetYaxis()->SetTitleFont(43);
   hframe__62->GetZaxis()->SetLabelFont(43);
   hframe__62->GetZaxis()->SetLabelOffset(0.007);
   hframe__62->GetZaxis()->SetLabelSize(27);
   hframe__62->GetZaxis()->SetTitleSize(33);
   hframe__62->GetZaxis()->SetTitleFont(43);
   hframe__62->Draw("sameaxis");
   baseline3Integral->Modified();
   baseline3Integral->cd();
   baseline3Integral->SetSelected(baseline3Integral);
}
