{
//=========Macro generated from canvas: baselineEWKFakeTaustaup_Teq60to70Integral/
//=========  (Wed Aug 13 15:49:52 2014) by ROOT version5.32/00
   TCanvas *baselineEWKFakeTaustaup_Teq60to70Integral = new TCanvas("baselineEWKFakeTaustaup_Teq60to70Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetHighLightColor(2);
   baselineEWKFakeTaustaup_Teq60to70Integral->Range(-101.2658,-1.172892,531.6456,0.1570456);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetFillColor(0);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetBorderMode(0);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetBorderSize(2);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetLogy();
   baselineEWKFakeTaustaup_Teq60to70Integral->SetTickx(1);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetTicky(1);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetLeftMargin(0.16);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetRightMargin(0.05);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetTopMargin(0.05);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetBottomMargin(0.13);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetFrameBorderMode(0);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselineEWKFakeTaustaup_Teq60to70Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__47 = new TH1F("hframe__47","",1000,0,500);
   hframe__47->SetMinimum(0.1);
   hframe__47->SetMaximum(1.231824);
   hframe__47->SetDirectory(0);
   hframe__47->SetStats(0);
   hframe__47->SetLineStyle(0);
   hframe__47->SetMarkerStyle(20);
   hframe__47->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__47->GetXaxis()->SetLabelFont(43);
   hframe__47->GetXaxis()->SetLabelOffset(0.007);
   hframe__47->GetXaxis()->SetLabelSize(27);
   hframe__47->GetXaxis()->SetTitleSize(33);
   hframe__47->GetXaxis()->SetTitleOffset(0.9);
   hframe__47->GetXaxis()->SetTitleFont(43);
   hframe__47->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__47->GetYaxis()->SetLabelFont(43);
   hframe__47->GetYaxis()->SetLabelOffset(0.007);
   hframe__47->GetYaxis()->SetLabelSize(27);
   hframe__47->GetYaxis()->SetTitleSize(33);
   hframe__47->GetYaxis()->SetTitleOffset(1.25);
   hframe__47->GetYaxis()->SetTitleFont(43);
   hframe__47->GetZaxis()->SetLabelFont(43);
   hframe__47->GetZaxis()->SetLabelOffset(0.007);
   hframe__47->GetZaxis()->SetLabelSize(27);
   hframe__47->GetZaxis()->SetTitleSize(33);
   hframe__47->GetZaxis()->SetTitleFont(43);
   hframe__47->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 3 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2","#tau p_{T}=60..70",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(3,0.001190992);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(4,0.09598724);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(5,0.06162917);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(6,0.3573494);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(8,0.3311515);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(9,0.1762742);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(10,0.2620701);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(11,0.06870976);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(12,0.6159121);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(13,0.07973243);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(14,0.3713728);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(15,0.09794991);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(17,0.1202765);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(21,0.01449369);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(23,0.2440402);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(26,0.08525996);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(3,0.001190992);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(4,0.081552);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(5,0.06162917);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(6,0.197853);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(8,0.1968902);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(9,0.1246479);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(10,0.1857253);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(11,0.06606193);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(12,0.360559);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(13,0.07973243);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(14,0.2770207);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(15,0.09794991);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(17,0.1063456);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(21,0.01449369);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(23,0.1863945);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(26,0.08525996);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetEntries(34);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus2->Draw("HIST same");
   
   TH1F *hframe__48 = new TH1F("hframe__48","",1000,0,500);
   hframe__48->SetMinimum(0.1);
   hframe__48->SetMaximum(1.231824);
   hframe__48->SetDirectory(0);
   hframe__48->SetStats(0);
   hframe__48->SetLineStyle(0);
   hframe__48->SetMarkerStyle(20);
   hframe__48->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__48->GetXaxis()->SetLabelFont(43);
   hframe__48->GetXaxis()->SetLabelOffset(0.007);
   hframe__48->GetXaxis()->SetLabelSize(27);
   hframe__48->GetXaxis()->SetTitleSize(33);
   hframe__48->GetXaxis()->SetTitleOffset(0.9);
   hframe__48->GetXaxis()->SetTitleFont(43);
   hframe__48->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__48->GetYaxis()->SetLabelFont(43);
   hframe__48->GetYaxis()->SetLabelOffset(0.007);
   hframe__48->GetYaxis()->SetLabelSize(27);
   hframe__48->GetYaxis()->SetTitleSize(33);
   hframe__48->GetYaxis()->SetTitleOffset(1.25);
   hframe__48->GetYaxis()->SetTitleFont(43);
   hframe__48->GetZaxis()->SetLabelFont(43);
   hframe__48->GetZaxis()->SetLabelOffset(0.007);
   hframe__48->GetZaxis()->SetLabelSize(27);
   hframe__48->GetZaxis()->SetTitleSize(33);
   hframe__48->GetZaxis()->SetTitleFont(43);
   hframe__48->Draw("sameaxis");
   baselineEWKFakeTaustaup_Teq60to70Integral->Modified();
   baselineEWKFakeTaustaup_Teq60to70Integral->cd();
   baselineEWKFakeTaustaup_Teq60to70Integral->SetSelected(baselineEWKFakeTaustaup_Teq60to70Integral);
}
