{
//=========Macro generated from canvas: baselineEWKGenuineTaustaup_Teq80to100Integral/
//=========  (Wed Aug 13 15:49:57 2014) by ROOT version5.32/00
   TCanvas *baselineEWKGenuineTaustaup_Teq80to100Integral = new TCanvas("baselineEWKGenuineTaustaup_Teq80to100Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetHighLightColor(2);
   baselineEWKGenuineTaustaup_Teq80to100Integral->Range(-101.2658,-1.243765,531.6456,0.6313534);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetFillColor(0);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetBorderMode(0);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetBorderSize(2);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetLogy();
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetTickx(1);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetTicky(1);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetLeftMargin(0.16);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetRightMargin(0.05);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetTopMargin(0.05);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetBottomMargin(0.13);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetFrameBorderMode(0);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__81 = new TH1F("hframe__81","",1000,0,500);
   hframe__81->SetMinimum(0.1);
   hframe__81->SetMaximum(3.44824);
   hframe__81->SetDirectory(0);
   hframe__81->SetStats(0);
   hframe__81->SetLineStyle(0);
   hframe__81->SetMarkerStyle(20);
   hframe__81->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__81->GetXaxis()->SetLabelFont(43);
   hframe__81->GetXaxis()->SetLabelOffset(0.007);
   hframe__81->GetXaxis()->SetLabelSize(27);
   hframe__81->GetXaxis()->SetTitleSize(33);
   hframe__81->GetXaxis()->SetTitleOffset(0.9);
   hframe__81->GetXaxis()->SetTitleFont(43);
   hframe__81->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__81->GetYaxis()->SetLabelFont(43);
   hframe__81->GetYaxis()->SetLabelOffset(0.007);
   hframe__81->GetYaxis()->SetLabelSize(27);
   hframe__81->GetYaxis()->SetTitleSize(33);
   hframe__81->GetYaxis()->SetTitleOffset(1.25);
   hframe__81->GetYaxis()->SetTitleFont(43);
   hframe__81->GetZaxis()->SetLabelFont(43);
   hframe__81->GetZaxis()->SetLabelOffset(0.007);
   hframe__81->GetZaxis()->SetLabelSize(27);
   hframe__81->GetZaxis()->SetTitleSize(33);
   hframe__81->GetZaxis()->SetTitleFont(43);
   hframe__81->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 17 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4","#tau p_{T}=80..100",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(1,0.004057712);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(2,0.1041449);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(3,0.8604861);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(4,0.7583656);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(5,1.72412);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(6,0.7114869);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(7,0.8257059);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(8,1.09041);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(9,0.7937672);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(10,0.7958291);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(11,0.7289916);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(12,1.512757);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(13,1.246925);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(14,0.7588536);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(15,0.6989908);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(16,0.5263858);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(17,0.5038279);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(18,0.7030811);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(19,0.3284921);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(20,0.4997261);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(21,0.2602106);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(22,0.3677524);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(23,0.4363529);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(24,0.05956192);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(25,0.1466495);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(26,0.430498);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(28,0.1746654);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(29,0.08663577);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(30,0.001867212);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(33,0.08582138);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(51,0.08528411);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(1,0.004057712);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(2,0.09916821);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(3,0.4928293);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(4,0.5012645);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(5,1.082721);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(6,0.2858244);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(7,0.399537);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(8,0.5152614);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(9,0.526466);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(10,0.2756591);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(11,0.277444);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(12,0.5907317);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(13,0.570678);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(14,0.3071934);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(15,0.2492068);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(16,0.2512237);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(17,0.2546334);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(18,0.2690075);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(19,0.19732);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(20,0.2146689);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(21,0.1521018);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(22,0.1708084);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(23,0.1846815);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(24,0.04835925);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(25,0.1044746);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(26,0.3199488);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(28,0.1746654);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(29,0.08663576);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(30,0.001867212);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(33,0.08582139);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(51,0.0852841);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetEntries(176);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->Draw("HIST same");
   
   TH1F *hframe__82 = new TH1F("hframe__82","",1000,0,500);
   hframe__82->SetMinimum(0.1);
   hframe__82->SetMaximum(3.44824);
   hframe__82->SetDirectory(0);
   hframe__82->SetStats(0);
   hframe__82->SetLineStyle(0);
   hframe__82->SetMarkerStyle(20);
   hframe__82->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__82->GetXaxis()->SetLabelFont(43);
   hframe__82->GetXaxis()->SetLabelOffset(0.007);
   hframe__82->GetXaxis()->SetLabelSize(27);
   hframe__82->GetXaxis()->SetTitleSize(33);
   hframe__82->GetXaxis()->SetTitleOffset(0.9);
   hframe__82->GetXaxis()->SetTitleFont(43);
   hframe__82->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__82->GetYaxis()->SetLabelFont(43);
   hframe__82->GetYaxis()->SetLabelOffset(0.007);
   hframe__82->GetYaxis()->SetLabelSize(27);
   hframe__82->GetYaxis()->SetTitleSize(33);
   hframe__82->GetYaxis()->SetTitleOffset(1.25);
   hframe__82->GetYaxis()->SetTitleFont(43);
   hframe__82->GetZaxis()->SetLabelFont(43);
   hframe__82->GetZaxis()->SetLabelOffset(0.007);
   hframe__82->GetZaxis()->SetLabelSize(27);
   hframe__82->GetZaxis()->SetTitleSize(33);
   hframe__82->GetZaxis()->SetTitleFont(43);
   hframe__82->Draw("sameaxis");
   baselineEWKGenuineTaustaup_Teq80to100Integral->Modified();
   baselineEWKGenuineTaustaup_Teq80to100Integral->cd();
   baselineEWKGenuineTaustaup_Teq80to100Integral->SetSelected(baselineEWKGenuineTaustaup_Teq80to100Integral);
}
