{
//=========Macro generated from canvas: baselineEWKFakeTaustaup_Teq50to60Integral/
//=========  (Fri Aug  1 09:24:32 2014) by ROOT version5.32/00
   TCanvas *baselineEWKFakeTaustaup_Teq50to60Integral = new TCanvas("baselineEWKFakeTaustaup_Teq50to60Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetHighLightColor(2);
   baselineEWKFakeTaustaup_Teq50to60Integral->Range(-101.2658,-1.282501,531.6456,0.8905835);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetFillColor(0);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetBorderMode(0);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetBorderSize(2);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetLogy();
   baselineEWKFakeTaustaup_Teq50to60Integral->SetTickx(1);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetTicky(1);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetLeftMargin(0.16);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetRightMargin(0.05);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetTopMargin(0.05);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetBottomMargin(0.13);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetFrameFillStyle(0);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetFrameBorderMode(0);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetFrameFillStyle(0);
   baselineEWKFakeTaustaup_Teq50to60Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__29 = new TH1F("hframe__29","",1000,0,500);
   hframe__29->SetMinimum(0.1);
   hframe__29->SetMaximum(6.052423);
   hframe__29->SetDirectory(0);
   hframe__29->SetStats(0);
   hframe__29->SetLineStyle(0);
   hframe__29->SetMarkerStyle(20);
   hframe__29->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__29->GetXaxis()->SetLabelFont(43);
   hframe__29->GetXaxis()->SetLabelOffset(0.007);
   hframe__29->GetXaxis()->SetLabelSize(27);
   hframe__29->GetXaxis()->SetTitleSize(33);
   hframe__29->GetXaxis()->SetTitleOffset(0.9);
   hframe__29->GetXaxis()->SetTitleFont(43);
   hframe__29->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__29->GetYaxis()->SetLabelFont(43);
   hframe__29->GetYaxis()->SetLabelOffset(0.007);
   hframe__29->GetYaxis()->SetLabelSize(27);
   hframe__29->GetYaxis()->SetTitleSize(33);
   hframe__29->GetYaxis()->SetTitleOffset(1.25);
   hframe__29->GetYaxis()->SetTitleFont(43);
   hframe__29->GetZaxis()->SetLabelFont(43);
   hframe__29->GetZaxis()->SetLabelOffset(0.007);
   hframe__29->GetZaxis()->SetLabelSize(27);
   hframe__29->GetZaxis()->SetTitleSize(33);
   hframe__29->GetZaxis()->SetTitleFont(43);
   hframe__29->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 11 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1","#tau p_{T}=50..60",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(1,1.767343);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(3,0.05395816);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(4,0.3464513);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(5,0.354224);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(6,0.05486226);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(7,0.03329706);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(8,0.8844997);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(9,0.04678678);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(10,1.111302);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(11,0.5890825);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(13,1.217386);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(14,1.230339);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(16,0.3434023);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(18,0.05801677);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(21,3.026212);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(27,0.03510796);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(1,1.767343);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(3,0.04000179);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(4,0.2392378);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(5,0.2986326);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(6,0.05486226);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(7,0.03329706);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(8,0.7293726);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(9,0.03433033);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(10,1.111302);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(11,0.5790829);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(13,1.119975);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(14,1.113836);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(16,0.3434023);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(18,0.05801677);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(21,3.026212);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(27,0.03510796);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetEntries(27);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus1->Draw("HIST same");
   
   TH1F *hframe__30 = new TH1F("hframe__30","",1000,0,500);
   hframe__30->SetMinimum(0.1);
   hframe__30->SetMaximum(6.052423);
   hframe__30->SetDirectory(0);
   hframe__30->SetStats(0);
   hframe__30->SetLineStyle(0);
   hframe__30->SetMarkerStyle(20);
   hframe__30->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__30->GetXaxis()->SetLabelFont(43);
   hframe__30->GetXaxis()->SetLabelOffset(0.007);
   hframe__30->GetXaxis()->SetLabelSize(27);
   hframe__30->GetXaxis()->SetTitleSize(33);
   hframe__30->GetXaxis()->SetTitleOffset(0.9);
   hframe__30->GetXaxis()->SetTitleFont(43);
   hframe__30->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__30->GetYaxis()->SetLabelFont(43);
   hframe__30->GetYaxis()->SetLabelOffset(0.007);
   hframe__30->GetYaxis()->SetLabelSize(27);
   hframe__30->GetYaxis()->SetTitleSize(33);
   hframe__30->GetYaxis()->SetTitleOffset(1.25);
   hframe__30->GetYaxis()->SetTitleFont(43);
   hframe__30->GetZaxis()->SetLabelFont(43);
   hframe__30->GetZaxis()->SetLabelOffset(0.007);
   hframe__30->GetZaxis()->SetLabelSize(27);
   hframe__30->GetZaxis()->SetTitleSize(33);
   hframe__30->GetZaxis()->SetTitleFont(43);
   hframe__30->Draw("sameaxis");
   baselineEWKFakeTaustaup_Teq50to60Integral->Modified();
   baselineEWKFakeTaustaup_Teq50to60Integral->cd();
   baselineEWKFakeTaustaup_Teq50to60Integral->SetSelected(baselineEWKFakeTaustaup_Teq50to60Integral);
}
