{
//=========Macro generated from canvas: baselinetaup_Teq60to70Integral/
//=========  (Fri Aug  1 09:24:34 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Teq60to70Integral = new TCanvas("baselinetaup_Teq60to70Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselinetaup_Teq60to70Integral->SetHighLightColor(2);
   baselinetaup_Teq60to70Integral->Range(-101.2658,-1.568248,531.6456,2.802888);
   baselinetaup_Teq60to70Integral->SetFillColor(0);
   baselinetaup_Teq60to70Integral->SetBorderMode(0);
   baselinetaup_Teq60to70Integral->SetBorderSize(2);
   baselinetaup_Teq60to70Integral->SetLogy();
   baselinetaup_Teq60to70Integral->SetTickx(1);
   baselinetaup_Teq60to70Integral->SetTicky(1);
   baselinetaup_Teq60to70Integral->SetLeftMargin(0.16);
   baselinetaup_Teq60to70Integral->SetRightMargin(0.05);
   baselinetaup_Teq60to70Integral->SetTopMargin(0.05);
   baselinetaup_Teq60to70Integral->SetBottomMargin(0.13);
   baselinetaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselinetaup_Teq60to70Integral->SetFrameBorderMode(0);
   baselinetaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselinetaup_Teq60to70Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__43 = new TH1F("hframe__43","",1000,0,500);
   hframe__43->SetMinimum(0.1);
   hframe__43->SetMaximum(384);
   hframe__43->SetDirectory(0);
   hframe__43->SetStats(0);
   hframe__43->SetLineStyle(0);
   hframe__43->SetMarkerStyle(20);
   hframe__43->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__43->GetXaxis()->SetLabelFont(43);
   hframe__43->GetXaxis()->SetLabelOffset(0.007);
   hframe__43->GetXaxis()->SetLabelSize(27);
   hframe__43->GetXaxis()->SetTitleSize(33);
   hframe__43->GetXaxis()->SetTitleOffset(0.9);
   hframe__43->GetXaxis()->SetTitleFont(43);
   hframe__43->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__43->GetYaxis()->SetLabelFont(43);
   hframe__43->GetYaxis()->SetLabelOffset(0.007);
   hframe__43->GetYaxis()->SetLabelSize(27);
   hframe__43->GetYaxis()->SetTitleSize(33);
   hframe__43->GetYaxis()->SetTitleOffset(1.25);
   hframe__43->GetYaxis()->SetTitleFont(43);
   hframe__43->GetZaxis()->SetLabelFont(43);
   hframe__43->GetZaxis()->SetLabelOffset(0.007);
   hframe__43->GetZaxis()->SetLabelSize(27);
   hframe__43->GetZaxis()->SetTitleSize(33);
   hframe__43->GetZaxis()->SetTitleFont(43);
   hframe__43->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 1400 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2","#tau p_{T}=60..70",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(1,55);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(2,142);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(3,183);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(4,192);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(5,151);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(6,110);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(7,65);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(8,45);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(9,40);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(10,43);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(11,38);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(12,36);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(13,34);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(14,32);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(15,36);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(16,39);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(17,28);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(18,27);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(19,18);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(20,15);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(21,19);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(22,10);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(23,8);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(24,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(25,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(26,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(27,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(28,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(29,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(30,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(31,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(32,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(33,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(34,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(38,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(41,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(1,7.416198);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(2,11.91638);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(3,13.52775);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(4,13.85641);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(5,12.28821);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(6,10.48809);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(7,8.062258);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(8,6.708204);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(9,6.324555);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(10,6.557439);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(11,6.164414);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(12,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(13,5.830952);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(14,5.656854);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(15,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(16,6.244998);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(17,5.291503);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(18,5.196152);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(19,4.242641);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(20,3.872983);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(21,4.358899);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(22,3.162278);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(23,2.828427);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(24,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(25,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(26,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(27,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(28,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(29,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(30,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(31,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(32,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(33,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(34,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(38,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(41,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetEntries(1400);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->Draw("HIST same");
   
   TH1F *hframe__44 = new TH1F("hframe__44","",1000,0,500);
   hframe__44->SetMinimum(0.1);
   hframe__44->SetMaximum(384);
   hframe__44->SetDirectory(0);
   hframe__44->SetStats(0);
   hframe__44->SetLineStyle(0);
   hframe__44->SetMarkerStyle(20);
   hframe__44->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__44->GetXaxis()->SetLabelFont(43);
   hframe__44->GetXaxis()->SetLabelOffset(0.007);
   hframe__44->GetXaxis()->SetLabelSize(27);
   hframe__44->GetXaxis()->SetTitleSize(33);
   hframe__44->GetXaxis()->SetTitleOffset(0.9);
   hframe__44->GetXaxis()->SetTitleFont(43);
   hframe__44->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__44->GetYaxis()->SetLabelFont(43);
   hframe__44->GetYaxis()->SetLabelOffset(0.007);
   hframe__44->GetYaxis()->SetLabelSize(27);
   hframe__44->GetYaxis()->SetTitleSize(33);
   hframe__44->GetYaxis()->SetTitleOffset(1.25);
   hframe__44->GetYaxis()->SetTitleFont(43);
   hframe__44->GetZaxis()->SetLabelFont(43);
   hframe__44->GetZaxis()->SetLabelOffset(0.007);
   hframe__44->GetZaxis()->SetLabelSize(27);
   hframe__44->GetZaxis()->SetTitleSize(33);
   hframe__44->GetZaxis()->SetTitleFont(43);
   hframe__44->Draw("sameaxis");
   baselinetaup_Teq60to70Integral->Modified();
   baselinetaup_Teq60to70Integral->cd();
   baselinetaup_Teq60to70Integral->SetSelected(baselinetaup_Teq60to70Integral);
}
