{
//=========Macro generated from canvas: baselinetaup_Tlt50Integral/
//=========  (Fri Aug  1 09:24:29 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Tlt50Integral = new TCanvas("baselinetaup_Tlt50Integral", "",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   baselinetaup_Tlt50Integral->SetHighLightColor(2);
   baselinetaup_Tlt50Integral->Range(-101.2658,-1.618091,531.6456,3.136452);
   baselinetaup_Tlt50Integral->SetFillColor(0);
   baselinetaup_Tlt50Integral->SetBorderMode(0);
   baselinetaup_Tlt50Integral->SetBorderSize(2);
   baselinetaup_Tlt50Integral->SetLogy();
   baselinetaup_Tlt50Integral->SetTickx(1);
   baselinetaup_Tlt50Integral->SetTicky(1);
   baselinetaup_Tlt50Integral->SetLeftMargin(0.16);
   baselinetaup_Tlt50Integral->SetRightMargin(0.05);
   baselinetaup_Tlt50Integral->SetTopMargin(0.05);
   baselinetaup_Tlt50Integral->SetBottomMargin(0.13);
   baselinetaup_Tlt50Integral->SetFrameFillStyle(0);
   baselinetaup_Tlt50Integral->SetFrameBorderMode(0);
   baselinetaup_Tlt50Integral->SetFrameFillStyle(0);
   baselinetaup_Tlt50Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__7 = new TH1F("hframe__7","",1000,0,500);
   hframe__7->SetMinimum(0.1);
   hframe__7->SetMaximum(792);
   hframe__7->SetDirectory(0);
   hframe__7->SetStats(0);
   hframe__7->SetLineStyle(0);
   hframe__7->SetMarkerStyle(20);
   hframe__7->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__7->GetXaxis()->SetLabelFont(43);
   hframe__7->GetXaxis()->SetLabelOffset(0.007);
   hframe__7->GetXaxis()->SetLabelSize(27);
   hframe__7->GetXaxis()->SetTitleSize(33);
   hframe__7->GetXaxis()->SetTitleOffset(0.9);
   hframe__7->GetXaxis()->SetTitleFont(43);
   hframe__7->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__7->GetYaxis()->SetLabelFont(43);
   hframe__7->GetYaxis()->SetLabelOffset(0.007);
   hframe__7->GetYaxis()->SetLabelSize(27);
   hframe__7->GetYaxis()->SetTitleSize(33);
   hframe__7->GetYaxis()->SetTitleOffset(1.25);
   hframe__7->GetYaxis()->SetTitleFont(43);
   hframe__7->GetZaxis()->SetLabelFont(43);
   hframe__7->GetZaxis()->SetLabelOffset(0.007);
   hframe__7->GetZaxis()->SetLabelSize(27);
   hframe__7->GetZaxis()->SetTitleSize(33);
   hframe__7->GetZaxis()->SetTitleFont(43);
   hframe__7->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 3168 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0","#tau p_{T}<50",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(1,89);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(2,236);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(3,376);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(4,396);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(5,360);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(6,266);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(7,215);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(8,151);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(9,95);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(10,98);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(11,94);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(12,98);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(13,102);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(14,84);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(15,80);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(16,71);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(17,60);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(18,48);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(19,45);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(20,40);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(21,28);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(22,21);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(23,19);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(24,17);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(25,14);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(26,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(27,11);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(28,10);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(29,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(30,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(31,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(32,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(33,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(34,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(35,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(37,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(38,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(44,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(47,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(48,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(1,9.433981);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(2,15.36229);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(3,19.39072);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(4,19.89975);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(5,18.97367);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(6,16.30951);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(7,14.66288);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(8,12.28821);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(9,9.746794);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(10,9.899495);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(11,9.69536);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(12,9.899495);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(13,10.0995);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(14,9.165151);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(15,8.944272);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(16,8.42615);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(17,7.745967);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(18,6.928203);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(19,6.708204);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(20,6.324555);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(21,5.291503);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(22,4.582576);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(23,4.358899);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(24,4.123106);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(25,3.741657);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(26,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(27,3.316625);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(28,3.162278);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(29,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(30,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(31,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(32,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(33,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(34,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(35,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(37,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(38,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(44,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(47,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(48,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetEntries(3168);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->Draw("HIST same");
   
   TH1F *hframe__8 = new TH1F("hframe__8","",1000,0,500);
   hframe__8->SetMinimum(0.1);
   hframe__8->SetMaximum(792);
   hframe__8->SetDirectory(0);
   hframe__8->SetStats(0);
   hframe__8->SetLineStyle(0);
   hframe__8->SetMarkerStyle(20);
   hframe__8->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__8->GetXaxis()->SetLabelFont(43);
   hframe__8->GetXaxis()->SetLabelOffset(0.007);
   hframe__8->GetXaxis()->SetLabelSize(27);
   hframe__8->GetXaxis()->SetTitleSize(33);
   hframe__8->GetXaxis()->SetTitleOffset(0.9);
   hframe__8->GetXaxis()->SetTitleFont(43);
   hframe__8->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__8->GetYaxis()->SetLabelFont(43);
   hframe__8->GetYaxis()->SetLabelOffset(0.007);
   hframe__8->GetYaxis()->SetLabelSize(27);
   hframe__8->GetYaxis()->SetTitleSize(33);
   hframe__8->GetYaxis()->SetTitleOffset(1.25);
   hframe__8->GetYaxis()->SetTitleFont(43);
   hframe__8->GetZaxis()->SetLabelFont(43);
   hframe__8->GetZaxis()->SetLabelOffset(0.007);
   hframe__8->GetZaxis()->SetLabelSize(27);
   hframe__8->GetZaxis()->SetTitleSize(33);
   hframe__8->GetZaxis()->SetTitleFont(43);
   hframe__8->Draw("sameaxis");
   baselinetaup_Tlt50Integral->Modified();
   baselinetaup_Tlt50Integral->cd();
   baselinetaup_Tlt50Integral->SetSelected(baselinetaup_Tlt50Integral);
}
