{
//=========Macro generated from canvas: baselineEWKGenuineTaustaup_Tgt120Integral/
//=========  (Wed Aug 13 15:50:02 2014) by ROOT version5.32/00
   TCanvas *baselineEWKGenuineTaustaup_Tgt120Integral = new TCanvas("baselineEWKGenuineTaustaup_Tgt120Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetHighLightColor(2);
   baselineEWKGenuineTaustaup_Tgt120Integral->Range(-101.2658,-1.221695,531.6456,0.4836535);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetFillColor(0);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetBorderMode(0);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetBorderSize(2);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetLogy();
   baselineEWKGenuineTaustaup_Tgt120Integral->SetTickx(1);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetTicky(1);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetLeftMargin(0.16);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetRightMargin(0.05);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetTopMargin(0.05);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetBottomMargin(0.13);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetFrameBorderMode(0);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Tgt120Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__117 = new TH1F("hframe__117","",1000,0,500);
   hframe__117->SetMinimum(0.1);
   hframe__117->SetMaximum(2.502569);
   hframe__117->SetDirectory(0);
   hframe__117->SetStats(0);
   hframe__117->SetLineStyle(0);
   hframe__117->SetMarkerStyle(20);
   hframe__117->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__117->GetXaxis()->SetLabelFont(43);
   hframe__117->GetXaxis()->SetLabelOffset(0.007);
   hframe__117->GetXaxis()->SetLabelSize(27);
   hframe__117->GetXaxis()->SetTitleSize(33);
   hframe__117->GetXaxis()->SetTitleOffset(0.9);
   hframe__117->GetXaxis()->SetTitleFont(43);
   hframe__117->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__117->GetYaxis()->SetLabelFont(43);
   hframe__117->GetYaxis()->SetLabelOffset(0.007);
   hframe__117->GetYaxis()->SetLabelSize(27);
   hframe__117->GetYaxis()->SetTitleSize(33);
   hframe__117->GetYaxis()->SetTitleOffset(1.25);
   hframe__117->GetYaxis()->SetTitleFont(43);
   hframe__117->GetZaxis()->SetLabelFont(43);
   hframe__117->GetZaxis()->SetLabelOffset(0.007);
   hframe__117->GetZaxis()->SetLabelSize(27);
   hframe__117->GetZaxis()->SetTitleSize(33);
   hframe__117->GetZaxis()->SetTitleFont(43);
   hframe__117->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 9 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6","#tau p_{T}>120",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(1,0.1024391);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(2,0.5643613);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(3,0.6173959);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(4,0.4409232);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(5,0.5649316);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(6,0.821048);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(7,0.7686582);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(8,0.06579214);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(9,1.174185);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(10,0.2108635);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(11,0.4326754);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(12,0.06435188);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(13,0.3433804);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(14,0.3292259);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(15,1.251284);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(16,0.6702092);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(18,0.1569391);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(19,0.2007295);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(21,0.186192);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(22,0.04446834);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(23,0.1075673);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(24,0.005022026);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(26,0.03489466);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(29,0.1342564);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(30,0.02333222);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(33,0.005219995);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(47,0.08097113);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(1,0.1024391);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(2,0.4696525);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(3,0.4653088);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(4,0.2329972);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(5,0.4595201);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(6,0.4866697);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(7,0.4608291);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(8,0.05831942);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(9,0.7659398);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(10,0.1545826);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(11,0.2138743);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(12,0.06435187);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(13,0.1960413);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(14,0.1631987);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(15,0.5584519);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(16,0.3066526);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(18,0.1110196);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(19,0.1201913);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(21,0.126066);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(22,0.04446834);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(23,0.1075672);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(24,0.005022026);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(26,0.03489465);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(29,0.1058015);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(30,0.02333222);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(33,0.005219995);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(47,0.08097113);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetEntries(101);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->Draw("HIST same");
   
   TH1F *hframe__118 = new TH1F("hframe__118","",1000,0,500);
   hframe__118->SetMinimum(0.1);
   hframe__118->SetMaximum(2.502569);
   hframe__118->SetDirectory(0);
   hframe__118->SetStats(0);
   hframe__118->SetLineStyle(0);
   hframe__118->SetMarkerStyle(20);
   hframe__118->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__118->GetXaxis()->SetLabelFont(43);
   hframe__118->GetXaxis()->SetLabelOffset(0.007);
   hframe__118->GetXaxis()->SetLabelSize(27);
   hframe__118->GetXaxis()->SetTitleSize(33);
   hframe__118->GetXaxis()->SetTitleOffset(0.9);
   hframe__118->GetXaxis()->SetTitleFont(43);
   hframe__118->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__118->GetYaxis()->SetLabelFont(43);
   hframe__118->GetYaxis()->SetLabelOffset(0.007);
   hframe__118->GetYaxis()->SetLabelSize(27);
   hframe__118->GetYaxis()->SetTitleSize(33);
   hframe__118->GetYaxis()->SetTitleOffset(1.25);
   hframe__118->GetYaxis()->SetTitleFont(43);
   hframe__118->GetZaxis()->SetLabelFont(43);
   hframe__118->GetZaxis()->SetLabelOffset(0.007);
   hframe__118->GetZaxis()->SetLabelSize(27);
   hframe__118->GetZaxis()->SetTitleSize(33);
   hframe__118->GetZaxis()->SetTitleFont(43);
   hframe__118->Draw("sameaxis");
   baselineEWKGenuineTaustaup_Tgt120Integral->Modified();
   baselineEWKGenuineTaustaup_Tgt120Integral->cd();
   baselineEWKGenuineTaustaup_Tgt120Integral->SetSelected(baselineEWKGenuineTaustaup_Tgt120Integral);
}
