{
//=========Macro generated from canvas: baselineEWKFakeTaustaup_Teq70to80Integral/
//=========  (Fri Aug  1 09:24:36 2014) by ROOT version5.32/00
   TCanvas *baselineEWKFakeTaustaup_Teq70to80Integral = new TCanvas("baselineEWKFakeTaustaup_Teq70to80Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetHighLightColor(2);
   baselineEWKFakeTaustaup_Teq70to80Integral->Range(-101.2658,-1.266706,531.6456,0.7848773);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetFillColor(0);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetBorderMode(0);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetBorderSize(2);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetLogy();
   baselineEWKFakeTaustaup_Teq70to80Integral->SetTickx(1);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetTicky(1);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetLeftMargin(0.16);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetRightMargin(0.05);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetTopMargin(0.05);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetBottomMargin(0.13);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetFrameFillStyle(0);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetFrameBorderMode(0);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetFrameFillStyle(0);
   baselineEWKFakeTaustaup_Teq70to80Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__65 = new TH1F("hframe__65","",1000,0,500);
   hframe__65->SetMinimum(0.1);
   hframe__65->SetMaximum(4.811695);
   hframe__65->SetDirectory(0);
   hframe__65->SetStats(0);
   hframe__65->SetLineStyle(0);
   hframe__65->SetMarkerStyle(20);
   hframe__65->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__65->GetXaxis()->SetLabelFont(43);
   hframe__65->GetXaxis()->SetLabelOffset(0.007);
   hframe__65->GetXaxis()->SetLabelSize(27);
   hframe__65->GetXaxis()->SetTitleSize(33);
   hframe__65->GetXaxis()->SetTitleOffset(0.9);
   hframe__65->GetXaxis()->SetTitleFont(43);
   hframe__65->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__65->GetYaxis()->SetLabelFont(43);
   hframe__65->GetYaxis()->SetLabelOffset(0.007);
   hframe__65->GetYaxis()->SetLabelSize(27);
   hframe__65->GetYaxis()->SetTitleSize(33);
   hframe__65->GetYaxis()->SetTitleOffset(1.25);
   hframe__65->GetYaxis()->SetTitleFont(43);
   hframe__65->GetZaxis()->SetLabelFont(43);
   hframe__65->GetZaxis()->SetLabelOffset(0.007);
   hframe__65->GetZaxis()->SetLabelSize(27);
   hframe__65->GetZaxis()->SetTitleSize(33);
   hframe__65->GetZaxis()->SetTitleFont(43);
   hframe__65->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 7 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3","#tau p_{T}=70..80",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(6,0.06430641);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(7,0.7471305);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(8,2.405848);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(9,0.5830564);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(10,2.234797);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(12,0.7738086);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(13,0.215972);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(14,0.001352659);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(17,0.1449805);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinContent(18,0.2791311);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(6,0.0643064);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(7,0.7275141);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(8,1.871827);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(9,0.5830564);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(10,1.501935);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(12,0.7738086);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(13,0.215972);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(14,0.001352659);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(17,0.1449805);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetBinError(18,0.2791311);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetEntries(14);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTaus3->Draw("HIST same");
   
   TH1F *hframe__66 = new TH1F("hframe__66","",1000,0,500);
   hframe__66->SetMinimum(0.1);
   hframe__66->SetMaximum(4.811695);
   hframe__66->SetDirectory(0);
   hframe__66->SetStats(0);
   hframe__66->SetLineStyle(0);
   hframe__66->SetMarkerStyle(20);
   hframe__66->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__66->GetXaxis()->SetLabelFont(43);
   hframe__66->GetXaxis()->SetLabelOffset(0.007);
   hframe__66->GetXaxis()->SetLabelSize(27);
   hframe__66->GetXaxis()->SetTitleSize(33);
   hframe__66->GetXaxis()->SetTitleOffset(0.9);
   hframe__66->GetXaxis()->SetTitleFont(43);
   hframe__66->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__66->GetYaxis()->SetLabelFont(43);
   hframe__66->GetYaxis()->SetLabelOffset(0.007);
   hframe__66->GetYaxis()->SetLabelSize(27);
   hframe__66->GetYaxis()->SetTitleSize(33);
   hframe__66->GetYaxis()->SetTitleOffset(1.25);
   hframe__66->GetYaxis()->SetTitleFont(43);
   hframe__66->GetZaxis()->SetLabelFont(43);
   hframe__66->GetZaxis()->SetLabelOffset(0.007);
   hframe__66->GetZaxis()->SetLabelSize(27);
   hframe__66->GetZaxis()->SetTitleSize(33);
   hframe__66->GetZaxis()->SetTitleFont(43);
   hframe__66->Draw("sameaxis");
   baselineEWKFakeTaustaup_Teq70to80Integral->Modified();
   baselineEWKFakeTaustaup_Teq70to80Integral->cd();
   baselineEWKFakeTaustaup_Teq70to80Integral->SetSelected(baselineEWKFakeTaustaup_Teq70to80Integral);
}
