{
//=========Macro generated from canvas: baselineEWK3Integral/
//=========  (Fri Jul  4 10:40:04 2014) by ROOT version5.32/00
   TCanvas *baselineEWK3Integral = new TCanvas("baselineEWK3Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   baselineEWK3Integral->SetHighLightColor(2);
   baselineEWK3Integral->Range(-101.2658,-1.434219,531.6456,1.905926);
   baselineEWK3Integral->SetFillColor(0);
   baselineEWK3Integral->SetBorderMode(0);
   baselineEWK3Integral->SetBorderSize(2);
   baselineEWK3Integral->SetLogy();
   baselineEWK3Integral->SetTickx(1);
   baselineEWK3Integral->SetTicky(1);
   baselineEWK3Integral->SetLeftMargin(0.16);
   baselineEWK3Integral->SetRightMargin(0.05);
   baselineEWK3Integral->SetTopMargin(0.05);
   baselineEWK3Integral->SetBottomMargin(0.13);
   baselineEWK3Integral->SetFrameFillStyle(0);
   baselineEWK3Integral->SetFrameBorderMode(0);
   baselineEWK3Integral->SetFrameFillStyle(0);
   baselineEWK3Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__43 = new TH1F("hframe__43","",1000,0,500);
   hframe__43->SetMinimum(0.1);
   hframe__43->SetMaximum(54.81742);
   hframe__43->SetDirectory(0);
   hframe__43->SetStats(0);
   hframe__43->SetLineStyle(0);
   hframe__43->SetMarkerStyle(20);
   hframe__43->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__43->GetXaxis()->SetLabelFont(43);
   hframe__43->GetXaxis()->SetLabelOffset(0.007);
   hframe__43->GetXaxis()->SetLabelSize(27);
   hframe__43->GetXaxis()->SetTitleSize(33);
   hframe__43->GetXaxis()->SetTitleOffset(0.9);
   hframe__43->GetXaxis()->SetTitleFont(43);
   hframe__43->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__43->GetYaxis()->SetLabelFont(43);
   hframe__43->GetYaxis()->SetLabelOffset(0.007);
   hframe__43->GetYaxis()->SetLabelSize(27);
   hframe__43->GetYaxis()->SetTitleSize(33);
   hframe__43->GetYaxis()->SetTitleOffset(1.25);
   hframe__43->GetYaxis()->SetTitleFont(43);
   hframe__43->GetZaxis()->SetLabelFont(43);
   hframe__43->GetZaxis()->SetLabelOffset(0.007);
   hframe__43->GetZaxis()->SetLabelSize(27);
   hframe__43->GetZaxis()->SetTitleSize(33);
   hframe__43->GetZaxis()->SetTitleFont(43);
   hframe__43->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 326 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3 = new TH1F("Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3","#tau p_{T}=70..80",50,0,500);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(1,2.812991);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(2,0.02113151);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(3,1.633557);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(4,1.33472);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(5,5.770948);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(6,10.7828);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(7,7.615098);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(8,8.714653);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(9,15.75875);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(10,13.97628);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(11,25.54185);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(12,27.40871);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(13,23.05313);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(14,17.59132);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(15,16.13914);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(16,20.35665);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(17,20.3889);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(18,19.73841);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(19,13.86904);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(20,11.8903);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(21,5.069881);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(22,5.353715);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(23,6.350666);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(24,5.489165);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(25,6.94424);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(26,5.708943);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(27,3.268137);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(28,5.068815);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(29,1.058552);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(30,4.167873);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(31,0.6919436);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(32,0.7131124);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(33,0.4568093);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(34,0.1194314);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(35,2.332017);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(36,1.240174);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(37,0.1448915);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(38,2.111103);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(39,1.396621);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(40,1.483969);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(41,1.163823);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(42,0.4200126);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(44,0.04870645);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(48,0.07518759);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(49,0.3971253);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinContent(50,0.4098043);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(1,2.524185);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(2,0.02113151);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(3,1.054421);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(4,0.9066153);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(5,1.879665);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(6,2.959479);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(7,1.976452);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(8,2.437321);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(9,3.602326);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(10,3.051445);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(11,4.231016);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(12,5.274253);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(13,3.878895);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(14,3.83869);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(15,3.587743);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(16,3.425266);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(17,3.595095);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(18,3.580723);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(19,3.429838);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(20,3.453083);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(21,1.450532);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(22,1.674695);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(23,1.923884);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(24,1.975121);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(25,2.034423);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(26,1.619651);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(27,1.174563);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(28,2.537998);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(29,0.8724325);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(30,1.534038);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(31,0.4901662);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(32,0.5607291);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(33,0.4568093);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(34,0.1194314);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(35,1.170217);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(36,0.9193654);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(37,0.1448915);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(38,1.094599);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(39,0.9900834);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(40,0.9524622);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(41,0.8585082);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(42,0.4200126);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(44,0.04870645);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(48,0.07518759);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(49,0.3971253);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetBinError(50,0.4098043);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetEntries(742);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetFillColor(ci);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetLineWidth(2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetMarkerStyle(20);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->SetMarkerSize(1.2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetXaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitle("Events / 10 GeV");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitleOffset(1.5);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetYaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->GetZaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts3->Draw("HIST same");
   
   TH1F *hframe__44 = new TH1F("hframe__44","",1000,0,500);
   hframe__44->SetMinimum(0.1);
   hframe__44->SetMaximum(54.81742);
   hframe__44->SetDirectory(0);
   hframe__44->SetStats(0);
   hframe__44->SetLineStyle(0);
   hframe__44->SetMarkerStyle(20);
   hframe__44->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__44->GetXaxis()->SetLabelFont(43);
   hframe__44->GetXaxis()->SetLabelOffset(0.007);
   hframe__44->GetXaxis()->SetLabelSize(27);
   hframe__44->GetXaxis()->SetTitleSize(33);
   hframe__44->GetXaxis()->SetTitleOffset(0.9);
   hframe__44->GetXaxis()->SetTitleFont(43);
   hframe__44->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__44->GetYaxis()->SetLabelFont(43);
   hframe__44->GetYaxis()->SetLabelOffset(0.007);
   hframe__44->GetYaxis()->SetLabelSize(27);
   hframe__44->GetYaxis()->SetTitleSize(33);
   hframe__44->GetYaxis()->SetTitleOffset(1.25);
   hframe__44->GetYaxis()->SetTitleFont(43);
   hframe__44->GetZaxis()->SetLabelFont(43);
   hframe__44->GetZaxis()->SetLabelOffset(0.007);
   hframe__44->GetZaxis()->SetLabelSize(27);
   hframe__44->GetZaxis()->SetTitleSize(33);
   hframe__44->GetZaxis()->SetTitleFont(43);
   hframe__44->Draw("sameaxis");
   baselineEWK3Integral->Modified();
   baselineEWK3Integral->cd();
   baselineEWK3Integral->SetSelected(baselineEWK3Integral);
}
