{
//=========Macro generated from canvas: baselineEWKFakeTausInclusiveIntegral/
//=========  (Fri Aug  1 09:24:47 2014) by ROOT version5.32/00
   TCanvas *baselineEWKFakeTausInclusiveIntegral = new TCanvas("baselineEWKFakeTausInclusiveIntegral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKFakeTausInclusiveIntegral->SetHighLightColor(2);
   baselineEWKFakeTausInclusiveIntegral->Range(-101.2658,-1.383063,531.6456,1.563576);
   baselineEWKFakeTausInclusiveIntegral->SetFillColor(0);
   baselineEWKFakeTausInclusiveIntegral->SetBorderMode(0);
   baselineEWKFakeTausInclusiveIntegral->SetBorderSize(2);
   baselineEWKFakeTausInclusiveIntegral->SetLogy();
   baselineEWKFakeTausInclusiveIntegral->SetTickx(1);
   baselineEWKFakeTausInclusiveIntegral->SetTicky(1);
   baselineEWKFakeTausInclusiveIntegral->SetLeftMargin(0.16);
   baselineEWKFakeTausInclusiveIntegral->SetRightMargin(0.05);
   baselineEWKFakeTausInclusiveIntegral->SetTopMargin(0.05);
   baselineEWKFakeTausInclusiveIntegral->SetBottomMargin(0.13);
   baselineEWKFakeTausInclusiveIntegral->SetFrameFillStyle(0);
   baselineEWKFakeTausInclusiveIntegral->SetFrameBorderMode(0);
   baselineEWKFakeTausInclusiveIntegral->SetFrameFillStyle(0);
   baselineEWKFakeTausInclusiveIntegral->SetFrameBorderMode(0);
   
   TH1F *hframe__137 = new TH1F("hframe__137","",1000,0,500);
   hframe__137->SetMinimum(0.1);
   hframe__137->SetMaximum(26.07617);
   hframe__137->SetDirectory(0);
   hframe__137->SetStats(0);
   hframe__137->SetLineStyle(0);
   hframe__137->SetMarkerStyle(20);
   hframe__137->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__137->GetXaxis()->SetLabelFont(43);
   hframe__137->GetXaxis()->SetLabelOffset(0.007);
   hframe__137->GetXaxis()->SetLabelSize(27);
   hframe__137->GetXaxis()->SetTitleSize(33);
   hframe__137->GetXaxis()->SetTitleOffset(0.9);
   hframe__137->GetXaxis()->SetTitleFont(43);
   hframe__137->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__137->GetYaxis()->SetLabelFont(43);
   hframe__137->GetYaxis()->SetLabelOffset(0.007);
   hframe__137->GetYaxis()->SetLabelSize(27);
   hframe__137->GetYaxis()->SetTitleSize(33);
   hframe__137->GetYaxis()->SetTitleOffset(1.25);
   hframe__137->GetYaxis()->SetTitleFont(43);
   hframe__137->GetZaxis()->SetLabelFont(43);
   hframe__137->GetZaxis()->SetLabelOffset(0.007);
   hframe__137->GetZaxis()->SetLabelSize(27);
   hframe__137->GetZaxis()->SetTitleSize(33);
   hframe__137->GetZaxis()->SetTitleFont(43);
   hframe__137->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 70 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive","METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(1,1.767343);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(2,0.2516302);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(3,2.004371);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(4,2.373698);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(5,5.511205);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(6,6.823359);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(7,1.541418);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(8,6.516476);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(9,6.303967);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(10,4.198389);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(11,0.8293468);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(12,13.03808);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(13,3.448806);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(14,5.14783);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(15,0.3867708);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(16,0.3434023);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(17,0.2507654);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(18,0.4667957);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(21,3.090298);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(23,3.173028);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(25,2.313863);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(27,0.03510796);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(40,0.01343465);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(1,1.767343);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(2,0.1642366);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(3,1.749948);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(4,1.578109);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(5,3.709156);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(6,4.546554);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(7,0.9470505);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(8,2.70436);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(9,3.847231);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(10,1.965331);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(11,0.6030622);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(12,5.957798);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(13,2.132094);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(14,2.544021);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(15,0.3476107);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(16,0.3434023);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(17,0.1634467);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(18,0.3131911);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(21,3.02689);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(23,1.916588);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(25,2.159702);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(27,0.03510796);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(40,0.01343465);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetEntries(124);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->Draw("HIST same");
   
   TH1F *hframe__138 = new TH1F("hframe__138","",1000,0,500);
   hframe__138->SetMinimum(0.1);
   hframe__138->SetMaximum(26.07617);
   hframe__138->SetDirectory(0);
   hframe__138->SetStats(0);
   hframe__138->SetLineStyle(0);
   hframe__138->SetMarkerStyle(20);
   hframe__138->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__138->GetXaxis()->SetLabelFont(43);
   hframe__138->GetXaxis()->SetLabelOffset(0.007);
   hframe__138->GetXaxis()->SetLabelSize(27);
   hframe__138->GetXaxis()->SetTitleSize(33);
   hframe__138->GetXaxis()->SetTitleOffset(0.9);
   hframe__138->GetXaxis()->SetTitleFont(43);
   hframe__138->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__138->GetYaxis()->SetLabelFont(43);
   hframe__138->GetYaxis()->SetLabelOffset(0.007);
   hframe__138->GetYaxis()->SetLabelSize(27);
   hframe__138->GetYaxis()->SetTitleSize(33);
   hframe__138->GetYaxis()->SetTitleOffset(1.25);
   hframe__138->GetYaxis()->SetTitleFont(43);
   hframe__138->GetZaxis()->SetLabelFont(43);
   hframe__138->GetZaxis()->SetLabelOffset(0.007);
   hframe__138->GetZaxis()->SetLabelSize(27);
   hframe__138->GetZaxis()->SetTitleSize(33);
   hframe__138->GetZaxis()->SetTitleFont(43);
   hframe__138->Draw("sameaxis");
   baselineEWKFakeTausInclusiveIntegral->Modified();
   baselineEWKFakeTausInclusiveIntegral->cd();
   baselineEWKFakeTausInclusiveIntegral->SetSelected(baselineEWKFakeTausInclusiveIntegral);
}
