{
//=========Macro generated from canvas: baselineEWK7Integral/
//=========  (Fri Jul  4 10:40:12 2014) by ROOT version5.32/00
   TCanvas *baselineEWK7Integral = new TCanvas("baselineEWK7Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   baselineEWK7Integral->SetHighLightColor(2);
   baselineEWK7Integral->Range(-101.2658,-1.352374,531.6456,1.358193);
   baselineEWK7Integral->SetFillColor(0);
   baselineEWK7Integral->SetBorderMode(0);
   baselineEWK7Integral->SetBorderSize(2);
   baselineEWK7Integral->SetLogy();
   baselineEWK7Integral->SetTickx(1);
   baselineEWK7Integral->SetTicky(1);
   baselineEWK7Integral->SetLeftMargin(0.16);
   baselineEWK7Integral->SetRightMargin(0.05);
   baselineEWK7Integral->SetTopMargin(0.05);
   baselineEWK7Integral->SetBottomMargin(0.13);
   baselineEWK7Integral->SetFrameFillStyle(0);
   baselineEWK7Integral->SetFrameBorderMode(0);
   baselineEWK7Integral->SetFrameFillStyle(0);
   baselineEWK7Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__91 = new TH1F("hframe__91","",1000,0,500);
   hframe__91->SetMinimum(0.1);
   hframe__91->SetMaximum(16.69802);
   hframe__91->SetDirectory(0);
   hframe__91->SetStats(0);
   hframe__91->SetLineStyle(0);
   hframe__91->SetMarkerStyle(20);
   hframe__91->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__91->GetXaxis()->SetLabelFont(43);
   hframe__91->GetXaxis()->SetLabelOffset(0.007);
   hframe__91->GetXaxis()->SetLabelSize(27);
   hframe__91->GetXaxis()->SetTitleSize(33);
   hframe__91->GetXaxis()->SetTitleOffset(0.9);
   hframe__91->GetXaxis()->SetTitleFont(43);
   hframe__91->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__91->GetYaxis()->SetLabelFont(43);
   hframe__91->GetYaxis()->SetLabelOffset(0.007);
   hframe__91->GetYaxis()->SetLabelSize(27);
   hframe__91->GetYaxis()->SetTitleSize(33);
   hframe__91->GetYaxis()->SetTitleOffset(1.25);
   hframe__91->GetYaxis()->SetTitleFont(43);
   hframe__91->GetZaxis()->SetLabelFont(43);
   hframe__91->GetZaxis()->SetLabelOffset(0.007);
   hframe__91->GetZaxis()->SetLabelSize(27);
   hframe__91->GetZaxis()->SetTitleSize(33);
   hframe__91->GetZaxis()->SetTitleFont(43);
   hframe__91->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 106 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7 = new TH1F("Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7","#tau p_{T}>150",50,0,500);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(1,0.4602692);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(2,2.97639);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(3,1.674984);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(4,2.775509);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(5,3.331427);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(6,2.608624);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(7,0.9593428);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(8,1.34733);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(9,7.406828);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(10,3.771763);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(11,3.197541);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(12,1.645536);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(13,8.34901);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(14,6.811357);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(15,7.858548);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(16,4.092618);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(17,1.672322);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(18,6.15203);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(19,3.960688);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(20,4.505374);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(21,0.9735622);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(22,2.106387);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(23,2.215508);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(24,1.164999);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(25,1.000657);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(26,1.629811);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(27,1.534446);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(28,0.7901767);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(29,4.870253);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(30,1.230367);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(31,1.833662);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(32,0.6658294);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(33,2.006471);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(34,0.6801339);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(36,0.4495584);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(40,0.3490514);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(41,0.5247146);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(42,2.110828);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(43,0.7174367);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(44,0.3628904);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(46,0.9315013);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(47,1.167636);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(48,0.7142353);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(49,0.3444401);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(50,0.1011396);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(51,0.7577545);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(1,0.4602692);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(2,2.162416);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(3,0.8126749);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(4,1.274139);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(5,2.159564);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(6,2.000202);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(7,0.5332815);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(8,0.6805823);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(9,4.019807);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(10,1.606788);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(11,1.16255);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(12,0.8435765);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(13,3.332688);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(14,2.973455);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(15,3.046891);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(16,1.579896);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(17,0.9108178);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(18,3.215997);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(19,1.283962);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(20,1.729847);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(21,0.5703204);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(22,0.9108955);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(23,1.022637);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(24,0.8149053);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(25,0.5618641);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(26,0.8886279);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(27,0.8855193);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(28,0.5889756);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(29,3.451418);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(30,0.8368841);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(31,0.9249085);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(32,0.4722883);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(33,1.308111);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(34,0.4704889);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(36,0.3597865);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(40,0.3490514);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(41,0.3883988);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(42,2.110828);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(43,0.5073485);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(44,0.3628904);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(46,0.9315013);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(47,0.9434475);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(48,0.5052325);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(49,0.3444401);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(50,0.1011396);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(51,0.5362278);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetEntries(238);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetFillColor(ci);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetLineWidth(2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetMarkerStyle(20);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetMarkerSize(1.2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitle("Events / 10 GeV");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitleOffset(1.5);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->Draw("HIST same");
   
   TH1F *hframe__92 = new TH1F("hframe__92","",1000,0,500);
   hframe__92->SetMinimum(0.1);
   hframe__92->SetMaximum(16.69802);
   hframe__92->SetDirectory(0);
   hframe__92->SetStats(0);
   hframe__92->SetLineStyle(0);
   hframe__92->SetMarkerStyle(20);
   hframe__92->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__92->GetXaxis()->SetLabelFont(43);
   hframe__92->GetXaxis()->SetLabelOffset(0.007);
   hframe__92->GetXaxis()->SetLabelSize(27);
   hframe__92->GetXaxis()->SetTitleSize(33);
   hframe__92->GetXaxis()->SetTitleOffset(0.9);
   hframe__92->GetXaxis()->SetTitleFont(43);
   hframe__92->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__92->GetYaxis()->SetLabelFont(43);
   hframe__92->GetYaxis()->SetLabelOffset(0.007);
   hframe__92->GetYaxis()->SetLabelSize(27);
   hframe__92->GetYaxis()->SetTitleSize(33);
   hframe__92->GetYaxis()->SetTitleOffset(1.25);
   hframe__92->GetYaxis()->SetTitleFont(43);
   hframe__92->GetZaxis()->SetLabelFont(43);
   hframe__92->GetZaxis()->SetLabelOffset(0.007);
   hframe__92->GetZaxis()->SetLabelSize(27);
   hframe__92->GetZaxis()->SetTitleSize(33);
   hframe__92->GetZaxis()->SetTitleFont(43);
   hframe__92->Draw("sameaxis");
   baselineEWK7Integral->Modified();
   baselineEWK7Integral->cd();
   baselineEWK7Integral->SetSelected(baselineEWK7Integral);
}
