{
//=========Macro generated from canvas: baselinetaup_Tgt150Integral/
//=========  (Thu Jul 31 09:28:42 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Tgt150Integral = new TCanvas("baselinetaup_Tgt150Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselinetaup_Tgt150Integral->SetHighLightColor(2);
   baselinetaup_Tgt150Integral->Range(-101.2658,-1.546007,531.6456,2.654048);
   baselinetaup_Tgt150Integral->SetFillColor(0);
   baselinetaup_Tgt150Integral->SetBorderMode(0);
   baselinetaup_Tgt150Integral->SetBorderSize(2);
   baselinetaup_Tgt150Integral->SetLogy();
   baselinetaup_Tgt150Integral->SetTickx(1);
   baselinetaup_Tgt150Integral->SetTicky(1);
   baselinetaup_Tgt150Integral->SetLeftMargin(0.16);
   baselinetaup_Tgt150Integral->SetRightMargin(0.05);
   baselinetaup_Tgt150Integral->SetTopMargin(0.05);
   baselinetaup_Tgt150Integral->SetBottomMargin(0.13);
   baselinetaup_Tgt150Integral->SetFrameFillStyle(0);
   baselinetaup_Tgt150Integral->SetFrameBorderMode(0);
   baselinetaup_Tgt150Integral->SetFrameFillStyle(0);
   baselinetaup_Tgt150Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__133 = new TH1F("hframe__133","",1000,0,500);
   hframe__133->SetMinimum(0.1);
   hframe__133->SetMaximum(278);
   hframe__133->SetDirectory(0);
   hframe__133->SetStats(0);
   hframe__133->SetLineStyle(0);
   hframe__133->SetMarkerStyle(20);
   hframe__133->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__133->GetXaxis()->SetLabelFont(43);
   hframe__133->GetXaxis()->SetLabelOffset(0.007);
   hframe__133->GetXaxis()->SetLabelSize(27);
   hframe__133->GetXaxis()->SetTitleSize(33);
   hframe__133->GetXaxis()->SetTitleOffset(0.9);
   hframe__133->GetXaxis()->SetTitleFont(43);
   hframe__133->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__133->GetYaxis()->SetLabelFont(43);
   hframe__133->GetYaxis()->SetLabelOffset(0.007);
   hframe__133->GetYaxis()->SetLabelSize(27);
   hframe__133->GetYaxis()->SetTitleSize(33);
   hframe__133->GetYaxis()->SetTitleOffset(1.25);
   hframe__133->GetYaxis()->SetTitleFont(43);
   hframe__133->GetZaxis()->SetLabelFont(43);
   hframe__133->GetZaxis()->SetLabelOffset(0.007);
   hframe__133->GetZaxis()->SetLabelSize(27);
   hframe__133->GetZaxis()->SetTitleSize(33);
   hframe__133->GetZaxis()->SetTitleFont(43);
   hframe__133->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 683 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7","#tau p_{T}>150",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(1,49);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(2,128);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(3,139);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(4,99);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(5,68);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(6,50);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(7,30);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(8,17);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(9,17);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(10,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(11,8);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(12,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(13,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(14,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(15,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(16,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(17,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(18,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(19,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(20,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(21,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(22,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(23,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(24,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(25,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(26,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(27,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(28,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(29,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(30,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(32,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(34,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(48,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinContent(51,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(1,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(2,11.31371);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(3,11.78983);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(4,9.949874);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(5,8.246211);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(6,7.071068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(7,5.477226);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(8,4.123106);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(9,4.123106);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(10,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(11,2.828427);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(12,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(13,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(14,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(15,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(16,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(17,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(18,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(19,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(20,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(21,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(22,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(23,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(24,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(25,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(26,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(27,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(28,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(29,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(30,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(32,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(33,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(34,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(39,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(48,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetBinError(51,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetEntries(684);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts7->Draw("HIST same");
   
   TH1F *hframe__134 = new TH1F("hframe__134","",1000,0,500);
   hframe__134->SetMinimum(0.1);
   hframe__134->SetMaximum(278);
   hframe__134->SetDirectory(0);
   hframe__134->SetStats(0);
   hframe__134->SetLineStyle(0);
   hframe__134->SetMarkerStyle(20);
   hframe__134->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__134->GetXaxis()->SetLabelFont(43);
   hframe__134->GetXaxis()->SetLabelOffset(0.007);
   hframe__134->GetXaxis()->SetLabelSize(27);
   hframe__134->GetXaxis()->SetTitleSize(33);
   hframe__134->GetXaxis()->SetTitleOffset(0.9);
   hframe__134->GetXaxis()->SetTitleFont(43);
   hframe__134->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__134->GetYaxis()->SetLabelFont(43);
   hframe__134->GetYaxis()->SetLabelOffset(0.007);
   hframe__134->GetYaxis()->SetLabelSize(27);
   hframe__134->GetYaxis()->SetTitleSize(33);
   hframe__134->GetYaxis()->SetTitleOffset(1.25);
   hframe__134->GetYaxis()->SetTitleFont(43);
   hframe__134->GetZaxis()->SetLabelFont(43);
   hframe__134->GetZaxis()->SetLabelOffset(0.007);
   hframe__134->GetZaxis()->SetLabelSize(27);
   hframe__134->GetZaxis()->SetTitleSize(33);
   hframe__134->GetZaxis()->SetTitleFont(43);
   hframe__134->Draw("sameaxis");
   baselinetaup_Tgt150Integral->Modified();
   baselinetaup_Tgt150Integral->cd();
   baselinetaup_Tgt150Integral->SetSelected(baselinetaup_Tgt150Integral);
}
