{
//=========Macro generated from canvas: baselineEWK5Integral/
//=========  (Fri Jul  4 10:40:08 2014) by ROOT version5.32/00
   TCanvas *baselineEWK5Integral = new TCanvas("baselineEWK5Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   baselineEWK5Integral->SetHighLightColor(2);
   baselineEWK5Integral->Range(-101.2658,-1.378183,531.6456,1.53092);
   baselineEWK5Integral->SetFillColor(0);
   baselineEWK5Integral->SetBorderMode(0);
   baselineEWK5Integral->SetBorderSize(2);
   baselineEWK5Integral->SetLogy();
   baselineEWK5Integral->SetTickx(1);
   baselineEWK5Integral->SetTicky(1);
   baselineEWK5Integral->SetLeftMargin(0.16);
   baselineEWK5Integral->SetRightMargin(0.05);
   baselineEWK5Integral->SetTopMargin(0.05);
   baselineEWK5Integral->SetBottomMargin(0.13);
   baselineEWK5Integral->SetFrameFillStyle(0);
   baselineEWK5Integral->SetFrameBorderMode(0);
   baselineEWK5Integral->SetFrameFillStyle(0);
   baselineEWK5Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__67 = new TH1F("hframe__67","",1000,0,500);
   hframe__67->SetMinimum(0.1);
   hframe__67->SetMaximum(24.2921);
   hframe__67->SetDirectory(0);
   hframe__67->SetStats(0);
   hframe__67->SetLineStyle(0);
   hframe__67->SetMarkerStyle(20);
   hframe__67->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__67->GetXaxis()->SetLabelFont(43);
   hframe__67->GetXaxis()->SetLabelOffset(0.007);
   hframe__67->GetXaxis()->SetLabelSize(27);
   hframe__67->GetXaxis()->SetTitleSize(33);
   hframe__67->GetXaxis()->SetTitleOffset(0.9);
   hframe__67->GetXaxis()->SetTitleFont(43);
   hframe__67->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__67->GetYaxis()->SetLabelFont(43);
   hframe__67->GetYaxis()->SetLabelOffset(0.007);
   hframe__67->GetYaxis()->SetLabelSize(27);
   hframe__67->GetYaxis()->SetTitleSize(33);
   hframe__67->GetYaxis()->SetTitleOffset(1.25);
   hframe__67->GetYaxis()->SetTitleFont(43);
   hframe__67->GetZaxis()->SetLabelFont(43);
   hframe__67->GetZaxis()->SetLabelOffset(0.007);
   hframe__67->GetZaxis()->SetLabelSize(27);
   hframe__67->GetZaxis()->SetTitleSize(33);
   hframe__67->GetZaxis()->SetTitleFont(43);
   hframe__67->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 183 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5 = new TH1F("Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5","#tau p_{T}=100..120",50,0,500);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(2,1.229195);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(3,2.983338);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(4,6.100532);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(5,3.353314);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(6,3.415189);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(7,7.718807);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(8,3.785823);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(9,9.354074);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(10,11.28903);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(11,6.270472);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(12,9.111636);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(13,10.53345);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(14,7.770809);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(15,9.896132);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(16,9.576791);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(17,9.074465);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(18,12.14605);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(19,4.37782);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(20,7.197632);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(21,9.134418);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(22,4.569513);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(23,5.201329);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(24,4.602641);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(25,3.610783);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(26,1.816945);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(27,1.605876);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(28,1.080967);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(29,3.34611);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(30,1.559755);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(31,0.594752);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(32,1.034554);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(33,1.169245);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(34,1.808039);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(36,1.816865);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(37,0.5443035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(39,0.08616413);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(40,1.121473);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(41,0.05441494);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(42,0.683526);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(43,1.142977);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(44,0.6163095);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(45,0.2901123);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(47,0.0005265118);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(49,0.3634821);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(51,1.205292);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(2,0.7866288);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(3,2.216322);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(4,1.994057);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(5,1.466592);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(6,1.157345);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(7,3.201976);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(8,1.455181);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(9,3.056599);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(10,4.582715);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(11,1.775549);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(12,2.764355);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(13,3.575694);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(14,2.040182);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(15,2.627465);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(16,2.995483);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(17,2.864721);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(18,2.270663);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(19,1.470042);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(20,2.566184);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(21,3.458701);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(22,1.471794);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(23,1.511231);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(24,1.59475);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(25,1.31467);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(26,0.9637172);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(27,0.8094061);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(28,0.6423959);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(29,1.444857);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(30,0.7939456);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(31,0.4298613);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(32,0.7141317);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(33,0.6251415);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(34,1.048728);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(36,1.012896);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(37,0.4343722);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(39,0.08616412);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(40,0.8191783);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(41,0.05441494);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(42,0.4907907);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(43,0.6631035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(44,0.6163096);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(45,0.2901123);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(47,0.0005265118);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(49,0.3634821);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(51,0.6919053);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetEntries(466);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetFillColor(ci);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetLineWidth(2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetMarkerStyle(20);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetMarkerSize(1.2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitle("Events / 10 GeV");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitleOffset(1.5);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->Draw("HIST same");
   
   TH1F *hframe__68 = new TH1F("hframe__68","",1000,0,500);
   hframe__68->SetMinimum(0.1);
   hframe__68->SetMaximum(24.2921);
   hframe__68->SetDirectory(0);
   hframe__68->SetStats(0);
   hframe__68->SetLineStyle(0);
   hframe__68->SetMarkerStyle(20);
   hframe__68->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__68->GetXaxis()->SetLabelFont(43);
   hframe__68->GetXaxis()->SetLabelOffset(0.007);
   hframe__68->GetXaxis()->SetLabelSize(27);
   hframe__68->GetXaxis()->SetTitleSize(33);
   hframe__68->GetXaxis()->SetTitleOffset(0.9);
   hframe__68->GetXaxis()->SetTitleFont(43);
   hframe__68->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__68->GetYaxis()->SetLabelFont(43);
   hframe__68->GetYaxis()->SetLabelOffset(0.007);
   hframe__68->GetYaxis()->SetLabelSize(27);
   hframe__68->GetYaxis()->SetTitleSize(33);
   hframe__68->GetYaxis()->SetTitleOffset(1.25);
   hframe__68->GetYaxis()->SetTitleFont(43);
   hframe__68->GetZaxis()->SetLabelFont(43);
   hframe__68->GetZaxis()->SetLabelOffset(0.007);
   hframe__68->GetZaxis()->SetLabelSize(27);
   hframe__68->GetZaxis()->SetTitleSize(33);
   hframe__68->GetZaxis()->SetTitleFont(43);
   hframe__68->Draw("sameaxis");
   baselineEWK5Integral->Modified();
   baselineEWK5Integral->cd();
   baselineEWK5Integral->SetSelected(baselineEWK5Integral);
}
