{
//=========Macro generated from canvas: baselinetaup_Tlt50Integral/
//=========  (Wed Aug 13 15:49:45 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Tlt50Integral = new TCanvas("baselinetaup_Tlt50Integral", "",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   baselinetaup_Tlt50Integral->SetHighLightColor(2);
   baselinetaup_Tlt50Integral->Range(-101.2658,-1.612666,531.6456,3.100152);
   baselinetaup_Tlt50Integral->SetFillColor(0);
   baselinetaup_Tlt50Integral->SetBorderMode(0);
   baselinetaup_Tlt50Integral->SetBorderSize(2);
   baselinetaup_Tlt50Integral->SetLogy();
   baselinetaup_Tlt50Integral->SetTickx(1);
   baselinetaup_Tlt50Integral->SetTicky(1);
   baselinetaup_Tlt50Integral->SetLeftMargin(0.16);
   baselinetaup_Tlt50Integral->SetRightMargin(0.05);
   baselinetaup_Tlt50Integral->SetTopMargin(0.05);
   baselinetaup_Tlt50Integral->SetBottomMargin(0.13);
   baselinetaup_Tlt50Integral->SetFrameFillStyle(0);
   baselinetaup_Tlt50Integral->SetFrameBorderMode(0);
   baselinetaup_Tlt50Integral->SetFrameFillStyle(0);
   baselinetaup_Tlt50Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__7 = new TH1F("hframe__7","",1000,0,500);
   hframe__7->SetMinimum(0.1);
   hframe__7->SetMaximum(732);
   hframe__7->SetDirectory(0);
   hframe__7->SetStats(0);
   hframe__7->SetLineStyle(0);
   hframe__7->SetMarkerStyle(20);
   hframe__7->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__7->GetXaxis()->SetLabelFont(43);
   hframe__7->GetXaxis()->SetLabelOffset(0.007);
   hframe__7->GetXaxis()->SetLabelSize(27);
   hframe__7->GetXaxis()->SetTitleSize(33);
   hframe__7->GetXaxis()->SetTitleOffset(0.9);
   hframe__7->GetXaxis()->SetTitleFont(43);
   hframe__7->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__7->GetYaxis()->SetLabelFont(43);
   hframe__7->GetYaxis()->SetLabelOffset(0.007);
   hframe__7->GetYaxis()->SetLabelSize(27);
   hframe__7->GetYaxis()->SetTitleSize(33);
   hframe__7->GetYaxis()->SetTitleOffset(1.25);
   hframe__7->GetYaxis()->SetTitleFont(43);
   hframe__7->GetZaxis()->SetLabelFont(43);
   hframe__7->GetZaxis()->SetLabelOffset(0.007);
   hframe__7->GetZaxis()->SetLabelSize(27);
   hframe__7->GetZaxis()->SetTitleSize(33);
   hframe__7->GetZaxis()->SetTitleFont(43);
   hframe__7->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 2276 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0","#tau p_{T}<50",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(1,83);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(2,218);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(3,353);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(4,366);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(5,326);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(6,225);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(7,168);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(8,111);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(9,64);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(10,48);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(11,56);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(12,38);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(13,48);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(14,27);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(15,27);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(16,26);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(17,19);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(18,14);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(19,16);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(20,10);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(21,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(22,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(23,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(24,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(25,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(26,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(27,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(32,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(33,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(1,9.110434);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(2,14.76482);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(3,18.78829);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(4,19.13113);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(5,18.05547);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(6,15);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(7,12.96148);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(8,10.53565);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(9,8);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(10,6.928203);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(11,7.483315);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(12,6.164414);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(13,6.928203);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(14,5.196152);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(15,5.196152);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(16,5.09902);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(17,4.358899);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(18,3.741657);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(19,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(20,3.162278);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(21,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(22,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(23,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(24,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(25,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(26,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(27,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(32,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(33,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetEntries(2276);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->Draw("HIST same");
   
   TH1F *hframe__8 = new TH1F("hframe__8","",1000,0,500);
   hframe__8->SetMinimum(0.1);
   hframe__8->SetMaximum(732);
   hframe__8->SetDirectory(0);
   hframe__8->SetStats(0);
   hframe__8->SetLineStyle(0);
   hframe__8->SetMarkerStyle(20);
   hframe__8->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__8->GetXaxis()->SetLabelFont(43);
   hframe__8->GetXaxis()->SetLabelOffset(0.007);
   hframe__8->GetXaxis()->SetLabelSize(27);
   hframe__8->GetXaxis()->SetTitleSize(33);
   hframe__8->GetXaxis()->SetTitleOffset(0.9);
   hframe__8->GetXaxis()->SetTitleFont(43);
   hframe__8->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__8->GetYaxis()->SetLabelFont(43);
   hframe__8->GetYaxis()->SetLabelOffset(0.007);
   hframe__8->GetYaxis()->SetLabelSize(27);
   hframe__8->GetYaxis()->SetTitleSize(33);
   hframe__8->GetYaxis()->SetTitleOffset(1.25);
   hframe__8->GetYaxis()->SetTitleFont(43);
   hframe__8->GetZaxis()->SetLabelFont(43);
   hframe__8->GetZaxis()->SetLabelOffset(0.007);
   hframe__8->GetZaxis()->SetLabelSize(27);
   hframe__8->GetZaxis()->SetTitleSize(33);
   hframe__8->GetZaxis()->SetTitleFont(43);
   hframe__8->Draw("sameaxis");
   baselinetaup_Tlt50Integral->Modified();
   baselinetaup_Tlt50Integral->cd();
   baselinetaup_Tlt50Integral->SetSelected(baselinetaup_Tlt50Integral);
}
