{
//=========Macro generated from canvas: baselineEWKGenuineTaustaup_Tlt50Integral/
//=========  (Wed Aug 13 15:49:45 2014) by ROOT version5.32/00
   TCanvas *baselineEWKGenuineTaustaup_Tlt50Integral = new TCanvas("baselineEWKGenuineTaustaup_Tlt50Integral", "",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetHighLightColor(2);
   baselineEWKGenuineTaustaup_Tlt50Integral->Range(-101.2658,-1.329803,531.6456,1.207146);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetFillColor(0);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetBorderMode(0);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetBorderSize(2);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetLogy();
   baselineEWKGenuineTaustaup_Tlt50Integral->SetTickx(1);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetTicky(1);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetLeftMargin(0.16);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetRightMargin(0.05);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetTopMargin(0.05);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetBottomMargin(0.13);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetFrameBorderMode(0);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Tlt50Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__9 = new TH1F("hframe__9","",1000,0,500);
   hframe__9->SetMinimum(0.1);
   hframe__9->SetMaximum(12.03091);
   hframe__9->SetDirectory(0);
   hframe__9->SetStats(0);
   hframe__9->SetLineStyle(0);
   hframe__9->SetMarkerStyle(20);
   hframe__9->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__9->GetXaxis()->SetLabelFont(43);
   hframe__9->GetXaxis()->SetLabelOffset(0.007);
   hframe__9->GetXaxis()->SetLabelSize(27);
   hframe__9->GetXaxis()->SetTitleSize(33);
   hframe__9->GetXaxis()->SetTitleOffset(0.9);
   hframe__9->GetXaxis()->SetTitleFont(43);
   hframe__9->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__9->GetYaxis()->SetLabelFont(43);
   hframe__9->GetYaxis()->SetLabelOffset(0.007);
   hframe__9->GetYaxis()->SetLabelSize(27);
   hframe__9->GetYaxis()->SetTitleSize(33);
   hframe__9->GetYaxis()->SetTitleOffset(1.25);
   hframe__9->GetYaxis()->SetTitleFont(43);
   hframe__9->GetZaxis()->SetLabelFont(43);
   hframe__9->GetZaxis()->SetLabelOffset(0.007);
   hframe__9->GetZaxis()->SetLabelSize(27);
   hframe__9->GetZaxis()->SetTitleSize(33);
   hframe__9->GetZaxis()->SetTitleFont(43);
   hframe__9->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 57 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0","#tau p_{T}<50",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(2,0.3122849);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(3,0.8341974);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(4,1.463231);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(5,3.045548);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(6,1.748616);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(7,1.540103);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(8,2.904439);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(9,3.803293);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(10,5.252552);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(11,5.492027);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(12,6.015457);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(13,3.885475);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(14,5.014835);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(15,2.577994);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(16,3.047884);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(17,2.125456);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(18,1.9466);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(19,1.620963);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(20,0.3219872);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(21,0.4399533);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(22,0.6526838);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(23,0.5925047);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(24,0.3065476);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(25,0.1717072);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(26,0.2164848);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(27,0.1364649);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(28,0.09306946);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(29,0.1726264);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(30,0.1530508);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(31,0.004859454);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(32,0.2995323);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(33,0.08378182);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(34,0.08425064);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(36,0.06957258);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(37,0.08137394);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(42,0.02194862);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(51,0.08177358);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(2,0.1842782);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(3,0.2759474);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(4,0.5926597);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(5,1.132951);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(6,0.4636303);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(7,0.3784676);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(8,0.7707842);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(9,1.094361);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(10,0.8410748);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(11,1.068773);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(12,1.09917);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(13,0.6325759);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(14,0.9639854);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(15,0.5381537);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(16,0.9064445);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(17,0.7428217);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(18,0.5140071);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(19,0.4590156);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(20,0.201572);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(21,0.2024655);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(22,0.2365766);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(23,0.2237967);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(24,0.187155);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(25,0.1168807);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(26,0.1566674);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(27,0.09962623);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(28,0.08531432);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(29,0.1220666);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(30,0.1091978);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(31,0.004859454);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(32,0.2995323);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(33,0.08378182);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(34,0.08425065);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(36,0.06957257);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(37,0.08137394);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(42,0.02194862);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(51,0.08177358);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetEntries(643);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->Draw("HIST same");
   
   TH1F *hframe__10 = new TH1F("hframe__10","",1000,0,500);
   hframe__10->SetMinimum(0.1);
   hframe__10->SetMaximum(12.03091);
   hframe__10->SetDirectory(0);
   hframe__10->SetStats(0);
   hframe__10->SetLineStyle(0);
   hframe__10->SetMarkerStyle(20);
   hframe__10->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__10->GetXaxis()->SetLabelFont(43);
   hframe__10->GetXaxis()->SetLabelOffset(0.007);
   hframe__10->GetXaxis()->SetLabelSize(27);
   hframe__10->GetXaxis()->SetTitleSize(33);
   hframe__10->GetXaxis()->SetTitleOffset(0.9);
   hframe__10->GetXaxis()->SetTitleFont(43);
   hframe__10->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__10->GetYaxis()->SetLabelFont(43);
   hframe__10->GetYaxis()->SetLabelOffset(0.007);
   hframe__10->GetYaxis()->SetLabelSize(27);
   hframe__10->GetYaxis()->SetTitleSize(33);
   hframe__10->GetYaxis()->SetTitleOffset(1.25);
   hframe__10->GetYaxis()->SetTitleFont(43);
   hframe__10->GetZaxis()->SetLabelFont(43);
   hframe__10->GetZaxis()->SetLabelOffset(0.007);
   hframe__10->GetZaxis()->SetLabelSize(27);
   hframe__10->GetZaxis()->SetTitleSize(33);
   hframe__10->GetZaxis()->SetTitleFont(43);
   hframe__10->Draw("sameaxis");
   baselineEWKGenuineTaustaup_Tlt50Integral->Modified();
   baselineEWKGenuineTaustaup_Tlt50Integral->cd();
   baselineEWKGenuineTaustaup_Tlt50Integral->SetSelected(baselineEWKGenuineTaustaup_Tlt50Integral);
}
