{
//=========Macro generated from canvas: invertedtaup_Teq50to60Integral/
//=========  (Wed Aug 13 15:49:48 2014) by ROOT version5.32/00
   TCanvas *invertedtaup_Teq50to60Integral = new TCanvas("invertedtaup_Teq50to60Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedtaup_Teq50to60Integral->SetHighLightColor(2);
   invertedtaup_Teq50to60Integral->Range(-101.2658,-1.785107,531.6456,4.254175);
   invertedtaup_Teq50to60Integral->SetFillColor(0);
   invertedtaup_Teq50to60Integral->SetBorderMode(0);
   invertedtaup_Teq50to60Integral->SetBorderSize(2);
   invertedtaup_Teq50to60Integral->SetLogy();
   invertedtaup_Teq50to60Integral->SetTickx(1);
   invertedtaup_Teq50to60Integral->SetTicky(1);
   invertedtaup_Teq50to60Integral->SetLeftMargin(0.16);
   invertedtaup_Teq50to60Integral->SetRightMargin(0.05);
   invertedtaup_Teq50to60Integral->SetTopMargin(0.05);
   invertedtaup_Teq50to60Integral->SetBottomMargin(0.13);
   invertedtaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedtaup_Teq50to60Integral->SetFrameBorderMode(0);
   invertedtaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedtaup_Teq50to60Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__19 = new TH1F("hframe__19","",1000,0,500);
   hframe__19->SetMinimum(0.1);
   hframe__19->SetMaximum(8958);
   hframe__19->SetDirectory(0);
   hframe__19->SetStats(0);
   hframe__19->SetLineStyle(0);
   hframe__19->SetMarkerStyle(20);
   hframe__19->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__19->GetXaxis()->SetLabelFont(43);
   hframe__19->GetXaxis()->SetLabelOffset(0.007);
   hframe__19->GetXaxis()->SetLabelSize(27);
   hframe__19->GetXaxis()->SetTitleSize(33);
   hframe__19->GetXaxis()->SetTitleOffset(0.9);
   hframe__19->GetXaxis()->SetTitleFont(43);
   hframe__19->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__19->GetYaxis()->SetLabelFont(43);
   hframe__19->GetYaxis()->SetLabelOffset(0.007);
   hframe__19->GetYaxis()->SetLabelSize(27);
   hframe__19->GetYaxis()->SetTitleSize(33);
   hframe__19->GetYaxis()->SetTitleOffset(1.25);
   hframe__19->GetYaxis()->SetTitleFont(43);
   hframe__19->GetZaxis()->SetLabelFont(43);
   hframe__19->GetZaxis()->SetLabelOffset(0.007);
   hframe__19->GetZaxis()->SetLabelSize(27);
   hframe__19->GetZaxis()->SetTitleSize(33);
   hframe__19->GetZaxis()->SetTitleFont(43);
   hframe__19->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 22717 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1","#tau p_{T}=50..60",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(1,1208);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(2,3325);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(3,4479);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(4,4242);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(5,3524);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(6,2386);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(7,1397);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(8,803);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(9,451);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(10,266);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(11,139);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(12,121);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(13,93);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(14,67);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(15,64);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(16,36);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(17,30);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(18,23);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(19,15);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(20,11);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(21,9);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(22,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(23,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(24,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(25,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(26,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(27,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(28,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(29,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(30,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(31,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(32,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(34,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(39,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(1,34.75629);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(2,57.66281);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(3,66.92533);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(4,65.13064);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(5,59.36329);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(6,48.8467);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(7,37.37646);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(8,28.33725);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(9,21.23676);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(10,16.30951);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(11,11.78983);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(12,11);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(13,9.643651);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(14,8.185353);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(15,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(16,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(17,5.477226);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(18,4.795832);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(19,3.872983);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(20,3.316625);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(21,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(22,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(23,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(24,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(25,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(26,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(27,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(28,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(29,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(30,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(31,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(32,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(34,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(39,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetEntries(22717);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->Draw("HIST same");
   
   TH1F *hframe__20 = new TH1F("hframe__20","",1000,0,500);
   hframe__20->SetMinimum(0.1);
   hframe__20->SetMaximum(8958);
   hframe__20->SetDirectory(0);
   hframe__20->SetStats(0);
   hframe__20->SetLineStyle(0);
   hframe__20->SetMarkerStyle(20);
   hframe__20->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__20->GetXaxis()->SetLabelFont(43);
   hframe__20->GetXaxis()->SetLabelOffset(0.007);
   hframe__20->GetXaxis()->SetLabelSize(27);
   hframe__20->GetXaxis()->SetTitleSize(33);
   hframe__20->GetXaxis()->SetTitleOffset(0.9);
   hframe__20->GetXaxis()->SetTitleFont(43);
   hframe__20->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__20->GetYaxis()->SetLabelFont(43);
   hframe__20->GetYaxis()->SetLabelOffset(0.007);
   hframe__20->GetYaxis()->SetLabelSize(27);
   hframe__20->GetYaxis()->SetTitleSize(33);
   hframe__20->GetYaxis()->SetTitleOffset(1.25);
   hframe__20->GetYaxis()->SetTitleFont(43);
   hframe__20->GetZaxis()->SetLabelFont(43);
   hframe__20->GetZaxis()->SetLabelOffset(0.007);
   hframe__20->GetZaxis()->SetLabelSize(27);
   hframe__20->GetZaxis()->SetTitleSize(33);
   hframe__20->GetZaxis()->SetTitleFont(43);
   hframe__20->Draw("sameaxis");
   invertedtaup_Teq50to60Integral->Modified();
   invertedtaup_Teq50to60Integral->cd();
   invertedtaup_Teq50to60Integral->SetSelected(invertedtaup_Teq50to60Integral);
}
