{
//=========Macro generated from canvas: invertedtaup_Teq80to100Integral/
//=========  (Fri Aug  1 09:24:38 2014) by ROOT version5.32/00
   TCanvas *invertedtaup_Teq80to100Integral = new TCanvas("invertedtaup_Teq80to100Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedtaup_Teq80to100Integral->SetHighLightColor(2);
   invertedtaup_Teq80to100Integral->Range(-101.2658,-1.789166,531.6456,4.28134);
   invertedtaup_Teq80to100Integral->SetFillColor(0);
   invertedtaup_Teq80to100Integral->SetBorderMode(0);
   invertedtaup_Teq80to100Integral->SetBorderSize(2);
   invertedtaup_Teq80to100Integral->SetLogy();
   invertedtaup_Teq80to100Integral->SetTickx(1);
   invertedtaup_Teq80to100Integral->SetTicky(1);
   invertedtaup_Teq80to100Integral->SetLeftMargin(0.16);
   invertedtaup_Teq80to100Integral->SetRightMargin(0.05);
   invertedtaup_Teq80to100Integral->SetTopMargin(0.05);
   invertedtaup_Teq80to100Integral->SetBottomMargin(0.13);
   invertedtaup_Teq80to100Integral->SetFrameFillStyle(0);
   invertedtaup_Teq80to100Integral->SetFrameBorderMode(0);
   invertedtaup_Teq80to100Integral->SetFrameFillStyle(0);
   invertedtaup_Teq80to100Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__73 = new TH1F("hframe__73","",1000,0,500);
   hframe__73->SetMinimum(0.1);
   hframe__73->SetMaximum(9502);
   hframe__73->SetDirectory(0);
   hframe__73->SetStats(0);
   hframe__73->SetLineStyle(0);
   hframe__73->SetMarkerStyle(20);
   hframe__73->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__73->GetXaxis()->SetLabelFont(43);
   hframe__73->GetXaxis()->SetLabelOffset(0.007);
   hframe__73->GetXaxis()->SetLabelSize(27);
   hframe__73->GetXaxis()->SetTitleSize(33);
   hframe__73->GetXaxis()->SetTitleOffset(0.9);
   hframe__73->GetXaxis()->SetTitleFont(43);
   hframe__73->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__73->GetYaxis()->SetLabelFont(43);
   hframe__73->GetYaxis()->SetLabelOffset(0.007);
   hframe__73->GetYaxis()->SetLabelSize(27);
   hframe__73->GetYaxis()->SetTitleSize(33);
   hframe__73->GetYaxis()->SetTitleOffset(1.25);
   hframe__73->GetYaxis()->SetTitleFont(43);
   hframe__73->GetZaxis()->SetLabelFont(43);
   hframe__73->GetZaxis()->SetLabelOffset(0.007);
   hframe__73->GetZaxis()->SetLabelSize(27);
   hframe__73->GetZaxis()->SetTitleSize(33);
   hframe__73->GetZaxis()->SetTitleFont(43);
   hframe__73->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 22204 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4","#tau p_{T}=80..100",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(1,1637);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(2,3953);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(3,4751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(4,4145);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(5,3016);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(6,1856);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(7,1086);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(8,566);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(9,336);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(10,215);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(11,131);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(12,111);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(13,76);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(14,46);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(15,46);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(16,38);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(17,37);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(18,33);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(19,27);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(20,21);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(21,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(22,10);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(23,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(24,9);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(25,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(26,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(27,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(28,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(29,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(30,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(32,5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(34,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(35,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinContent(37,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(1,40.45986);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(2,62.87289);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(3,68.9275);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(4,64.38167);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(5,54.91812);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(6,43.08132);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(7,32.95451);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(8,23.79075);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(9,18.3303);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(10,14.66288);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(11,11.44552);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(12,10.53565);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(13,8.717798);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(14,6.78233);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(15,6.78233);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(16,6.164414);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(17,6.082763);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(18,5.744563);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(19,5.196152);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(20,4.582576);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(21,2.828427);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(22,3.162278);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(23,2.828427);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(24,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(25,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(26,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(27,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(28,2.828427);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(29,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(30,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(32,2.236068);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(34,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(35,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetBinError(37,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetEntries(22204);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts4->Draw("HIST same");
   
   TH1F *hframe__74 = new TH1F("hframe__74","",1000,0,500);
   hframe__74->SetMinimum(0.1);
   hframe__74->SetMaximum(9502);
   hframe__74->SetDirectory(0);
   hframe__74->SetStats(0);
   hframe__74->SetLineStyle(0);
   hframe__74->SetMarkerStyle(20);
   hframe__74->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__74->GetXaxis()->SetLabelFont(43);
   hframe__74->GetXaxis()->SetLabelOffset(0.007);
   hframe__74->GetXaxis()->SetLabelSize(27);
   hframe__74->GetXaxis()->SetTitleSize(33);
   hframe__74->GetXaxis()->SetTitleOffset(0.9);
   hframe__74->GetXaxis()->SetTitleFont(43);
   hframe__74->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__74->GetYaxis()->SetLabelFont(43);
   hframe__74->GetYaxis()->SetLabelOffset(0.007);
   hframe__74->GetYaxis()->SetLabelSize(27);
   hframe__74->GetYaxis()->SetTitleSize(33);
   hframe__74->GetYaxis()->SetTitleOffset(1.25);
   hframe__74->GetYaxis()->SetTitleFont(43);
   hframe__74->GetZaxis()->SetLabelFont(43);
   hframe__74->GetZaxis()->SetLabelOffset(0.007);
   hframe__74->GetZaxis()->SetLabelSize(27);
   hframe__74->GetZaxis()->SetTitleSize(33);
   hframe__74->GetZaxis()->SetTitleFont(43);
   hframe__74->Draw("sameaxis");
   invertedtaup_Teq80to100Integral->Modified();
   invertedtaup_Teq80to100Integral->cd();
   invertedtaup_Teq80to100Integral->SetSelected(invertedtaup_Teq80to100Integral);
}
