{
//=========Macro generated from canvas: invertedEWKGenuineTaus0Integral/
//=========  (Sun Jul 20 15:00:23 2014) by ROOT version5.32/00
   TCanvas *invertedEWKGenuineTaus0Integral = new TCanvas("invertedEWKGenuineTaus0Integral", "",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   invertedEWKGenuineTaus0Integral->SetHighLightColor(2);
   invertedEWKGenuineTaus0Integral->Range(-101.2658,-1.48746,531.6456,2.262233);
   invertedEWKGenuineTaus0Integral->SetFillColor(0);
   invertedEWKGenuineTaus0Integral->SetBorderMode(0);
   invertedEWKGenuineTaus0Integral->SetBorderSize(2);
   invertedEWKGenuineTaus0Integral->SetLogy();
   invertedEWKGenuineTaus0Integral->SetTickx(1);
   invertedEWKGenuineTaus0Integral->SetTicky(1);
   invertedEWKGenuineTaus0Integral->SetLeftMargin(0.16);
   invertedEWKGenuineTaus0Integral->SetRightMargin(0.05);
   invertedEWKGenuineTaus0Integral->SetTopMargin(0.05);
   invertedEWKGenuineTaus0Integral->SetBottomMargin(0.13);
   invertedEWKGenuineTaus0Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaus0Integral->SetFrameBorderMode(0);
   invertedEWKGenuineTaus0Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaus0Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__3 = new TH1F("hframe__3","",1000,0,500);
   hframe__3->SetMinimum(0.1);
   hframe__3->SetMaximum(118.7813);
   hframe__3->SetDirectory(0);
   hframe__3->SetStats(0);
   hframe__3->SetLineStyle(0);
   hframe__3->SetMarkerStyle(20);
   hframe__3->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__3->GetXaxis()->SetLabelFont(43);
   hframe__3->GetXaxis()->SetLabelOffset(0.007);
   hframe__3->GetXaxis()->SetLabelSize(27);
   hframe__3->GetXaxis()->SetTitleSize(33);
   hframe__3->GetXaxis()->SetTitleOffset(0.9);
   hframe__3->GetXaxis()->SetTitleFont(43);
   hframe__3->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__3->GetYaxis()->SetLabelFont(43);
   hframe__3->GetYaxis()->SetLabelOffset(0.007);
   hframe__3->GetYaxis()->SetLabelSize(27);
   hframe__3->GetYaxis()->SetTitleSize(33);
   hframe__3->GetYaxis()->SetTitleOffset(1.25);
   hframe__3->GetYaxis()->SetTitleFont(43);
   hframe__3->GetZaxis()->SetLabelFont(43);
   hframe__3->GetZaxis()->SetLabelOffset(0.007);
   hframe__3->GetZaxis()->SetLabelSize(27);
   hframe__3->GetZaxis()->SetTitleSize(33);
   hframe__3->GetZaxis()->SetTitleFont(43);
   hframe__3->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 680 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0","#tau p_{T}<50",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(1,0.24011);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(2,2.229705);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(3,1.306359);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(4,9.914589);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(5,8.276661);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(6,29.76154);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(7,22.85166);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(8,27.47339);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(9,37.51457);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(10,45.67224);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(11,53.23891);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(12,59.39063);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(13,55.54897);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(14,47.58768);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(15,35.70042);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(16,34.06789);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(17,36.76271);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(18,33.29765);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(19,23.34865);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(20,19.8033);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(21,15.83234);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(22,15.47358);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(23,8.806076);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(24,7.91598);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(25,7.582013);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(26,4.24232);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(27,6.937985);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(28,3.669881);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(29,1.799814);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(30,1.639598);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(31,4.459526);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(32,4.162322);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(33,0.9242052);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(34,2.25227);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(35,0.2142826);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(36,1.550096);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(37,1.521385);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(38,1.193714);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(39,1.098609);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(40,0.3638135);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(42,0.4118261);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(44,1.026242);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(45,1.816439);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(47,0.3703712);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(48,1.039962);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinContent(51,0.7066737);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(1,0.24011);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(2,1.00106);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(3,0.7862749);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(4,3.534683);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(5,2.125601);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(6,5.925524);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(7,4.749123);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(8,4.317462);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(9,5.811482);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(10,5.902984);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(11,6.281831);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(12,6.367209);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(13,6.08129);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(14,5.965614);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(15,4.329062);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(16,4.466975);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(17,6.070298);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(18,5.472574);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(19,4.224793);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(20,3.252345);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(21,2.901938);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(22,2.960957);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(23,2.832447);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(24,1.910454);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(25,1.828771);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(26,1.399562);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(27,1.995765);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(28,1.427727);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(29,0.9066759);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(30,0.8922599);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(31,1.462042);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(32,1.6771);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(33,0.6672553);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(34,1.172353);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(35,0.1515216);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(36,0.7445783);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(37,1.146708);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(38,0.7939833);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(39,0.635064);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(40,0.3638135);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(42,0.3325867);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(44,0.7537008);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(45,1.324643);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(47,0.3703712);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(48,1.039962);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetBinError(51,0.4378858);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetEntries(1524);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus0->Draw("HIST same");
   
   TH1F *hframe__4 = new TH1F("hframe__4","",1000,0,500);
   hframe__4->SetMinimum(0.1);
   hframe__4->SetMaximum(118.7813);
   hframe__4->SetDirectory(0);
   hframe__4->SetStats(0);
   hframe__4->SetLineStyle(0);
   hframe__4->SetMarkerStyle(20);
   hframe__4->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__4->GetXaxis()->SetLabelFont(43);
   hframe__4->GetXaxis()->SetLabelOffset(0.007);
   hframe__4->GetXaxis()->SetLabelSize(27);
   hframe__4->GetXaxis()->SetTitleSize(33);
   hframe__4->GetXaxis()->SetTitleOffset(0.9);
   hframe__4->GetXaxis()->SetTitleFont(43);
   hframe__4->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__4->GetYaxis()->SetLabelFont(43);
   hframe__4->GetYaxis()->SetLabelOffset(0.007);
   hframe__4->GetYaxis()->SetLabelSize(27);
   hframe__4->GetYaxis()->SetTitleSize(33);
   hframe__4->GetYaxis()->SetTitleOffset(1.25);
   hframe__4->GetYaxis()->SetTitleFont(43);
   hframe__4->GetZaxis()->SetLabelFont(43);
   hframe__4->GetZaxis()->SetLabelOffset(0.007);
   hframe__4->GetZaxis()->SetLabelSize(27);
   hframe__4->GetZaxis()->SetTitleSize(33);
   hframe__4->GetZaxis()->SetTitleFont(43);
   hframe__4->Draw("sameaxis");
   invertedEWKGenuineTaus0Integral->Modified();
   invertedEWKGenuineTaus0Integral->cd();
   invertedEWKGenuineTaus0Integral->SetSelected(invertedEWKGenuineTaus0Integral);
}
