{
//=========Macro generated from canvas: invertedEWKFakeTaustaup_Teq60to70Integral/
//=========  (Fri Aug  1 09:24:34 2014) by ROOT version5.32/00
   TCanvas *invertedEWKFakeTaustaup_Teq60to70Integral = new TCanvas("invertedEWKFakeTaustaup_Teq60to70Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetHighLightColor(2);
   invertedEWKFakeTaustaup_Teq60to70Integral->Range(-101.2658,-1.372069,531.6456,1.49);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetFillColor(0);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetBorderMode(0);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetBorderSize(2);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetLogy();
   invertedEWKFakeTaustaup_Teq60to70Integral->SetTickx(1);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetTicky(1);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetLeftMargin(0.16);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetRightMargin(0.05);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetTopMargin(0.05);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetBottomMargin(0.13);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetFrameBorderMode(0);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq60to70Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__41 = new TH1F("hframe__41","",1000,0,500);
   hframe__41->SetMinimum(0.1);
   hframe__41->SetMaximum(22.2278);
   hframe__41->SetDirectory(0);
   hframe__41->SetStats(0);
   hframe__41->SetLineStyle(0);
   hframe__41->SetMarkerStyle(20);
   hframe__41->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__41->GetXaxis()->SetLabelFont(43);
   hframe__41->GetXaxis()->SetLabelOffset(0.007);
   hframe__41->GetXaxis()->SetLabelSize(27);
   hframe__41->GetXaxis()->SetTitleSize(33);
   hframe__41->GetXaxis()->SetTitleOffset(0.9);
   hframe__41->GetXaxis()->SetTitleFont(43);
   hframe__41->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__41->GetYaxis()->SetLabelFont(43);
   hframe__41->GetYaxis()->SetLabelOffset(0.007);
   hframe__41->GetYaxis()->SetLabelSize(27);
   hframe__41->GetYaxis()->SetTitleSize(33);
   hframe__41->GetYaxis()->SetTitleOffset(1.25);
   hframe__41->GetYaxis()->SetTitleFont(43);
   hframe__41->GetZaxis()->SetLabelFont(43);
   hframe__41->GetZaxis()->SetLabelOffset(0.007);
   hframe__41->GetZaxis()->SetLabelSize(27);
   hframe__41->GetZaxis()->SetTitleSize(33);
   hframe__41->GetZaxis()->SetTitleFont(43);
   hframe__41->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 93 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2","#tau p_{T}=60..70",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(1,0.1769819);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(2,0.4897507);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(3,4.48358);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(4,2.40082);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(5,4.027876);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(6,3.309701);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(7,6.43784);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(8,9.521472);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(9,9.384538);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(10,11.1139);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(11,6.154612);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(12,7.284242);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(13,2.434053);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(14,2.577861);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(15,9.535341);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(16,1.764374);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(17,3.037182);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(18,4.114608);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(19,0.7413555);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(20,0.0004289546);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(21,1.779224);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(22,0.1071701);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(23,0.4820004);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(24,0.06609669);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(26,0.0537544);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(31,0.03246931);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinContent(39,1.727836);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(1,0.1330996);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(2,0.3038722);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(3,4.040452);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(4,1.73351);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(5,2.530419);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(6,1.956714);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(7,3.263634);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(8,3.828084);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(9,4.095584);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(10,4.343678);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(11,2.594152);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(12,3.385715);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(13,1.726524);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(14,1.871585);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(15,4.169226);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(16,1.041027);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(17,2.006142);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(18,2.393348);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(19,0.5957389);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(20,0.0004289546);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(21,1.745593);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(22,0.07675876);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(23,0.4820005);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(24,0.06303193);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(26,0.0537544);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(31,0.03246931);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetBinError(39,1.727836);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetEntries(171);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus2->Draw("HIST same");
   
   TH1F *hframe__42 = new TH1F("hframe__42","",1000,0,500);
   hframe__42->SetMinimum(0.1);
   hframe__42->SetMaximum(22.2278);
   hframe__42->SetDirectory(0);
   hframe__42->SetStats(0);
   hframe__42->SetLineStyle(0);
   hframe__42->SetMarkerStyle(20);
   hframe__42->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__42->GetXaxis()->SetLabelFont(43);
   hframe__42->GetXaxis()->SetLabelOffset(0.007);
   hframe__42->GetXaxis()->SetLabelSize(27);
   hframe__42->GetXaxis()->SetTitleSize(33);
   hframe__42->GetXaxis()->SetTitleOffset(0.9);
   hframe__42->GetXaxis()->SetTitleFont(43);
   hframe__42->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__42->GetYaxis()->SetLabelFont(43);
   hframe__42->GetYaxis()->SetLabelOffset(0.007);
   hframe__42->GetYaxis()->SetLabelSize(27);
   hframe__42->GetYaxis()->SetTitleSize(33);
   hframe__42->GetYaxis()->SetTitleOffset(1.25);
   hframe__42->GetYaxis()->SetTitleFont(43);
   hframe__42->GetZaxis()->SetLabelFont(43);
   hframe__42->GetZaxis()->SetLabelOffset(0.007);
   hframe__42->GetZaxis()->SetLabelSize(27);
   hframe__42->GetZaxis()->SetTitleSize(33);
   hframe__42->GetZaxis()->SetTitleFont(43);
   hframe__42->Draw("sameaxis");
   invertedEWKFakeTaustaup_Teq60to70Integral->Modified();
   invertedEWKFakeTaustaup_Teq60to70Integral->cd();
   invertedEWKFakeTaustaup_Teq60to70Integral->SetSelected(invertedEWKFakeTaustaup_Teq60to70Integral);
}
