{
//=========Macro generated from canvas: invertedEWK5Integral/
//=========  (Fri Jul  4 10:40:08 2014) by ROOT version5.32/00
   TCanvas *invertedEWK5Integral = new TCanvas("invertedEWK5Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   invertedEWK5Integral->SetHighLightColor(2);
   invertedEWK5Integral->Range(-101.2658,-1.400806,531.6456,1.682315);
   invertedEWK5Integral->SetFillColor(0);
   invertedEWK5Integral->SetBorderMode(0);
   invertedEWK5Integral->SetBorderSize(2);
   invertedEWK5Integral->SetLogy();
   invertedEWK5Integral->SetTickx(1);
   invertedEWK5Integral->SetTicky(1);
   invertedEWK5Integral->SetLeftMargin(0.16);
   invertedEWK5Integral->SetRightMargin(0.05);
   invertedEWK5Integral->SetTopMargin(0.05);
   invertedEWK5Integral->SetBottomMargin(0.13);
   invertedEWK5Integral->SetFrameFillStyle(0);
   invertedEWK5Integral->SetFrameBorderMode(0);
   invertedEWK5Integral->SetFrameFillStyle(0);
   invertedEWK5Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__63 = new TH1F("hframe__63","",1000,0,500);
   hframe__63->SetMinimum(0.1);
   hframe__63->SetMaximum(33.74105);
   hframe__63->SetDirectory(0);
   hframe__63->SetStats(0);
   hframe__63->SetLineStyle(0);
   hframe__63->SetMarkerStyle(20);
   hframe__63->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__63->GetXaxis()->SetLabelFont(43);
   hframe__63->GetXaxis()->SetLabelOffset(0.007);
   hframe__63->GetXaxis()->SetLabelSize(27);
   hframe__63->GetXaxis()->SetTitleSize(33);
   hframe__63->GetXaxis()->SetTitleOffset(0.9);
   hframe__63->GetXaxis()->SetTitleFont(43);
   hframe__63->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__63->GetYaxis()->SetLabelFont(43);
   hframe__63->GetYaxis()->SetLabelOffset(0.007);
   hframe__63->GetYaxis()->SetLabelSize(27);
   hframe__63->GetYaxis()->SetTitleSize(33);
   hframe__63->GetYaxis()->SetTitleOffset(1.25);
   hframe__63->GetYaxis()->SetTitleFont(43);
   hframe__63->GetZaxis()->SetLabelFont(43);
   hframe__63->GetZaxis()->SetLabelOffset(0.007);
   hframe__63->GetZaxis()->SetLabelSize(27);
   hframe__63->GetZaxis()->SetTitleSize(33);
   hframe__63->GetZaxis()->SetTitleFont(43);
   hframe__63->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 228 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5","#tau p_{T}=100..120",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(1,0.7214961);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(2,6.061739);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(3,11.69807);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(4,8.610862);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(5,8.656619);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(6,10.1171);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(7,9.074087);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(8,16.87053);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(9,10.19449);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(10,16.01404);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(11,11.26039);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(12,9.629733);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(13,10.67153);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(14,11.9123);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(15,16.60516);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(16,16.28456);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(17,6.800976);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(18,7.593304);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(19,9.223537);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(20,4.124529);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(21,4.166635);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(22,3.226072);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(23,3.949129);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(24,2.16195);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(25,1.213399);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(26,0.1332983);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(27,1.858687);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(28,3.75263);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(29,0.3478764);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(31,0.1090433);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(32,1.034889);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(33,1.168283);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(34,0.3506965);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(35,0.2894717);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(36,0.3626453);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(37,0.3620614);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(39,0.1282558);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(40,0.004094242);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(41,0.6575221);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(42,0.4038803);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(45,0.3328371);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinContent(51,0.253416);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(1,0.5267037);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(2,2.124933);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(3,2.560275);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(4,2.74893);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(5,1.942009);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(6,2.092105);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(7,2.027935);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(8,4.666466);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(9,2.314538);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(10,4.507947);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(11,2.558189);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(12,2.161428);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(13,2.297567);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(14,2.250107);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(15,2.966332);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(16,3.554062);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(17,1.666088);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(18,2.147395);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(19,2.082763);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(20,1.257642);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(21,1.429185);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(22,1.111535);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(23,1.276605);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(24,1.16623);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(25,0.5991095);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(26,0.1332983);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(27,0.7554293);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(28,1.555323);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(29,0.3478764);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(31,0.1090433);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(32,0.6228761);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(33,0.7476419);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(34,0.3506965);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(35,0.2894717);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(36,0.3626453);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(37,0.3620614);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(39,0.1282558);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(40,0.004094241);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(41,0.6575222);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(42,0.4038803);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(45,0.3328372);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetBinError(51,0.2257409);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetEntries(621);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts5->Draw("HIST same");
   
   TH1F *hframe__64 = new TH1F("hframe__64","",1000,0,500);
   hframe__64->SetMinimum(0.1);
   hframe__64->SetMaximum(33.74105);
   hframe__64->SetDirectory(0);
   hframe__64->SetStats(0);
   hframe__64->SetLineStyle(0);
   hframe__64->SetMarkerStyle(20);
   hframe__64->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__64->GetXaxis()->SetLabelFont(43);
   hframe__64->GetXaxis()->SetLabelOffset(0.007);
   hframe__64->GetXaxis()->SetLabelSize(27);
   hframe__64->GetXaxis()->SetTitleSize(33);
   hframe__64->GetXaxis()->SetTitleOffset(0.9);
   hframe__64->GetXaxis()->SetTitleFont(43);
   hframe__64->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__64->GetYaxis()->SetLabelFont(43);
   hframe__64->GetYaxis()->SetLabelOffset(0.007);
   hframe__64->GetYaxis()->SetLabelSize(27);
   hframe__64->GetYaxis()->SetTitleSize(33);
   hframe__64->GetYaxis()->SetTitleOffset(1.25);
   hframe__64->GetYaxis()->SetTitleFont(43);
   hframe__64->GetZaxis()->SetLabelFont(43);
   hframe__64->GetZaxis()->SetLabelOffset(0.007);
   hframe__64->GetZaxis()->SetLabelSize(27);
   hframe__64->GetZaxis()->SetTitleSize(33);
   hframe__64->GetZaxis()->SetTitleFont(43);
   hframe__64->Draw("sameaxis");
   invertedEWK5Integral->Modified();
   invertedEWK5Integral->cd();
   invertedEWK5Integral->SetSelected(invertedEWK5Integral);
}
