{
//=========Macro generated from canvas: invertedEWKFakeTaus5Integral/
//=========  (Sun Jul 20 15:00:37 2014) by ROOT version5.32/00
   TCanvas *invertedEWKFakeTaus5Integral = new TCanvas("invertedEWKFakeTaus5Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKFakeTaus5Integral->SetHighLightColor(2);
   invertedEWKFakeTaus5Integral->Range(-101.2658,-1.373883,531.6456,1.50214);
   invertedEWKFakeTaus5Integral->SetFillColor(0);
   invertedEWKFakeTaus5Integral->SetBorderMode(0);
   invertedEWKFakeTaus5Integral->SetBorderSize(2);
   invertedEWKFakeTaus5Integral->SetLogy();
   invertedEWKFakeTaus5Integral->SetTickx(1);
   invertedEWKFakeTaus5Integral->SetTicky(1);
   invertedEWKFakeTaus5Integral->SetLeftMargin(0.16);
   invertedEWKFakeTaus5Integral->SetRightMargin(0.05);
   invertedEWKFakeTaus5Integral->SetTopMargin(0.05);
   invertedEWKFakeTaus5Integral->SetBottomMargin(0.13);
   invertedEWKFakeTaus5Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaus5Integral->SetFrameBorderMode(0);
   invertedEWKFakeTaus5Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaus5Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__95 = new TH1F("hframe__95","",1000,0,500);
   hframe__95->SetMinimum(0.1);
   hframe__95->SetMaximum(22.82124);
   hframe__95->SetDirectory(0);
   hframe__95->SetStats(0);
   hframe__95->SetLineStyle(0);
   hframe__95->SetMarkerStyle(20);
   hframe__95->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__95->GetXaxis()->SetLabelFont(43);
   hframe__95->GetXaxis()->SetLabelOffset(0.007);
   hframe__95->GetXaxis()->SetLabelSize(27);
   hframe__95->GetXaxis()->SetTitleSize(33);
   hframe__95->GetXaxis()->SetTitleOffset(0.9);
   hframe__95->GetXaxis()->SetTitleFont(43);
   hframe__95->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__95->GetYaxis()->SetLabelFont(43);
   hframe__95->GetYaxis()->SetLabelOffset(0.007);
   hframe__95->GetYaxis()->SetLabelSize(27);
   hframe__95->GetYaxis()->SetTitleSize(33);
   hframe__95->GetYaxis()->SetTitleOffset(1.25);
   hframe__95->GetYaxis()->SetTitleFont(43);
   hframe__95->GetZaxis()->SetLabelFont(43);
   hframe__95->GetZaxis()->SetLabelOffset(0.007);
   hframe__95->GetZaxis()->SetLabelSize(27);
   hframe__95->GetZaxis()->SetTitleSize(33);
   hframe__95->GetZaxis()->SetTitleFont(43);
   hframe__95->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 128 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5","#tau p_{T}=100..120",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(1,0.7214961);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(2,6.046849);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(3,11.37311);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(4,5.576408);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(5,7.708252);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(6,7.856712);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(7,6.864182);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(8,11.41062);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(9,6.47411);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(10,9.196239);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(11,8.337589);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(12,5.662776);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(13,6.89822);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(14,5.618956);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(15,6.945923);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(16,6.137952);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(17,3.05104);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(18,2.466926);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(19,1.997686);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(20,1.084169);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(21,0.02389223);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(22,0.8919517);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(23,1.924966);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(24,1.805198);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(27,0.4020604);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(28,1.459443);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(51,0.2237882);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(1,0.5267037);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(2,2.124881);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(3,2.547549);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(4,1.612198);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(5,1.866898);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(6,1.815182);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(7,1.777511);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(8,4.231221);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(9,1.857093);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(10,2.179796);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(11,2.289757);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(12,1.718166);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(13,1.881354);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(14,1.557952);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(15,1.832948);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(16,1.68024);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(17,1.039334);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(18,1.226727);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(19,0.9908345);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(20,0.6259724);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(21,0.02389223);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(22,0.5209944);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(23,0.8367953);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(24,1.110324);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(27,0.4020604);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(28,0.9668698);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(51,0.2237882);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetEntries(341);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->Draw("HIST same");
   
   TH1F *hframe__96 = new TH1F("hframe__96","",1000,0,500);
   hframe__96->SetMinimum(0.1);
   hframe__96->SetMaximum(22.82124);
   hframe__96->SetDirectory(0);
   hframe__96->SetStats(0);
   hframe__96->SetLineStyle(0);
   hframe__96->SetMarkerStyle(20);
   hframe__96->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__96->GetXaxis()->SetLabelFont(43);
   hframe__96->GetXaxis()->SetLabelOffset(0.007);
   hframe__96->GetXaxis()->SetLabelSize(27);
   hframe__96->GetXaxis()->SetTitleSize(33);
   hframe__96->GetXaxis()->SetTitleOffset(0.9);
   hframe__96->GetXaxis()->SetTitleFont(43);
   hframe__96->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__96->GetYaxis()->SetLabelFont(43);
   hframe__96->GetYaxis()->SetLabelOffset(0.007);
   hframe__96->GetYaxis()->SetLabelSize(27);
   hframe__96->GetYaxis()->SetTitleSize(33);
   hframe__96->GetYaxis()->SetTitleOffset(1.25);
   hframe__96->GetYaxis()->SetTitleFont(43);
   hframe__96->GetZaxis()->SetLabelFont(43);
   hframe__96->GetZaxis()->SetLabelOffset(0.007);
   hframe__96->GetZaxis()->SetLabelSize(27);
   hframe__96->GetZaxis()->SetTitleSize(33);
   hframe__96->GetZaxis()->SetTitleFont(43);
   hframe__96->Draw("sameaxis");
   invertedEWKFakeTaus5Integral->Modified();
   invertedEWKFakeTaus5Integral->cd();
   invertedEWKFakeTaus5Integral->SetSelected(invertedEWKFakeTaus5Integral);
}
