{
//=========Macro generated from canvas: invertedEWK3Integral/
//=========  (Fri Jul  4 10:40:04 2014) by ROOT version5.32/00
   TCanvas *invertedEWK3Integral = new TCanvas("invertedEWK3Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   invertedEWK3Integral->SetHighLightColor(2);
   invertedEWK3Integral->Range(-101.2658,-1.458589,531.6456,2.069019);
   invertedEWK3Integral->SetFillColor(0);
   invertedEWK3Integral->SetBorderMode(0);
   invertedEWK3Integral->SetBorderSize(2);
   invertedEWK3Integral->SetLogy();
   invertedEWK3Integral->SetTickx(1);
   invertedEWK3Integral->SetTicky(1);
   invertedEWK3Integral->SetLeftMargin(0.16);
   invertedEWK3Integral->SetRightMargin(0.05);
   invertedEWK3Integral->SetTopMargin(0.05);
   invertedEWK3Integral->SetBottomMargin(0.13);
   invertedEWK3Integral->SetFrameFillStyle(0);
   invertedEWK3Integral->SetFrameBorderMode(0);
   invertedEWK3Integral->SetFrameFillStyle(0);
   invertedEWK3Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__39 = new TH1F("hframe__39","",1000,0,500);
   hframe__39->SetMinimum(0.1);
   hframe__39->SetMaximum(78.09771);
   hframe__39->SetDirectory(0);
   hframe__39->SetStats(0);
   hframe__39->SetLineStyle(0);
   hframe__39->SetMarkerStyle(20);
   hframe__39->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__39->GetXaxis()->SetLabelFont(43);
   hframe__39->GetXaxis()->SetLabelOffset(0.007);
   hframe__39->GetXaxis()->SetLabelSize(27);
   hframe__39->GetXaxis()->SetTitleSize(33);
   hframe__39->GetXaxis()->SetTitleOffset(0.9);
   hframe__39->GetXaxis()->SetTitleFont(43);
   hframe__39->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__39->GetYaxis()->SetLabelFont(43);
   hframe__39->GetYaxis()->SetLabelOffset(0.007);
   hframe__39->GetYaxis()->SetLabelSize(27);
   hframe__39->GetYaxis()->SetTitleSize(33);
   hframe__39->GetYaxis()->SetTitleOffset(1.25);
   hframe__39->GetYaxis()->SetTitleFont(43);
   hframe__39->GetZaxis()->SetLabelFont(43);
   hframe__39->GetZaxis()->SetLabelOffset(0.007);
   hframe__39->GetZaxis()->SetLabelSize(27);
   hframe__39->GetZaxis()->SetTitleSize(33);
   hframe__39->GetZaxis()->SetTitleFont(43);
   hframe__39->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 466 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3","#tau p_{T}=70..80",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(1,4.705564);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(2,7.441047);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(3,19.47235);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(4,16.7228);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(5,20.07917);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(6,21.32237);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(7,22.05035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(8,24.92881);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(9,20.51235);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(10,28.08167);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(11,34.05982);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(12,23.39473);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(13,39.04885);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(14,29.72145);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(15,27.36497);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(16,14.75135);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(17,19.94394);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(18,9.739013);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(19,18.35065);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(20,11.09077);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(21,6.867891);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(22,9.367542);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(23,4.52354);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(24,2.794146);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(25,4.232475);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(26,5.411064);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(27,3.773358);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(28,2.328654);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(29,4.419355);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(30,2.177811);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(31,0.4359111);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(32,0.7455409);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(33,1.509096);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(34,0.9512646);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(35,0.8933298);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(36,0.3985075);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(38,0.328458);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(39,0.4178914);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(43,0.8117809);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(46,0.4182121);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(47,0.4202334);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(51,0.626588);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(1,1.66059);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(2,1.997726);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(3,5.498411);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(4,3.11664);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(5,3.71901);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(6,4.233867);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(7,4.225309);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(8,5.156418);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(9,3.42309);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(10,4.056716);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(11,6.934106);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(12,4.264868);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(13,6.989713);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(14,4.376394);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(15,4.464088);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(16,2.700199);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(17,3.620227);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(18,2.249671);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(19,4.056711);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(20,2.428529);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(21,1.952254);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(22,3.896621);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(23,1.43292);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(24,1.251081);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(25,1.491229);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(26,1.578986);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(27,1.840497);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(28,1.145124);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(29,3.0341);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(30,1.162496);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(31,0.4062117);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(32,0.5020344);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(33,0.8815);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(34,0.6242057);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(35,0.8460265);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(36,0.3985075);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(38,0.328458);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(39,0.4178914);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(43,0.5740171);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(46,0.4182121);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(47,0.4202334);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(51,0.533464);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetEntries(1030);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->Draw("HIST same");
   
   TH1F *hframe__40 = new TH1F("hframe__40","",1000,0,500);
   hframe__40->SetMinimum(0.1);
   hframe__40->SetMaximum(78.09771);
   hframe__40->SetDirectory(0);
   hframe__40->SetStats(0);
   hframe__40->SetLineStyle(0);
   hframe__40->SetMarkerStyle(20);
   hframe__40->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__40->GetXaxis()->SetLabelFont(43);
   hframe__40->GetXaxis()->SetLabelOffset(0.007);
   hframe__40->GetXaxis()->SetLabelSize(27);
   hframe__40->GetXaxis()->SetTitleSize(33);
   hframe__40->GetXaxis()->SetTitleOffset(0.9);
   hframe__40->GetXaxis()->SetTitleFont(43);
   hframe__40->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__40->GetYaxis()->SetLabelFont(43);
   hframe__40->GetYaxis()->SetLabelOffset(0.007);
   hframe__40->GetYaxis()->SetLabelSize(27);
   hframe__40->GetYaxis()->SetTitleSize(33);
   hframe__40->GetYaxis()->SetTitleOffset(1.25);
   hframe__40->GetYaxis()->SetTitleFont(43);
   hframe__40->GetZaxis()->SetLabelFont(43);
   hframe__40->GetZaxis()->SetLabelOffset(0.007);
   hframe__40->GetZaxis()->SetLabelSize(27);
   hframe__40->GetZaxis()->SetTitleSize(33);
   hframe__40->GetZaxis()->SetTitleFont(43);
   hframe__40->Draw("sameaxis");
   invertedEWK3Integral->Modified();
   invertedEWK3Integral->cd();
   invertedEWK3Integral->SetSelected(invertedEWK3Integral);
}
