{
//=========Macro generated from canvas: invertedEWKGenuineTausInclusiveIntegral/
//=========  (Wed Aug 13 15:50:04 2014) by ROOT version5.32/00
   TCanvas *invertedEWKGenuineTausInclusiveIntegral = new TCanvas("invertedEWKGenuineTausInclusiveIntegral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKGenuineTausInclusiveIntegral->SetHighLightColor(2);
   invertedEWKGenuineTausInclusiveIntegral->Range(-101.2658,-1.355926,531.6456,1.381968);
   invertedEWKGenuineTausInclusiveIntegral->SetFillColor(0);
   invertedEWKGenuineTausInclusiveIntegral->SetBorderMode(0);
   invertedEWKGenuineTausInclusiveIntegral->SetBorderSize(2);
   invertedEWKGenuineTausInclusiveIntegral->SetLogy();
   invertedEWKGenuineTausInclusiveIntegral->SetTickx(1);
   invertedEWKGenuineTausInclusiveIntegral->SetTicky(1);
   invertedEWKGenuineTausInclusiveIntegral->SetLeftMargin(0.16);
   invertedEWKGenuineTausInclusiveIntegral->SetRightMargin(0.05);
   invertedEWKGenuineTausInclusiveIntegral->SetTopMargin(0.05);
   invertedEWKGenuineTausInclusiveIntegral->SetBottomMargin(0.13);
   invertedEWKGenuineTausInclusiveIntegral->SetFrameFillStyle(0);
   invertedEWKGenuineTausInclusiveIntegral->SetFrameBorderMode(0);
   invertedEWKGenuineTausInclusiveIntegral->SetFrameFillStyle(0);
   invertedEWKGenuineTausInclusiveIntegral->SetFrameBorderMode(0);
   
   TH1F *hframe__129 = new TH1F("hframe__129","",1000,0,500);
   hframe__129->SetMinimum(0.1);
   hframe__129->SetMaximum(17.58221);
   hframe__129->SetDirectory(0);
   hframe__129->SetStats(0);
   hframe__129->SetLineStyle(0);
   hframe__129->SetMarkerStyle(20);
   hframe__129->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__129->GetXaxis()->SetLabelFont(43);
   hframe__129->GetXaxis()->SetLabelOffset(0.007);
   hframe__129->GetXaxis()->SetLabelSize(27);
   hframe__129->GetXaxis()->SetTitleSize(33);
   hframe__129->GetXaxis()->SetTitleOffset(0.9);
   hframe__129->GetXaxis()->SetTitleFont(43);
   hframe__129->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__129->GetYaxis()->SetLabelFont(43);
   hframe__129->GetYaxis()->SetLabelOffset(0.007);
   hframe__129->GetYaxis()->SetLabelSize(27);
   hframe__129->GetYaxis()->SetTitleSize(33);
   hframe__129->GetYaxis()->SetTitleOffset(1.25);
   hframe__129->GetYaxis()->SetTitleFont(43);
   hframe__129->GetZaxis()->SetLabelFont(43);
   hframe__129->GetZaxis()->SetLabelOffset(0.007);
   hframe__129->GetZaxis()->SetLabelSize(27);
   hframe__129->GetZaxis()->SetTitleSize(33);
   hframe__129->GetZaxis()->SetTitleFont(43);
   hframe__129->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 93 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive","METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(1,0.2155862);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(2,0.8631511);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(3,1.273272);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(4,5.529496);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(5,3.19743);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(6,4.486444);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(7,5.159297);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(8,6.014187);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(9,6.264813);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(10,8.791105);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(11,6.285677);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(12,7.687359);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(13,6.922993);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(14,6.677154);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(15,4.806133);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(16,4.08761);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(17,2.363043);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(18,2.699538);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(19,2.557997);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(20,1.292456);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(21,1.621815);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(22,0.8360461);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(23,0.273937);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(24,0.4906401);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(25,0.3090143);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(26,0.245758);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(27,0.4194195);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(29,0.08778214);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(30,0.080165);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(31,0.1596902);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(32,0.4567913);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(33,0.03897451);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(35,0.1708174);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(39,0.2625517);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(41,0.1701199);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinContent(51,0.01919733);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(1,0.1233753);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(2,0.3027017);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(3,0.3396243);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(4,1.396112);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(5,0.7677475);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(6,1.059399);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(7,1.028096);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(8,1.084692);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(9,0.9433358);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(10,1.303519);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(11,0.8879569);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(12,1.079999);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(13,1.139387);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(14,1.16275);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(15,0.7423735);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(16,0.6947859);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(17,0.4885613);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(18,0.657447);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(19,0.6966536);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(20,0.4691445);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(21,0.4498906);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(22,0.2982347);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(23,0.1558995);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(24,0.2062884);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(25,0.1732995);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(26,0.1428698);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(27,0.1888571);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(29,0.08778215);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(30,0.080165);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(31,0.1130658);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(32,0.1929944);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(33,0.03897451);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(35,0.1207049);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(39,0.1779298);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(41,0.1701199);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetBinError(51,0.01919733);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetEntries(1086);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTausInclusive->Draw("HIST same");
   
   TH1F *hframe__130 = new TH1F("hframe__130","",1000,0,500);
   hframe__130->SetMinimum(0.1);
   hframe__130->SetMaximum(17.58221);
   hframe__130->SetDirectory(0);
   hframe__130->SetStats(0);
   hframe__130->SetLineStyle(0);
   hframe__130->SetMarkerStyle(20);
   hframe__130->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__130->GetXaxis()->SetLabelFont(43);
   hframe__130->GetXaxis()->SetLabelOffset(0.007);
   hframe__130->GetXaxis()->SetLabelSize(27);
   hframe__130->GetXaxis()->SetTitleSize(33);
   hframe__130->GetXaxis()->SetTitleOffset(0.9);
   hframe__130->GetXaxis()->SetTitleFont(43);
   hframe__130->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__130->GetYaxis()->SetLabelFont(43);
   hframe__130->GetYaxis()->SetLabelOffset(0.007);
   hframe__130->GetYaxis()->SetLabelSize(27);
   hframe__130->GetYaxis()->SetTitleSize(33);
   hframe__130->GetYaxis()->SetTitleOffset(1.25);
   hframe__130->GetYaxis()->SetTitleFont(43);
   hframe__130->GetZaxis()->SetLabelFont(43);
   hframe__130->GetZaxis()->SetLabelOffset(0.007);
   hframe__130->GetZaxis()->SetLabelSize(27);
   hframe__130->GetZaxis()->SetTitleSize(33);
   hframe__130->GetZaxis()->SetTitleFont(43);
   hframe__130->Draw("sameaxis");
   invertedEWKGenuineTausInclusiveIntegral->Modified();
   invertedEWKGenuineTausInclusiveIntegral->cd();
   invertedEWKGenuineTausInclusiveIntegral->SetSelected(invertedEWKGenuineTausInclusiveIntegral);
}
