{
//=========Macro generated from canvas: invertedtaup_Tgt120Integral/
//=========  (Wed Aug 13 15:50:02 2014) by ROOT version5.32/00
   TCanvas *invertedtaup_Tgt120Integral = new TCanvas("invertedtaup_Tgt120Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedtaup_Tgt120Integral->SetHighLightColor(2);
   invertedtaup_Tgt120Integral->Range(-101.2658,-1.789455,531.6456,4.283276);
   invertedtaup_Tgt120Integral->SetFillColor(0);
   invertedtaup_Tgt120Integral->SetBorderMode(0);
   invertedtaup_Tgt120Integral->SetBorderSize(2);
   invertedtaup_Tgt120Integral->SetLogy();
   invertedtaup_Tgt120Integral->SetTickx(1);
   invertedtaup_Tgt120Integral->SetTicky(1);
   invertedtaup_Tgt120Integral->SetLeftMargin(0.16);
   invertedtaup_Tgt120Integral->SetRightMargin(0.05);
   invertedtaup_Tgt120Integral->SetTopMargin(0.05);
   invertedtaup_Tgt120Integral->SetBottomMargin(0.13);
   invertedtaup_Tgt120Integral->SetFrameFillStyle(0);
   invertedtaup_Tgt120Integral->SetFrameBorderMode(0);
   invertedtaup_Tgt120Integral->SetFrameFillStyle(0);
   invertedtaup_Tgt120Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__109 = new TH1F("hframe__109","",1000,0,500);
   hframe__109->SetMinimum(0.1);
   hframe__109->SetMaximum(9542);
   hframe__109->SetDirectory(0);
   hframe__109->SetStats(0);
   hframe__109->SetLineStyle(0);
   hframe__109->SetMarkerStyle(20);
   hframe__109->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__109->GetXaxis()->SetLabelFont(43);
   hframe__109->GetXaxis()->SetLabelOffset(0.007);
   hframe__109->GetXaxis()->SetLabelSize(27);
   hframe__109->GetXaxis()->SetTitleSize(33);
   hframe__109->GetXaxis()->SetTitleOffset(0.9);
   hframe__109->GetXaxis()->SetTitleFont(43);
   hframe__109->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__109->GetYaxis()->SetLabelFont(43);
   hframe__109->GetYaxis()->SetLabelOffset(0.007);
   hframe__109->GetYaxis()->SetLabelSize(27);
   hframe__109->GetYaxis()->SetTitleSize(33);
   hframe__109->GetYaxis()->SetTitleOffset(1.25);
   hframe__109->GetYaxis()->SetTitleFont(43);
   hframe__109->GetZaxis()->SetLabelFont(43);
   hframe__109->GetZaxis()->SetLabelOffset(0.007);
   hframe__109->GetZaxis()->SetLabelSize(27);
   hframe__109->GetZaxis()->SetTitleSize(33);
   hframe__109->GetZaxis()->SetTitleFont(43);
   hframe__109->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 21583 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6","#tau p_{T}>120",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(1,1699);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(2,4274);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(3,4771);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(4,4122);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(5,2829);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(6,1689);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(7,982);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(8,545);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(9,265);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(10,136);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(11,93);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(12,43);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(13,26);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(14,22);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(15,15);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(16,13);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(17,9);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(18,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(19,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(20,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(21,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(22,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(23,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(24,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(25,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(26,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(27,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(28,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(31,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(32,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinContent(48,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(1,41.21893);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(2,65.37584);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(3,69.07243);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(4,64.2028);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(5,53.18834);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(6,41.09745);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(7,31.33688);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(8,23.34524);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(9,16.27882);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(10,11.6619);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(11,9.643651);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(12,6.557439);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(13,5.09902);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(14,4.690416);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(15,3.872983);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(16,3.605551);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(17,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(18,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(19,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(20,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(21,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(22,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(23,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(24,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(25,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(26,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(27,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(28,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(31,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(32,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetBinError(48,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetEntries(21583);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts6->Draw("HIST same");
   
   TH1F *hframe__110 = new TH1F("hframe__110","",1000,0,500);
   hframe__110->SetMinimum(0.1);
   hframe__110->SetMaximum(9542);
   hframe__110->SetDirectory(0);
   hframe__110->SetStats(0);
   hframe__110->SetLineStyle(0);
   hframe__110->SetMarkerStyle(20);
   hframe__110->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__110->GetXaxis()->SetLabelFont(43);
   hframe__110->GetXaxis()->SetLabelOffset(0.007);
   hframe__110->GetXaxis()->SetLabelSize(27);
   hframe__110->GetXaxis()->SetTitleSize(33);
   hframe__110->GetXaxis()->SetTitleOffset(0.9);
   hframe__110->GetXaxis()->SetTitleFont(43);
   hframe__110->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__110->GetYaxis()->SetLabelFont(43);
   hframe__110->GetYaxis()->SetLabelOffset(0.007);
   hframe__110->GetYaxis()->SetLabelSize(27);
   hframe__110->GetYaxis()->SetTitleSize(33);
   hframe__110->GetYaxis()->SetTitleOffset(1.25);
   hframe__110->GetYaxis()->SetTitleFont(43);
   hframe__110->GetZaxis()->SetLabelFont(43);
   hframe__110->GetZaxis()->SetLabelOffset(0.007);
   hframe__110->GetZaxis()->SetLabelSize(27);
   hframe__110->GetZaxis()->SetTitleSize(33);
   hframe__110->GetZaxis()->SetTitleFont(43);
   hframe__110->Draw("sameaxis");
   invertedtaup_Tgt120Integral->Modified();
   invertedtaup_Tgt120Integral->cd();
   invertedtaup_Tgt120Integral->SetSelected(invertedtaup_Tgt120Integral);
}
