{
//=========Macro generated from canvas: invertedEWKGenuineTaus4Integral/
//=========  (Sun Jul 20 15:00:34 2014) by ROOT version5.32/00
   TCanvas *invertedEWKGenuineTaus4Integral = new TCanvas("invertedEWKGenuineTaus4Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKGenuineTaus4Integral->SetHighLightColor(2);
   invertedEWKGenuineTaus4Integral->Range(-101.2658,-1.416216,531.6456,1.785448);
   invertedEWKGenuineTaus4Integral->SetFillColor(0);
   invertedEWKGenuineTaus4Integral->SetBorderMode(0);
   invertedEWKGenuineTaus4Integral->SetBorderSize(2);
   invertedEWKGenuineTaus4Integral->SetLogy();
   invertedEWKGenuineTaus4Integral->SetTickx(1);
   invertedEWKGenuineTaus4Integral->SetTicky(1);
   invertedEWKGenuineTaus4Integral->SetLeftMargin(0.16);
   invertedEWKGenuineTaus4Integral->SetRightMargin(0.05);
   invertedEWKGenuineTaus4Integral->SetTopMargin(0.05);
   invertedEWKGenuineTaus4Integral->SetBottomMargin(0.13);
   invertedEWKGenuineTaus4Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaus4Integral->SetFrameBorderMode(0);
   invertedEWKGenuineTaus4Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaus4Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__75 = new TH1F("hframe__75","",1000,0,500);
   hframe__75->SetMinimum(0.1);
   hframe__75->SetMaximum(42.20512);
   hframe__75->SetDirectory(0);
   hframe__75->SetStats(0);
   hframe__75->SetLineStyle(0);
   hframe__75->SetMarkerStyle(20);
   hframe__75->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__75->GetXaxis()->SetLabelFont(43);
   hframe__75->GetXaxis()->SetLabelOffset(0.007);
   hframe__75->GetXaxis()->SetLabelSize(27);
   hframe__75->GetXaxis()->SetTitleSize(33);
   hframe__75->GetXaxis()->SetTitleOffset(0.9);
   hframe__75->GetXaxis()->SetTitleFont(43);
   hframe__75->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__75->GetYaxis()->SetLabelFont(43);
   hframe__75->GetYaxis()->SetLabelOffset(0.007);
   hframe__75->GetYaxis()->SetLabelSize(27);
   hframe__75->GetYaxis()->SetTitleSize(33);
   hframe__75->GetYaxis()->SetTitleOffset(1.25);
   hframe__75->GetYaxis()->SetTitleFont(43);
   hframe__75->GetZaxis()->SetLabelFont(43);
   hframe__75->GetZaxis()->SetLabelOffset(0.007);
   hframe__75->GetZaxis()->SetLabelSize(27);
   hframe__75->GetZaxis()->SetTitleSize(33);
   hframe__75->GetZaxis()->SetTitleFont(43);
   hframe__75->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 224 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4","#tau p_{T}=80..100",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(1,0.3853355);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(2,0.3758903);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(3,2.504717);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(4,3.421497);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(5,8.29839);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(6,2.900331);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(7,8.200897);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(8,5.116469);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(9,8.558113);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(10,11.57029);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(11,17.0908);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(12,21.10256);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(13,9.392612);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(14,13.26576);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(15,14.5116);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(16,8.823538);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(17,14.34945);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(18,9.409343);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(19,6.749579);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(20,6.519011);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(21,9.595824);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(22,4.953078);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(23,5.965177);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(24,3.284351);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(25,3.24307);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(26,3.205685);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(27,1.595299);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(28,3.741202);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(29,2.195537);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(30,3.127364);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(31,2.71076);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(32,2.955005);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(33,0.3971731);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(34,0.7637593);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(35,0.5098783);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(37,0.7904312);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(39,0.5842161);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(41,0.7643656);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(43,0.06301269);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(44,0.3801723);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(47,0.001912265);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(49,0.4003208);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinContent(51,2.523462);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(1,0.3853355);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(2,0.3758903);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(3,1.138743);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(4,2.488321);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(5,3.578414);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(6,1.155795);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(7,4.090864);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(8,1.589509);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(9,2.285306);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(10,3.951677);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(11,3.651924);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(12,4.833847);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(13,2.051814);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(14,2.898309);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(15,3.150189);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(16,2.178809);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(17,3.075602);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(18,2.316963);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(19,1.793);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(20,1.965253);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(21,2.565123);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(22,1.450555);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(23,1.610528);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(24,1.292369);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(25,1.132216);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(26,1.354326);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(27,0.7114811);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(28,1.760295);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(29,1.17983);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(30,1.250476);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(31,1.378804);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(32,1.377616);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(33,0.3971731);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(34,0.4537033);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(35,0.5098783);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(37,0.7314394);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(39,0.4616866);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(41,0.7643656);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(43,0.06301268);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(44,0.3801723);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(47,0.001912265);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(49,0.4003208);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetBinError(51,1.15766);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetEntries(523);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus4->Draw("HIST same");
   
   TH1F *hframe__76 = new TH1F("hframe__76","",1000,0,500);
   hframe__76->SetMinimum(0.1);
   hframe__76->SetMaximum(42.20512);
   hframe__76->SetDirectory(0);
   hframe__76->SetStats(0);
   hframe__76->SetLineStyle(0);
   hframe__76->SetMarkerStyle(20);
   hframe__76->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__76->GetXaxis()->SetLabelFont(43);
   hframe__76->GetXaxis()->SetLabelOffset(0.007);
   hframe__76->GetXaxis()->SetLabelSize(27);
   hframe__76->GetXaxis()->SetTitleSize(33);
   hframe__76->GetXaxis()->SetTitleOffset(0.9);
   hframe__76->GetXaxis()->SetTitleFont(43);
   hframe__76->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__76->GetYaxis()->SetLabelFont(43);
   hframe__76->GetYaxis()->SetLabelOffset(0.007);
   hframe__76->GetYaxis()->SetLabelSize(27);
   hframe__76->GetYaxis()->SetTitleSize(33);
   hframe__76->GetYaxis()->SetTitleOffset(1.25);
   hframe__76->GetYaxis()->SetTitleFont(43);
   hframe__76->GetZaxis()->SetLabelFont(43);
   hframe__76->GetZaxis()->SetLabelOffset(0.007);
   hframe__76->GetZaxis()->SetLabelSize(27);
   hframe__76->GetZaxis()->SetTitleSize(33);
   hframe__76->GetZaxis()->SetTitleFont(43);
   hframe__76->Draw("sameaxis");
   invertedEWKGenuineTaus4Integral->Modified();
   invertedEWKGenuineTaus4Integral->cd();
   invertedEWKGenuineTaus4Integral->SetSelected(invertedEWKGenuineTaus4Integral);
}
