{
//=========Macro generated from canvas: invertedEWKFakeTaustaup_Teq50to60Integral/
//=========  (Fri Aug  1 09:24:31 2014) by ROOT version5.32/00
   TCanvas *invertedEWKFakeTaustaup_Teq50to60Integral = new TCanvas("invertedEWKFakeTaustaup_Teq50to60Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetHighLightColor(2);
   invertedEWKFakeTaustaup_Teq50to60Integral->Range(-101.2658,-1.406749,531.6456,1.722092);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetFillColor(0);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetBorderMode(0);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetBorderSize(2);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetLogy();
   invertedEWKFakeTaustaup_Teq50to60Integral->SetTickx(1);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetTicky(1);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetLeftMargin(0.16);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetRightMargin(0.05);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetTopMargin(0.05);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetBottomMargin(0.13);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetFrameBorderMode(0);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq50to60Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__23 = new TH1F("hframe__23","",1000,0,500);
   hframe__23->SetMinimum(0.1);
   hframe__23->SetMaximum(36.78325);
   hframe__23->SetDirectory(0);
   hframe__23->SetStats(0);
   hframe__23->SetLineStyle(0);
   hframe__23->SetMarkerStyle(20);
   hframe__23->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__23->GetXaxis()->SetLabelFont(43);
   hframe__23->GetXaxis()->SetLabelOffset(0.007);
   hframe__23->GetXaxis()->SetLabelSize(27);
   hframe__23->GetXaxis()->SetTitleSize(33);
   hframe__23->GetXaxis()->SetTitleOffset(0.9);
   hframe__23->GetXaxis()->SetTitleFont(43);
   hframe__23->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__23->GetYaxis()->SetLabelFont(43);
   hframe__23->GetYaxis()->SetLabelOffset(0.007);
   hframe__23->GetYaxis()->SetLabelSize(27);
   hframe__23->GetYaxis()->SetTitleSize(33);
   hframe__23->GetYaxis()->SetTitleOffset(1.25);
   hframe__23->GetYaxis()->SetTitleFont(43);
   hframe__23->GetZaxis()->SetLabelFont(43);
   hframe__23->GetZaxis()->SetLabelOffset(0.007);
   hframe__23->GetZaxis()->SetLabelSize(27);
   hframe__23->GetZaxis()->SetTitleSize(33);
   hframe__23->GetZaxis()->SetTitleFont(43);
   hframe__23->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 150 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1","#tau p_{T}=50..60",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(1,0.2385248);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(2,0.07998654);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(3,3.001214);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(4,9.809807);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(5,0.9316543);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(6,5.11749);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(7,13.05476);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(8,13.35406);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(9,10.06822);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(10,18.39162);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(11,11.69552);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(12,9.192458);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(13,8.811086);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(14,10.63568);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(15,12.22128);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(16,6.511426);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(17,2.048121);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(18,3.775403);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(19,6.547297);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(20,1.480127);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(21,0.0019412);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(22,1.808481);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(24,0.09173871);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(26,0.0357853);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(27,0.04625252);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(29,1.345099);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinContent(37,0.004344337);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(1,0.1526018);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(2,0.05827086);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(3,2.002177);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(4,9.10874);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(5,0.3636103);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(6,2.436947);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(7,5.293515);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(8,4.358675);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(9,3.741531);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(10,5.422679);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(11,4.089127);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(12,3.681183);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(13,3.68049);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(14,4.257492);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(15,4.195148);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(16,2.91829);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(17,1.965081);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(18,2.255762);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(19,3.059742);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(20,1.364829);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(21,0.0019412);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(22,1.808481);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(24,0.06650522);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(26,0.03578529);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(27,0.04625252);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(29,1.170733);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetBinError(37,0.004344337);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetEntries(250);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus1->Draw("HIST same");
   
   TH1F *hframe__24 = new TH1F("hframe__24","",1000,0,500);
   hframe__24->SetMinimum(0.1);
   hframe__24->SetMaximum(36.78325);
   hframe__24->SetDirectory(0);
   hframe__24->SetStats(0);
   hframe__24->SetLineStyle(0);
   hframe__24->SetMarkerStyle(20);
   hframe__24->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__24->GetXaxis()->SetLabelFont(43);
   hframe__24->GetXaxis()->SetLabelOffset(0.007);
   hframe__24->GetXaxis()->SetLabelSize(27);
   hframe__24->GetXaxis()->SetTitleSize(33);
   hframe__24->GetXaxis()->SetTitleOffset(0.9);
   hframe__24->GetXaxis()->SetTitleFont(43);
   hframe__24->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__24->GetYaxis()->SetLabelFont(43);
   hframe__24->GetYaxis()->SetLabelOffset(0.007);
   hframe__24->GetYaxis()->SetLabelSize(27);
   hframe__24->GetYaxis()->SetTitleSize(33);
   hframe__24->GetYaxis()->SetTitleOffset(1.25);
   hframe__24->GetYaxis()->SetTitleFont(43);
   hframe__24->GetZaxis()->SetLabelFont(43);
   hframe__24->GetZaxis()->SetLabelOffset(0.007);
   hframe__24->GetZaxis()->SetLabelSize(27);
   hframe__24->GetZaxis()->SetTitleSize(33);
   hframe__24->GetZaxis()->SetTitleFont(43);
   hframe__24->Draw("sameaxis");
   invertedEWKFakeTaustaup_Teq50to60Integral->Modified();
   invertedEWKFakeTaustaup_Teq50to60Integral->cd();
   invertedEWKFakeTaustaup_Teq50to60Integral->SetSelected(invertedEWKFakeTaustaup_Teq50to60Integral);
}
