{
//=========Macro generated from canvas: invertedtaup_Teq50to60Integral/
//=========  (Fri Aug  1 09:24:31 2014) by ROOT version5.32/00
   TCanvas *invertedtaup_Teq50to60Integral = new TCanvas("invertedtaup_Teq50to60Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedtaup_Teq50to60Integral->SetHighLightColor(2);
   invertedtaup_Teq50to60Integral->Range(-101.2658,-1.791236,531.6456,4.295193);
   invertedtaup_Teq50to60Integral->SetFillColor(0);
   invertedtaup_Teq50to60Integral->SetBorderMode(0);
   invertedtaup_Teq50to60Integral->SetBorderSize(2);
   invertedtaup_Teq50to60Integral->SetLogy();
   invertedtaup_Teq50to60Integral->SetTickx(1);
   invertedtaup_Teq50to60Integral->SetTicky(1);
   invertedtaup_Teq50to60Integral->SetLeftMargin(0.16);
   invertedtaup_Teq50to60Integral->SetRightMargin(0.05);
   invertedtaup_Teq50to60Integral->SetTopMargin(0.05);
   invertedtaup_Teq50to60Integral->SetBottomMargin(0.13);
   invertedtaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedtaup_Teq50to60Integral->SetFrameBorderMode(0);
   invertedtaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedtaup_Teq50to60Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__19 = new TH1F("hframe__19","",1000,0,500);
   hframe__19->SetMinimum(0.1);
   hframe__19->SetMaximum(9792);
   hframe__19->SetDirectory(0);
   hframe__19->SetStats(0);
   hframe__19->SetLineStyle(0);
   hframe__19->SetMarkerStyle(20);
   hframe__19->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__19->GetXaxis()->SetLabelFont(43);
   hframe__19->GetXaxis()->SetLabelOffset(0.007);
   hframe__19->GetXaxis()->SetLabelSize(27);
   hframe__19->GetXaxis()->SetTitleSize(33);
   hframe__19->GetXaxis()->SetTitleOffset(0.9);
   hframe__19->GetXaxis()->SetTitleFont(43);
   hframe__19->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__19->GetYaxis()->SetLabelFont(43);
   hframe__19->GetYaxis()->SetLabelOffset(0.007);
   hframe__19->GetYaxis()->SetLabelSize(27);
   hframe__19->GetYaxis()->SetTitleSize(33);
   hframe__19->GetYaxis()->SetTitleOffset(1.25);
   hframe__19->GetYaxis()->SetTitleFont(43);
   hframe__19->GetZaxis()->SetLabelFont(43);
   hframe__19->GetZaxis()->SetLabelOffset(0.007);
   hframe__19->GetZaxis()->SetLabelSize(27);
   hframe__19->GetZaxis()->SetTitleSize(33);
   hframe__19->GetZaxis()->SetTitleFont(43);
   hframe__19->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 26316 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1","#tau p_{T}=50..60",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(1,1355);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(2,3706);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(3,4896);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(4,4660);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(5,3939);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(6,2800);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(7,1689);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(8,1055);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(9,617);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(10,411);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(11,243);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(12,202);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(13,146);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(14,115);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(15,111);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(16,82);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(17,65);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(18,46);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(19,31);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(20,27);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(21,18);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(22,18);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(23,14);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(24,18);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(25,5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(26,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(27,5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(28,5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(29,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(30,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(31,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(32,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(34,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(37,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(39,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(40,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(41,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(44,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(45,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinContent(46,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(1,36.81032);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(2,60.87693);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(3,69.97142);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(4,68.26419);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(5,62.76145);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(6,52.91503);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(7,41.09745);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(8,32.48076);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(9,24.83948);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(10,20.27313);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(11,15.58846);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(12,14.21267);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(13,12.08305);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(14,10.72381);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(15,10.53565);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(16,9.055385);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(17,8.062258);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(18,6.78233);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(19,5.567764);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(20,5.196152);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(21,4.242641);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(22,4.242641);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(23,3.741657);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(24,4.242641);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(25,2.236068);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(26,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(27,2.236068);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(28,2.236068);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(29,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(30,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(31,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(32,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(34,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(37,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(39,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(40,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(41,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(44,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(45,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetBinError(46,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetEntries(26316);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts1->Draw("HIST same");
   
   TH1F *hframe__20 = new TH1F("hframe__20","",1000,0,500);
   hframe__20->SetMinimum(0.1);
   hframe__20->SetMaximum(9792);
   hframe__20->SetDirectory(0);
   hframe__20->SetStats(0);
   hframe__20->SetLineStyle(0);
   hframe__20->SetMarkerStyle(20);
   hframe__20->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__20->GetXaxis()->SetLabelFont(43);
   hframe__20->GetXaxis()->SetLabelOffset(0.007);
   hframe__20->GetXaxis()->SetLabelSize(27);
   hframe__20->GetXaxis()->SetTitleSize(33);
   hframe__20->GetXaxis()->SetTitleOffset(0.9);
   hframe__20->GetXaxis()->SetTitleFont(43);
   hframe__20->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__20->GetYaxis()->SetLabelFont(43);
   hframe__20->GetYaxis()->SetLabelOffset(0.007);
   hframe__20->GetYaxis()->SetLabelSize(27);
   hframe__20->GetYaxis()->SetTitleSize(33);
   hframe__20->GetYaxis()->SetTitleOffset(1.25);
   hframe__20->GetYaxis()->SetTitleFont(43);
   hframe__20->GetZaxis()->SetLabelFont(43);
   hframe__20->GetZaxis()->SetLabelOffset(0.007);
   hframe__20->GetZaxis()->SetLabelSize(27);
   hframe__20->GetZaxis()->SetTitleSize(33);
   hframe__20->GetZaxis()->SetTitleFont(43);
   hframe__20->Draw("sameaxis");
   invertedtaup_Teq50to60Integral->Modified();
   invertedtaup_Teq50to60Integral->cd();
   invertedtaup_Teq50to60Integral->SetSelected(invertedtaup_Teq50to60Integral);
}
