{
//=========Macro generated from canvas: invertedEWKGenuineTaustaup_Teq50to60Integral/
//=========  (Wed Aug 13 15:49:49 2014) by ROOT version5.32/00
   TCanvas *invertedEWKGenuineTaustaup_Teq50to60Integral = new TCanvas("invertedEWKGenuineTaustaup_Teq50to60Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetHighLightColor(2);
   invertedEWKGenuineTaustaup_Teq50to60Integral->Range(-101.2658,-1.257808,531.6456,0.7253324);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetFillColor(0);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetBorderMode(0);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetBorderSize(2);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetLogy();
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetTickx(1);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetTicky(1);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetLeftMargin(0.16);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetRightMargin(0.05);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetTopMargin(0.05);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetBottomMargin(0.13);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetFrameBorderMode(0);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__21 = new TH1F("hframe__21","",1000,0,500);
   hframe__21->SetMinimum(0.1);
   hframe__21->SetMaximum(4.228394);
   hframe__21->SetDirectory(0);
   hframe__21->SetStats(0);
   hframe__21->SetLineStyle(0);
   hframe__21->SetMarkerStyle(20);
   hframe__21->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__21->GetXaxis()->SetLabelFont(43);
   hframe__21->GetXaxis()->SetLabelOffset(0.007);
   hframe__21->GetXaxis()->SetLabelSize(27);
   hframe__21->GetXaxis()->SetTitleSize(33);
   hframe__21->GetXaxis()->SetTitleOffset(0.9);
   hframe__21->GetXaxis()->SetTitleFont(43);
   hframe__21->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__21->GetYaxis()->SetLabelFont(43);
   hframe__21->GetYaxis()->SetLabelOffset(0.007);
   hframe__21->GetYaxis()->SetLabelSize(27);
   hframe__21->GetYaxis()->SetTitleSize(33);
   hframe__21->GetYaxis()->SetTitleOffset(1.25);
   hframe__21->GetYaxis()->SetTitleFont(43);
   hframe__21->GetZaxis()->SetLabelFont(43);
   hframe__21->GetZaxis()->SetLabelOffset(0.007);
   hframe__21->GetZaxis()->SetLabelSize(27);
   hframe__21->GetZaxis()->SetTitleSize(33);
   hframe__21->GetZaxis()->SetTitleFont(43);
   hframe__21->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 21 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1","#tau p_{T}=50..60",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(1,0.08371486);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(2,0.3735234);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(3,0.1717074);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(4,1.671768);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(5,0.5406532);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(6,0.6462911);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(7,1.033574);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(8,1.231345);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(9,1.860954);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(10,1.627574);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(11,1.375639);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(12,1.847389);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(13,1.650398);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(14,2.114197);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(15,1.090931);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(16,0.6687564);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(17,0.4880638);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(18,0.1773439);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(19,1.161477);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(20,0.3512421);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(21,0.1161598);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(22,0.1328975);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(24,0.1027216);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(27,0.1026584);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(32,0.08415286);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinContent(35,0.0335737);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(1,0.08371485);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(2,0.2261944);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(3,0.1078072);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(4,0.6164391);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(5,0.2355921);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(6,0.215536);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(7,0.3228685);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(8,0.5560077);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(9,0.5625407);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(10,0.4118858);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(11,0.4447831);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(12,0.5694606);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(13,0.4355344);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(14,0.7167339);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(15,0.36508);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(16,0.2796197);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(17,0.2460538);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(18,0.124977);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(19,0.5871613);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(20,0.341032);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(21,0.1160003);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(22,0.1328975);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(24,0.08793518);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(27,0.1026584);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(32,0.08415286);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetBinError(35,0.0335737);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetEntries(239);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus1->Draw("HIST same");
   
   TH1F *hframe__22 = new TH1F("hframe__22","",1000,0,500);
   hframe__22->SetMinimum(0.1);
   hframe__22->SetMaximum(4.228394);
   hframe__22->SetDirectory(0);
   hframe__22->SetStats(0);
   hframe__22->SetLineStyle(0);
   hframe__22->SetMarkerStyle(20);
   hframe__22->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__22->GetXaxis()->SetLabelFont(43);
   hframe__22->GetXaxis()->SetLabelOffset(0.007);
   hframe__22->GetXaxis()->SetLabelSize(27);
   hframe__22->GetXaxis()->SetTitleSize(33);
   hframe__22->GetXaxis()->SetTitleOffset(0.9);
   hframe__22->GetXaxis()->SetTitleFont(43);
   hframe__22->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__22->GetYaxis()->SetLabelFont(43);
   hframe__22->GetYaxis()->SetLabelOffset(0.007);
   hframe__22->GetYaxis()->SetLabelSize(27);
   hframe__22->GetYaxis()->SetTitleSize(33);
   hframe__22->GetYaxis()->SetTitleOffset(1.25);
   hframe__22->GetYaxis()->SetTitleFont(43);
   hframe__22->GetZaxis()->SetLabelFont(43);
   hframe__22->GetZaxis()->SetLabelOffset(0.007);
   hframe__22->GetZaxis()->SetLabelSize(27);
   hframe__22->GetZaxis()->SetTitleSize(33);
   hframe__22->GetZaxis()->SetTitleFont(43);
   hframe__22->Draw("sameaxis");
   invertedEWKGenuineTaustaup_Teq50to60Integral->Modified();
   invertedEWKGenuineTaustaup_Teq50to60Integral->cd();
   invertedEWKGenuineTaustaup_Teq50to60Integral->SetSelected(invertedEWKGenuineTaustaup_Teq50to60Integral);
}
