{
//=========Macro generated from canvas: invertedInclusiveIntegral/
//=========  (Wed Aug 13 15:50:04 2014) by ROOT version5.32/00
   TCanvas *invertedInclusiveIntegral = new TCanvas("invertedInclusiveIntegral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedInclusiveIntegral->SetHighLightColor(2);
   invertedInclusiveIntegral->Range(-101.2658,-1.911854,531.6456,5.102408);
   invertedInclusiveIntegral->SetFillColor(0);
   invertedInclusiveIntegral->SetBorderMode(0);
   invertedInclusiveIntegral->SetBorderSize(2);
   invertedInclusiveIntegral->SetLogy();
   invertedInclusiveIntegral->SetTickx(1);
   invertedInclusiveIntegral->SetTicky(1);
   invertedInclusiveIntegral->SetLeftMargin(0.16);
   invertedInclusiveIntegral->SetRightMargin(0.05);
   invertedInclusiveIntegral->SetTopMargin(0.05);
   invertedInclusiveIntegral->SetBottomMargin(0.13);
   invertedInclusiveIntegral->SetFrameFillStyle(0);
   invertedInclusiveIntegral->SetFrameBorderMode(0);
   invertedInclusiveIntegral->SetFrameFillStyle(0);
   invertedInclusiveIntegral->SetFrameBorderMode(0);
   
   TH1F *hframe__127 = new TH1F("hframe__127","",1000,0,500);
   hframe__127->SetMinimum(0.1);
   hframe__127->SetMaximum(56454);
   hframe__127->SetDirectory(0);
   hframe__127->SetStats(0);
   hframe__127->SetLineStyle(0);
   hframe__127->SetMarkerStyle(20);
   hframe__127->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__127->GetXaxis()->SetLabelFont(43);
   hframe__127->GetXaxis()->SetLabelOffset(0.007);
   hframe__127->GetXaxis()->SetLabelSize(27);
   hframe__127->GetXaxis()->SetTitleSize(33);
   hframe__127->GetXaxis()->SetTitleOffset(0.9);
   hframe__127->GetXaxis()->SetTitleFont(43);
   hframe__127->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__127->GetYaxis()->SetLabelFont(43);
   hframe__127->GetYaxis()->SetLabelOffset(0.007);
   hframe__127->GetYaxis()->SetLabelSize(27);
   hframe__127->GetYaxis()->SetTitleSize(33);
   hframe__127->GetYaxis()->SetTitleOffset(1.25);
   hframe__127->GetYaxis()->SetTitleFont(43);
   hframe__127->GetZaxis()->SetLabelFont(43);
   hframe__127->GetZaxis()->SetLabelOffset(0.007);
   hframe__127->GetZaxis()->SetLabelSize(27);
   hframe__127->GetZaxis()->SetTitleSize(33);
   hframe__127->GetZaxis()->SetTitleFont(43);
   hframe__127->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 136977 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive","METInvertedTauIdAfterCollinearCutsInclusive",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(1,8725);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(2,22664);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(3,28227);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(4,26290);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(5,19841);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(6,12863);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(7,7517);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(8,4223);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(9,2244);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(10,1294);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(11,789);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(12,576);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(13,414);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(14,285);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(15,235);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(16,172);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(17,144);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(18,108);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(19,75);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(20,62);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(21,35);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(22,39);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(23,31);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(24,31);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(25,17);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(26,16);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(27,11);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(28,11);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(29,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(30,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(31,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(32,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(33,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(34,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(35,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(37,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(38,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(39,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(41,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(45,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(48,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(1,93.40771);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(2,150.5457);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(3,168.0089);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(4,162.1419);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(5,140.8581);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(6,113.4152);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(7,86.70063);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(8,64.98461);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(9,47.37088);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(10,35.97221);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(11,28.08914);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(12,24);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(13,20.34699);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(14,16.88194);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(15,15.32971);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(16,13.11488);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(17,12);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(18,10.3923);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(19,8.660254);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(20,7.874008);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(21,5.91608);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(22,6.244998);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(23,5.567764);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(24,5.567764);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(25,4.123106);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(26,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(27,3.316625);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(28,3.316625);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(29,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(30,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(31,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(32,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(33,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(34,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(35,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(37,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(38,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(39,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(41,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(45,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(48,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetEntries(136977);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->Draw("HIST same");
   
   TH1F *hframe__128 = new TH1F("hframe__128","",1000,0,500);
   hframe__128->SetMinimum(0.1);
   hframe__128->SetMaximum(56454);
   hframe__128->SetDirectory(0);
   hframe__128->SetStats(0);
   hframe__128->SetLineStyle(0);
   hframe__128->SetMarkerStyle(20);
   hframe__128->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__128->GetXaxis()->SetLabelFont(43);
   hframe__128->GetXaxis()->SetLabelOffset(0.007);
   hframe__128->GetXaxis()->SetLabelSize(27);
   hframe__128->GetXaxis()->SetTitleSize(33);
   hframe__128->GetXaxis()->SetTitleOffset(0.9);
   hframe__128->GetXaxis()->SetTitleFont(43);
   hframe__128->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__128->GetYaxis()->SetLabelFont(43);
   hframe__128->GetYaxis()->SetLabelOffset(0.007);
   hframe__128->GetYaxis()->SetLabelSize(27);
   hframe__128->GetYaxis()->SetTitleSize(33);
   hframe__128->GetYaxis()->SetTitleOffset(1.25);
   hframe__128->GetYaxis()->SetTitleFont(43);
   hframe__128->GetZaxis()->SetLabelFont(43);
   hframe__128->GetZaxis()->SetLabelOffset(0.007);
   hframe__128->GetZaxis()->SetLabelSize(27);
   hframe__128->GetZaxis()->SetTitleSize(33);
   hframe__128->GetZaxis()->SetTitleFont(43);
   hframe__128->Draw("sameaxis");
   invertedInclusiveIntegral->Modified();
   invertedInclusiveIntegral->cd();
   invertedInclusiveIntegral->SetSelected(invertedInclusiveIntegral);
}
