{
//=========Macro generated from canvas: invertedEWKFakeTaustaup_Teq120to150Integral/
//=========  (Thu Jul 31 09:28:38 2014) by ROOT version5.32/00
   TCanvas *invertedEWKFakeTaustaup_Teq120to150Integral = new TCanvas("invertedEWKFakeTaustaup_Teq120to150Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetHighLightColor(2);
   invertedEWKFakeTaustaup_Teq120to150Integral->Range(-101.2658,-1.356691,531.6456,1.387086);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetFillColor(0);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetBorderMode(0);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetBorderSize(2);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetLogy();
   invertedEWKFakeTaustaup_Teq120to150Integral->SetTickx(1);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetTicky(1);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetLeftMargin(0.16);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetRightMargin(0.05);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetTopMargin(0.05);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetBottomMargin(0.13);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetFrameBorderMode(0);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq120to150Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__113 = new TH1F("hframe__113","",1000,0,500);
   hframe__113->SetMinimum(0.1);
   hframe__113->SetMaximum(17.77857);
   hframe__113->SetDirectory(0);
   hframe__113->SetStats(0);
   hframe__113->SetLineStyle(0);
   hframe__113->SetMarkerStyle(20);
   hframe__113->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__113->GetXaxis()->SetLabelFont(43);
   hframe__113->GetXaxis()->SetLabelOffset(0.007);
   hframe__113->GetXaxis()->SetLabelSize(27);
   hframe__113->GetXaxis()->SetTitleSize(33);
   hframe__113->GetXaxis()->SetTitleOffset(0.9);
   hframe__113->GetXaxis()->SetTitleFont(43);
   hframe__113->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__113->GetYaxis()->SetLabelFont(43);
   hframe__113->GetYaxis()->SetLabelOffset(0.007);
   hframe__113->GetYaxis()->SetLabelSize(27);
   hframe__113->GetYaxis()->SetTitleSize(33);
   hframe__113->GetYaxis()->SetTitleOffset(1.25);
   hframe__113->GetYaxis()->SetTitleFont(43);
   hframe__113->GetZaxis()->SetLabelFont(43);
   hframe__113->GetZaxis()->SetLabelOffset(0.007);
   hframe__113->GetZaxis()->SetLabelSize(27);
   hframe__113->GetZaxis()->SetTitleSize(33);
   hframe__113->GetZaxis()->SetTitleFont(43);
   hframe__113->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 91 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6","#tau p_{T}=120..150",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(1,0.758155);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(2,1.981836);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(3,5.028875);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(4,8.01926);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(5,7.201947);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(6,6.628036);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(7,3.766417);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(8,6.839564);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(9,5.013684);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(10,8.889286);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(11,5.654876);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(12,3.615697);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(13,1.0839);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(14,3.018365);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(15,4.75544);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(16,2.223285);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(17,3.976266);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(18,1.218795);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(19,0.003240324);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(20,3.589924);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(21,0.6969615);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(22,1.273423);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(23,1.780239);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(24,0.3547527);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(26,0.5466465);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(27,0.1934918);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(28,0.01487785);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(29,0.356382);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(30,0.3513534);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(31,0.3493078);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(32,0.3546576);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(35,0.8133196);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(38,0.364712);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinContent(44,0.08616413);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(1,0.4427263);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(2,0.8621446);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(3,1.567285);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(4,2.695317);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(5,1.820073);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(6,1.840889);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(7,1.301588);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(8,1.980269);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(9,1.67564);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(10,3.084438);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(11,1.50169);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(12,1.247679);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(13,0.6851014);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(14,1.303429);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(15,2.053445);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(16,0.9178769);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(17,1.753842);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(18,0.7594491);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(19,0.003240324);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(20,1.388753);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(21,0.4786292);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(22,0.7050745);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(23,0.8720557);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(24,0.3547527);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(26,0.4229044);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(27,0.1934918);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(28,0.01487786);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(29,0.356382);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(30,0.3513534);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(31,0.3493078);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(32,0.3546576);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(35,0.8133197);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(38,0.364712);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetBinError(44,0.08616412);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetEntries(262);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus6->Draw("HIST same");
   
   TH1F *hframe__114 = new TH1F("hframe__114","",1000,0,500);
   hframe__114->SetMinimum(0.1);
   hframe__114->SetMaximum(17.77857);
   hframe__114->SetDirectory(0);
   hframe__114->SetStats(0);
   hframe__114->SetLineStyle(0);
   hframe__114->SetMarkerStyle(20);
   hframe__114->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__114->GetXaxis()->SetLabelFont(43);
   hframe__114->GetXaxis()->SetLabelOffset(0.007);
   hframe__114->GetXaxis()->SetLabelSize(27);
   hframe__114->GetXaxis()->SetTitleSize(33);
   hframe__114->GetXaxis()->SetTitleOffset(0.9);
   hframe__114->GetXaxis()->SetTitleFont(43);
   hframe__114->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__114->GetYaxis()->SetLabelFont(43);
   hframe__114->GetYaxis()->SetLabelOffset(0.007);
   hframe__114->GetYaxis()->SetLabelSize(27);
   hframe__114->GetYaxis()->SetTitleSize(33);
   hframe__114->GetYaxis()->SetTitleOffset(1.25);
   hframe__114->GetYaxis()->SetTitleFont(43);
   hframe__114->GetZaxis()->SetLabelFont(43);
   hframe__114->GetZaxis()->SetLabelOffset(0.007);
   hframe__114->GetZaxis()->SetLabelSize(27);
   hframe__114->GetZaxis()->SetTitleSize(33);
   hframe__114->GetZaxis()->SetTitleFont(43);
   hframe__114->Draw("sameaxis");
   invertedEWKFakeTaustaup_Teq120to150Integral->Modified();
   invertedEWKFakeTaustaup_Teq120to150Integral->cd();
   invertedEWKFakeTaustaup_Teq120to150Integral->SetSelected(invertedEWKFakeTaustaup_Teq120to150Integral);
}
