{
//=========Macro generated from canvas: invertedInclusiveIntegral/
//=========  (Fri Aug  1 09:24:46 2014) by ROOT version5.32/00
   TCanvas *invertedInclusiveIntegral = new TCanvas("invertedInclusiveIntegral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedInclusiveIntegral->SetHighLightColor(2);
   invertedInclusiveIntegral->Range(-101.2658,-1.918995,531.6456,5.150201);
   invertedInclusiveIntegral->SetFillColor(0);
   invertedInclusiveIntegral->SetBorderMode(0);
   invertedInclusiveIntegral->SetBorderSize(2);
   invertedInclusiveIntegral->SetLogy();
   invertedInclusiveIntegral->SetTickx(1);
   invertedInclusiveIntegral->SetTicky(1);
   invertedInclusiveIntegral->SetLeftMargin(0.16);
   invertedInclusiveIntegral->SetRightMargin(0.05);
   invertedInclusiveIntegral->SetTopMargin(0.05);
   invertedInclusiveIntegral->SetBottomMargin(0.13);
   invertedInclusiveIntegral->SetFrameFillStyle(0);
   invertedInclusiveIntegral->SetFrameBorderMode(0);
   invertedInclusiveIntegral->SetFrameFillStyle(0);
   invertedInclusiveIntegral->SetFrameBorderMode(0);
   
   TH1F *hframe__127 = new TH1F("hframe__127","",1000,0,500);
   hframe__127->SetMinimum(0.1);
   hframe__127->SetMaximum(62624);
   hframe__127->SetDirectory(0);
   hframe__127->SetStats(0);
   hframe__127->SetLineStyle(0);
   hframe__127->SetMarkerStyle(20);
   hframe__127->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__127->GetXaxis()->SetLabelFont(43);
   hframe__127->GetXaxis()->SetLabelOffset(0.007);
   hframe__127->GetXaxis()->SetLabelSize(27);
   hframe__127->GetXaxis()->SetTitleSize(33);
   hframe__127->GetXaxis()->SetTitleOffset(0.9);
   hframe__127->GetXaxis()->SetTitleFont(43);
   hframe__127->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__127->GetYaxis()->SetLabelFont(43);
   hframe__127->GetYaxis()->SetLabelOffset(0.007);
   hframe__127->GetYaxis()->SetLabelSize(27);
   hframe__127->GetYaxis()->SetTitleSize(33);
   hframe__127->GetYaxis()->SetTitleOffset(1.25);
   hframe__127->GetYaxis()->SetTitleFont(43);
   hframe__127->GetZaxis()->SetLabelFont(43);
   hframe__127->GetZaxis()->SetLabelOffset(0.007);
   hframe__127->GetZaxis()->SetLabelSize(27);
   hframe__127->GetZaxis()->SetTitleSize(33);
   hframe__127->GetZaxis()->SetTitleFont(43);
   hframe__127->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=19 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 158432 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive","METInvertedTauIdAfterCollinearCutsInclusive",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(1,9950);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(2,25448);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(3,31312);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(4,29162);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(5,22299);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(6,14914);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(7,9120);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(8,5429);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(9,3107);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(10,1933);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(11,1235);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(12,966);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(13,713);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(14,511);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(15,453);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(16,359);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(17,305);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(18,245);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(19,159);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(20,152);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(21,101);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(22,99);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(23,85);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(24,71);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(25,46);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(26,47);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(27,36);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(28,33);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(29,17);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(30,17);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(31,12);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(32,19);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(33,10);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(34,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(35,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(36,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(37,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(38,9);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(39,9);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(40,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(41,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(43,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(44,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(45,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(46,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(47,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(48,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(49,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(50,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinContent(51,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(1,99.74969);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(2,159.5243);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(3,176.952);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(4,170.7688);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(5,149.3285);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(6,122.1229);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(7,95.49869);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(8,73.68175);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(9,55.74047);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(10,43.9659);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(11,35.14257);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(12,31.08054);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(13,26.70206);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(14,22.60531);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(15,21.2838);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(16,18.9473);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(17,17.46425);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(18,15.65248);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(19,12.60952);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(20,12.32883);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(21,10.04988);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(22,9.949874);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(23,9.219544);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(24,8.42615);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(25,6.78233);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(26,6.855655);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(27,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(28,5.744563);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(29,4.123106);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(30,4.123106);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(31,3.464102);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(32,4.358899);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(33,3.162278);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(34,2.828427);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(35,2.645751);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(36,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(37,2.828427);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(38,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(39,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(40,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(41,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(43,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(44,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(45,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(46,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(47,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(48,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(49,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(50,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetBinError(51,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetEntries(158438);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCutsInclusive->Draw("HIST same");
   
   TH1F *hframe__128 = new TH1F("hframe__128","",1000,0,500);
   hframe__128->SetMinimum(0.1);
   hframe__128->SetMaximum(62624);
   hframe__128->SetDirectory(0);
   hframe__128->SetStats(0);
   hframe__128->SetLineStyle(0);
   hframe__128->SetMarkerStyle(20);
   hframe__128->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__128->GetXaxis()->SetLabelFont(43);
   hframe__128->GetXaxis()->SetLabelOffset(0.007);
   hframe__128->GetXaxis()->SetLabelSize(27);
   hframe__128->GetXaxis()->SetTitleSize(33);
   hframe__128->GetXaxis()->SetTitleOffset(0.9);
   hframe__128->GetXaxis()->SetTitleFont(43);
   hframe__128->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__128->GetYaxis()->SetLabelFont(43);
   hframe__128->GetYaxis()->SetLabelOffset(0.007);
   hframe__128->GetYaxis()->SetLabelSize(27);
   hframe__128->GetYaxis()->SetTitleSize(33);
   hframe__128->GetYaxis()->SetTitleOffset(1.25);
   hframe__128->GetYaxis()->SetTitleFont(43);
   hframe__128->GetZaxis()->SetLabelFont(43);
   hframe__128->GetZaxis()->SetLabelOffset(0.007);
   hframe__128->GetZaxis()->SetLabelSize(27);
   hframe__128->GetZaxis()->SetTitleSize(33);
   hframe__128->GetZaxis()->SetTitleFont(43);
   hframe__128->Draw("sameaxis");
   invertedInclusiveIntegral->Modified();
   invertedInclusiveIntegral->cd();
   invertedInclusiveIntegral->SetSelected(invertedInclusiveIntegral);
}
