{
//=========Macro generated from canvas: baselinetaup_Teq100to120Integral/
//=========  (Wed Aug 13 15:50:00 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Teq100to120Integral = new TCanvas("baselinetaup_Teq100to120Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselinetaup_Teq100to120Integral->SetHighLightColor(2);
   baselinetaup_Teq100to120Integral->Range(-101.2658,-1.556974,531.6456,2.727438);
   baselinetaup_Teq100to120Integral->SetFillColor(0);
   baselinetaup_Teq100to120Integral->SetBorderMode(0);
   baselinetaup_Teq100to120Integral->SetBorderSize(2);
   baselinetaup_Teq100to120Integral->SetLogy();
   baselinetaup_Teq100to120Integral->SetTickx(1);
   baselinetaup_Teq100to120Integral->SetTicky(1);
   baselinetaup_Teq100to120Integral->SetLeftMargin(0.16);
   baselinetaup_Teq100to120Integral->SetRightMargin(0.05);
   baselinetaup_Teq100to120Integral->SetTopMargin(0.05);
   baselinetaup_Teq100to120Integral->SetBottomMargin(0.13);
   baselinetaup_Teq100to120Integral->SetFrameFillStyle(0);
   baselinetaup_Teq100to120Integral->SetFrameBorderMode(0);
   baselinetaup_Teq100to120Integral->SetFrameFillStyle(0);
   baselinetaup_Teq100to120Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__97 = new TH1F("hframe__97","",1000,0,500);
   hframe__97->SetMinimum(0.1);
   hframe__97->SetMaximum(326);
   hframe__97->SetDirectory(0);
   hframe__97->SetStats(0);
   hframe__97->SetLineStyle(0);
   hframe__97->SetMarkerStyle(20);
   hframe__97->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__97->GetXaxis()->SetLabelFont(43);
   hframe__97->GetXaxis()->SetLabelOffset(0.007);
   hframe__97->GetXaxis()->SetLabelSize(27);
   hframe__97->GetXaxis()->SetTitleSize(33);
   hframe__97->GetXaxis()->SetTitleOffset(0.9);
   hframe__97->GetXaxis()->SetTitleFont(43);
   hframe__97->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__97->GetYaxis()->SetLabelFont(43);
   hframe__97->GetYaxis()->SetLabelOffset(0.007);
   hframe__97->GetYaxis()->SetLabelSize(27);
   hframe__97->GetYaxis()->SetTitleSize(33);
   hframe__97->GetYaxis()->SetTitleOffset(1.25);
   hframe__97->GetYaxis()->SetTitleFont(43);
   hframe__97->GetZaxis()->SetLabelFont(43);
   hframe__97->GetZaxis()->SetLabelOffset(0.007);
   hframe__97->GetZaxis()->SetLabelSize(27);
   hframe__97->GetZaxis()->SetTitleSize(33);
   hframe__97->GetZaxis()->SetTitleFont(43);
   hframe__97->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 687 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5","#tau p_{T}=100..120",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(1,66);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(2,113);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(3,163);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(4,119);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(5,92);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(6,57);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(7,29);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(8,12);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(9,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(10,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(11,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(12,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(13,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(14,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(15,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(16,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(21,3);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinContent(24,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(1,8.124038);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(2,10.63015);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(3,12.76715);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(4,10.90871);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(5,9.591663);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(6,7.549834);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(7,5.385165);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(8,3.464102);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(9,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(10,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(11,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(12,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(13,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(14,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(15,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(16,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(21,1.732051);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetBinError(24,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetEntries(687);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts5->Draw("HIST same");
   
   TH1F *hframe__98 = new TH1F("hframe__98","",1000,0,500);
   hframe__98->SetMinimum(0.1);
   hframe__98->SetMaximum(326);
   hframe__98->SetDirectory(0);
   hframe__98->SetStats(0);
   hframe__98->SetLineStyle(0);
   hframe__98->SetMarkerStyle(20);
   hframe__98->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__98->GetXaxis()->SetLabelFont(43);
   hframe__98->GetXaxis()->SetLabelOffset(0.007);
   hframe__98->GetXaxis()->SetLabelSize(27);
   hframe__98->GetXaxis()->SetTitleSize(33);
   hframe__98->GetXaxis()->SetTitleOffset(0.9);
   hframe__98->GetXaxis()->SetTitleFont(43);
   hframe__98->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__98->GetYaxis()->SetLabelFont(43);
   hframe__98->GetYaxis()->SetLabelOffset(0.007);
   hframe__98->GetYaxis()->SetLabelSize(27);
   hframe__98->GetYaxis()->SetTitleSize(33);
   hframe__98->GetYaxis()->SetTitleOffset(1.25);
   hframe__98->GetYaxis()->SetTitleFont(43);
   hframe__98->GetZaxis()->SetLabelFont(43);
   hframe__98->GetZaxis()->SetLabelOffset(0.007);
   hframe__98->GetZaxis()->SetLabelSize(27);
   hframe__98->GetZaxis()->SetTitleSize(33);
   hframe__98->GetZaxis()->SetTitleFont(43);
   hframe__98->Draw("sameaxis");
   baselinetaup_Teq100to120Integral->Modified();
   baselinetaup_Teq100to120Integral->cd();
   baselinetaup_Teq100to120Integral->SetSelected(baselinetaup_Teq100to120Integral);
}
