{
//=========Macro generated from canvas: baselineEWK2Integral/
//=========  (Fri Jul  4 10:40:03 2014) by ROOT version5.32/00
   TCanvas *baselineEWK2Integral = new TCanvas("baselineEWK2Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   baselineEWK2Integral->SetHighLightColor(2);
   baselineEWK2Integral->Range(-101.2658,-1.48461,531.6456,2.243162);
   baselineEWK2Integral->SetFillColor(0);
   baselineEWK2Integral->SetBorderMode(0);
   baselineEWK2Integral->SetBorderSize(2);
   baselineEWK2Integral->SetLogy();
   baselineEWK2Integral->SetTickx(1);
   baselineEWK2Integral->SetTicky(1);
   baselineEWK2Integral->SetLeftMargin(0.16);
   baselineEWK2Integral->SetRightMargin(0.05);
   baselineEWK2Integral->SetTopMargin(0.05);
   baselineEWK2Integral->SetBottomMargin(0.13);
   baselineEWK2Integral->SetFrameFillStyle(0);
   baselineEWK2Integral->SetFrameBorderMode(0);
   baselineEWK2Integral->SetFrameFillStyle(0);
   baselineEWK2Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__31 = new TH1F("hframe__31","",1000,0,500);
   hframe__31->SetMinimum(0.1);
   hframe__31->SetMaximum(113.9655);
   hframe__31->SetDirectory(0);
   hframe__31->SetStats(0);
   hframe__31->SetLineStyle(0);
   hframe__31->SetMarkerStyle(20);
   hframe__31->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__31->GetXaxis()->SetLabelFont(43);
   hframe__31->GetXaxis()->SetLabelOffset(0.007);
   hframe__31->GetXaxis()->SetLabelSize(27);
   hframe__31->GetXaxis()->SetTitleSize(33);
   hframe__31->GetXaxis()->SetTitleOffset(0.9);
   hframe__31->GetXaxis()->SetTitleFont(43);
   hframe__31->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__31->GetYaxis()->SetLabelFont(43);
   hframe__31->GetYaxis()->SetLabelOffset(0.007);
   hframe__31->GetYaxis()->SetLabelSize(27);
   hframe__31->GetYaxis()->SetTitleSize(33);
   hframe__31->GetYaxis()->SetTitleOffset(1.25);
   hframe__31->GetYaxis()->SetTitleFont(43);
   hframe__31->GetZaxis()->SetLabelFont(43);
   hframe__31->GetZaxis()->SetLabelOffset(0.007);
   hframe__31->GetZaxis()->SetLabelSize(27);
   hframe__31->GetZaxis()->SetTitleSize(33);
   hframe__31->GetZaxis()->SetTitleFont(43);
   hframe__31->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 523 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2 = new TH1F("Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2","#tau p_{T}=60..70",50,0,500);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(2,3.637452);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(3,1.843462);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(4,3.259711);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(5,4.675246);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(6,18.93646);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(7,14.99883);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(8,15.50633);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(9,22.17697);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(10,27.3482);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(11,33.16715);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(12,35.14132);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(13,56.98274);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(14,39.93268);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(15,35.54167);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(16,34.78849);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(17,24.7476);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(18,25.01396);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(19,20.75743);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(20,17.01678);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(21,13.21833);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(22,13.15754);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(23,10.45535);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(24,7.010199);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(25,9.304541);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(26,5.204443);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(27,7.544862);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(28,2.998847);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(29,2.07795);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(30,1.980105);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(31,2.448681);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(32,2.651047);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(33,0.2124213);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(34,2.779939);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(35,1.088677);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(36,0.9771628);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(37,0.3390513);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(38,0.5712497);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(39,0.9629309);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(40,1.123103);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(41,0.3712829);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(43,0.4420989);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(44,0.7754627);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(47,0.2440813);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(48,0.03117104);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(49,0.00527093);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(51,2.150192);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(2,2.68892);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(3,1.026921);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(4,1.609828);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(5,1.926876);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(6,4.77796);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(7,3.012835);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(8,2.870102);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(9,4.006395);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(10,4.374106);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(11,5.542629);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(12,4.959138);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(13,7.556993);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(14,5.639028);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(15,4.825112);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(16,5.135479);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(17,3.980762);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(18,4.382144);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(19,4.047893);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(20,3.580396);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(21,2.673865);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(22,3.498754);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(23,2.253172);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(24,1.898832);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(25,2.900108);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(26,1.428431);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(27,2.034492);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(28,1.13845);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(29,1.015263);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(30,0.9242548);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(31,1.020202);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(32,1.09825);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(33,0.1525675);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(34,1.465532);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(35,0.7011118);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(36,0.5777693);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(37,0.2422733);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(38,0.4029024);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(39,0.7001477);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(40,0.653101);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(41,0.3712829);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(43,0.4420989);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(44,0.7754627);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(47,0.1802538);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(48,0.03117103);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(49,0.005270929);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(51,0.8820277);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetEntries(1217);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetFillColor(ci);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetLineWidth(2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetMarkerStyle(20);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetMarkerSize(1.2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitle("Events / 10 GeV");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleOffset(1.5);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->Draw("HIST same");
   
   TH1F *hframe__32 = new TH1F("hframe__32","",1000,0,500);
   hframe__32->SetMinimum(0.1);
   hframe__32->SetMaximum(113.9655);
   hframe__32->SetDirectory(0);
   hframe__32->SetStats(0);
   hframe__32->SetLineStyle(0);
   hframe__32->SetMarkerStyle(20);
   hframe__32->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__32->GetXaxis()->SetLabelFont(43);
   hframe__32->GetXaxis()->SetLabelOffset(0.007);
   hframe__32->GetXaxis()->SetLabelSize(27);
   hframe__32->GetXaxis()->SetTitleSize(33);
   hframe__32->GetXaxis()->SetTitleOffset(0.9);
   hframe__32->GetXaxis()->SetTitleFont(43);
   hframe__32->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__32->GetYaxis()->SetLabelFont(43);
   hframe__32->GetYaxis()->SetLabelOffset(0.007);
   hframe__32->GetYaxis()->SetLabelSize(27);
   hframe__32->GetYaxis()->SetTitleSize(33);
   hframe__32->GetYaxis()->SetTitleOffset(1.25);
   hframe__32->GetYaxis()->SetTitleFont(43);
   hframe__32->GetZaxis()->SetLabelFont(43);
   hframe__32->GetZaxis()->SetLabelOffset(0.007);
   hframe__32->GetZaxis()->SetLabelSize(27);
   hframe__32->GetZaxis()->SetTitleSize(33);
   hframe__32->GetZaxis()->SetTitleFont(43);
   hframe__32->Draw("sameaxis");
   baselineEWK2Integral->Modified();
   baselineEWK2Integral->cd();
   baselineEWK2Integral->SetSelected(baselineEWK2Integral);
}
