{
//=========Macro generated from canvas: baselineEWKFakeTausInclusiveIntegral/
//=========  (Wed Aug 13 15:50:05 2014) by ROOT version5.32/00
   TCanvas *baselineEWKFakeTausInclusiveIntegral = new TCanvas("baselineEWKFakeTausInclusiveIntegral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKFakeTausInclusiveIntegral->SetHighLightColor(2);
   baselineEWKFakeTausInclusiveIntegral->Range(-101.2658,-1.253954,531.6456,0.6995391);
   baselineEWKFakeTausInclusiveIntegral->SetFillColor(0);
   baselineEWKFakeTausInclusiveIntegral->SetBorderMode(0);
   baselineEWKFakeTausInclusiveIntegral->SetBorderSize(2);
   baselineEWKFakeTausInclusiveIntegral->SetLogy();
   baselineEWKFakeTausInclusiveIntegral->SetTickx(1);
   baselineEWKFakeTausInclusiveIntegral->SetTicky(1);
   baselineEWKFakeTausInclusiveIntegral->SetLeftMargin(0.16);
   baselineEWKFakeTausInclusiveIntegral->SetRightMargin(0.05);
   baselineEWKFakeTausInclusiveIntegral->SetTopMargin(0.05);
   baselineEWKFakeTausInclusiveIntegral->SetBottomMargin(0.13);
   baselineEWKFakeTausInclusiveIntegral->SetFrameFillStyle(0);
   baselineEWKFakeTausInclusiveIntegral->SetFrameBorderMode(0);
   baselineEWKFakeTausInclusiveIntegral->SetFrameFillStyle(0);
   baselineEWKFakeTausInclusiveIntegral->SetFrameBorderMode(0);
   
   TH1F *hframe__137 = new TH1F("hframe__137","",1000,0,500);
   hframe__137->SetMinimum(0.1);
   hframe__137->SetMaximum(3.998199);
   hframe__137->SetDirectory(0);
   hframe__137->SetStats(0);
   hframe__137->SetLineStyle(0);
   hframe__137->SetMarkerStyle(20);
   hframe__137->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__137->GetXaxis()->SetLabelFont(43);
   hframe__137->GetXaxis()->SetLabelOffset(0.007);
   hframe__137->GetXaxis()->SetLabelSize(27);
   hframe__137->GetXaxis()->SetTitleSize(33);
   hframe__137->GetXaxis()->SetTitleOffset(0.9);
   hframe__137->GetXaxis()->SetTitleFont(43);
   hframe__137->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__137->GetYaxis()->SetLabelFont(43);
   hframe__137->GetYaxis()->SetLabelOffset(0.007);
   hframe__137->GetYaxis()->SetLabelSize(27);
   hframe__137->GetYaxis()->SetTitleSize(33);
   hframe__137->GetYaxis()->SetTitleOffset(1.25);
   hframe__137->GetYaxis()->SetTitleFont(43);
   hframe__137->GetZaxis()->SetLabelFont(43);
   hframe__137->GetZaxis()->SetLabelOffset(0.007);
   hframe__137->GetZaxis()->SetLabelSize(27);
   hframe__137->GetZaxis()->SetTitleSize(33);
   hframe__137->GetZaxis()->SetTitleFont(43);
   hframe__137->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 20 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive","METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(1,0.0853356);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(2,0.3603918);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(3,0.4389085);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(4,0.9003944);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(5,1.00645);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(6,1.936937);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(7,1.451004);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(8,1.786477);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(9,1.491139);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(10,1.535441);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(11,1.243787);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(12,1.999099);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(13,0.9351323);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(14,0.9439219);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(15,0.4874762);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(16,0.4088945);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(17,0.2890987);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(18,0.2359915);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(19,0.183415);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(20,0.2043192);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(21,0.2445742);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(22,0.3002703);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(23,0.2872161);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(25,0.4950833);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(26,0.1662793);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(27,0.007940003);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(28,0.004212651);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(29,0.08555961);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(33,0.07601745);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinContent(40,0.08852233);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(1,0.08449814);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(2,0.2018176);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(3,0.1995188);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(4,0.2725564);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(5,0.3238082);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(6,0.9808942);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(7,0.4156952);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(8,0.4432764);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(9,0.3947065);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(10,0.4942908);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(11,0.3482387);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(12,0.5323144);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(13,0.3535805);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(14,0.3823078);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(15,0.2277656);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(16,0.2147415);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(17,0.1598819);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(18,0.1378327);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(19,0.1218297);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(20,0.1211526);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(21,0.1686281);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(22,0.1507223);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(23,0.1913298);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(25,0.4876215);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(26,0.1176155);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(27,0.007940003);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(28,0.004212651);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(29,0.08555961);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(33,0.07601745);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetBinError(40,0.08553792);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetEntries(264);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsOnlyEWKFakeTaus/METBaselineTauIdAfterCollinearCutsOnlyEWKFakeTausInclusive->Draw("HIST same");
   
   TH1F *hframe__138 = new TH1F("hframe__138","",1000,0,500);
   hframe__138->SetMinimum(0.1);
   hframe__138->SetMaximum(3.998199);
   hframe__138->SetDirectory(0);
   hframe__138->SetStats(0);
   hframe__138->SetLineStyle(0);
   hframe__138->SetMarkerStyle(20);
   hframe__138->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__138->GetXaxis()->SetLabelFont(43);
   hframe__138->GetXaxis()->SetLabelOffset(0.007);
   hframe__138->GetXaxis()->SetLabelSize(27);
   hframe__138->GetXaxis()->SetTitleSize(33);
   hframe__138->GetXaxis()->SetTitleOffset(0.9);
   hframe__138->GetXaxis()->SetTitleFont(43);
   hframe__138->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__138->GetYaxis()->SetLabelFont(43);
   hframe__138->GetYaxis()->SetLabelOffset(0.007);
   hframe__138->GetYaxis()->SetLabelSize(27);
   hframe__138->GetYaxis()->SetTitleSize(33);
   hframe__138->GetYaxis()->SetTitleOffset(1.25);
   hframe__138->GetYaxis()->SetTitleFont(43);
   hframe__138->GetZaxis()->SetLabelFont(43);
   hframe__138->GetZaxis()->SetLabelOffset(0.007);
   hframe__138->GetZaxis()->SetLabelSize(27);
   hframe__138->GetZaxis()->SetTitleSize(33);
   hframe__138->GetZaxis()->SetTitleFont(43);
   hframe__138->Draw("sameaxis");
   baselineEWKFakeTausInclusiveIntegral->Modified();
   baselineEWKFakeTausInclusiveIntegral->cd();
   baselineEWKFakeTausInclusiveIntegral->SetSelected(baselineEWKFakeTausInclusiveIntegral);
}
