{
//=========Macro generated from canvas: baselineEWK0Integral/
//=========  (Fri Jul  4 10:39:59 2014) by ROOT version5.32/00
   TCanvas *baselineEWK0Integral = new TCanvas("baselineEWK0Integral", "",0,0,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   baselineEWK0Integral->SetHighLightColor(2);
   baselineEWK0Integral->Range(-101.2658,-1.519689,531.6456,2.477916);
   baselineEWK0Integral->SetFillColor(0);
   baselineEWK0Integral->SetBorderMode(0);
   baselineEWK0Integral->SetBorderSize(2);
   baselineEWK0Integral->SetLogy();
   baselineEWK0Integral->SetTickx(1);
   baselineEWK0Integral->SetTicky(1);
   baselineEWK0Integral->SetLeftMargin(0.16);
   baselineEWK0Integral->SetRightMargin(0.05);
   baselineEWK0Integral->SetTopMargin(0.05);
   baselineEWK0Integral->SetBottomMargin(0.13);
   baselineEWK0Integral->SetFrameFillStyle(0);
   baselineEWK0Integral->SetFrameBorderMode(0);
   baselineEWK0Integral->SetFrameFillStyle(0);
   baselineEWK0Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__7 = new TH1F("hframe__7","",1000,0,500);
   hframe__7->SetMinimum(0.1);
   hframe__7->SetMaximum(189.6862);
   hframe__7->SetDirectory(0);
   hframe__7->SetStats(0);
   hframe__7->SetLineStyle(0);
   hframe__7->SetMarkerStyle(20);
   hframe__7->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__7->GetXaxis()->SetLabelFont(43);
   hframe__7->GetXaxis()->SetLabelOffset(0.007);
   hframe__7->GetXaxis()->SetLabelSize(27);
   hframe__7->GetXaxis()->SetTitleSize(33);
   hframe__7->GetXaxis()->SetTitleOffset(0.9);
   hframe__7->GetXaxis()->SetTitleFont(43);
   hframe__7->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__7->GetYaxis()->SetLabelFont(43);
   hframe__7->GetYaxis()->SetLabelOffset(0.007);
   hframe__7->GetYaxis()->SetLabelSize(27);
   hframe__7->GetYaxis()->SetTitleSize(33);
   hframe__7->GetYaxis()->SetTitleOffset(1.25);
   hframe__7->GetYaxis()->SetTitleFont(43);
   hframe__7->GetZaxis()->SetLabelFont(43);
   hframe__7->GetZaxis()->SetLabelOffset(0.007);
   hframe__7->GetZaxis()->SetLabelSize(27);
   hframe__7->GetZaxis()->SetTitleSize(33);
   hframe__7->GetZaxis()->SetTitleFont(43);
   hframe__7->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 1093 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0 = new TH1F("Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0","#tau p_{T}<50",50,0,500);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(1,0.7409966);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(2,4.43424);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(3,8.844879);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(4,13.19723);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(5,24.60835);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(6,21.87705);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(7,31.29814);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(8,43.35704);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(9,56.17537);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(10,69.97743);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(11,80.49399);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(12,91.1827);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(13,94.84309);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(14,84.15745);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(15,80.72363);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(16,72.89666);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(17,55.41541);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(18,39.80658);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(19,32.58211);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(20,29.33081);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(21,26.7159);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(22,20.66673);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(23,23.54883);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(24,14.21854);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(25,12.37482);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(26,8.999037);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(27,3.630665);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(28,10.73626);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(29,4.031805);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(30,8.355945);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(31,2.470749);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(32,3.583113);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(33,3.725292);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(34,1.030905);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(35,0.4092428);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(36,2.085065);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(37,1.582963);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(38,0.1214807);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(39,1.700418);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(40,1.960052);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(41,1.056803);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(42,2.494071);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(43,0.1543604);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(45,0.3867022);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(46,1.232912);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinContent(51,1.738653);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(1,0.7409966);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(2,1.591174);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(3,2.128589);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(4,3.3068);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(5,5.815977);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(6,3.702064);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(7,4.315864);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(8,6.191858);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(9,7.033035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(10,6.721175);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(11,7.963558);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(12,8.636795);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(13,8.658694);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(14,7.56649);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(15,8.338127);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(16,8.688394);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(17,6.878583);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(18,4.755251);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(19,4.109384);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(20,4.189887);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(21,3.689367);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(22,3.274851);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(23,3.667376);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(24,2.745811);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(25,2.376618);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(26,1.977001);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(27,1.217908);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(28,2.414429);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(29,1.463788);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(30,2.228756);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(31,1.108925);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(32,1.695833);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(33,1.391942);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(34,0.594629);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(35,0.3636975);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(36,1.068983);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(37,0.8722294);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(38,0.1214807);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(39,0.8730842);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(40,1.051825);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(41,0.6955682);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(42,1.538159);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(43,0.1543604);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(45,0.3867022);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(46,0.9322639);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetBinError(51,0.8330586);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetEntries(2545);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetFillColor(ci);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetLineWidth(2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetMarkerStyle(20);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->SetMarkerSize(1.2);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetXaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitle("Events / 10 GeV");
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleOffset(1.5);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetYaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetLabelFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetLabelSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetTitleSize(0.035);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->GetZaxis()->SetTitleFont(42);
   Baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts0->Draw("HIST same");
   
   TH1F *hframe__8 = new TH1F("hframe__8","",1000,0,500);
   hframe__8->SetMinimum(0.1);
   hframe__8->SetMaximum(189.6862);
   hframe__8->SetDirectory(0);
   hframe__8->SetStats(0);
   hframe__8->SetLineStyle(0);
   hframe__8->SetMarkerStyle(20);
   hframe__8->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__8->GetXaxis()->SetLabelFont(43);
   hframe__8->GetXaxis()->SetLabelOffset(0.007);
   hframe__8->GetXaxis()->SetLabelSize(27);
   hframe__8->GetXaxis()->SetTitleSize(33);
   hframe__8->GetXaxis()->SetTitleOffset(0.9);
   hframe__8->GetXaxis()->SetTitleFont(43);
   hframe__8->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__8->GetYaxis()->SetLabelFont(43);
   hframe__8->GetYaxis()->SetLabelOffset(0.007);
   hframe__8->GetYaxis()->SetLabelSize(27);
   hframe__8->GetYaxis()->SetTitleSize(33);
   hframe__8->GetYaxis()->SetTitleOffset(1.25);
   hframe__8->GetYaxis()->SetTitleFont(43);
   hframe__8->GetZaxis()->SetLabelFont(43);
   hframe__8->GetZaxis()->SetLabelOffset(0.007);
   hframe__8->GetZaxis()->SetLabelSize(27);
   hframe__8->GetZaxis()->SetTitleSize(33);
   hframe__8->GetZaxis()->SetTitleFont(43);
   hframe__8->Draw("sameaxis");
   baselineEWK0Integral->Modified();
   baselineEWK0Integral->cd();
   baselineEWK0Integral->SetSelected(baselineEWK0Integral);
}
