{
//=========Macro generated from canvas: baselinetaup_Teq60to70Integral/
//=========  (Wed Aug 13 15:49:52 2014) by ROOT version5.32/00
   TCanvas *baselinetaup_Teq60to70Integral = new TCanvas("baselinetaup_Teq60to70Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselinetaup_Teq60to70Integral->SetHighLightColor(2);
   baselinetaup_Teq60to70Integral->Range(-101.2658,-1.563804,531.6456,2.77315);
   baselinetaup_Teq60to70Integral->SetFillColor(0);
   baselinetaup_Teq60to70Integral->SetBorderMode(0);
   baselinetaup_Teq60to70Integral->SetBorderSize(2);
   baselinetaup_Teq60to70Integral->SetLogy();
   baselinetaup_Teq60to70Integral->SetTickx(1);
   baselinetaup_Teq60to70Integral->SetTicky(1);
   baselinetaup_Teq60to70Integral->SetLeftMargin(0.16);
   baselinetaup_Teq60to70Integral->SetRightMargin(0.05);
   baselinetaup_Teq60to70Integral->SetTopMargin(0.05);
   baselinetaup_Teq60to70Integral->SetBottomMargin(0.13);
   baselinetaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselinetaup_Teq60to70Integral->SetFrameBorderMode(0);
   baselinetaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselinetaup_Teq60to70Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__43 = new TH1F("hframe__43","",1000,0,500);
   hframe__43->SetMinimum(0.1);
   hframe__43->SetMaximum(360);
   hframe__43->SetDirectory(0);
   hframe__43->SetStats(0);
   hframe__43->SetLineStyle(0);
   hframe__43->SetMarkerStyle(20);
   hframe__43->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__43->GetXaxis()->SetLabelFont(43);
   hframe__43->GetXaxis()->SetLabelOffset(0.007);
   hframe__43->GetXaxis()->SetLabelSize(27);
   hframe__43->GetXaxis()->SetTitleSize(33);
   hframe__43->GetXaxis()->SetTitleOffset(0.9);
   hframe__43->GetXaxis()->SetTitleFont(43);
   hframe__43->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__43->GetYaxis()->SetLabelFont(43);
   hframe__43->GetYaxis()->SetLabelOffset(0.007);
   hframe__43->GetYaxis()->SetLabelSize(27);
   hframe__43->GetYaxis()->SetTitleSize(33);
   hframe__43->GetYaxis()->SetTitleOffset(1.25);
   hframe__43->GetYaxis()->SetTitleFont(43);
   hframe__43->GetZaxis()->SetLabelFont(43);
   hframe__43->GetZaxis()->SetLabelOffset(0.007);
   hframe__43->GetZaxis()->SetLabelSize(27);
   hframe__43->GetZaxis()->SetTitleSize(33);
   hframe__43->GetZaxis()->SetTitleFont(43);
   hframe__43->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 1034 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2","#tau p_{T}=60..70",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(1,53);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(2,136);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(3,173);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(4,180);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(5,138);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(6,96);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(7,57);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(8,36);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(9,26);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(10,22);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(11,20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(12,16);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(13,17);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(14,10);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(15,11);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(16,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(17,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(18,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(19,7);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(20,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(21,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(22,5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(23,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(25,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinContent(27,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(1,7.28011);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(2,11.6619);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(3,13.15295);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(4,13.41641);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(5,11.74734);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(6,9.797959);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(7,7.549834);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(8,6);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(9,5.09902);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(10,4.690416);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(11,4.472136);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(12,4);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(13,4.123106);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(14,3.162278);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(15,3.316625);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(16,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(17,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(18,2.44949);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(19,2.645751);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(20,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(21,2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(22,2.236068);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(23,1.414214);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(25,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetBinError(27,1);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetEntries(1034);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCuts/METBaselineTauIdAfterCollinearCuts2->Draw("HIST same");
   
   TH1F *hframe__44 = new TH1F("hframe__44","",1000,0,500);
   hframe__44->SetMinimum(0.1);
   hframe__44->SetMaximum(360);
   hframe__44->SetDirectory(0);
   hframe__44->SetStats(0);
   hframe__44->SetLineStyle(0);
   hframe__44->SetMarkerStyle(20);
   hframe__44->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__44->GetXaxis()->SetLabelFont(43);
   hframe__44->GetXaxis()->SetLabelOffset(0.007);
   hframe__44->GetXaxis()->SetLabelSize(27);
   hframe__44->GetXaxis()->SetTitleSize(33);
   hframe__44->GetXaxis()->SetTitleOffset(0.9);
   hframe__44->GetXaxis()->SetTitleFont(43);
   hframe__44->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__44->GetYaxis()->SetLabelFont(43);
   hframe__44->GetYaxis()->SetLabelOffset(0.007);
   hframe__44->GetYaxis()->SetLabelSize(27);
   hframe__44->GetYaxis()->SetTitleSize(33);
   hframe__44->GetYaxis()->SetTitleOffset(1.25);
   hframe__44->GetYaxis()->SetTitleFont(43);
   hframe__44->GetZaxis()->SetLabelFont(43);
   hframe__44->GetZaxis()->SetLabelOffset(0.007);
   hframe__44->GetZaxis()->SetLabelSize(27);
   hframe__44->GetZaxis()->SetTitleSize(33);
   hframe__44->GetZaxis()->SetTitleFont(43);
   hframe__44->Draw("sameaxis");
   baselinetaup_Teq60to70Integral->Modified();
   baselinetaup_Teq60to70Integral->cd();
   baselinetaup_Teq60to70Integral->SetSelected(baselinetaup_Teq60to70Integral);
}
