{
//=========Macro generated from canvas: baselineEWKGenuineTaustaup_Teq60to70Integral/
//=========  (Wed Aug 13 15:49:52 2014) by ROOT version5.32/00
   TCanvas *baselineEWKGenuineTaustaup_Teq60to70Integral = new TCanvas("baselineEWKGenuineTaustaup_Teq60to70Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetHighLightColor(2);
   baselineEWKGenuineTaustaup_Teq60to70Integral->Range(-101.2658,-1.272853,531.6456,0.8260161);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetFillColor(0);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetBorderMode(0);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetBorderSize(2);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetLogy();
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetTickx(1);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetTicky(1);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetLeftMargin(0.16);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetRightMargin(0.05);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetTopMargin(0.05);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetBottomMargin(0.13);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetFrameBorderMode(0);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetFrameFillStyle(0);
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__45 = new TH1F("hframe__45","",1000,0,500);
   hframe__45->SetMinimum(0.1);
   hframe__45->SetMaximum(5.261053);
   hframe__45->SetDirectory(0);
   hframe__45->SetStats(0);
   hframe__45->SetLineStyle(0);
   hframe__45->SetMarkerStyle(20);
   hframe__45->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__45->GetXaxis()->SetLabelFont(43);
   hframe__45->GetXaxis()->SetLabelOffset(0.007);
   hframe__45->GetXaxis()->SetLabelSize(27);
   hframe__45->GetXaxis()->SetTitleSize(33);
   hframe__45->GetXaxis()->SetTitleOffset(0.9);
   hframe__45->GetXaxis()->SetTitleFont(43);
   hframe__45->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__45->GetYaxis()->SetLabelFont(43);
   hframe__45->GetYaxis()->SetLabelOffset(0.007);
   hframe__45->GetYaxis()->SetLabelSize(27);
   hframe__45->GetYaxis()->SetTitleSize(33);
   hframe__45->GetYaxis()->SetTitleOffset(1.25);
   hframe__45->GetYaxis()->SetTitleFont(43);
   hframe__45->GetZaxis()->SetLabelFont(43);
   hframe__45->GetZaxis()->SetLabelOffset(0.007);
   hframe__45->GetZaxis()->SetLabelSize(27);
   hframe__45->GetZaxis()->SetTitleSize(33);
   hframe__45->GetZaxis()->SetTitleFont(43);
   hframe__45->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 21 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2 = new TH1F("baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2","#tau p_{T}=60..70",50,0,500);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(2,0.6576598);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(3,0.2399714);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(4,0.4669801);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(5,0.9152463);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(6,1.763342);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(7,0.8437981);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(8,0.7075927);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(9,0.6906121);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(10,1.427787);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(11,2.630526);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(12,1.499788);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(13,2.332401);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(14,1.447977);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(15,1.192896);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(16,0.7415968);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(17,0.74777);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(18,0.8564075);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(19,0.4676112);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(20,0.08528852);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(21,0.3231373);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(22,0.3676257);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(23,0.1274892);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(24,0.04098778);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(25,0.3129486);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(27,0.1296311);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(32,0.08275034);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(33,0.02784808);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinContent(48,0.006937535);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(2,0.5788558);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(3,0.1789058);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(4,0.3344039);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(5,0.4195988);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(6,0.7304852);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(7,0.2540765);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(8,0.2238755);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(9,0.2879996);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(10,0.5830904);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(11,0.836292);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(12,0.3861673);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(13,0.8397626);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(14,0.5811534);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(15,0.4939869);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(16,0.3218595);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(17,0.3060099);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(18,0.2907503);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(19,0.1930937);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(20,0.08286356);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(21,0.1636231);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(22,0.187505);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(23,0.1274892);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(24,0.03581384);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(25,0.2222276);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(27,0.09215486);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(32,0.08275034);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(33,0.02784808);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetBinError(48,0.006937536);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetEntries(239);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetFillColor(ci);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetLineWidth(2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetMarkerStyle(20);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->SetMarkerSize(1.2);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetXaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetXaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetXaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetXaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetYaxis()->SetTitle("Events / 10 GeV");
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetYaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetYaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetYaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetYaxis()->SetTitleOffset(1.5);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetYaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetZaxis()->SetLabelFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetZaxis()->SetLabelSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetZaxis()->SetTitleSize(0.035);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->GetZaxis()->SetTitleFont(42);
   baseline/METBaseLineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METBaselineTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus2->Draw("HIST same");
   
   TH1F *hframe__46 = new TH1F("hframe__46","",1000,0,500);
   hframe__46->SetMinimum(0.1);
   hframe__46->SetMaximum(5.261053);
   hframe__46->SetDirectory(0);
   hframe__46->SetStats(0);
   hframe__46->SetLineStyle(0);
   hframe__46->SetMarkerStyle(20);
   hframe__46->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__46->GetXaxis()->SetLabelFont(43);
   hframe__46->GetXaxis()->SetLabelOffset(0.007);
   hframe__46->GetXaxis()->SetLabelSize(27);
   hframe__46->GetXaxis()->SetTitleSize(33);
   hframe__46->GetXaxis()->SetTitleOffset(0.9);
   hframe__46->GetXaxis()->SetTitleFont(43);
   hframe__46->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__46->GetYaxis()->SetLabelFont(43);
   hframe__46->GetYaxis()->SetLabelOffset(0.007);
   hframe__46->GetYaxis()->SetLabelSize(27);
   hframe__46->GetYaxis()->SetTitleSize(33);
   hframe__46->GetYaxis()->SetTitleOffset(1.25);
   hframe__46->GetYaxis()->SetTitleFont(43);
   hframe__46->GetZaxis()->SetLabelFont(43);
   hframe__46->GetZaxis()->SetLabelOffset(0.007);
   hframe__46->GetZaxis()->SetLabelSize(27);
   hframe__46->GetZaxis()->SetTitleSize(33);
   hframe__46->GetZaxis()->SetTitleFont(43);
   hframe__46->Draw("sameaxis");
   baselineEWKGenuineTaustaup_Teq60to70Integral->Modified();
   baselineEWKGenuineTaustaup_Teq60to70Integral->cd();
   baselineEWKGenuineTaustaup_Teq60to70Integral->SetSelected(baselineEWKGenuineTaustaup_Teq60to70Integral);
}
