{
//=========Macro generated from canvas: invertedtaup_Teq70to80Integral/
//=========  (Wed Aug 13 15:49:55 2014) by ROOT version5.32/00
   TCanvas *invertedtaup_Teq70to80Integral = new TCanvas("invertedtaup_Teq70to80Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedtaup_Teq70to80Integral->SetHighLightColor(2);
   invertedtaup_Teq70to80Integral->Range(-101.2658,-1.75591,531.6456,4.05878);
   invertedtaup_Teq70to80Integral->SetFillColor(0);
   invertedtaup_Teq70to80Integral->SetBorderMode(0);
   invertedtaup_Teq70to80Integral->SetBorderSize(2);
   invertedtaup_Teq70to80Integral->SetLogy();
   invertedtaup_Teq70to80Integral->SetTickx(1);
   invertedtaup_Teq70to80Integral->SetTicky(1);
   invertedtaup_Teq70to80Integral->SetLeftMargin(0.16);
   invertedtaup_Teq70to80Integral->SetRightMargin(0.05);
   invertedtaup_Teq70to80Integral->SetTopMargin(0.05);
   invertedtaup_Teq70to80Integral->SetBottomMargin(0.13);
   invertedtaup_Teq70to80Integral->SetFrameFillStyle(0);
   invertedtaup_Teq70to80Integral->SetFrameBorderMode(0);
   invertedtaup_Teq70to80Integral->SetFrameFillStyle(0);
   invertedtaup_Teq70to80Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__55 = new TH1F("hframe__55","",1000,0,500);
   hframe__55->SetMinimum(0.1);
   hframe__55->SetMaximum(5862);
   hframe__55->SetDirectory(0);
   hframe__55->SetStats(0);
   hframe__55->SetLineStyle(0);
   hframe__55->SetMarkerStyle(20);
   hframe__55->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__55->GetXaxis()->SetLabelFont(43);
   hframe__55->GetXaxis()->SetLabelOffset(0.007);
   hframe__55->GetXaxis()->SetLabelSize(27);
   hframe__55->GetXaxis()->SetTitleSize(33);
   hframe__55->GetXaxis()->SetTitleOffset(0.9);
   hframe__55->GetXaxis()->SetTitleFont(43);
   hframe__55->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__55->GetYaxis()->SetLabelFont(43);
   hframe__55->GetYaxis()->SetLabelOffset(0.007);
   hframe__55->GetYaxis()->SetLabelSize(27);
   hframe__55->GetYaxis()->SetTitleSize(33);
   hframe__55->GetYaxis()->SetTitleOffset(1.25);
   hframe__55->GetYaxis()->SetTitleFont(43);
   hframe__55->GetZaxis()->SetLabelFont(43);
   hframe__55->GetZaxis()->SetLabelOffset(0.007);
   hframe__55->GetZaxis()->SetLabelSize(27);
   hframe__55->GetZaxis()->SetTitleSize(33);
   hframe__55->GetZaxis()->SetTitleFont(43);
   hframe__55->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 13463 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3","#tau p_{T}=70..80",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(1,896);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(2,2171);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(3,2931);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(4,2666);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(5,1970);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(6,1269);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(7,688);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(8,360);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(9,197);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(10,77);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(11,64);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(12,49);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(13,26);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(14,19);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(15,19);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(16,18);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(17,12);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(18,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(19,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(20,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(21,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(22,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(23,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(24,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(26,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinContent(28,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(1,29.93326);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(2,46.59399);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(3,54.13871);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(4,51.63332);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(5,44.38468);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(6,35.62303);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(7,26.22975);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(8,18.97367);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(9,14.03567);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(10,8.774964);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(11,8);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(12,7);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(13,5.09902);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(14,4.358899);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(15,4.358899);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(16,4.242641);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(17,3.464102);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(18,2.828427);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(19,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(20,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(21,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(22,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(23,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(24,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(26,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetBinError(28,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetEntries(13463);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts3->Draw("HIST same");
   
   TH1F *hframe__56 = new TH1F("hframe__56","",1000,0,500);
   hframe__56->SetMinimum(0.1);
   hframe__56->SetMaximum(5862);
   hframe__56->SetDirectory(0);
   hframe__56->SetStats(0);
   hframe__56->SetLineStyle(0);
   hframe__56->SetMarkerStyle(20);
   hframe__56->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__56->GetXaxis()->SetLabelFont(43);
   hframe__56->GetXaxis()->SetLabelOffset(0.007);
   hframe__56->GetXaxis()->SetLabelSize(27);
   hframe__56->GetXaxis()->SetTitleSize(33);
   hframe__56->GetXaxis()->SetTitleOffset(0.9);
   hframe__56->GetXaxis()->SetTitleFont(43);
   hframe__56->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__56->GetYaxis()->SetLabelFont(43);
   hframe__56->GetYaxis()->SetLabelOffset(0.007);
   hframe__56->GetYaxis()->SetLabelSize(27);
   hframe__56->GetYaxis()->SetTitleSize(33);
   hframe__56->GetYaxis()->SetTitleOffset(1.25);
   hframe__56->GetYaxis()->SetTitleFont(43);
   hframe__56->GetZaxis()->SetLabelFont(43);
   hframe__56->GetZaxis()->SetLabelOffset(0.007);
   hframe__56->GetZaxis()->SetLabelSize(27);
   hframe__56->GetZaxis()->SetTitleSize(33);
   hframe__56->GetZaxis()->SetTitleFont(43);
   hframe__56->Draw("sameaxis");
   invertedtaup_Teq70to80Integral->Modified();
   invertedtaup_Teq70to80Integral->cd();
   invertedtaup_Teq70to80Integral->SetSelected(invertedtaup_Teq70to80Integral);
}
