{
//=========Macro generated from canvas: invertedEWKGenuineTaustaup_Tgt120Integral/
//=========  (Wed Aug 13 15:50:02 2014) by ROOT version5.32/00
   TCanvas *invertedEWKGenuineTaustaup_Tgt120Integral = new TCanvas("invertedEWKGenuineTaustaup_Tgt120Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetHighLightColor(2);
   invertedEWKGenuineTaustaup_Tgt120Integral->Range(-101.2658,-1.222564,531.6456,0.4894637);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetFillColor(0);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetBorderMode(0);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetBorderSize(2);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetLogy();
   invertedEWKGenuineTaustaup_Tgt120Integral->SetTickx(1);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetTicky(1);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetLeftMargin(0.16);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetRightMargin(0.05);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetTopMargin(0.05);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetBottomMargin(0.13);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetFrameBorderMode(0);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetFrameFillStyle(0);
   invertedEWKGenuineTaustaup_Tgt120Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__111 = new TH1F("hframe__111","",1000,0,500);
   hframe__111->SetMinimum(0.1);
   hframe__111->SetMaximum(2.534325);
   hframe__111->SetDirectory(0);
   hframe__111->SetStats(0);
   hframe__111->SetLineStyle(0);
   hframe__111->SetMarkerStyle(20);
   hframe__111->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__111->GetXaxis()->SetLabelFont(43);
   hframe__111->GetXaxis()->SetLabelOffset(0.007);
   hframe__111->GetXaxis()->SetLabelSize(27);
   hframe__111->GetXaxis()->SetTitleSize(33);
   hframe__111->GetXaxis()->SetTitleOffset(0.9);
   hframe__111->GetXaxis()->SetTitleFont(43);
   hframe__111->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__111->GetYaxis()->SetLabelFont(43);
   hframe__111->GetYaxis()->SetLabelOffset(0.007);
   hframe__111->GetYaxis()->SetLabelSize(27);
   hframe__111->GetYaxis()->SetTitleSize(33);
   hframe__111->GetYaxis()->SetTitleOffset(1.25);
   hframe__111->GetYaxis()->SetTitleFont(43);
   hframe__111->GetZaxis()->SetLabelFont(43);
   hframe__111->GetZaxis()->SetLabelOffset(0.007);
   hframe__111->GetZaxis()->SetLabelSize(27);
   hframe__111->GetZaxis()->SetTitleSize(33);
   hframe__111->GetZaxis()->SetTitleFont(43);
   hframe__111->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 5 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6","#tau p_{T}>120",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(1,0.07357145);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(3,0.08093514);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(4,1.267163);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(5,0.173775);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(6,0.02338596);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(7,0.264002);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(8,0.5186017);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(9,0.3367142);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(10,0.07971249);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(12,0.402054);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(13,0.166365);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(14,0.2425722);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(15,0.3104012);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(16,0.2369862);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(17,0.1015188);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(18,0.1204447);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(19,0.1257772);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(22,0.1896013);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(24,0.1211883);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(26,0.06902478);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(31,0.07575803);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinContent(39,0.1583358);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(1,0.06938602);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(3,0.05025264);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(4,0.8457437);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(5,0.1242063);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(6,0.01666936);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(7,0.1685273);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(8,0.2721538);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(9,0.1971706);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(10,0.07367627);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(12,0.2268525);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(13,0.1055804);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(14,0.129021);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(15,0.2424159);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(16,0.1739827);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(17,0.08420509);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(18,0.09120399);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(19,0.1051538);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(22,0.1245518);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(24,0.1211883);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(26,0.06902478);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(31,0.07575803);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetBinError(39,0.1583358);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetEntries(66);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus/METInvertedTauIdAfterCollinearCutsPlusFilteredEWKFakeTaus6->Draw("HIST same");
   
   TH1F *hframe__112 = new TH1F("hframe__112","",1000,0,500);
   hframe__112->SetMinimum(0.1);
   hframe__112->SetMaximum(2.534325);
   hframe__112->SetDirectory(0);
   hframe__112->SetStats(0);
   hframe__112->SetLineStyle(0);
   hframe__112->SetMarkerStyle(20);
   hframe__112->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__112->GetXaxis()->SetLabelFont(43);
   hframe__112->GetXaxis()->SetLabelOffset(0.007);
   hframe__112->GetXaxis()->SetLabelSize(27);
   hframe__112->GetXaxis()->SetTitleSize(33);
   hframe__112->GetXaxis()->SetTitleOffset(0.9);
   hframe__112->GetXaxis()->SetTitleFont(43);
   hframe__112->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__112->GetYaxis()->SetLabelFont(43);
   hframe__112->GetYaxis()->SetLabelOffset(0.007);
   hframe__112->GetYaxis()->SetLabelSize(27);
   hframe__112->GetYaxis()->SetTitleSize(33);
   hframe__112->GetYaxis()->SetTitleOffset(1.25);
   hframe__112->GetYaxis()->SetTitleFont(43);
   hframe__112->GetZaxis()->SetLabelFont(43);
   hframe__112->GetZaxis()->SetLabelOffset(0.007);
   hframe__112->GetZaxis()->SetLabelSize(27);
   hframe__112->GetZaxis()->SetTitleSize(33);
   hframe__112->GetZaxis()->SetTitleFont(43);
   hframe__112->Draw("sameaxis");
   invertedEWKGenuineTaustaup_Tgt120Integral->Modified();
   invertedEWKGenuineTaustaup_Tgt120Integral->cd();
   invertedEWKGenuineTaustaup_Tgt120Integral->SetSelected(invertedEWKGenuineTaustaup_Tgt120Integral);
}
