{
//=========Macro generated from canvas: invertedtaup_Tgt150Integral/
//=========  (Thu Jul 31 09:28:41 2014) by ROOT version5.32/00
   TCanvas *invertedtaup_Tgt150Integral = new TCanvas("invertedtaup_Tgt150Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedtaup_Tgt150Integral->SetHighLightColor(2);
   invertedtaup_Tgt150Integral->Range(-101.2658,-1.752835,531.6456,4.038205);
   invertedtaup_Tgt150Integral->SetFillColor(0);
   invertedtaup_Tgt150Integral->SetBorderMode(0);
   invertedtaup_Tgt150Integral->SetBorderSize(2);
   invertedtaup_Tgt150Integral->SetLogy();
   invertedtaup_Tgt150Integral->SetTickx(1);
   invertedtaup_Tgt150Integral->SetTicky(1);
   invertedtaup_Tgt150Integral->SetLeftMargin(0.16);
   invertedtaup_Tgt150Integral->SetRightMargin(0.05);
   invertedtaup_Tgt150Integral->SetTopMargin(0.05);
   invertedtaup_Tgt150Integral->SetBottomMargin(0.13);
   invertedtaup_Tgt150Integral->SetFrameFillStyle(0);
   invertedtaup_Tgt150Integral->SetFrameBorderMode(0);
   invertedtaup_Tgt150Integral->SetFrameFillStyle(0);
   invertedtaup_Tgt150Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__127 = new TH1F("hframe__127","",1000,0,500);
   hframe__127->SetMinimum(0.1);
   hframe__127->SetMaximum(5606);
   hframe__127->SetDirectory(0);
   hframe__127->SetStats(0);
   hframe__127->SetLineStyle(0);
   hframe__127->SetMarkerStyle(20);
   hframe__127->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__127->GetXaxis()->SetLabelFont(43);
   hframe__127->GetXaxis()->SetLabelOffset(0.007);
   hframe__127->GetXaxis()->SetLabelSize(27);
   hframe__127->GetXaxis()->SetTitleSize(33);
   hframe__127->GetXaxis()->SetTitleOffset(0.9);
   hframe__127->GetXaxis()->SetTitleFont(43);
   hframe__127->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__127->GetYaxis()->SetLabelFont(43);
   hframe__127->GetYaxis()->SetLabelOffset(0.007);
   hframe__127->GetYaxis()->SetLabelSize(27);
   hframe__127->GetYaxis()->SetTitleSize(33);
   hframe__127->GetYaxis()->SetTitleOffset(1.25);
   hframe__127->GetYaxis()->SetTitleFont(43);
   hframe__127->GetZaxis()->SetLabelFont(43);
   hframe__127->GetZaxis()->SetLabelOffset(0.007);
   hframe__127->GetZaxis()->SetLabelSize(27);
   hframe__127->GetZaxis()->SetTitleSize(33);
   hframe__127->GetZaxis()->SetTitleFont(43);
   hframe__127->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 13049 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7","#tau p_{T}>150",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(1,978);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(2,2474);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(3,2803);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(4,2411);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(5,1656);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(6,1035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(7,603);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(8,410);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(9,218);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(10,121);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(11,83);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(12,58);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(13,33);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(14,31);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(15,25);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(16,23);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(17,13);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(18,14);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(19,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(20,11);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(21,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(22,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(23,4);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(24,3);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(25,6);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(26,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(27,5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(31,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(32,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(35,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(37,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(43,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(49,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(50,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinContent(51,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(1,31.27299);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(2,49.73932);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(3,52.94337);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(4,49.10193);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(5,40.69398);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(6,32.17142);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(7,24.55606);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(8,20.24846);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(9,14.76482);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(10,11);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(11,9.110434);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(12,7.615773);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(13,5.744563);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(14,5.567764);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(15,5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(16,4.795832);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(17,3.605551);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(18,3.741657);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(19,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(20,3.316625);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(21,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(22,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(23,2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(24,1.732051);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(25,2.44949);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(26,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(27,2.236068);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(31,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(32,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(33,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(35,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(36,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(37,1.414214);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(38,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(43,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(49,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(50,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetBinError(51,1);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetEntries(13050);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts7->Draw("HIST same");
   
   TH1F *hframe__128 = new TH1F("hframe__128","",1000,0,500);
   hframe__128->SetMinimum(0.1);
   hframe__128->SetMaximum(5606);
   hframe__128->SetDirectory(0);
   hframe__128->SetStats(0);
   hframe__128->SetLineStyle(0);
   hframe__128->SetMarkerStyle(20);
   hframe__128->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__128->GetXaxis()->SetLabelFont(43);
   hframe__128->GetXaxis()->SetLabelOffset(0.007);
   hframe__128->GetXaxis()->SetLabelSize(27);
   hframe__128->GetXaxis()->SetTitleSize(33);
   hframe__128->GetXaxis()->SetTitleOffset(0.9);
   hframe__128->GetXaxis()->SetTitleFont(43);
   hframe__128->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__128->GetYaxis()->SetLabelFont(43);
   hframe__128->GetYaxis()->SetLabelOffset(0.007);
   hframe__128->GetYaxis()->SetLabelSize(27);
   hframe__128->GetYaxis()->SetTitleSize(33);
   hframe__128->GetYaxis()->SetTitleOffset(1.25);
   hframe__128->GetYaxis()->SetTitleFont(43);
   hframe__128->GetZaxis()->SetLabelFont(43);
   hframe__128->GetZaxis()->SetLabelOffset(0.007);
   hframe__128->GetZaxis()->SetLabelSize(27);
   hframe__128->GetZaxis()->SetTitleSize(33);
   hframe__128->GetZaxis()->SetTitleFont(43);
   hframe__128->Draw("sameaxis");
   invertedtaup_Tgt150Integral->Modified();
   invertedtaup_Tgt150Integral->cd();
   invertedtaup_Tgt150Integral->SetSelected(invertedtaup_Tgt150Integral);
}
