{
//=========Macro generated from canvas: invertedEWKFakeTaustaup_Teq100to120Integral/
//=========  (Wed Aug 13 15:50:00 2014) by ROOT version5.32/00
   TCanvas *invertedEWKFakeTaustaup_Teq100to120Integral = new TCanvas("invertedEWKFakeTaustaup_Teq100to120Integral", "",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetHighLightColor(2);
   invertedEWKFakeTaustaup_Teq100to120Integral->Range(-101.2658,-1.236331,531.6456,0.5815967);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetFillColor(0);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetBorderMode(0);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetBorderSize(2);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetLogy();
   invertedEWKFakeTaustaup_Teq100to120Integral->SetTickx(1);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetTicky(1);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetLeftMargin(0.16);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetRightMargin(0.05);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetTopMargin(0.05);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetBottomMargin(0.13);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetFrameBorderMode(0);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetFrameFillStyle(0);
   invertedEWKFakeTaustaup_Teq100to120Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__95 = new TH1F("hframe__95","",1000,0,500);
   hframe__95->SetMinimum(0.1);
   hframe__95->SetMaximum(3.095283);
   hframe__95->SetDirectory(0);
   hframe__95->SetStats(0);
   hframe__95->SetLineStyle(0);
   hframe__95->SetMarkerStyle(20);
   hframe__95->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__95->GetXaxis()->SetLabelFont(43);
   hframe__95->GetXaxis()->SetLabelOffset(0.007);
   hframe__95->GetXaxis()->SetLabelSize(27);
   hframe__95->GetXaxis()->SetTitleSize(33);
   hframe__95->GetXaxis()->SetTitleOffset(0.9);
   hframe__95->GetXaxis()->SetTitleFont(43);
   hframe__95->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__95->GetYaxis()->SetLabelFont(43);
   hframe__95->GetYaxis()->SetLabelOffset(0.007);
   hframe__95->GetYaxis()->SetLabelSize(27);
   hframe__95->GetYaxis()->SetTitleSize(33);
   hframe__95->GetYaxis()->SetTitleOffset(1.25);
   hframe__95->GetYaxis()->SetTitleFont(43);
   hframe__95->GetZaxis()->SetLabelFont(43);
   hframe__95->GetZaxis()->SetLabelOffset(0.007);
   hframe__95->GetZaxis()->SetLabelSize(27);
   hframe__95->GetZaxis()->SetTitleSize(33);
   hframe__95->GetZaxis()->SetTitleFont(43);
   hframe__95->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=4.4 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 14 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5","#tau p_{T}=100..120",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(1,0.1605787);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(2,0.3637861);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(3,0.7467797);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(4,0.4145499);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(5,0.6841554);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(6,0.8687981);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(7,0.9413236);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(8,1.547642);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(9,0.6955943);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(10,0.9799495);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(11,0.8802189);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(12,0.7471514);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(13,0.3220846);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(14,0.8565131);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(15,0.9450396);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(16,1.028219);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(17,0.369045);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(18,0.08135642);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(19,0.3334636);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(20,0.2412965);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(21,0.00531754);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(22,0.1985159);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(23,0.189312);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(24,0.1344629);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(28,0.1822016);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinContent(51,0.0498071);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(1,0.117225);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(2,0.3032927);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(3,0.282192);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(4,0.1729225);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(5,0.2156586);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(6,0.2940137);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(7,0.2984088);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(8,0.8495687);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(9,0.2730451);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(10,0.3044459);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(11,0.2711331);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(12,0.2652691);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(13,0.1661032);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(14,0.2900099);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(15,0.3011152);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(16,0.3239779);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(17,0.1444757);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(18,0.08135642);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(19,0.1904644);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(20,0.1393186);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(21,0.00531754);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(22,0.1159544);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(23,0.1071049);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(24,0.1344629);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(28,0.161143);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetBinError(51,0.0498071);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetEntries(201);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus/METInvertedTauIdAfterCollinearCutsOnlyEWKFakeTaus5->Draw("HIST same");
   
   TH1F *hframe__96 = new TH1F("hframe__96","",1000,0,500);
   hframe__96->SetMinimum(0.1);
   hframe__96->SetMaximum(3.095283);
   hframe__96->SetDirectory(0);
   hframe__96->SetStats(0);
   hframe__96->SetLineStyle(0);
   hframe__96->SetMarkerStyle(20);
   hframe__96->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__96->GetXaxis()->SetLabelFont(43);
   hframe__96->GetXaxis()->SetLabelOffset(0.007);
   hframe__96->GetXaxis()->SetLabelSize(27);
   hframe__96->GetXaxis()->SetTitleSize(33);
   hframe__96->GetXaxis()->SetTitleOffset(0.9);
   hframe__96->GetXaxis()->SetTitleFont(43);
   hframe__96->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__96->GetYaxis()->SetLabelFont(43);
   hframe__96->GetYaxis()->SetLabelOffset(0.007);
   hframe__96->GetYaxis()->SetLabelSize(27);
   hframe__96->GetYaxis()->SetTitleSize(33);
   hframe__96->GetYaxis()->SetTitleOffset(1.25);
   hframe__96->GetYaxis()->SetTitleFont(43);
   hframe__96->GetZaxis()->SetLabelFont(43);
   hframe__96->GetZaxis()->SetLabelOffset(0.007);
   hframe__96->GetZaxis()->SetLabelSize(27);
   hframe__96->GetZaxis()->SetTitleSize(33);
   hframe__96->GetZaxis()->SetTitleFont(43);
   hframe__96->Draw("sameaxis");
   invertedEWKFakeTaustaup_Teq100to120Integral->Modified();
   invertedEWKFakeTaustaup_Teq100to120Integral->cd();
   invertedEWKFakeTaustaup_Teq100to120Integral->SetSelected(invertedEWKFakeTaustaup_Teq100to120Integral);
}
