{
//=========Macro generated from canvas: invertedEWK2Integral/
//=========  (Fri Jul  4 10:40:03 2014) by ROOT version5.32/00
   TCanvas *invertedEWK2Integral = new TCanvas("invertedEWK2Integral", "",0,0,600,600);
   gStyle->SetOptTitle(0);
   invertedEWK2Integral->SetHighLightColor(2);
   invertedEWK2Integral->Range(-101.2658,-1.476147,531.6456,2.186525);
   invertedEWK2Integral->SetFillColor(0);
   invertedEWK2Integral->SetBorderMode(0);
   invertedEWK2Integral->SetBorderSize(2);
   invertedEWK2Integral->SetLogy();
   invertedEWK2Integral->SetTickx(1);
   invertedEWK2Integral->SetTicky(1);
   invertedEWK2Integral->SetLeftMargin(0.16);
   invertedEWK2Integral->SetRightMargin(0.05);
   invertedEWK2Integral->SetTopMargin(0.05);
   invertedEWK2Integral->SetBottomMargin(0.13);
   invertedEWK2Integral->SetFrameFillStyle(0);
   invertedEWK2Integral->SetFrameBorderMode(0);
   invertedEWK2Integral->SetFrameFillStyle(0);
   invertedEWK2Integral->SetFrameBorderMode(0);
   
   TH1F *hframe__27 = new TH1F("hframe__27","",1000,0,500);
   hframe__27->SetMinimum(0.1);
   hframe__27->SetMaximum(100.7838);
   hframe__27->SetDirectory(0);
   hframe__27->SetStats(0);
   hframe__27->SetLineStyle(0);
   hframe__27->SetMarkerStyle(20);
   hframe__27->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__27->GetXaxis()->SetLabelFont(43);
   hframe__27->GetXaxis()->SetLabelOffset(0.007);
   hframe__27->GetXaxis()->SetLabelSize(27);
   hframe__27->GetXaxis()->SetTitleSize(33);
   hframe__27->GetXaxis()->SetTitleOffset(0.9);
   hframe__27->GetXaxis()->SetTitleFont(43);
   hframe__27->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__27->GetYaxis()->SetLabelFont(43);
   hframe__27->GetYaxis()->SetLabelOffset(0.007);
   hframe__27->GetYaxis()->SetLabelSize(27);
   hframe__27->GetYaxis()->SetTitleSize(33);
   hframe__27->GetYaxis()->SetTitleOffset(1.25);
   hframe__27->GetYaxis()->SetTitleFont(43);
   hframe__27->GetZaxis()->SetLabelFont(43);
   hframe__27->GetZaxis()->SetLabelOffset(0.007);
   hframe__27->GetZaxis()->SetLabelSize(27);
   hframe__27->GetZaxis()->SetTitleSize(33);
   hframe__27->GetZaxis()->SetTitleFont(43);
   hframe__27->Draw(" ");
   TLatex *   tex = new TLatex(0.62,0.96,"CMS Preliminary");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.19,0.96,"#sqrt{s} = 8 TeV");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.43,0.96,"L=20 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(43);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.4,0.7,"Integral = 628 ev");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(27);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2 = new TH1F("Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2","#tau p_{T}=60..70",50,0,500);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(1,2.0723);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(2,9.352064);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(3,14.11782);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(4,18.22289);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(5,18.94781);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(6,27.10209);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(7,21.01011);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(8,35.52941);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(9,42.79083);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(10,45.60097);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(11,42.77722);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(12,50.39192);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(13,34.67878);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(14,38.65509);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(15,42.14683);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(16,29.66948);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(17,24.0675);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(18,19.80591);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(19,12.312);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(20,16.47168);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(21,8.526074);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(22,13.69909);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(23,9.574255);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(24,5.167298);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(25,7.673341);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(26,4.195568);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(27,4.279055);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(28,3.096295);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(29,2.618096);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(30,3.265393);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(31,0.4427063);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(32,5.903402);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(33,2.276145);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(34,4.882844);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(35,0.8344531);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(36,1.062869);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(37,0.9549307);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(38,1.158588);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(39,0.7331582);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(41,0.5298809);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(42,0.9486787);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(45,0.3691069);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(47,0.3710073);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinContent(51,1.163805);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(1,0.9919972);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(2,2.143692);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(3,4.68383);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(4,3.074791);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(5,3.176173);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(6,3.973837);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(7,4.100789);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(8,5.485812);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(9,5.349342);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(10,5.230004);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(11,5.03064);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(12,6.156493);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(13,4.395212);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(14,4.945563);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(15,5.657016);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(16,4.178706);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(17,3.845316);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(18,3.202157);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(19,2.339782);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(20,2.851452);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(21,1.932343);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(22,3.198217);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(23,2.308461);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(24,1.589908);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(25,1.931924);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(26,1.436248);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(27,1.677424);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(28,1.199135);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(29,1.181312);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(30,1.393094);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(31,0.2935505);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(32,2.712151);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(33,1.141946);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(34,1.640423);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(35,0.5949385);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(36,0.7544645);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(37,0.7243581);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(38,0.6375884);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(39,0.5184615);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(41,0.5298809);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(42,0.6851227);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(45,0.3691069);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(47,0.3710073);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetBinError(51,0.8739375);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetEntries(1553);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetFillColor(ci);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetLineWidth(2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetMarkerStyle(20);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->SetMarkerSize(1.2);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetXaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetXaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetXaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetXaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetYaxis()->SetTitle("Events / 10 GeV");
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetYaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetYaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetYaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetYaxis()->SetTitleOffset(1.5);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetYaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetZaxis()->SetLabelFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetZaxis()->SetLabelSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetZaxis()->SetTitleSize(0.035);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->GetZaxis()->SetTitleFont(42);
   Inverted/METInvertedTauIdAfterCollinearCuts/METInvertedTauIdAfterCollinearCuts2->Draw("HIST same");
   
   TH1F *hframe__28 = new TH1F("hframe__28","",1000,0,500);
   hframe__28->SetMinimum(0.1);
   hframe__28->SetMaximum(100.7838);
   hframe__28->SetDirectory(0);
   hframe__28->SetStats(0);
   hframe__28->SetLineStyle(0);
   hframe__28->SetMarkerStyle(20);
   hframe__28->GetXaxis()->SetTitle("Type1 PFMET (GeV)");
   hframe__28->GetXaxis()->SetLabelFont(43);
   hframe__28->GetXaxis()->SetLabelOffset(0.007);
   hframe__28->GetXaxis()->SetLabelSize(27);
   hframe__28->GetXaxis()->SetTitleSize(33);
   hframe__28->GetXaxis()->SetTitleOffset(0.9);
   hframe__28->GetXaxis()->SetTitleFont(43);
   hframe__28->GetYaxis()->SetTitle("Events / 10 GeV");
   hframe__28->GetYaxis()->SetLabelFont(43);
   hframe__28->GetYaxis()->SetLabelOffset(0.007);
   hframe__28->GetYaxis()->SetLabelSize(27);
   hframe__28->GetYaxis()->SetTitleSize(33);
   hframe__28->GetYaxis()->SetTitleOffset(1.25);
   hframe__28->GetYaxis()->SetTitleFont(43);
   hframe__28->GetZaxis()->SetLabelFont(43);
   hframe__28->GetZaxis()->SetLabelOffset(0.007);
   hframe__28->GetZaxis()->SetLabelSize(27);
   hframe__28->GetZaxis()->SetTitleSize(33);
   hframe__28->GetZaxis()->SetTitleFont(43);
   hframe__28->Draw("sameaxis");
   invertedEWK2Integral->Modified();
   invertedEWK2Integral->cd();
   invertedEWK2Integral->SetSelected(invertedEWK2Integral);
}
