#!/bin/csh

#@$-r  h2tau   # request name
#@$-lf 90mb     # output file size limit
#@$-eo          # direct stderr output to the stdout destination
#-me          # send mail upon termination
#@$-s /bin/csh
#@$

	setenv MAXEVENTS 10

#	setenv ROOTFILEPATH rfio:$CASTOR_HOME/hch300_tauola_HLT
#	setenv ROOTFILE HLTtable_hch300_tauola_1.root
        setenv ROOTFILEPATH rfio:/castor/cern.ch/cms/store/relval/CMSSW_2_2_4/RelValTTbar/GEN-SIM-RECO/STARTUP_V8_v1/0000
	setenv ROOTFILE 200EB7E3-90F3-DD11-B1B0-001D09F2432B.root


	setenv CASTOR_DIR test

        if( $%1 > 0 ) then
                setenv ROOTFILEPATH $1
                setenv ROOTFILE $2
        endif

        echo ${ROOTFILEPATH}
        echo ${ROOTFILE}

        if( $ENVIRONMENT != "BATCH" ) then
          echo Setting workdir to SCRATCH
          setenv WORKDIR $TMP
          setenv LS_SUBCWD $PWD
        endif

        cd ${LS_SUBCWD}
        echo "Setting runtime environment"
        eval `scramv1 runtime -csh`

	cd ${WORKDIR}

	cp -f ${LS_SUBCWD}/offlineAnalysis_cfg.py ${WORKDIR}/analysis_${ROOTFILE}_cfg.py
	cat > changedcfg <<END_OF_CONFIG
process.maxEvents.input = cms.untracked.int32(${MAXEVENTS})
process.source.fileNames = cms.untracked.vstring(
        '${ROOTFILEPATH}/${ROOTFILE}'
)

END_OF_CONFIG

	cat changedcfg >> ${WORKDIR}/analysis_${ROOTFILE}_cfg.py
#        if ( -f $WORKDIR/analysis_${ROOTFILE}_cfg.py ) rm -f $WORKDIR/analysis_${ROOTFILE}_cfg.py
#        cat > $WORKDIR/analysis_${ROOTFILE}_cfg.py <<END_OF_CONFIG
#
#
#END_OF_CONFIG

        cat ${WORKDIR}/analysis_${ROOTFILE}_cfg.py

        if( -f ${WORKDIR}/analysis_${ROOTFILE}.out ) mv ${WORKDIR}/analysis_${ROOTFILE}.out ${WORKDIR}/analysis_${ROOTFILE}.out_old
        cmsRun ${WORKDIR}/analysis_${ROOTFILE}_cfg.py
#       cmsRun ${WORKDIR}/analysis_${ROOTFILE}_cfg.py >& ${WORKDIR}/analysis_${ROOTFILE}.out

#ls ${WORKDIR} -lt

####        if( -f ${WORKDIR}/analysis_${ROOTFILE}.out ) rfcp ${WORKDIR}/analysis_${ROOTFILE}.out ${CASTOR_HOME}/${CASTOR_DIR}
        if( -f ${WORKDIR}/analysis.root ) then
		mv ${WORKDIR}/analysis.root ${WORKDIR}/analysis_${ROOTFILE}
####		rfcp ${WORKDIR}/analysis_${ROOTFILE} ${CASTOR_HOME}/${CASTOR_DIR}
		mv ${WORKDIR}/analysis_${ROOTFILE} $LS_SUBCWD
	endif
